### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue-loader#1]
Is it possible to add hot module replacement like it works in react? (http://vimeo.com/100010922)

**Comment by OEvgeny** [comment]
Not sure, that it is fixes the issue :)

**Comment by azamat-sharapov** [comment]
That commit fixes https://github.com/Q42/vue-multi-loader/issues/1 because when they replaced this repo's code with vue-multi-loader's, references in commit messages pointing to this repo.

**Comment by OEvgeny** [comment]
@azamat-sharapov thanks for explanation.
