### ISSUE TITLE
Add support for valid XML and DTD

### ISSUE THREAD

**Issue by mindplay-dk** [vuejs/vue-loader#100]
I have been [trying](https://github.com/postalservice14/vuejs-plugin/issues/1#issuecomment-164872059) to get IDEA (Storm) to properly highlight `.vue` files, and it almost worked.

I was able to configure the language injections using an xpath query like e.g. `//style[@lang='sass']` which sort of works, but with some issues, because `.vue` files currently are not valid XML.

I propose adding (optional) support for valid XML, which might consist of the following:

  1. Providing a DTD, with the `<template>`, `<style>` and `<script>` tags (and attributes) formally defined as child-nodes of an e.g. `<vue>` root-element.

  2. Possibly an alternate file-extension, maybe `.vue.xml`, to help tools recognize that these are in fact XML files, and so the official tools can distinguish these from the lightweight, non-valid `.vue` format currently supported.

  3. Official tools recognizing the valid XML format, e.g.:

```xml
<?xml version="1.0"?>
<!DOCTYPE vue SYSTEM "vuejs.org/dtd">
<vue>
<style>
  ...
</style>
<template>
   ...
</template>
<script>
   ...
</script>
</vue>
```

When I say "official tool", I mean this (vue-loader) and probably vueify (?)

**Comment by yyx990803** [comment]
I don't really like the idea of thinking of Vue components as XML just for the sake of getting proper syntax highlighting for a particular IDE. If anything, this is more like a problem with how inflexible that IDE's syntax highlighting system is.

I think the proper action is to urge JetBrains to make it easier to highlight arbitrary file formats in their IDEs. But regarding your proposal:

1 & 3: These are doable, although I personally do not have enough interest in this. You are welcome to contribute though! (For 3, it's important to make this format optional and backwards compatible)

2: `vueify` is currently hard-coded with the `*.vue` extension, but it's easy to change to to be configurable via `vue.config.js`. `vue-loader` can already be used on arbitrary extensions as long as you configure it properly in Webpack's config.

**Comment by mindplay-dk** [comment]
> I don't really like the idea of thinking of Vue components as XML just for the sake of getting proper syntax highlighting for a particular IDE.

It's not "just for the sake of getting proper syntax highlighting" - actually, that's the least of it. My primary concern is to get support for language injections, which is about much more than just syntax highlighting. For example, real TypeScript and SASS support, with auto-completion, real-time inspections, etc.

It's also not "for a particular IDE" - yes, it helps in the case of this IDE, but XML and DTD are standard technology supported by a wealth of tools, whereas Vue's XML-like format is supported, out of the box, by any tool, merely as a plain text-file.

While most editors and IDEs will of course allow you to designate the `.vue` file-extension as an XML file, if the tool is any good, it should start to bark about invalid XML right out of the gate.

I think there are more than a few good reasons to build on standards rather than inventing your own. IDE support is one of them, and yes, this happens to be particularly good in IDEA-based IDEs, but any IDE should be able to at least syntax-check valid XML, and many will support checking a DTD, out of the box, without waiting for the community to hand-roll plug-ins or scripts for every IDE and text-editor out there.

> If anything, this is more like a problem with how inflexible that IDE's syntax highlighting system is.

IDEA is more configurable in terms of syntax than any other IDE that I know of - unless you're talking about scripting or writing plug-ins? As far as end users being able to configure syntax highlighting on a per-project basis (such as defining the default/primary language used in `<script>` tags with no `lang` attribute) it packs more features and flexibility than anything else I've tried.

Either way, I'm not campaigning not for IDE support here, but for following standards.

Breaking standards is bad, unless your reason for doing so is really, really, really good ;-)

**Comment by yyx990803** [comment]
Well, it's pretty easy to enable full support for another languages (syntax, autocomplete, snippets...) inside `*.vue` files in editors like Sublime Text and Atom - that's exactly what [vue syntax highlight](https://github.com/vuejs/vue-syntax-highlight) does. I assume JetBrains' IDEs have more powerful code intelligence, but I don't see why it's such a hassle to implement a custom file syntax in userland, and why it has anything to do with XML.

On the other hand - `*.vue` files **never intended to be XML**. If anything, Vue files are a valid subset of HTML (vue-loader uses parse5, which is a standards compliant HTML parser to parse Vue files). Just because Vue files use tags doesn't mean it has to be XML, and it's funny to talk about "breaking standards" when the standards doesn't apply to what is in question in the first place.

**Comment by mindplay-dk** [comment]
So just to be clear, the intention is to comply with HTML5?

I'm not trying to facetious, but your "if anything" preface makes me a bit uncertain if that was your point.

I had no idea this was valid HTML5, but that makes a lot of sense - possibly more so than XML.

Sadly, IDEA does not allow language injections for HTML5, only for XML - probably because HTML5 is expected to have a predefined/well-known set of language injections.

IMO, using HTML5 as a container format for HTML5, JS, CSS and other types of documents would make a lot of sense, but for one, the `lang` attribute indicates human language, not programming language, so it isn't even really HTML5, is it?

I mean, if what you're saying is, `.vue` is it's own format entirely, it just happens to borrow from HTML5, then, yeah, there's nothing to debate here. It's not what I was hoping for, but yeah...

**Comment by yyx990803** [comment]
Yeah, I think "`.vue` is its own format that borrows from HTML5" is a pretty accurate description ;)
