### ISSUE TITLE
vue-loader 13.3.0 和nodejs 4.8兼容性问题

### ISSUE THREAD

**Issue by haodouya** [vuejs/vue-loader#1010]
Version
13.3.0

Reproduction link
https://codepen.io/haodouya123/pen/gGBdxw

Steps to reproduce
在nodejs 4.8环境下 用vue cli创建任意项目，安装npm install 将vue-loader升级到13.3.0版，运行npm run dev

What is expected?
不报出 "Unexpected token {"错误，cli正常运行

What is actually happening?
vue-loader解析文件会报出 "Unexpected token {"错误
更换到node.js 5以上的版本就会恢复正常
将vue-loader降级到13.0.x版本也会恢复正常
vue-loader 13.3.0不在支持nodejs 5以下的版本了么？

**Comment by HeuHax** [comment]
I also have this problem on node.js version 8.7.0

**Comment by hsamadi** [comment]
I have the same issue on all 13.3.x versions.
Node.js v8.7.0

**Comment by HeuHax** [comment]
It occurred specifically after upgrading vue-loader. Downgrading to version 13.0.5 fixes the error.

**Comment by LinusBorg** [comment]
Since no actual reproduction was provided, I have no idea what this is about, can someone translate and maybe even reproduce what OP is trying to report?

**Comment by HeuHax** [comment]
Here is my package.json:
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "webpack": "^3.8.0",
    "aspnet-webpack": "^2.0.1",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "extract-text-webpack-plugin": "^3.0.1",
    "image-webpack-loader": "^3.4.2",
    "vue-loader": "13.0.5",
    "vue-template-compiler": "^2.5.2",
    "webpack-hot-middleware": "^2.20.0",
    "css-loader": "^0.28.7",
    "style-loader": "^0.19.0"
  },
  "dependencies": {
    "aspnet-prerendering": "^3.0.1",
    "axios": "^0.16.2",
    "babel-polyfill": "^6.26.0",
    "moment": "^2.19.1",
    "vee-validate": "^2.0.0-rc.19",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.5.2",
    "vuex": "^3.0.0",
    "vue-analytics": "^5.1.1",
    "vue-stripe-elements": "^0.2.3",
    "vuetify": "^0.16.7",
    "vue-scrollto": "^2.7.8"
  }
}

**Comment by HeuHax** [comment]
And my webpack.config is pretty standardi think with these rules:

module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                include: __dirname,
                exclude: /node_modules/
            },
            {
                test: /\.css/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: ['css-loader']
                })
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'file?hash=sha512&digest=hex&name=[hash].[ext]',
                    'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
                ]
            }
        ]
    }

**Comment by HeuHax** [comment]
Here is the full error in english:

ERROR in ./App/components/App.vue
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\****\node_modules\vue-loader\index.js:1:80)

**Comment by LinusBorg** [comment]
1. have you removed `node_modules` and reinstalled everything?
2. what does App.vue look like?
3. Can you share a repository with a minimal reproduction?

**Comment by HeuHax** [comment]
1: Yes
2:
<template>

    <div>
        Test
    </div>

</template>

<script>
    export default {
        data() {
            return {

            }
        },
        components: {},
        computed: {

        },
        created() {

        },
        mounted() {

        }
    };
</script>

3: I'll try. I work mostly in visual studio and .Net so I have to try and make a simple node.js environment.

**Comment by xuguogang** [comment]
我出现了同样的问题，在13.3.0下报错：

ERROR in ./components/app-nav.vue
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
 @ ./components/index.js 3:14-38

最开始我以为我的代码与新版VUE不兼容，我回撤到13.0.2就正常了。
我用了一个空vue文件测试发现依然有错误，最后发现是vue-loader的问题。

首先发现是这段代码用的是ES6写法，webpack调用时识别不了，认为是语法错误。我改成普通写法后，不报错了，但是前面很多const之类的ES6写法，提示在严格模式下是不可以的。总之，vue-loader的ES6写法webpack打包时识别不了，这怎么解决？nodejs开始8.0不行降级到6.11.4还是不行。难道要在哪里设置什么？

// When extracting parts from the source vue file, we want to apply the
// loaders chained before vue-loader, but exclude some loaders that simply
// produces side effects such as linting.
function getRawRequest (
  { resource, loaderIndex, loaders },
  excludedPreLoaders = /eslint-loader/
) {
  return loaderUtils.getRemainingRequest({
    resource: resource,
    loaderIndex: loaderIndex,
    loaders: loaders.filter(loader => !excludedPreLoaders.test(loader.path))
  })
}

**Comment by yyx990803** [comment]
13.3.0 indeed drops support for Node 4.x, but we had been using ES2015 features long time ago...

However, the tests pass for Node version greater than 6.x. If you are running into issues, **it's likely that your IDE is not using the same version of Node in your shell**.

**Comment by Danita** [comment]
For anyone that's having the same problem on Node 5.x: last known version of vue-loader to run OK on Node 5 is 13.0.2. You have to update to a newer Node version in order to run 13.3.0.
