### ISSUE TITLE
Functional components do not support "components" option

### ISSUE THREAD

**Issue by autumnwoodberry** [vuejs/vue-loader#1013]
### Version
13.3.0

### Reproduction link
[https://github.com/autumnwoodberry/vue-functional-template-components](https://github.com/autumnwoodberry/vue-functional-template-components)

### Steps to reproduce
created repo using vue-cli webpack template:

- npm install
- npm run dev

Look at the "HelloWorld.vue" component definition. The template block has been marked as "functional" and an attempt has been made to import and use an external component:

```
import TestComp from './TestComp'

export default {
  name: 'HelloWorld',
  components: {
    TestComp
  },
}
```

### What is expected?
Adding a components option to a functional component registers the specified components, which will be available in the functional component's template.

### What is actually happening?
The external component is not registered, and is not recognized in the template:

"Unknown custom element: <TestComp> - did you register the component correctly?"

---
From a post on the forums:

https://forum.vuejs.org/t/how-can-i-use-dynamic-components-inside-vue-js-funcional-components-with-templates/19739/9

**Comment by autumnwoodberry** [comment]
This should probably be in vue core.

**Comment by tatsuhirosatou** [comment]
@autumnwoodberry Shall I post this on core?

**Comment by yyx990803** [comment]
Yeah, this should be feature request in vue core.

**Comment by ThomasKotowicz-S1** [comment]
@autumnwoodberry This is possible if you import the component in the parent which is using this functional component.

**Comment by hirokiosame** [comment]
For reference, the new issue is: https://github.com/vuejs/vue/issues/6872
