### ISSUE TITLE
module IDs should be a digest of the contents

### ISSUE THREAD

**Issue by inopinatus** [vuejs/vue-loader#1016]
### What problem does this feature solve?
Module IDs are currently generated by hashing part of the filename. This leads to inconsistency, since it assumes paths are the same on all servers, which they are not. We've had trouble with content delivery due to inconsistent manifests.

Systems like git and sprockets use sha for fingerprinting. Perhaps module IDs should be the same.

### What does the proposed API look like?
I am using this in production with my fork of vue-loader/lib/utils/gen-id.js:

```
// utility for generating a uid for each component file
// used in scoped CSS rewriting
const cache = Object.create(null)
const crypto = require('crypto')
const fs = require('fs')

function createHash (file, algorithm, encoding, maxlen) {
  var hash = crypto.createHash(algorithm)
  var contents = fs.readFileSync(file)
  hash.update(contents)
  return hash.digest(encoding).toLowerCase().trim().substring(0, maxlen)
}

module.exports = function genId (file) {
  return cache[file] || (cache[file] = createHash(file, 'sha256', 'hex', 10))
}
```

**Comment by yyx990803** [comment]
Yes, this is something I realized a while ago but haven't implemented yet. If you'd like please make a PR!

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue-loader/pull/1018#issuecomment-341797205
