### ISSUE TITLE
Template syntax issue stalls webpack build when using UglifyJsPlugin

### ISSUE THREAD

**Issue by lazabogdan** [vuejs/vue-loader#102]
Not sure if this is a vue-loader or html-loader issue.

When using the following shorthand in the template tag within a .vue file, and running `webpack -p` or `webpack --optimize-minimize` the build progress stalls at "build modules" and never completes.

```
<a @click="doSomething"></a>
```

While this works without a problem:

```
<a v-on:click="doSomething"></a>
```

**Comment by yyx990803** [comment]
You should use [`vue-html-loader`](https://github.com/vuejs/vue-html-loader) instead of `html-loader`.

**Comment by lazabogdan** [comment]
Thanks @yyx990803 .. I somehow missed that! Awesome docs btw, just saw it.

**Comment by rwilsonjr** [comment]
I also experience this error and don't have an html-loader defined in my webpack.config.

**Comment by nils-werner** [comment]
@rwilsonjr did you find a fix?
