### ISSUE TITLE
[Feature Request] Need for new option to remove data-test-id

### ISSUE THREAD

**Issue by rnons** [vuejs/vue-loader#1022]
### What problem does this feature solve?
When writing tests, we often need to inject id/class to help select an element. I want to remove them in prod.

Can we support this in `vue-loader` or do you have any ideas how to do that? Thanks.

### What does the proposed API look like?
Similar to https://github.com/kutyel/babel-plugin-remove-test-ids

**Comment by nicholaslee119** [comment]
Yes, I think it is implementable and meaningful. just do some a plugin to postCSS and do some works with template-compiler.

**Comment by Jinjiang** [comment]
I think you can have a try with `compilerModules` options: https://vue-loader.vuejs.org/en/options.html#compilermodules .
Just write a compiler module to remove attributes like `data-set-id`.
Thanks.

**Comment by LinusBorg** [comment]
This was discusssed on the forum, as working implementation can be found here:

https://forum.vuejs.org/t/how-to-remove-attributes-from-tags-inside-vue-components/24138/3?u=linusborg
