### ISSUE TITLE
配置了vue-loader options里的loader以后，hmr无法正确工作

### ISSUE THREAD

**Issue by JasonKid** [vuejs/vue-loader#1026]
下面是webpack中的配置：
```js
{ test: /\.vue$/, use: [{
    loader: 'vue-loader',
        options: {
            loaders: {
                less: `vue-style-loader!css-loader!less-loader?paths[]=${resolve(__dirname, '../src')}`
            }
    }
 }]}
```

然后再`.vue`文件中使用
```
<style>
    @import 'styles/theme.less';
     ...
</style>
```

如此情况的时候，theme.less如果有变更，会触发hmr，但是hmr没有任何内容，无法正常更新样式。

而我删掉options.loaders.less之后，在<style>中使用相对路径加载theme.less则可以正确hmr。

**Comment by Justineo** [comment]
When run with the arg `paths`, `less-loader` will disable its built-in `WebpackFileManager`, which makes it impossible for webpack to learn the `@import` dependency inside a Less file. This makes HMR stop working.
---
`less-loader` 在使用了 `paths` 参数时，会禁用掉自带的 `WebpackFileManager`，这样 webpack 将无法感知的 Less 文件内的 `@import` 依赖，从而导致 HMR 失效。

**Comment by Dafrok** [comment]
这个目前有解么

**Comment by Dafrok** [comment]
这个目前有解么，我遇到了类似的问题

**Comment by Justineo** [comment]
@Dafrok 不用 `paths`，显式引入依赖。

**Comment by Dafrok** [comment]
@Justineo 我的场景没用 `paths`，是 pug include 了一个 `.md` 文件，如果显示引入依赖的话岂不是要多声明一遍

**Comment by Justineo** [comment]
这要看 pug 有没有什么插件机制可以在 include 的时候想办法 `addDependency` 了……

**Comment by yyx990803** [comment]
Closing as it's not solvable in `vue-loader`.
