### ISSUE TITLE
Maybe we need some way to modify the path of vue-hot-reload-api and other loaders

### ISSUE THREAD

**Issue by 879479119** [vuejs/vue-loader#1027]
### What problem does this feature solve?
Now i'm working on something that can help me building my project, which is treated as a terminal tool.

e.g: I can use `vc-tool start` to start the server and build the application, without install all the packages in the project folder, because all I need have been listed in the `vc-tool/package.json` and installed in the `vc-tool/node_modules`.

but when Im trying to add HMR function for vue, I found that `vue-loader` can only add the request for `vue-hot-reload-api` just the same as itself. I really need to find a way to add some prefix or pass a real path to it in order to change the changed code to become something like `/user/vc-tool/vue-hot`

Or I have to add a abrupt dependency in the `project/package.json`, that's too bad

Maybe I haven't tell what I need clearly, please check what Im doing [here](https://github.com/vueComponent/vc-tool/blob/webpack/src/config/development.js)

```
exports.dep = dep => {
  if (IS_TEST) {
    return dep
  } else if (
    fs.existsSync(path.resolve(__dirname, '../../node_modules', dep))
  ) {
    // npm 2 or npm linked
    return 'vue-loader/node_modules/'   dep
  } else {
    // npm 3
    return dep
  }
}
```

### What does the proposed API look like?
we can provide a string prefix or let the users find out their way to get the prefix

```
{
   options: {
      moduleBase: string | function,
   }
}
```

**Comment by nicocevallos** [comment]
I have the same issue, when I use `pnpm` I need to install `vue-hot-reload-api` to my project to allow `vue-loader` to find the `vue-hot-reload-api` module

**Comment by yyx990803** [comment]
You can add a webpack alias for `vue-hot-reload-api` and point it to whatever you need.
