### ISSUE TITLE
/deep/ isn't compiled away

### ISSUE THREAD

**Issue by paglias** [vuejs/vue-loader#1029]
Using SCSS it doesn't go away:

<img width="354" alt="schermata 2017-10-30 alle 23 16 02" src="https://user-images.githubusercontent.com/589911/32198429-54be9fba-bdc8-11e7-9a59-31103cfd82b4.png">

^ this works in chrome but not in firefox

Using `>>>` doesn't work at all

**Comment by paglias** [comment]
Sorry, I just realized I wasn't in a scoped style block

**Comment by jasonlfunk** [comment]
In case anyone stumbles across this, my problem was that nested /deep/s aren't compiled away (and aren't necessary!)
