### ISSUE TITLE
使用webpack 时出现 “Module build failed: TypeError: this._init is not a function at Object.Vue”

### ISSUE THREAD

**Issue by mrcuix** [vuejs/vue-loader#103]
Module build failed: TypeError: this._init is not a function
at Object.Vue (c:\test-vue\node_modules\vue\dist\vue.common.js:9003:8)

**Comment by mrcuix** [comment]
已找到问题，npm 不熟造成

**Comment by hentaicracker** [comment]
@mrcuix 请问是怎么解决的？

**Comment by athena0304** [comment]
@mrcuix  是啊，求问怎么解决的

**Comment by mrcuix** [comment]
使用 cnpm 安装 ，用npm执行
