### ISSUE TITLE
Disable Hot Reload by option

### ISSUE THREAD

**Issue by gejgalis** [vuejs/vue-loader#1036]
### What problem does this feature solve?

We have built in our project Hot Module Replacement on higher level abstraction and vue-loader prevents our `module.hot.accept()` trigger. We need to turn off vue-loader Hot Reload feature to be able to use our HMR.

For end user experience - there will be additional option which may be used to disable Hot Reload staying in "development" environment. NOTE: we don't need to disable HMR in styles - this part doesn't break our functionality.

### What does the proposed API look like?

```js
module: {
  rules: [
    {
      test: /\.vue$/,
      loader: 'vue-loader',
      options: {
        hotReload: false // disables Hot Reload
      }
    }
  ]
}
```

I will contribute PullRequest in next few hours.

**Comment by gejgalis** [comment]
BTW after @yyx990803 commit: https://github.com/vuejs/vue-loader/commit/d8c82d5f6e61b5510178d60f07a6263e4ba7d69c Hot Reload is broken. Tested in generated project using: `vue init foo`

**Comment by yyx990803** [comment]
@gejgalis thanks for pointing that out, addressed in 153d237.

As for the option to disable HMR, a PR is welcome.

**Comment by gejgalis** [comment]
I did PR: https://github.com/vuejs/vue-loader/pull/1037

**Comment by Jinjiang** [comment]
@yyx990803 @LinusBorg I guess this issue has been solved and could be closed.
Thanks.
