### ISSUE TITLE
HelloWorld projet - Module build failed: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by nagyzsolthun** [vuejs/vue-loader#1040]
### Version
13.4.0

### Reproduction link
[https://github.com/nagyzsolthun/vue-syntax-error](https://github.com/nagyzsolthun/vue-syntax-error)

### Steps to reproduce
1. confirm that the project builds with the dependencies set in the current package.json (npm install; webpack)
2. update vue-loader to 13.4.0 in package.json
3. run npm upate
4. build again

### What is expected?
successful build

### What is actually happening?
ERROR in ./app.vue
Module build failed: SyntaxError: Unexpected token {...

**Comment by LinusBorg** [comment]
Can't reproduce that:

<img width="846" alt="bildschirmfoto 2017-11-04 um 10 46 12" src="https://user-images.githubusercontent.com/1444526/32404296-67cc1708-c14d-11e7-8798-46859d5647ed.png">

**Comment by nagyzsolthun** [comment]
I reinstalled my OS, build finishes as expected.

**Comment by aeolusheath** [comment]
@LinusBorg  bro, I meet the same error:

"Module build failed: SyntaxError: Unexpected token {"

vue-loader version is 13.5.0, but as u say I modify it to 13.4.0 . error occur。

versions as below:



![image](https://user-images.githubusercontent.com/5978548/32716839-168060f8-c81d-11e7-8e2f-b0cdc2476d4c.png)

**Comment by LinusBorg** [comment]
That screenshot doesn't really help me in understanding your problem. simply saying "same error" doesn't help either.

You likely just have to freshly update and re-install(!) *all* dependencies.

If it continues to be a problem, please:

1. Open a new issue
2. show the exact error that'S happening
3. provide some runnable code that reprodues the problem.

**Comment by dannon** [comment]
@aeolusheath For what it's worth, I had this happen when testing against a very old nodejs 4.x version, but 6.x and newer versions work fine.

**Comment by aeolusheath** [comment]
@dannon  yes u r right

**Comment by niksy** [comment]
Seems like it’s related to Node version. Is latest vue-loader compatible with Node 4?

**Comment by abiodunjames** [comment]
@aeolusheath You save my day. Thank you.
