### ISSUE TITLE
@13.3.0  [Vue warn]: Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by CharlieLau** [vuejs/vue-loader#1044]
![Uploading image-20171107+1.png…]()

**Comment by LinusBorg** [comment]
Hello @CharlieLau,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
