### ISSUE TITLE
Webpack bundle for non-spa application

### ISSUE THREAD

**Issue by uharbachou** [vuejs/vue-loader#1049]
### What problem does this feature solve?
For current state use vue.js in non-spa application and our vision should be possible to load styles on page in one additional bundle. 
Will be config options which will manage loading styles as now and in one additional bundle. But here need discussion how will work it with scoped styles. As in current implementation or need to think how it should works.

Thanks in advance 

### What does the proposed API look like?
```
test: /\.vue$/,
          enforce: 'pre',
          loader: 'vue-loader',
          bundle: true, 
          bundlePath: '..'
```

**Comment by Jinjiang** [comment]
Is `extractCSS` OK for you? https://vue-loader.vuejs.org/en/options.html#extractcss

**Comment by lokky2082** [comment]
I have a problem with extractCSS, it not change paths on relative,  maybe someone have the same problem and resolve this ?

**Comment by Jinjiang** [comment]
@lokky2082 Would you mind to supply a reproduced repo or code sample about this? I'm afraid I can't get your problem exactly 😅.
Thanks.

**Comment by lokky2082** [comment]
Hi, i edit my question )))  thanks for pay attention

2017-11-30 12:03 GMT+05:00 勾三股四 <notifications@github.com>:

**Comment by lokky2082** [comment]
Hi again, solve problem, forgot pablickPath:'/' in config

2017-11-30 12:43 GMT+05:00 Юлия Зайцева <lokky2082@gmail.com>:
