### ISSUE TITLE
Allow postcss options to be a function (webpack) => PostCSSPlugin[]

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue-loader#106]
To allow the `postcss-import` add dependencies to webpack, it should accept some options like:

```js
{
  addDependencyTo: webpack
}
```

So the `vue-loader` should also allow the postcss options be a `function(webpack): []`, just like [postcss-loader](https://github.com/postcss/postcss-loader#integration-with-postcss-import).

**Comment by yyx990803** [comment]
Sounds right, feel free to submit a PR for this! https://github.com/vuejs/vue-loader/blob/master/lib/style-rewriter.js#L39-L41

**Comment by yyx990803** [comment]
Shipped in 7.4.0
