### ISSUE TITLE
why vue-loader not automatically install vue-template-compiler?

### ISSUE THREAD

**Issue by iggbond** [vuejs/vue-loader#1060]
### Version
13.5.0

### Reproduction link
[https://vue-loader.vuejs.org/zh-cn/](https://vue-loader.vuejs.org/zh-cn/)

### Steps to reproduce
...

### What is expected?
I hope install vue-loader will install vue-template-compiler

### What is actually happening?
install vue-loader will not automatically install vue-template-compiler

**Comment by LinusBorg** [comment]
vue-template-compiler has to*exactly* match the Vue version that you are using, so we can't make it a direct dependency.
