### ISSUE TITLE
The scoped attribute cause a missing id attribute on td element

### ISSUE THREAD

**Issue by pmesgari** [vuejs/vue-loader#1061]
### Version
13.5.0

### Reproduction link
[https://codesandbox.io/s/yjkyl000w9](https://codesandbox.io/s/yjkyl000w9)

### Steps to reproduce
Setting the `items` for a table component during `mounted` hook causes the first `td` element of the table to have different dimensions, while trying to apply a `scoped` css style.
You can see this in the ContourTable component in sandbox

### What is expected?
The `scoped` css style to be applied to the entire table, and all elements selected in the css selector to receive the applied style.

### What is actually happening?
The `td` element that does not get the style is missing an `id` attribute

---
This happens only when the items are filled in the mounted hook. If items are defined and populated directly in the data options of the component, things works fine, even with a scoped css. The solutions to keep the scoped css and still populate items in the mounted hooks are two: 1. Using a deep selector with >>> and applying it to the table. 2. Not having the scoped attribute

**Comment by yyx990803** [comment]
So I cloned your project from codesandbox and tested it in a fresh vue-cli 2.x setup, the bug is no longer there. If you are still running into it, please open a new issue with a repository as a repro instead of using CodeSandbox because it doesn't reflect the actual dependencies in real projects.
