### ISSUE TITLE
src folder not included in dist after npm run build command execute in vuejs

### ISSUE THREAD

**Issue by bhavin458** [vuejs/vue-loader#1066]

**Comment by LinusBorg** [comment]
Hello @bhavin458,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
