### ISSUE TITLE
Error on "Name = undefiend" in package

### ISSUE THREAD

**Issue by ambrt** [vuejs/vue-loader#1069]
I try to load my client api in vue project. The api is in es6.

but i get the error:

Module parse failed: Unexpected token (92:9)
You may need an appropriate loader to handle this file type.
```
|     * @member {String} Name
|     */
|     Name = undefined;
|     /**
|     * @member {Number} LastPrice

 @ ./node_modules/myapi/src/index.js 25:0-32
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/CartVote.vue
 @ ./src/components/CartVote.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/Cart.vue
 @ ./src/components/Cart.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

Project is generated via vue-cli and api is generated via swagger-codegen.

**Comment by LinusBorg** [comment]
Hello @ambrt,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))

Thank you.

**Comment by ambrt** [comment]
@LinusBorg 

I created a repo containing errors: https://github.com/ambrt/loopback-vue-swagger , can you re open?

**Comment by LinusBorg** [comment]
It would be nice if you helped us navigate the source. You seem to have built a custom npm package that can't be transpiled.

**Comment by ambrt** [comment]
@LinusBorg 
I don't think i need npm package but including just files gives same error. I commited an update with `/src/swagcli/` that contain same files as pacage.

**Comment by LinusBorg** [comment]
But I still don't see what that is supposed to have to do with vue-loader ...

**Comment by ambrt** [comment]
I assumed its the vue-loader problem because its mentioned in error:<br>`@ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/CartVote.vue`

Do you suggest its error in babel-loader?

**Comment by LinusBorg** [comment]
It seems like it's a problem with your babel config.

**Comment by ambrt** [comment]
Ok
