### ISSUE TITLE
weex配置webConfig的vue-loader css提取导致样式大小是native的两倍

### ISSUE THREAD

**Issue by chenwenxian** [vuejs/vue-loader#1074]
有人遇到下面的问题么：
weex配置webConfig的vue-loader css提取导致样式大小是native的两倍了，这个是什么问题来着？
![image](https://user-images.githubusercontent.com/5305181/33127104-065ed162-cfc2-11e7-9b17-91f5df6c2e01.png)
![image](https://user-images.githubusercontent.com/5305181/33127126-20a8aec6-cfc2-11e7-9448-37e5452115e9.png)
web页面展示出来的UI是native的两倍：
![image](https://user-images.githubusercontent.com/5305181/33127173-61f139e8-cfc2-11e7-9557-2c0420274fe3.png)

**Comment by yyx990803** [comment]
Not appropriate place to ask questions like this.
