### ISSUE TITLE
vue-loader 不支持扩展运算符(...)

### ISSUE THREAD

**Issue by SteveCruise** [vuejs/vue-loader#1076]
### Version
13.5.0

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/no_url](https://jsfiddle.net/api/post/library/pure/no_url)

### Steps to reproduce
我这里没用babel，因为是后台页面，公司内部使用，可以指定chrome 61+。而chrome 61+原生支持es6+新语法，不需要babel，不懂vue-loader跟js的语法有直接的关系没？反正是vue-loader报错了，具体自己弄个简单的demo测试吧

### What is expected?
支持

### What is actually happening?
```
ERROR in ./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Manage.vue
Module parse failed: Unexpected token (173:80)
You may need an appropriate loader to handle this file type.
|                         type: 'success'
|                     }).then(() => {
|                         this.$socketio.send({type: 'block', msg: { block: true, ...this.blockForm } }, (data) => {
|                             console.log('block data: ', data);
|                             if (data.code === 200) {
 @ ./src/views/Manage.vue 3:0-107
 @ ./src/router/index.js
 @ ./src/app.js
```

**Comment by Jinjiang** [comment]
你给的 Reproduction link 有问题，麻烦重新提供一下吧
谢谢

**Comment by SteveCruise** [comment]
没有url。。。就是想问问vue-loader 不支持扩展运算符，这是可能的把？

**Comment by Jinjiang** [comment]
感谢您的指教

vue-loader 没有做特殊处理，如果您不愿意提供 demo，有劳先把相同或类似的 js 代码直接放 js 文件里而不是 vue 文件里，看会不会报错。然后再做进一步排查。

**Comment by Justineo** [comment]
见 https://github.com/vuejs/vue/issues/6307#issuecomment-345751066。

**Comment by Justineo** [comment]
恩，这个问题和 vuejs/vue#6307 好像还不太一样，不是模板里的语句报错。

**Comment by HerringtonDarkholme** [comment]
Webpack by default uses acorn as parser.

Acorn doesn't support spread syntax. So you do need a transpiler for webpack. Vue-loader by default only extract script and pass it to webpack.

**Comment by wangyi7099** [comment]
这个问题我也遇到过。试试这样能不能行得通。
1 新建一个.babelrc文件在项目的根目录里面。
2 在里面加上这样的内容： 
 <pre>
{
 "plugins": ["transform-object-rest-spread"]
}
 </pre>

**Comment by SteveCruise** [comment]
@wangyi7099 没有用到babel

**Comment by SteveCruise** [comment]
@Jinjiang 按照您的意思试了下，果然是webpack的问题，不兼容扩展运算符（...）。

首先，这个是webpack打包时报的错，并不是node.js环境或者浏览器运行时报的错。所以，我同样webpack打包了一个纯node.js项目，包含下面这个语句：
```
const result = await ExecUtil.exec(fullname);
                result.execState = result.state;
                result.state = CONST.UPLOAD_STATE.SUCCESS;
                // pomelo.notify('connector.userHandler.upload', Object.assign(result, { id }));
                pomelo.notify('connector.userHandler.upload', { id, ...result });
```
然后打包报错：
```
ERROR in ./app.js
Module parse failed: Unexpected token (283:68)
You may need an appropriate loader to handle this file type.
|                 result.state = CONST.UPLOAD_STATE.SUCCESS;
|                 // pomelo.notify('connector.userHandler.upload', Object.assign(result, { id }));
|                 pomelo.notify('connector.userHandler.upload', { id, ...result });
|             } else {
|                 pomelo.notify('connector.userHandler.upload', { id, state: CONST.UPLOAD_STATE.SUCCESS });
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! phc-controller-user@1.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the phc-controller-user@1.0.0 build script.
```
错误是同样的，所以呢，大概是webpack内置的js解析器不支持扩展运算符。
