### ISSUE TITLE
Use object  in vue-loader's loaders property

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue-loader#1077]
### What problem does this feature solve?
First,It can enhance the vue-loader ....

Second, I'm  developing with a project mixed with ts and js..  But I found the Option in ts-loader:
<pre>options: {
                    appendTsSuffixTo: [/\.vue$/]
           }
</pre>
doesn't work.  When I debug, I found the '.ts' suffix doesn't append to the '.vue' file . And  what the file I import '.vue' is a js file.. So , I think vue-loader should add this feature.  

### What does the proposed API look like?
The property 'loaders' in vue-loader isn't just a string...  It can be a object like :
<pre>
module: {
  rules: [
    {
      test: /\.vue$/,
      loader: 'vue-loader',
      options: {
        loaders: {
          ts: {
         loader:'ts-loader',
        options: {
                    appendTsSuffixTo: [/\.vue$/]
           }
           }
        }
      }
    }
  ]
}
</pre>

**Comment by LinusBorg** [comment]
That is actually generally possible today.

"Generally", because it only works for options that can be converted to the query format.

The point why your concrete example doesn't work is because this option makes no sense in that place. You have to define it on a rule for `.ts` files, not on the loader for ts *inside* of `.vue` files

**Comment by ffxsam** [comment]
I can vouch that options specified in the webpack rules do not get carried over into `vue-loader` loader options. For example, in my `webpack.base.conf.js`, I have this:

```js
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'tslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          configFile: 'tslint.json',
          tsConfigFile: 'tsconfig.json',
          typeCheck: true,
        },
      },
```

And in `vue-loader.conf.js`:

```js
'use strict';

const utils = require('./utils');
const config = require('../config');
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  loaders: {
    ...utils.cssLoaders({
      sourceMap: isProduction
        ? config.build.productionSourceMap
        : config.dev.cssSourceMap,
      extract: isProduction,
    }),
    ts: 'ts-loader!tslint-loader',
  },
  transformToRequire: {
    video: ['src', 'poster'],
    source: 'src',
    img: 'src',
    image: 'xlink:href',
  },
};
```

Despite this, when I run `yarn dev`, I see the following warning:
>Warning: The 'no-unused-variable' rule requires type information.

So the `typeCheck: true` option is indeed not being recognized by `vue-loader`.

**Comment by LinusBorg** [comment]
H, looking at this again my initial reply was incorrect. vue-loader generally does not "re-use" the options from other loaders like that. os @ffxsam, what you are seeing is expected behaviour. you have to add those options again for the ts-loader which you define in vue-loader options.

The problem of OP maybe has to do with the fact that vue-loader does stringifying the options object internally:
```
{
  loader: ts-loader,
  options: {
    appendTsSuffixTo: [/\.vue$/]
  }
}
// becomes:
'ts-loader?appendSuffixTo=/\.vue$/'
```

And maybe that conversion fails for this regexp option, But I'm not sure, maybe you can try it and verify?

**Comment by bobbylight** [comment]
@LinusBorg, I'm being a little slow here, could you provide an example of how to pass an option like `typeCheck: true` into the tslint-loader used by vue-loader?  What I've got today:

```javascript
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      ts: 'ts-loader!tslint-loader',
      css: 'vue-style-loader!css-loader'
    }
  }
}
```

I'm a little confused becuase options for "top-level" loaders are in the "options" section itself, where I'm specifying nested loaders for vue-loader:

```javascript
{
    test: /\.tsx?$/,
    enforce: 'pre',
    loader: 'tslint-loader',
    exclude: /node_modules/,
    options: {
        typeCheck: true
    }
}
```

I've tried a few things but none seem to work.

**Comment by LinusBorg** [comment]
`ts: 'ts-loader!tslint-loader?typeCheck'` would be the quickest way. 

You can pass anything to the `ts` potion that' an pass to the `use` option of a normal webpack rule

**Comment by bobbylight** [comment]
Thanks @LinusBorg.  Appending `?typeCheck` triggers the following error - I suppose this is a tslint-loader, being unhappy with the *.vue suffix (or rather just that the file isn't a "real" TypeScript source file)?  Note I've specified `appendTsSuffixTo: [ /\.vue$/ ]` where needed the ts-loader for *.ts files.  The "standard" tslint rules seem to run OK with this setup, but something about this option triggers this error.

```
ERROR in ./node_modules/ts-loader!./node_modules/tslint-loader?typeCheck!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./client/search.vue
Module build failed: FatalError:
Invalid source file: D:\dev\kinase\rak\src\main\frontend\client\search.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
```
