### ISSUE TITLE
New scoped ID generation since v13.4 may cause duplicated ID (needs option to disable)

### ISSUE THREAD

**Issue by whitetrefoil** [vuejs/vue-loader#1084]
### Version
13.5.0

### Reproduction link
[https://github.com/whitetrefoil/vue-ts-arch/blob/repo-1/src/components/my-global-comp/index.vue](https://github.com/whitetrefoil/vue-ts-arch/blob/repo-1/src/components/my-global-comp/index.vue)

### Steps to reproduce
1. npm install
2. npx gulp build

### What is expected?
4 .vue components get different scoped ID.

### What is actually happening?
All 4 .vue component got the same scoped ID: data-v-5b49856c

---
Since v13.4.0 the scoped ID is calculated base on vue file content, but in my project I separated the content to separated files and all .vue files look same, all generated scoped ID are same.

It will be better if there's a option / switch to choose the previous way of id generation.

**Comment by Jinjiang** [comment]
From this case I think both the content and file path need to be hashed.

**Comment by yyx990803** [comment]
fixed via #1086
