### ISSUE TITLE
从12.2.1升级到13.0.0后报错

### ISSUE THREAD

**Issue by YongMaple** [vuejs/vue-loader#1085]
### Version
13.0.0

### Reproduction link
[https://github.com/YongMaple/vue-ssr-template](https://github.com/YongMaple/vue-ssr-template)

### Steps to reproduce
vue-loader.config.js 
```
module.exports = {
  preserveWhitespace: false,
  postcss: [
    require('autoprefixer')({
      browsers: ['> 5%']
    })
  ]
}

```
webpack.base.config.js

```
...
module: {
noParse: /es6-promise\.js$/, // avoid webpack shimming process
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
...

```

### What is expected?
Normal execution

### What is actually happening?
Error: render function or template not defined in component: anonymous

**Comment by Jinjiang** [comment]
https://github.com/vuejs/vue-loader/releases/tag/v13.0.0
Please make sure the breaking change in v13.0.0: The `esModule` option is now `true` by default.
Thanks.
