### ISSUE TITLE
Support loading .vue file as a custom element with inline styles (similar to a web component)

### ISSUE THREAD

**Issue by andremarianiello** [vuejs/vue-loader#1089]
### What problem does this feature solve?
I want to use HTML imports to dynamically load web components and display custom elements on the screen. I want to use Vue to create my web components, but Vue components are not fully-fledged web components. I currently use https://github.com/karol-f/vue-custom-element to turn my vue component into a custom element, which I can import and use, but I have issues with styling.

Vue components (loaded from .vue files) use injectStyles to create the CSS needed to display the component correctly when the page is loaded. No styles are injected after this point, typically. However, this doesn't work correctly with the HTML imports polyfill because when you import the component multiple times, the styles get injected once, but not again, so the custom element appears unstyled. (I can go into more detail about this if necessary). I could work around this, but using styles from HTML imports is deprecated and going to be removed from Chrome in March 2018. I believe that if the styles from the .vue file were instead made part of the custom element, then the element would display correctly when I HTML import it every time. vue-custom-element already has support for inline CSS being added to the custom element, so all I would need was a way for vue-loader to support this use case.

### What does the proposed API look like?
I believe the minimum change I would need would be access to the styles loaded from a vue file in the loaded vue component (in the following example the styling is stored as a string in a property of the component called 'css'. This would allow me to create my custom element like so

```javascript
import MyElement from './MyElement.vue';

Vue.customElement('my-element', MyElement, {
  shadow: true,
  shadowCss: MyElement.css
});
```
The css could be a separate named export if you wished.

If vue-loader wanted to offer further support of custom elements inline styles, you could add a loader option to enable defining the custom element as part of the loading process. The user would simply import the component anywhere, using the loader option, and this would have the generated webpack javascript create the custom element for the user. This would be a nice experience for the user and make vue-loader that much more powerful for not much cost, but it is not strictly necessary.

**Comment by yyx990803** [comment]
This is now possible [with Vue CLI 3](https://github.com/vuejs/vue-cli/blob/dev/docs/build-targets.md#web-component). The usage is a bit different, and is currently reliant on building using the latest CLI, but we may make it individually usable when it's stable enough.
