### ISSUE TITLE
"You may need an appropriate loader" when webpacking .vue files using webpack.base.conf.js included from vuejs-templates.

### ISSUE THREAD

**Issue by ggJSC** [vuejs/vue-loader#1094]
### Version
13.5.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/83414/](https://jsfiddle.net/50wL7mdz/83414/)

### Steps to reproduce
The attached link is my `webpack.base.conf.js` which, as far as I know, is exactly as it appears when setting up using https://github.com/vuejs-templates/webpack.

This is my build.sh file for webpacking the copying the resulting file to another path (with doesn't work for whatever reason if I try to define it in webpack config options, CLI or otherwise).

```
webpack --config build/webpack.base.conf.js ./src/main.js bundle.js
yes | cp bundle.js /opt/htdocs/mediawiki/extensions/MeetingMinutes
```

### What is expected?
Webpack handles the `.vue` module using vue-loader.

### What is actually happening?
Module parsing error when reading the `<template>` tag call for single file vue components.

---
Just trying to migrate my existing SPA to VueJS but building/developing on the existing backend I have has been a nightmare. All I want to do is verify the webpack building is working, which it's not.

**Comment by eelcowen** [comment]
Hey ggJSC,

What was the issue? having the same problem...
