### ISSUE TITLE
keyframes scoped but -webkit-keyframs does't have change to -data-v-xxx

### ISSUE THREAD

**Issue by eadio** [vuejs/vue-loader#1099]
**i have some question like this. the keyframes has change to data-v-xxx,, but the -webkit-keyframes doesn't have changed。**

i write the code like this:
`<style lang="styl" scoped>
.ani
  animation a 1s ease 0s
@keyframes a
  0%
    width 0
  100%
    width 100px
</style>`

But they have become that：
`<style type="text/css">
.ani
 { 
-webkit-animation: a-data-v-xxx 1s ease 0s;
animation: a-data-v-xxx 1s ease 0s;}
**# //this -webkit-keyframes doesn't changed to -data-v-xxx**
@-webkit-keyframes a{
  0%{
    width: 0;
  }
  100%{
    width: 100px;
  }    
}
@keyframes a-data-v-xxx{
  0%{
    width: 0;
  }
  100%{
    width: 100px;
  }    
}
</style>`

**# My project is build on vue-cli webpack.**

How to solve it. Thinks!!

**Comment by Jinjiang** [comment]
v13.5.1 has solved this problem via #1058 
https://github.com/vuejs/vue-loader/releases/tag/v13.5.1
Please have a re-check.
Thanks.

**Comment by Jinjiang** [comment]
@LinusBorg I guess this issue could be closed :-)
