### ISSUE TITLE
miss postcss-loader in css dialect

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vue-loader#11]
for example:

```
<!-- main.vue -->

<style lang="sass">
  body {display: flex;}
</style>

<style>
  body {display: flex;}
</style>
```

- webpack loader config: `{ test: /\.vue$/, loader: vue.withLoaders({css: 'style!css!postcss-loader'})}`
- postcss config: `postcss: function () {return {defaults: [autoprefixer]}}`

and the different bundle:

```
"body {\n  display: flex; }\n"
"body {display: -webkit-box;display: -webkit-flex;display: -ms-flexbox;display: flex;}"
```

Seems like the `sass` code not processed by `postcss-loader`

**Comment by sjoerdvisscher** [comment]
You're using sass instead of css, so your config should be:

    { test: /\.vue$/, loader: vue.withLoaders({sass: 'style!css!postcss!sass'})}

**Comment by beihaifeiwu** [comment]
Hi sjoerdvisscher, I wite a vue component like:
```xml
<style lang="postcss">
  html, body {
  	background-color: gray(85);
  	color:color(red blackness(80%));
  }
</style>

<template>
<h1>Hello World</h1>
</template>

<script type="text/javascript">
	module.exports = {}
</script>
```
the webpack config like:

```js
        module: {
            loaders: [
                {test: /\.vue$/, loader: 'vue'},
                {test: /\.css$/, loader: "style!css!postcss"}
            ]
        },
        postcss: function () {
            return [cssnext, cssnano];
        }
```
but I can't get the vue compiled, Can you give me some advices?

**Comment by sjoerdvisscher** [comment]
What error do you get from webpack?

**Comment by beihaifeiwu** [comment]
The error looks like:

![qq 20150701091343](https://cloud.githubusercontent.com/assets/5372382/8445526/f55e8338-1fd0-11e5-8f18-494379eba7cc.png)

**Comment by beihaifeiwu** [comment]
Ok, I have found the solution, the correct webpack configuration is:
```js
{
        module: {
            loaders: [
                {test: /\.vue$/, loader: vue.withLoaders({postcss: 'style!css!postcss'})},
                {test: /\.css$/, loader: "style!css!postcss"},
                {test: /\.(png|jpg)$/, loader: 'url?limit=8192'}
            ]
        },
        postcss: function () {
            return [autoprefixer, cssnano(), cssnext()];
        }
    }
```
