### ISSUE TITLE
postcss plugin initialize repeatedly

### ISSUE THREAD

**Issue by zhuyunhe** [vuejs/vue-loader#1105]
### Version
13.6.1

### Reproduction link
[https://github.com/zhuyunhe/postcss-plugin-demo](https://github.com/zhuyunhe/postcss-plugin-demo)

### Steps to reproduce
I write a postcss plugin and test in my vue demo.

here is my postcss plugin code: 

```
var postcss = require('postcss');
module.exports = postcss.plugin('myplugin', function () {
    var count = 0    
    return function (root, result) {
        // 处理逻辑
        count   
        console.log('hello'   count)
    };
});
```
and my webpack config for *.vue: 
```
{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
            extractCSS: true,            
            postcss: {
                useConfigFile: true
            },
            loaders: {
            }
            
          // other vue-loader options go here
        }
```

postcss-config.js: 
```
var testPlugin = require('./src/util/postcss-test');


module.exports = {
    plugins: [
        require('autoprefixer'),
        testPlugin
    ]
}
```

when I do 'npm run dev' in terminal, i Got this in log:  
```
hello1  
hello2  
hello3  
hello4  
hello5   
hello6
```

### What is expected?
if I want to extract all the processed CSS in all Vue components into a single CSS file, I don't expect the postcss plugin initialize for every component. Can we do the postcss after I extracted the css in one css file, so that I only need to initialize the postcss plugins once ? 

### What is actually happening?
When I  extracted all the processed CSS in all Vue components into a single CSS file,  the postcss plugin initialize for every component. When I have many components, it's slow.

---
It's not a bug, but maybe it have better solution to make the process more efficiently

**Comment by Jinjiang** [comment]
After my test, if you use only one `*.vue` file with only one `<style>` and without `extractCSS` config, the plugin will run just once. But `extractCSS` config will cause the compiler run twice. It's not a bug imo.
Thanks.

**Comment by yyx990803** [comment]
`extractCss` should only be used in production. The reason why it is being called twice still needs some investigation, but doesn't seem like a bug-level issue.
