### ISSUE TITLE
support external template fragments

### ISSUE THREAD

**Issue by jschoedt** [vuejs/vue-loader#1106]
### What problem does this feature solve?
Having a full "browsable" HTML file that the front-end (html/css) developers can work with without the overhead of a server/compiler etc. The file can contain multiple vue templates and even nested templates that can be precompiled.

### What does the proposed API look like?
Extending the existing:
`<template src="./template.html"></template>`
to support fragments in a larger HTML file:
`<template src="./template.html#my-fragment"></template>`

An example is how the Errai framework is doing it: 
http://docs.jboss.org/errai/latest/errai/reference/html/sid-51806600.html#_using_an_html_fragment_as_a_template

**Comment by yyx990803** [comment]
I don't think this is in the scope of `vue-loader` - also, it's possible to write a custom webpack loader that does this. e.g. name it `fragment-loader` and then

``` vue
<template src="fragment-loader?id=fragment!./template.html">
```
