### ISSUE TITLE
Can't import image, if set css module

### ISSUE THREAD

**Issue by limichange** [vuejs/vue-loader#1109]
### Version
13.6.1

### Reproduction link
[https://github.com/limichange/vue-loader-demo](https://github.com/limichange/vue-loader-demo)

https://github.com/limichange/vue-loader-demo/blob/master/src/App.vue#L20-L36

### Steps to reproduce
You can look my code.

### What is expected?
import image correct.

### What is actually happening?
Error
```
To install it, you can run: npm install --save assets/logo.png
```

**Comment by Jinjiang** [comment]
That's not `vue-loader`'s bug imo. If you remove `"postcss-url": {}` in `.postcssrc.js` it works fine. Please have a check on your own.
Thanks.

**Comment by limichange** [comment]
👍
You're right. Thank you so much.

**Comment by limichange** [comment]
🤔  but why 'scoped' is fine?

**Comment by Jinjiang** [comment]
Good question. Maybe it need a deep look into `postcss-url` and `css-loader` (The feature of CSS Modules is implemented in `css-loader`).
