### ISSUE TITLE
the css is not injected in the dev mode when use vue-loader > 12.0.0

### ISSUE THREAD

**Issue by jiangtao** [vuejs/vue-loader#1111]
### Version
13.6.1

### Reproduction link
[https://github.com/jiangtao/vue-loader-test](https://github.com/jiangtao/vue-loader-test)

### Steps to reproduce
```bash
git clone https://github.com/jiangtao/vue-loader-test.git
cd vue-loader-test
yarn install
yarn run dev
```

### What is expected?
When open the page, `This is a alert dialog` is shown at the left bottom corner, this is a dialog with css.

### What is actually happening?
When open the page, `This is a alert dialog` is shown at the left bottom corner, this is a dialog without css.

---
webpack: >= 2.7
vue-loader: >=12.0.0
npm: >=5.0

**Comment by berwin** [comment]
https://github.com/vue-tools/vt-alert/blob/master/src/pc/index.vue
这个文件中有一个代码是这样写的

```html
<style src="./style.css"></style>
```
我不太清楚 style 标签什么时候可以写src了，，，，难道是我孤陋寡闻了。。这有点触及我的知识盲区了。。😝😜😁

**Comment by yyx990803** [comment]
This is a problem with your dependency `vt-alert`. We can't tell if this is really a `vue-loader` problem. Also, 12.0 is outdated.
