### ISSUE TITLE
got an error when use array in mounted

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vue-loader#1116]
```javascript
mounted(){
	[2,3].forEach(item=>{
		console.log(item)
	})
  }
```
![image](https://user-images.githubusercontent.com/1060733/34757463-4dbbce64-f60c-11e7-9ba8-43fe6de73a8c.png)

**Comment by Jinjiang** [comment]
I cannot reproduce this error. It works for me. I suggest you to have a look at your dev environment carefully. Or you should provide more information which is enough to reproduce your problem.
Thanks.

**Comment by yyx990803** [comment]
You probably missed a semicolon on the line before it.
