### ISSUE TITLE
[Feature Request] Better handling of compile errors in hot mode

### ISSUE THREAD

**Issue by skyronic** [vuejs/vue-loader#112]
If I encounter a compile error in hot mode, currently the following happens:

1. The console shows an error and page goes blank.
2. If I fix the error the app reloads and state is brought to initial state

It would be nice if:

a) Instead of a blank page, the error message is displayed on the screen
b) After fixing the compile error, the hot-state is refreshed (I checked with react's hot module replacement and the state is persisted even if there's a compile error and it's fixed)

I tried looking into the code and adding this myself but I couldn't figure it out.

**Comment by yyx990803** [comment]
Good suggestion, will look into it!

**Comment by yyx990803** [comment]
I did some brief investigation and it seems react-transform only catches runtime render errors rather than compile errors. AFAIK there's no easy way to intercept and handle the compilation error emitted from e.g. webpack or babel-loader while keeping current state.

**Comment by chrisvfritz** [comment]
@yyx990803 I believe [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) uses [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) to catch and display syntax errors.

**Comment by yyx990803** [comment]
@chrisvfritz thanks for the info! The great news is that it doesn't need changes in `vue-loader` and I have updated the official vue-cli webpack template to use that instead: https://github.com/vuejs-templates/webpack/blob/master/template/build/dev-server.js

**Comment by chrisvfritz** [comment]
Thank _you_ @yyx990803. You're definitely one of the most responsive ecosystem maintainers I've seen!
