### ISSUE TITLE
Cannot import template using webpack

### ISSUE THREAD

**Issue by jrgleason** [vuejs/vue-loader#1121]
My current working code looks like this...

    {
      template: require("upload.html"),
      ...
    }

I am trying to do something like this...

    <template>require("./upload.html")</template>

But it said I needed a tag so I did...

    <template><div>require("./upload.html")</div></template>

But this doesn't run the html-loader before the vue-loader and I just get the require text. Is there a way to accomplish this besides using the template property in the component?

**Comment by patriciussanctus** [comment]
use in template
```<template src="./upload.html">```
or in component
```
<template>
  <div v-html="uploadHtml"></div>
</template>
<script>
{
  uploadHtml: require('./upload.html')
}
</script>
```
or in compiled component
```
new Vue({ template: require('./upload.html') })
```

**Comment by jrgleason** [comment]
@patriciussanctus Can I use src with script too?

**Comment by Jinjiang** [comment]
Sure. Here is the docs: https://vue-loader.vuejs.org/en/start/spec.html#src-imports
