### ISSUE TITLE
Removal of fragments makes it difficult to deal with certain elements.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-loader#1129]
Certain components, for example ones that need to render two `<tr>` elements, do not work without fragments.

( @LinusBorg, this [isn't a question](https://github.com/vuejs/vue-loader/issues/384#issuecomment-271326499), it's an issue. )

In the `<tr>` case, an ugly workaround might be to create a new component that renders `slot`, then wrap the `<tr>`s in that wrapper component so that they get slotted into the no-op wrapper.

**Comment by LinusBorg** [comment]
> ( @LinusBorg, this isn't a question, it's an issue. )

It's a feature request, I would say, and has nothing to do with vue-loader.

We already have an issue for this in the appropriate repository (vue)

https://github.com/vuejs/vue/issues/7088

**Comment by trusktr** [comment]
cc @junerockwell @nbdavies @harrywong (people that expressed the problem they had in the other issue)

**Comment by trusktr** [comment]
@LinusBorg Sorry about that, it seemed like a vue-loader issue initially based on that other issue. I add some thoughts over there. 😊

**Comment by LinusBorg** [comment]
No problem. :)
