### ISSUE TITLE
Scoped CSS on slot content

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-loader#113]
It could be a legitimate use case that a component wants to style slot content inserted from parent. Currently it's a bit awkward to achieve that.

Red: https://github.com/vuejs/vue/issues/2094

**Comment by rascada** [comment]
:+1:

**Comment by oliviertr** [comment]
What's the recommended approach for this currently? Are we expected to style the parent content from the parent each time we use the component (assuming scoped style in parent)? Or should we just set a global css style elsewhere (eg: `.my-component-slot-paragraph { color: blue; }` )? Some other way?

**Comment by ealves-pt** [comment]
:+1:

**Comment by rguanghui** [comment]
👍

**Comment by flyyang** [comment]
so... what's the solution for this issue

**Comment by booxood** [comment]
@flyyang I solution it to write new style that no scoped...

**Comment by booxood** [comment]
@yyx990803 Whether to consider providing another way of generating class for scoped?
```css
/* now */
.item[_v-3f1fec1e] {}
/* css-modules */
.item_v-3f1fec1e {}
```

**Comment by flyyang** [comment]
I'd like this go `vue-loader`. 

Don't break the single file component law.

**Comment by nickspiel** [comment]
This is currently causing us massive headaches. @yyx990803 any thoughts on how this can be addressed?

**Comment by devboxr** [comment]
I keep having this issue, and not only this. Another related issue is that if you generate content dynamically, the namespace tag is also not applied. Scoping of CSS could be really useful, but for the majority of components you eventually run into a wall.

**Comment by yyx990803** [comment]
This is now supported in 9.x.

**Comment by iiiron** [comment]
this is a important change that should be written into the official document

**Comment by lxmfly123** [comment]
> so... what's the solution for this issue

I use `/deep/` to apply style on slot content, see [here](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors).

**Comment by Arturexe** [comment]
Sooooo, I'm from the future and I'm still missing this feature like hell. It pretty much makes layouts (slot components) useless

**Comment by LinusBorg** [comment]
You're aware that you are commenting this on an issue that was closed because the feature was implemented in 2016, are you?

**Comment by Arturexe** [comment]
@LinusBorg Really? I wasn't able to find a way to use this, not on git nor stack or elsewhere. Mind sharing how it works?

**Comment by LinusBorg** [comment]
I assume you mean this:


https://vuejs.org/api/sfc-css-features.html#slotted-selectors
