### ISSUE TITLE
Empty children of flex element, that contain margin do not return correct height

### ISSUE THREAD

**Issue by vblagomir** [vuejs/vue-loader#1133]
### Version
13.7.0

### Reproduction link
[https://codepan.net/gist/23d46422c6e02292480c739122783705](https://codepan.net/gist/23d46422c6e02292480c739122783705)

### Steps to reproduce
```
<template>

  <div class='wrapper'>
    <div class='inner'></div>
  </div>

  <!-- <div style='display: flex; background: blue;'>
    <div style='margin: 1rem; background: red;'></div>
  </div> -->

</template><script>

  export default {
    mounted () {
      console.log('Height 1', this.$el.clientHeight)

      this.$nextTick(() => {
        console.log('Height 2', this.$el.clientHeight)
      })

      setTimeout(() => {
        console.log('Height 3', this.$el.clientHeight)
      }, 300)
    }
  }

</script><style>

  .wrapper {
    display: flex;
    background: blue;
  }

  .inner {
    margin: 1rem;
    background: red;
  }

</style>
```

### What is expected?
At least 'Height 2' (that happened after the $nextTick) expect to equal 'Height 3'. Ideally all 'heights' should be equal 'Height 3'.

### What is actually happening?
'Height 1' and 'Height 2' return 0 and only after 'some' delay, 'Height 3' returns correct height.

---
This happens only when using styles within <style></style> tags within .vue files. When using in-line styles or external full-page styles, the 'Height 1' and 'Height 2' are returning correct height right away. You can check it by uncommenting the commented part of the template.

P.S. The issue is not reproducible on JSFiddle/JSBin/CodePen/CodePan because none of them seem to support vue-loader and .vue files. Yet I have put the example which works fine. But if you try to run it within a .vue file the bug will be evident. 

P.P.S. This thing is required to get and match heights of absolutely positioned child elements.

**Comment by LinusBorg** [comment]
.S. The issue is not reproducible on JSFiddle/JSBin/CodePen/CodePan because none of them seem to support vue-loader and .vue files. Yet I have put the example which works fine. But if you try to run it within a .vue file the bug will be evident.

You can of course link to a small git repository re-recreating the issue. That ensures we have the exact same setup as you do.

**Comment by vblagomir** [comment]
I run it in a heavy setup under Meteor at the moment. Once I figure out how to setup a lightweight Vue-only environment, will update.

**Comment by LinusBorg** [comment]
you may do:
```
npx vue-cli init webpack-simple someFolder
```

**Comment by vblagomir** [comment]
Ok, I have managed to install it but can not reproduce it on the 'light' vie-only build... So it must be an issue of https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component or https://github.com/meteor-vue/vue-meteor implementation. Will have to figure out there. Thank you for quick feedback.
