### ISSUE TITLE
EsLint is not recognizing : in vue file

### ISSUE THREAD

**Issue by jrgleason** [vuejs/vue-loader#1134]
I have the following component

```
<script>
export default {
  name: "log-graph",
  template: require("./logGraph.html"),
  create: function(){
    console.log("On Create Log Graph");
  }
}
</script>
<style scoped>
</style>
```

When I try to run Webpack I get the following error. 

```
ERROR in ./src/logGraph.vue

...\src\logGraph.vue
  3:7  error  Parsing error: Unexpected token :

? 1 problem (1 error, 0 warnings)

 @ ./src/index.js 3:0-38
```

If I am not mistaken that means the bad char is the `:` in `name: "log-graph",` but as far as I can tell from example that is acceptable.

**Comment by Jinjiang** [comment]
it works for me.
I suggest you to have a check to the elsewhere of your whole project. Or you could provide more information to let us help you better.
Thanks.

**Comment by LinusBorg** [comment]
Either way this is related to eslint, not vue-loader
