### ISSUE TITLE
use vue-loader?inject with scss and webpack 2 can not resolve global settings file

### ISSUE THREAD

**Issue by StudentWan** [vuejs/vue-loader#1135]
### Version
13.7.0

### Reproduction link
[https://github.com/StudentWan/ashen-blog/tree/dev](https://github.com/StudentWan/ashen-blog/tree/dev)

### Steps to reproduce
```
git clone https://github.com/StudentWan/ashen-blog/tree/dev
npm install
npm run test-client
```

**Actually, its easier to just explain what happened...**

Like [Loading a global settings file](https://vue-loader.vuejs.org/en/configurations/pre-processors.html) says, we can use `sass-resources-loader` to set a global setting file

When comes to unit test, I want to use inject-loader

```
const exampleInjector = require('!!vue-loader?inject!./example.vue')
```

Meanwhile, using scss scoped style in my component, which references to a global variable.

```CSS
<style lang="scss" scoped>
.title {
    color: $title;
    padding-bottom: 0.3em;
}
</style>
```

### What is expected?
style get parsed correctly 

### What is actually happening?
![scss error](http://p20zi8dae.bkt.clouddn.com/vue-err.png)

---
This issue is actually has connect with issue#724

**Comment by HaoyCn** [comment]
It's acually not a problem of `vue-loader`. When you use a inline loader, global configuration won't be applied. [See more here](https://webpack.js.org/concepts/loaders/#inline).

**Comment by StudentWan** [comment]
@HaoyCn

Thx for your help!

So there is no way to continue using my global configuration during unit test?

**Comment by HaoyCn** [comment]
I myself didn't have a try but maybe `webpack.LoaderOptionsPlugin` can help you. Use it like below:

```
new webpack.LoaderOptionsPlugin({
    vue: {
        // your loader options
    }
})
```

**Comment by StudentWan** [comment]
@HaoyCn

Thx a lot, I’ll take a shot.
