### ISSUE TITLE
我使用的vue-loader版本是11.3.4，出现vue.esm.js?57ca:578 [Vue warn]: Failed to mount component: template or render function not defined.只是一两个文件有，而且esModule也改成false了

### ISSUE THREAD

**Issue by ShannyShanny** [vuejs/vue-loader#1137]
{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
         
      },

var vueLoaderConfig = require('./vue-loader.conf')

module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: isProduction
      ? config.build.productionSourceMap
      : config.dev.cssSourceMap,
    extract: isProduction
  }),
  esModule: false
}

**Comment by LinusBorg** [comment]
https://new-issue.vuejs.org/?lang=zh-cn
