### ISSUE TITLE
[idea] normalize the component definition on import.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-loader#1138]
Based on https://github.com/vuejs/vue/issues/7494, it may be a good idea to normalize the component definitions (f.e. the `props`) here in the loader so that the definition is already normalized by the time it is imported, and that way people who are relying on the spec for various things don't have to conditionally check for the non-mormalized vs normalized state of the spec.

As a workaround, someone who needs to rely on the spec can call

```js
import spec from './somewhere.vue'

// causes normalization
Vue.extend(spec)

// now it is normalized, f.e.
console.log("type" in spec.props.someProp) // will be true
```

otherwise,

```js
import spec from './somewhere.vue'

// spec.props is not normalized yet
console.log("type" in spec.props.someProp) // will throw if spec.props is an array.
```

**Comment by trusktr** [comment]
What's the use case?

Some library authors might like to rely on it. For example, suppose someone wants to make a function that accepts a component definition then outputs a Custom Element that renders based on that definition. They might at first rely on the non-normalized form of the definition. Then later, perhaps due to async events, the definition might get normalized and cause an unexpected error (hopefully not in production).

**Comment by trusktr** [comment]
Another example:

```js
import spec from './somewhere.vue'

// the person looks at the spec during development using the debugger, and sees props is an array, then:

for (for const prop of spec.props) {
  // works with an array
}
```

Then, if by chance the spec get normalized on other application startups:


```js
import spec from './somewhere.vue'

// the person looked at the spec during development using the debugger, and saw props was an array, however they didn't forsee some other process may have normalized it, then:

for (for const prop of spec.props) {} // Uncaught TypeError: spec.props is not iterable
```

**Comment by posva** [comment]
I don't think normalizing props on an imported component is a good idea because it's counter-intuitive and it would also be a breaking change in vue-loader

**Comment by yyx990803** [comment]
I don't think this should be baked into `vue-loader` as it could be counter-intuitive for another group of users who expect to import exactly what is exported.

This should also be doable in userland - you can create a [pitching loader](https://webpack.js.org/api/loaders/#pitching-loader), chained before `vue-loader`, that imports the remaining request and export a normalized version of it.
