### ISSUE TITLE
CSS Variables not working when using single file components

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs/vue-loader#1140]
### Version
13.7.0

### Steps to reproduce
When CSS variables are imported they are not getting resolved. For example, the below is not working:
````
<style src="../../static/css-var.css"></style>
<style scoped>
	.propContent {
		background: var(--background-active);
	}
</style>
````
where as defining the css variables directly in the component file is working. The below works.
````
<style scoped>
      :root {
          --background: #495060;
       }   
	.propContent {
		background: var(--background-active);
	}
</style>
````

### What is expected?
CSS Variables should be importable and work correctly

### What is actually happening?
CSS Variables defined in another file are not getting resolved. Not working

**Comment by HaoyCn** [comment]
Different sections, even if they are the same type, are compiled independently. I suggest you to use SCSS/SASS/LESS to deal with this case.
