### ISSUE TITLE
[webpack@next] vue-loader support for webpack 4 breaking changes.

### ISSUE THREAD

**Issue by VesterDe** [vuejs/vue-loader#1142]
### What problem does this feature solve?
Vue-loader seems to have some problems with webpack4, as seen here: https://github.com/webpack/webpack/issues/6064#issuecomment-349135128

For ESLint-loader (https://github.com/MoOx/eslint-loader/issues/204) and File-loader (https://github.com/webpack-contrib/file-loader/issues/233) the issues are related, so I though I'd open this one for reference and to get a head-start on solving it for the upcoming webpack4 stable release, in about a month.

### What does the proposed API look like?
I'm not sure what the fix is exactly... Reproducing the code that fixed file-loader didn't work outright for me.

**Comment by sqal** [comment]
I think it already supports WP4 https://github.com/vuejs/vue-loader/commit/289b4d9e7c4d2761597c9f038332897abb5c3f76 :)

**Comment by yyx990803** [comment]
Yes, 14.1.0 should be compatible with webpack 4 now. However note a bunch of plugins that Vue apps typically rely on are not compatible with wp4 yet, so you might want to wait before upgrading.

**Comment by jingzheshan** [comment]
@yyx990803 any chance we could have a replacement for extract-text-plugin with native Webpack 4 css module supports? https://github.com/webpack/webpack/pull/6448

**Comment by LinusBorg** [comment]
Once that feature is actually available and stable, we will surely integrate it, if that is even necessary.
