### ISSUE TITLE
Add route attribute to template tag to simplify route config

### ISSUE THREAD

**Issue by jarrettv** [vuejs/vue-loader#1149]
### What problem does this feature solve?
This suggestion is in honor of single file components (which are awesome) and would simplify route config and reduce code. The intent is not to expose the full feature set of vue-router but cover the 80/20 rule.

Simple ✔️
Intuitive ✔️

https://github.com/vuejs/vue-router/issues/2039

### What does the proposed API look like?
`Vue.use(VueRouter)`

**./pages/Dashboard.vue**
`<template route="/"></template>`

**./pages/UserDetail.vue**
`<template route="/users/:id"></template>`

**Comment by yyx990803** [comment]
I'd rather use a file-structure based convention than having it placed in SFCs. Having to tightly couple `vue-router` and `vue-loader` for this is not ideal.
