### ISSUE TITLE
vue-loader v14.1.* make error compile with happypack 4.0.1

### ISSUE THREAD

**Issue by TrungRueta** [vuejs/vue-loader#1152]
### Version
14.1.0

### Reproduction link
[https://github.com/TrungRueta/vue-happy-issue-v14](https://github.com/TrungRueta/vue-happy-issue-v14)

### Steps to reproduce
1. open file `webpack.json`
2. see vue-loader version (default is `v14.1.0`)
3. run: `yarn` to install packages
3. see `line 42` and `line 44` in [`webpack.json`] and read my description. 
4. run: `webpack` 
5. see error response.
6. go to [`webpack.json`] and switch block comment from `line 42` to `line 43`
7. run: `webpack` 
8. see terminal run thought and complete
9. open file [`package.json`] . change vue-loader `v14.1.0` to `v13.7.1`
10. run: `yarn` to install packages again
11. run: `webpack`
12. see process work fine
13. change again block `line 42` and open `line 43` ( use `happypack`)
14. run: `webpack`
15. see process work fine

### What is expected?
vue-loader should run thought happypack setup with no issue

### What is actually happening?
happypack hanged up with error:
ERROR in ./src/test.vue
Module build failed: TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at Object.module.exports (/buildweb/demo/vue-happy/node_modules/vue-loader/lib/loader.js:25:10)
....

---
I am not good english to explains detail, so i make small project with minimum setup. Please see in webpack.config.js my description and try. 

Thankyou!!

**Comment by Jinjiang** [comment]
It seems that in v14+ vue-loader [internally](https://github.com/vuejs/vue-loader/blob/v14.1.0/lib/loader.js#L25) uses a hacky API [this._compilation](https://webpack.js.org/api/loaders/#this-_compilation). That is lost under happypeck and causes `TypeError: Object.defineProperty`.

**Comment by yyx990803** [comment]
Tracking in #1179
