### ISSUE TITLE
In lib\template-compiler\preprocessor.js, `this._compilation.__vueOptions__` is not available when hot-reload

### ISSUE THREAD

**Issue by cutsin** [vuejs/vue-loader#1154]
Example:
In `a.vue`:
```vue
<template lang="pug" src="./b.pug"></template>
```
In `vue-loader.conf.js`:
```javascript
module.exports = {..., template: {basedir: '/abc'}}
```
If I saved in `a.vue`, everything is ok.
If I saved in `b.pug`,  I got a error like: `Module build failed: Error: the "basedir" option is required to use includes and extends with "absolute" paths`

**Comment by yyx990803** [comment]
Tracking in #1179
