### ISSUE TITLE
the first result of vue-loader processed by webpack

### ISSUE THREAD

**Issue by stoneyallen** [vuejs/vue-loader#1155]
When I print the result of vue-loader, I get this code 
`
function injectStyle (ssrContext) {
  if (disposed) return
  require("!!vue-style-loader!css-loader!../../node_modules/vue-loader/lib/style-compiler/index?{\"vue\":true,\"id\":\"data-v-5ac14b92\",\"scoped\":false,\"hasInlineConfig\":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./entry.vue")
}
var normalizeComponent = require("!../../node_modules/vue-loader/lib/component-normalizer")
/* script */
export * from "!!babel-loader!../../node_modules/vue-loader/lib/selector?type=script&index=0!./entry.vue"
import __vue_script__ from "!!babel-loader!../../node_modules/vue-loader/lib/selector?type=script&index=0!./entry.vue"
/* template */
import __vue_template__ from "!!../../node_modules/vue-loader/lib/template-compiler/index?{\"id\":\"data-v-5ac14b92\",\"hasScoped\":false,\"buble\":{\"transforms\":{}}}!../../node_modules/vue-loader/lib/selector?type=template&index=0!./entry.vue"
`
Why not deal with this process at once, can you answer my doubts？

**Comment by EnMod** [comment]
What did you do to resolve this?

**Comment by aoliaoliao** [comment]
I got this quession too, how do I create one loader after vue-loader ?
