### ISSUE TITLE
ECONNRESET building on digitalocean, works on local ubuntu

### ISSUE THREAD

**Issue by sgehrman** [vuejs/vue-loader#1157]
Anyone know what's going on?  It was building previously.  Only change is I upgraded disk size to add space on digital ocean.

steve@stellar-node:~/github/stellarkit.io$ yarn site
yarn run v1.3.2
$ cross-env NODE_ENV=production webpack --progress --hide-modules
Hash: f6889c19b3fcb545d09f
Version: webpack 3.10.0
Time: 57332ms
                                      Asset       Size  Chunks                    Chunk Names
images/74f7cdffc9b2c3f62771c7acac3f512d.png    45.5 kB          [emitted]
images/377720723dcfb17eb3f0f5cb03f6469d.png    19.7 kB          [emitted]
images/511c6653a04283943a17e5fb009609f4.png  464 bytes          [emitted]
                                    site.js    1.82 MB       0  [emitted]  [big]  main

ERROR in ./src/target-site/images/spaceman.jpg
Module build failed: Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at Pipe.onread (net.js:623:25)
 @ ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-90e7eecc","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/target-site/SiteAppHeader.vue 7:690-722
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-90e7eecc","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/target-site/SiteAppHeader.vue
 @ ./src/target-site/SiteAppHeader.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/target-site/SiteApp.vue
 @ ./src/target-site/SiteApp.vue
 @ ./src/target-site/site-entry.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Also seeing this too, slightly different

ERROR in ./src/target-site/images/spaceman.jpg
Module build failed: Error: write EPIPE
    at _errnoException (util.js:1003:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:866:14)
 @ ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-90e7eecc","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/target-site/SiteAppHeader.vue 7:690-722
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-90e7eecc","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/target-site/SiteAppHeader.vue
 @ ./src/target-site/SiteAppHeader.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/target-site/SiteApp.vue
 @ ./src/target-site/SiteApp.vue
 @ ./src/target-site/site-entry.js
error Command failed with exit code 2.

**Comment by sgehrman** [comment]
found this in npm install.  I'll investigate mozjpeg...

The `/home/steve/github/stellarkit.io/node_modules/img-loader/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/steve/github/stellarkit.io/node_modules/img-loader/node_modules/mozjpeg/vendor" --bindir="/home/steve/github/stellarkit.io/node_modules/img-loader/node_modules/mozjpeg/vendor" --libdir="/home/steve/github/stellarkit.io/node_modules/img-loader/node_modules/mozjpeg/vendor" && make -j1 && make install -j1
Command failed: autoreconf -fiv
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by czelusniakdawid** [comment]
Hi,

Unfortunately, I am getting the same error on when running Webpack on Node 9.5.0 on Debian 9 stretch. Could you help me with debugging this issue?

Webpack: 3.7.1
npm: 5.6.0
Node: 9.5.0
Debian: 9.3.0

My command:
```
./node_modules/webpack/bin/webpack.js -p --progress
```

```
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

Thank you in advance :)

**Comment by sgehrman** [comment]
Look at the output of non install and install any missing tools. I can't remember which one's I needed. But that was the solution.

**Comment by czelusniakdawid** [comment]
Could you tell me how can I exactly check which tools are missing? I can't find that information in logs.
