### ISSUE TITLE
关于 `vue-template-compiler` 的疑惑

### ISSUE THREAD

**Issue by yugasun** [vuejs/vue-loader#1158]
默认情况下 `vue-template-compiler` 是作为 `peerDependencies` 的，也就是 `npm install` 的时候是不会自动安装的，但是实际项目使用 `.vue` 文件时，缺少这个依赖，是会报错的，然后不得不手动安装。建议将 `vue-template-compiler` 依赖移到 `dependencies` 中。

**Comment by JounQin** [comment]
https://github.com/vuejs/vue-loader/pull/1123#pullrequestreview-88420554

**Comment by yugasun** [comment]
@JounQin 这个跟 https://github.com/vuejs/vue-loader/pull/1123#pullrequestreview-88420554 虽然类似，但是官方解释无法信服。因为不可能每个人开发 vuejs 项目都是通过 `vue-cli` 脚手架工具初始化，对于初学者来说，这个问题一直都存在。虽然可以通过每次出现问题，手动安装就行，但这不正是说明了 `vue-loader` 是无法缺失 `vue-template-compiler` 依赖吗？而且，至少官方文档在此处有所说明，以免造成误解。

**Comment by JounQin** [comment]
里面已经说了是为了保证跟 `vue` 版本完全一致啊，用 `dependencies` 是无法保证的，因为 `vue` 升级 `vue-loader` 不一定需要升级。

**Comment by yugasun** [comment]
恩，理解，还是建议 README 中添加相关说明。

**Comment by Jinjiang** [comment]
@JounQin 正解
@yugasun 目前 vue-loader 使用时需要配置细节确实很多，诸如 `vue-template-compiler` 版本号这样的细节，最“傻瓜”且通用的方式毫无疑问就是直接通过 vue-cli 或最新的 vue@cli 创建了。如果你留意过 vue-loader 文档的 installation 那一页的历史的话就更能体会了，包括你建议的 README 里也做了明确说明。
以上

**Comment by yugasun** [comment]
@Jinjiang 感谢耐心解答，的确现在坐着也推荐使用 `vue-cli` 直接傻瓜式创建项目，这里只是为了在自己从零配置项目过程中，慢慢学习，发现这个疑惑，才提出的。现在没什么疑问了。

**Comment by wang-176** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Build:指定的路径不存在:“E:\vue项目代码\HaiPingMian\HaiPingMian\hpm\node_modules\vue-template-compiler\types\tsconfig.json”。	HaiPingMian	E:\vue项目代码\HaiPingMian\HaiPingMian\tsc		

请问这是什么错误？这什么意思？
