### ISSUE TITLE
How to remove eval and Function constructor from webpack build to avoid CSP issues

### ISSUE THREAD

**Issue by akanshgulati** [vuejs/vue-loader#1159]
### Version
14.1.0

### Reproduction link
[https://github.com/vuejs-templates/webpack-simple](https://github.com/vuejs-templates/webpack-simple)

### Steps to reproduce
Just use yarn run build and you will find eval method being used by vue-loader

### What is expected?
I am expecting of no eval methods as I am using vue runtime version and tried building with latest version of webpack and vue-loader too. Still see eval method. There should be no eval check line in the end. 

### What is actually happening?
This line

g = g || Function("return this")() || (1,eval)("this");

This comes while running prod as well as dev build.

---
I have opened same issue with webpack too but I believe issue is with loader and trying to update vue-loader team about the same https://github.com/webpack/webpack/issues/6461

**Comment by Jinjiang** [comment]
As [the docs](https://vuejs.org/v2/guide/installation.html#CSP-environments) says, the bundle which is using the Vue (runtime-only build) with webpack + vue-loader is CSP compliant. And the `webpack-simple` template you mentioned just works fine.
And I can't find this line of code: `g = g || Function("return this")() || (1,eval)("this");` sorry. 
Would you please have a check again, or provide more details to let us find the problem?
Thanks.

**Comment by yyx990803** [comment]
To avoid CSP you need to use the runtime-only build by commenting out [this line](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js#L77)

**Comment by akanshgulati** [comment]
Actually the problem was in webpack config. It is not an issue of vue-loader. 
````
g = g || Function("return this")() || (1,eval)("this");
````
This was coming because of global scope. I just added `node: false` in webpack config file and it didn't come after that.
