### ISSUE TITLE
template可以import多个文件吗

### ISSUE THREAD

**Issue by zhouwenbin** [vuejs/vue-loader#116]
比如用gulp生成了svg symbol，生成的是一个svg文件，需要弄成inline svg，要怎么import进来

**Comment by yyx990803** [comment]
作为 `<img>` 用 url-loader 做成 base64 内联。具体用法请自行查找相关文档

**Comment by zhouwenbin** [comment]
说的不是一个东西

**Comment by yyx990803** [comment]
那请你说清楚一点

**Comment by lilijialiang** [comment]
我也遇上同样的问题，想把 svg 文件直接作为元素 inline到 html 中，因为这样比较好用 css 控制样式。img   src 的确可以引用到 svg，但是 css 不好控制 svg 样式。
