### ISSUE TITLE
`postcss` option is not working after v14.0.2

### ISSUE THREAD

**Issue by weizhenye** [vuejs/vue-loader#1160]
### Version
14.1.1

### Reproduction link
[https://gist.github.com/weizhenye/2288bcf2854f4ae38f5ba604548fabd3](https://gist.github.com/weizhenye/2288bcf2854f4ae38f5ba604548fabd3)

### Steps to reproduce
1. Download [this gist ZIP](https://gist.github.com/weizhenye/2288bcf2854f4ae38f5ba604548fabd3)
2. `npm i`
3. `npm i vue-loader@14.0.1`
4. `npm run build`
5. Open `dist/style.css`
6. `npm i vue-loader@14.0.2`
7. `npm run build`
8. Open `dist/style.css`

### What is expected?
The nesting syntax should be compiled by PostCSS

### What is actually happening?
`postcss: [cssnext()]` in `webpack.config.js` is not working in 14.0.2 (and also v14.1.1)

---
It might be caused by [this commit](https://github.com/vuejs/vue-loader/commit/289b4d9e7c4d2761597c9f038332897abb5c3f76)

**Comment by blake-newman** [comment]
I have found this to be an issue with cssnext, for a while. At [my workplace](https://www.askattest.com/) we have a React app also with same issue. Havn't explored to deeply, however you can resolve this simply adding https://github.com/postcss/postcss-nested, this plugin seems to work much better than that provided by the cssnext tooling.

**Comment by weizhenye** [comment]
@blake-newman 
No, it's not about cssnext, it **is** an issue with vue-loader.
Any other conditions are same, the only difference is update vue-loader from v14.0.1 to v14.0.2, and then **all** plugins in postcss option is not working.
I just install `postcss-nested` and replace config with `postcss: [require('postcss-nested')()]`, it still not work.
You can reproduce it with above steps.

**Comment by jarrodldavis** [comment]
I’m having the same issue, even when using `postcss.config.js` instead of the inline config in webpack. Downgrading to 14.0.1 also fixes the problem for me.

**Comment by sscharfenberg** [comment]
Same problem here.
Setup is similar, instead of cssnext I `postcss-use flexbugs-fixes`, `autoprefixer` and `cssnano` - none of them are applied with vue-loader@14.1.1.

**Comment by yyx990803** [comment]
Should be fixed in 905b813
