### ISSUE TITLE
SFC: Unclosed <style> tag should throw error, or should work

### ISSUE THREAD

**Issue by hibiyasleep** [vuejs/vue-loader#1161]
### What problem does this feature solve?
In Single File Component, `<script>` tag may or may not closed, so this works:

```html
<template>
  <div class="chicken">
    Chicken: {{ chicken }}
  </div>
</template>

<script>
export default {
  data() { return { chicken: 'fried' } }
}
// (EOF)
```

However, `<style>` isn't; if there's no `</style>`, styles are **simply ignored** without any warning or errors.

```html
<template>
  <div class="chicken">
    Chicken: {{ chicken }}
  </div>
</template>

<script>
export default {
  data() { return { chicken: 'fried' } }
}
</script>

<style scoped>
.chicken { /* super important */
  font-weight: 900;
}
/* (EOF) */
```

### What does the proposed API look like?
Any `<template>`, `<script>`, `<style>` tags should **explicitly**:

* Closed - unclosed tag should throw a warning and refuse to build.
* or May not closed - contents should build correctly even it's not closed.

**Comment by Jinjiang** [comment]
Agree, I think the [vue-template-compiler](https://github.com/vuejs/vue/blob/dev/src/compiler/parser/html-parser.js) could be improved at this point. But actually, it's not written in vue-loader. I suggest it's better to discuss this issue in vue main repo. 🙂
Thanks.

**Comment by hibiyasleep** [comment]
Oops, I'll move this issue there. sorry ;(
