### ISSUE TITLE
Target out of scope ancestors

### ISSUE THREAD

**Issue by rayfranco** [vuejs/vue-loader#1162]
### What problem does this feature solve?
Allow ancestors cascading states to be used on scoped styles.

### What does the proposed API look like?
```
<style lang="stylus" scoped>
section
  display block

>>> html.some-state <<<
  section
    display none
</style>
```

Is the equivalent of:

```
section[data-v-xxxxxxx]
  display block

html.some-state
  section[data-v-xxxxxxx]
    display none
```

**Comment by rayfranco** [comment]
Not sure Stylus was the best example to illustrate since we could reference the root by doing

```
section
  display block
  html.some-state &
    display none
```

I leave this open even if this solves it for my use case (stylus) but I am guessing this could get harder with non preprocessed styles.

**Comment by Jinjiang** [comment]
Maybe #1103 could do this job.
Thanks.

**Comment by yyx990803** [comment]
I think this probably should be the job of a pre-processor. Or can be done via a custom PostCSS plugin.
