### ISSUE TITLE
using variable in require() not works [emits could not find module] 

### ISSUE THREAD

**Issue by CharlesKumar** [vuejs/vue-loader#1165]
### Version
14.1.0 

tried with 

vue-loader: 14.1.1
webpack: 3.10, 3.11
url-loader: 0.6.2
file-loader: 1.1.6

### Reproduction link
[https://codesandbox.io/s/w07pnxvwml](https://codesandbox.io/s/w07pnxvwml)

### Steps to reproduce
1. Run the codesandbox link
you will get the ModuleNotFoundError
Could not find module in path: './../assets/iphone8.png'

from /components/HelloWorld.vue:40:24

### What is expected?
require(var) should work as require('literal path')

### What is actually happening?
require(var) is breaking with module not found error

---
tried using

1. string constructor (new string(var);  a brand new string)
2. string.slice(0) (using a returned string)
3. var let const (the variable - in case of any scope problem)

nothing works as expected

**Comment by LinusBorg** [comment]
Well, there is no file called `iphone8.png` in `/assets` - it's in `/assets/cards`
