### ISSUE TITLE
Ability to have multiple root elements in a functional view.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-loader#1167]
Just continuing https://github.com/vuejs/vue/issues/7088#issuecomment-366720489 here.

It can be nice to have multiple roots in template:

```html
<template>
  <div class="one"></div>
  <div class="two"></div>
</template>
```

See the other issue for some background.

**Comment by LinusBorg** [comment]
@trusktr When I wrote to open an issue here, I was referring to the comment before mine, which was talking about multiple root nodes for functional templates. This is probably indeed best solved in vue-loader, so I asked for someone to open an issue about it.

I took the freedom to change the title of your issue accordingly.

As explained in the original issue thread, multiple root nodes in normal components wold require a rewrite of large parts of the virtualdom functionality, so if we decided to tackle this, it would be in the Vue core repository.

**Comment by LinusBorg** [comment]
Okay, I'll close this in favor of #1168, which is more to the point.
