### ISSUE TITLE
ESLint issues after upgrading vue-loader

### ISSUE THREAD

**Issue by lazabogdan** [vuejs/vue-loader#117]
Hello,

I like to always have a first level of indentation inside all my template, script and style tags. It's a personal preference and for me, the vue file is more readable.

![screen shot 2016-01-02 at 00 52 50](https://cloud.githubusercontent.com/assets/6580668/12072531/3e1e0bc4-b0eb-11e5-99ae-f67b3ee6d010.png)

However, after upgrading vue-loader from 7.2.0 to 7.5.0, I'm getting hundreds of indentation errors in as many files, saying it's expecting 0 tabs but found 1. Also, the lines reported by ESLint for the vue files are incorrect.

**Comment by yyx990803** [comment]
Are you using eslint-loader?

**Comment by yyx990803** [comment]
Should be fixed in 7.5.1 now

**Comment by lazabogdan** [comment]
Yep, no more warnings. Thank you
