### ISSUE TITLE
v14.1.0 No longer works with thread-loader

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue-loader#1178]
### Version
14.1.0

### Reproduction link
[https://github.com/decademoon/vue-thread-loader-bug](https://github.com/decademoon/vue-thread-loader-bug)

### Steps to reproduce
```
$ npm i
$ npm run build
```

### What is expected?
No errors.

### What is actually happening?
```
ERROR in ./Comp.vue
Module build failed: Thread Loader (Worker 0)
Object.defineProperty called on non-object

    at Function.defineProperty (<anonymous>)
    at Object.module.exports (/Users/dean/Sites/vue-thread-loader/node_modules/vue-loader/lib/loader.js:25:10)
```

---
It appears that commit https://github.com/vuejs/vue-loader/commit/289b4d9e7c4d2761597c9f038332897abb5c3f76 introduced the use of `this._compilation` which does not exist when `vue-loader` is used with `thread-loader`:

https://github.com/vuejs/vue-loader/blob/289b4d9e7c4d2761597c9f038332897abb5c3f76/lib/loader.js#L68-L73

**Comment by yyx990803** [comment]
This is the same issue with #1152 and we are investigating how to solve that.
