### ISSUE TITLE
alias error

### ISSUE THREAD

**Issue by 714273725** [vuejs/vue-loader#1181]
![vue](https://user-images.githubusercontent.com/14801679/37131784-1cc3ddac-22c5-11e8-8cb0-f8210de2588d.png)

i set an alias like the image,but get a error while using it.

![vue22](https://user-images.githubusercontent.com/14801679/37131866-903fcd36-22c5-11e8-8eab-f80f4714c474.png)

![vue33](https://user-images.githubusercontent.com/14801679/37131888-b4b773c6-22c5-11e8-9361-b7fa18b89394.png)

Is there anything to be ignored？

**Comment by sqal** [comment]
https://github.com/vuejs/vue-loader/issues/1050#issuecomment-343146915

so you should do:

`~images/logo2.png`

**Comment by 714273725** [comment]
@sqal actually,I did it,you can see it in the second image.By the way,I work it with vue 2.9.3 and webpack 3.6.0

**Comment by 714273725** [comment]
![1](https://user-images.githubusercontent.com/14801679/37152033-dca404e2-2312-11e8-9ba2-870df8a38a38.png)
![2](https://user-images.githubusercontent.com/14801679/37152037-deb87614-2312-11e8-8d4f-001e5753867d.png)
![3](https://user-images.githubusercontent.com/14801679/37152038-e0392a60-2312-11e8-8a11-6b1df7b5f6d0.png)
I make a new project,and get the same error

**Comment by yyx990803** [comment]
Can't reproduce. This may have to do with your terminal/IDE setup.
