### ISSUE TITLE
How to pass options to sass-loader within vue loader options?

### ISSUE THREAD

**Issue by andosteinmetz** [vuejs/vue-loader#1186]
Hi,

I recently updated Webpack from `2.x` to `3.x` and `vue-loader` from `12.x` to `14.x`, and after the updates, I was getting errors in my build script from every vue component that look like this: 
```
Module not found: Error: Can't resolve '[object Object]' in '_path_/_to_/_project_/src/components/search'
```
I tracked this down to a failure in sass-loader within the vue-loader, I think to locate scss imports. Here is my webpack config for vue-loader:
```
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      css: ExtractTextPlugin.extract({
          fallback: 'vue-style-loader',
          loader: 'css-loader',
      }),
      scss: ExtractTextPlugin.extract({
        fallback: 'vue-style-loader',
        use: [
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
                sourceMap: true
            }
          },
          {
            loader: 'sass-loader',
            options: { includePaths: ['scss']}
          }
        ]
      })
    }
  }
},
```
This config had been working under `webpack 2.x`, and was quite convenient for setting my scss import path, but started breaking under `webpack 3.x`.

I solved the problem by removing all custom style rules in `vue-loader` and just setting `extractCss: true`, and then creating an alias to reference my `scss` directory in my Vue components. 

This is fine, but I'm curious if it's still possible to pass `includePaths` to `sass-loader` from `vue-loader` and if so, what is the correct method?

Apologies for not using the issue template, but I'm not really sure if it applies in this case.

If the prior config _should_ still work and this seems like a bug, let me know, and I'll recreate the issue using the template with a minimal reproduction.

**Comment by yyx990803** [comment]
Please [use the issue helper and provide a reproduction](new-issue.vuejs.org/?repo=vuejs/vue-loader).
