### ISSUE TITLE
src imported styles that bear the scope attribute are not applied/loaded

### ISSUE THREAD

**Issue by burningTyger** [vuejs/vue-loader#1187]
### Version
14.1.0

### Reproduction link
[https://jsfiddle.net/strLx199/](https://jsfiddle.net/strLx199/) -> I don't know how to create jsfiddle with a sfc and sandbox is broken.

### Steps to reproduce
Any template with

    <style scoped src="./page.css"></style>

### What is expected?
should load all styles and scope them.

### What is actually happening?
does not load or apply page.css styles at all.

---
works as expected:

    <style src="./page.css"></style>

This is basically the same issue as #235

**Comment by yyx990803** [comment]
Please do provide a proper reproduction (can be a repository) because this usage is [covered in the tests](https://github.com/vuejs/vue-loader/blob/master/test/basic.js#L61-L63).

**Comment by varunkumarmedam** [comment]
Still an issue, hope will find an active vue resolver will look t it :(

**Comment by varunkumarmedam** [comment]
`<style scoped src="./vue-material.min.css"></style>`
this is not loading.

`<style src="./vue-material.min.css"></style>`
this works as expected

**Comment by bart** [comment]
Any updates on this?
