### ISSUE TITLE
Unused components are not unmounted

### ISSUE THREAD

**Issue by ChambreNoire** [vuejs/vue-loader#1188]
### Version
14.2.1

### Reproduction link
[https://codesandbox.io/s/x95p35p9kz](https://codesandbox.io/s/x95p35p9kz)

### Steps to reproduce
Just click 'Next'. The inner component will be changed from ChildA to ChildB.

### What is expected?
The style block within \<head\> corresponding to ChildA (which contains .red) should no longer be present in \<head\>.

### What is actually happening?
Both ChindA and ChildB \<style\> blocks are present. As we swap out inner components, the previous \<style\> blocks are kept in the \<head\> despite the fact that said previous inner component is no longer in use...

---
I assumed that there is some kind of component use counter which would entail unmounting of unused components and their \<style\> blocks but this doesn't seem to be the case.

**Comment by LinusBorg** [comment]
That's expected behaviour, that's how (vue-)style-loader works. 

It's recommended to extract all css into a file for production anyway.

**Comment by yyx990803** [comment]
This is expected behavior. In v15 we will also revert to the behavior where all component CSS being injected upfront so it's less confusing.
