### ISSUE TITLE
vue-loader is incompatible with remap-istanbul because of missing "file" property on sourcemap.

### ISSUE THREAD

**Issue by Ross-Esmond** [vuejs/vue-loader#1189]
### Version
14.2.1

### Reproduction link
[https://github.com/scry/VueCoverage](https://github.com/scry/VueCoverage)

### Steps to reproduce
clone the repo, yarn install, karma start.

Karma will break because of [these lines](https://github.com/SitePen/remap-istanbul/blob/master/src/CoverageTransformer.js#L142-L143) in remap-istanbul.

remap-istanbul expects sourcemaps to have the "file" property, but vue-loader isn't setting it.

### What is expected?
parser.js should be passing the file option to SourceMapGenerator, as per [SourceMapGenerator docs](https://www.npmjs.com/package/source-map#with-sourcemapgenerator-low-level-api).

[Link to line in vue-loader.](https://github.com/vuejs/vue-loader/blob/master/lib/parser.js#L41)

### What is actually happening?
parser.js skips the file property, which results in a map being exported without file specified.

---
This causes an issue specifically with remap-istanbul. I thought the bug was theirs for a while but it looks like it's a saner fix in vue-loader.

**Comment by Ross-Esmond** [comment]
I added a pull. #1190 It's almost a one-liner.

**Comment by yyx990803** [comment]
Thanks for the PR!
