### ISSUE TITLE
Issues with scoped CSS when using extract-text-webpack-plugin

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-loader#119]
I use `extract-text-webpack-plugin` to bundle css into a single files, my webpack config is:

```js
vue: {
    loaders: {
        css: ExtractTextPlugin.extract('style-loader', 'css-loader')
    }
},
plugins: [
  new ExtractTextPlugin('styles.[contenthash].css')
]
```

When I navigated to browser I just got different hash attributes in html and css, like:

```
// html
<div class="todo" _v-70fd86ce></div>
// css
.todo[_v-34hs81jd] {
  ...
}
```

Sure I used the `scoped css` feature, it works when I didn't use `extract-text-webpack-plugin` 

Relate file: https://github.com/egoist/vuepack/blob/master/scripts%2Fwebpack.config.js#L30

**Comment by yyx990803** [comment]
Hmm, it works properly with the setup in https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.prod.conf.js

Can you reproduce this in a repo?

**Comment by egoist** [comment]
sorry, my mistake.

**Comment by ThermScissorpunch** [comment]
@egoist can you tell me what you changed? I am also experiencing this issue.
