### ISSUE TITLE
how to remove spaces and newlines from ssr response body?

### ISSUE THREAD

**Issue by falstack** [vuejs/vue-loader#1191]
### What problem does this feature solve?
when i use vue ssr, everything work perfect

but in crhome open view-source, the ssr response body have many newlines and spaces, i want remove them

how should i do?

### What does the proposed API look like?
remove spaces and newlines auto

**Comment by yyx990803** [comment]
You probably want to use the `preserveWhitespace: false` option.

**Comment by falstack** [comment]
my webpack config：https://github.com/calibur-tv/RhoAias/blob/master/build/webpack.base.config.js#L39

check this page：view-source:https://www.calibur.tv/
we will see:
![image](https://user-images.githubusercontent.com/16357724/37278319-5001dfe2-2622-11e8-9b7d-85ca5664abdc.png)

what i want?
see this page：view-source:https://www.zhihu.com/
![image](https://user-images.githubusercontent.com/16357724/37278490-d446ddb6-2622-11e8-872f-0e5e50327490.png)

and this issue：https://github.com/vuejs/vue-hackernews-2.0/issues/295

因为我这个问题我不知道该在哪一层解决（vue-loader, node.js, nginx），所以才来问这个问题
preserveWhitespace: false 好像只能 remove 掉 html-template 里的空格，我看到 hacknews-ssr 也是有 tab 和少量空格的

**Comment by falstack** [comment]
closed, from https://github.com/vuejs/vue-hackernews-2.0/issues/295#issuecomment-373268661
