### ISSUE TITLE
scoped style "data-v-*" incorrect

### ISSUE THREAD

**Issue by uginroot** [vuejs/vue-loader#1195]
### Version
14.2.1

### Reproduction link
[https://github.com/uginroot/frontend](https://github.com/uginroot/frontend)

### Steps to reproduce
I was not able to repeat this in CodeSandbox, so I decided to send the whole project, it is still very small.

### What is expected?
Scoped style work in all block in template

### What is actually happening?
vue-loader does not set a "data-v- *" attribute on the first child

---
File "src/components/MyBody.vue" element .my-header scoped styles not work
![image](https://user-images.githubusercontent.com/2391460/37500742-65c3b5b4-28f5-11e8-8f54-462e5b7c8989.png)

**Comment by uginroot** [comment]
Sorry, there is already such a bug https://github.com/vuejs/vue-loader/issues/1061

**Comment by yyx990803** [comment]
Sorry but your repository is not runnable.
