### ISSUE TITLE
Discussion: extractCSS, Webpack 4, extract-text-webpack-plugin and mini-css-extract-plugin

### ISSUE THREAD

**Issue by darylteo** [vuejs/vue-loader#1196]
### What problem does this feature solve?
There is currently a bit of uncertainty regarding the future of extract-text-webpack-plugin and sokraj's mini-css-extract-plugin. Unfortunately despite this plugin being one of the most commonly recommended plugins for Webpack, the transition for this plugin hasn't been handled very well (no blame being placed on anyone, that's just how things are). However, in the context of vue-loader, the extractCSS property is a hard dependency on extract-text-webpack-plugin, and I did not see any discussion regarding how this is going to be handled in the future so I'd recommend having this discussion sooner rather than later.

For some additional context, there is an existing discussion https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749 

### What does the proposed API look like?
Don't have any recommendations here... except maybe have extractCSS take a loader.

**Comment by yyx990803** [comment]
In v15 we will simply deprecate `extractCSS` since the configuration will be done in normal webpack config instead of in `vue-loader`'s own options. It will work with both WETP and the new MCEP (in fact it's already tested [here](https://github.com/vuejs/vue-loader/blob/next/test/advanced.spec.js#L67)).

For v14, we'll likely have to keep it as-is.

**Comment by darylteo** [comment]
Great news. Thanks very much for your work @yyx990803

**Comment by luisatmaniak** [comment]
@yyx990803 How will this change impact SSR/critical CSS extraction?

**Comment by yyx990803** [comment]
@luisatmaniak no change.

**Comment by jingzheshan** [comment]
# I can not wait for v15.

**Comment by cartok** [comment]
Hey @yyx990803 to me it looked like with the old CSS Extraction we would be able to choose from which components I want to extract CSS as we could just match full component names in the loader setting. Isn't that correct. I think the that option is gone now   or at least deprecated. I'm not sure if thats a good change. Correct me if I'm wrong.

**Comment by cartok** [comment]
> Hey @yyx990803 to me it looked like with the old CSS Extraction we would be able to choose which components we want to extract CSS from by matching component names in the loader settings. I think the that option is gone now or at least deprecated. I'm not sure if thats a good change. Please correct me if I'm wrong.

Found a soltuion, it can be done using the issuer option in the rule.
