### ISSUE TITLE
Component style should be scoped to component

### ISSUE THREAD

**Issue by FWeinb** [vuejs/vue-loader#12]
All styles are currently in the global scope, it would be great if the vue-loader could generate unique identifiers for components. So something like this.

```vue
<style>
   .profile{ }
   .profile__picture{ }
</style>
<template>
   <div class="profile">
       <img class="profile__picture" />
   </div>
</template>
[...]
```

Would be transformed to:
```vue
<style>
   .uniqueID--profile{ }
   .uniqueID--profile__picture{ }
</style>
<template>
   <div class="uniqueID--profile">
       <img class="uniqueID--profile__picture" />
   </div>
</template>
[...]
```

**Comment by azamat-sharapov** [comment]
I personally always have root tag to component with identifier and put all CSS under that identifier. I think that's less verbose and easy solution then your proposal. But I agree on making this styles kindda "local" automatically, that would be cool. There was great article on this topic not long ago: https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284
I think one can achieve "local CSS" in Vue components piping styles through another loader for transforming CSS into "local" like described in article. Didn't have time to try it yet, but if you do, please let us know!

**Comment by FWeinb** [comment]
That looks promising. The only think that would be left is to define a way to access these styles in the template. I would like to see something like this:

```
// app.vue
<style>
  .red {
    color: #f00;
  }
</style>

<template>
  <h1 class="{{styles.red}}">{{msg}}</h1>
</template>

<script>
  module.exports = {
    data: function () {
      return {
        msg: 'Hello world!'
      }
    }
  }
</script>
```
Than `vue-loader` would just need to inject the required css from the `style` tag into the `data` of the module.

**Comment by azamat-sharapov** [comment]
Why would you want to access CSS like that? Wouldn't just `<h1 class="red">{{msg}}</h1>` work?

**Comment by FWeinb** [comment]
Not if webpack is remaining the classes to ensure that they are unique. Like described in the article you linked.

**Comment by azamat-sharapov** [comment]
I do like this:

```
<style lang="stylus">
.component-a
  .red
    color #f00
  .bold
    font-weight bold
</style>

<template>
  <div class="component-a">
    <h1 class="red bold">msg</h1>
  </div>
</template>
```

As for "local css", looks like Tobias [already implemented this on css-loader](https://github.com/webpack/css-loader#local-scope). So it should already work.

**Comment by FWeinb** [comment]
Yeah, the "local css" part is solved the current problem is how to access the identifiers for that css.

**Comment by taylorzane** [comment]
@FWeinb I found the need to use the `css-loader` locals in my project. I [forked](https://github.com/taylorzane/vue-loader) the project and added in a couple lines to expose the code. My current implementation isn't exactly "eloquent" but it works for me.

```javascript
// BEGIN ORIGINAL CODE
// add require for template
var hasTemplate = false
for (var lang in parts.template) {
  if (hasTemplate)
    return cb(new Error('Only one template element allowed per vue component!'))
  output += 'module.exports.template = ' + getRequire('template', lang) + '\n'

  hasTemplate = true
}
//END ORIGINAL CODE

// START CSS-LOADER SHIM
// Shim to allow accessing css-loader locals.
for (var lang in parts.style) {
  output += 'module.exports.styleLocals = ' + getRequire('style', lang) + '\n'
}
// END CSS-LOADER SHIM
```

This allows me to access the locals in the component template and module. The one thing that I have to add into the module is the following:

```coffee-script
module.exports =
  data: ->
    styles: @$options.styleLocals
```

Then you'd be able to reference the style inside the template using mustache bindings. Or in a `computed` property, or method.

If you'd prefer something a little more integrated, I can try to prioritize finishing up this implementation of accessing locals, and submit a PR.

**Comment by yyx990803** [comment]
Closing this for now, because I feel the CSS modules solution still exerts too much usage overhead. What we will probably do in the future is add an option to enable the class names injection, and leave the actual usage pattern to userland. For now, we will resort to downward-cascading scoped CSS.
