### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by daddybh** [vuejs/vue-loader#122]
Hi,
I got following error when I upgrade vue-loader to the latest.

```
Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":null,"original":{"line":1,"column":0},"name":null}
```

It looks like a issue of babel-loader, I upgrade babel-loader to latest, the error gone. @yyx990803, Could you update the `dependecies` to lastest? 
```
https://github.com/babel/babel-loader/issues/147
```

And by the way, the vue-loader is super slow after I updated from `3.0.3`, it takes more than 30s to finished `webpack -d`. Any Idea we could do?

**Comment by yyx990803** [comment]
When you do a fresh install `babel-loader` will automatically be the latest `6.x` version, no need to update it unless it goes up to `7.x`.

For the slow build - how many files do you have? What pre-processors are you using?

**Comment by daddybh** [comment]
It looks like i mess with the npm-shrinkwrap.json file, now it is fixed.

There are not much files, only 72 `.vue` files. And my webpack config is also simple.
It stuck for a while when I run `webpack -p` or `webpack -d`

```
module :{
        loaders: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader?sourceMap")
            },
            { test: /\.(png|gif|svg)$/, loader: "file-loader?name=../img/[name].[ext]?[hash]"},
            { test: /\.vue$/, loader: 'vue'}
        ]
    },
    plugins: [
        new Clean(["server/public/dist/"]),
        new webpack.optimize.CommonsChunkPlugin("publib","[name].[chunkhash].js"),
        new ExtractTextPlugin("[name].[contenthash].css",{allChunks: true})
    ]
```
