### ISSUE TITLE
Styles are different when using webpack vs webpack-dev-server

### ISSUE THREAD

**Issue by CLL80** [vuejs/vue-loader#1223]
### Version
14.2.2

### Reproduction link
[https://github.com/CLL80/vue-loader-test](https://github.com/CLL80/vue-loader-test)

### Steps to reproduce
Clone the repro repo, run `npm install`, run `npm run dev`. You will see CSS missing (defined in the `body` class) that should be present on the body.

This was broken after `vue-loader@11.3.4`. Using `vue-loader` 11.3.4, the styles between the dev server and built sites are identical.

### What is expected?
There is a `.body` class  in `src/index.vue` which should be included in the sources and used for the `body` element. Styles should be the same in dev localhost and built site.

### What is actually happening?
When building, `npm run build`, you will see the ".body" class is correctly included in the bundle and rendered when viewed in browser (for example, this shows a grey body background-color). When using `webpack-dev-server`, the `.body` class is not available. In the repo example, it results in the body background being white.

---
The `working-loader` branch in this repo can be used to see the styles correctly included for the `.body` class with both `webpack-dev-server` and `webpack` using `vue-loader@11.3.4`.

**Comment by yyx990803** [comment]
This is likely because you are not exporting an actual object in `index.vue`. FYI Vue files **must** export the component it defines and you should not instantiate the root instance inside a Vue file.
