### ISSUE TITLE
After installing and removing vue-loader cannot compile again

### ISSUE THREAD

**Issue by neorganic** [vuejs/vue-loader#1227]
````
ERROR in ./resources/assets/js/main.js
Module not found: Error: Can't resolve 'vue-loader' in '/home/reaper/sites/sitename'
 @ ./resources/assets/js/main.js 31:0-49
 @ multi ./resources/assets/js/main.js ./resources/assets/sass/app.scss ./resources/assets/sass/main.scss ./resources/assets/sass/basic.scss
````

I don't have it specifically being imported in any of these files, but get this message for most likely all my files... about 30 similar messages spammed in terminal for different files
It's not defined anywhere, so looking to git history trying to understand what else have change only thing I see is the `vue-loader` being added to package.json ...
might this be some sort of cache related thing ?

I am using laravel mix .

***Update*** : So it seems that the  ``vue-loader`` is present in the ``package.lock.json`` - after manually deleting it  and running ``npm install`` a new ``package.lock.json`` is being generated, but it also contains the ``vue-loader``  . How this might of happen if ``package.json`` doesn't contain ``vue-loader`` anymore ?

**Comment by neorganic** [comment]
**Fixed:** It was a strange cache issue: 
`laravel-mix` pulls `vue-loader` as a dependency itself , so adding `vue-loader` to package.json  , running npm install, then removing `vue-loader` and running npm install triggered this issue. When `vue-loader` was being visible in `package.lock.json` , but not in `node_modules`

**Comment by vhanla** [comment]
Indeed, somehow `laravel-mix` package dependency `vue-loader` can't be installed after those steps you mentioned, so to fix that is a matter of uninstalling it from the project's `package.json` and just installing back the missing `vue-loader@<version required by laravel mix's package.json>` no need to use `--save-dev` nor `--save`
