### ISSUE TITLE
can't Extracting CSS into a Single File

### ISSUE THREAD

**Issue by a298003154** [vuejs/vue-loader#1228]
i want to Extracting CSS into a Single File.
webpack@3.11.0
vue-loader@12.2.2
extract-text-webpack-plugin: "^3.0.2"

after build, there is none css files built in folder. 
and i try use "extractCSS: true", but the result also like that.

![1](https://user-images.githubusercontent.com/24939100/38305526-ba088f10-383f-11e8-962f-9c23d174d7c9.png)
![3](https://user-images.githubusercontent.com/24939100/38305651-33f0d698-3840-11e8-9835-b9f02a40b3e5.png)

![2](https://user-images.githubusercontent.com/24939100/38305617-14d85182-3840-11e8-8970-59bb1d9294fb.png)

**Comment by yyx990803** [comment]
Please read the issue instruction and provide a **reproduction**. Also, you are using a very old version of `vue-loader`, try upgrading first.

**Comment by a298003154** [comment]
@yyx990803  fixed it.
I use require.ensure to organize router. Actually,this method make extractCSS uesless.
thanks u, Evan You
