### ISSUE TITLE
Is event's modifiers will support 'async'??

### ISSUE THREAD

**Issue by SmallGress** [vuejs/vue-loader#1229]
### What problem does this feature solve?
When I write custom event, I found the EmitEvent isn't very supportive for asynchronous programming.

When I made a request, maybe the child component just need know the request finish.In the case, if the child component want get this request, I must use a variable to save this request and use this variable pass to child component.

If It's just a litte of requests I can made use this way, but If It have dozens of requests, that will be dozens of variables.

### What does the proposed API look like?
So, I think maybe vue can have a modifiers like 'async' to support.It will write like this:

component A
```
<template>
  <div>
    <component-b v-on:go.async="ajax"></component-b>
  </div>
</template>
<script>
export default {
  name: "componentA",
  methods: {
    ajax() {
      return httprequest()
    }
  }
}
</script>
```
component B
```

<template>
  <button v-on:click="emit">
    <span v-if="loading">loading...</span>
    <span>component-b</span>
  </button>
</template>
<script>
export default {
  name: "componentB",
  props: ['loading'],
  methods: {
    emit() {
      this.loading = true
      this.$emit('go').then(() => {
        this.loading = false
      })
    }
  }
}
</script>
```

**Comment by yyx990803** [comment]
This is the wrong repo since this is a vue core feature request.

That said, this isn't something that should be done as a modifier... this kind of event ping-pong typically leads to very brittle code in the long run because your components are relying on implementation details of each other.
