### ISSUE TITLE
Duplicate loaders for .css

### ISSUE THREAD

**Issue by clarkdo** [vuejs/vue-loader#1231]
### Version
15.0.0-rc.1

### Reproduction link
[https://github.com/nuxt/nuxt.js/tree/dev/examples/async-component-injection](https://github.com/nuxt/nuxt.js/tree/dev/examples/async-component-injection)

### Steps to reproduce
Use `<style src="">` to import css.

```vue
<template>
  <div> </div>
</template>

<script>
export default {
}
</script>

<style src="@/assets/css/index.css"/>

```

### What is expected?
CSS can ben loaded by `css-loader`, `vue-style-loader` successfully.

### What is actually happening?
Error:

> Module build failed: Syntax Error
> (5:1) Unknown word

---
According to my investigation, https://github.com/vuejs/vue-loader/commit/5a9ee91358e104288d04b056b65568aa660a96e7 introduced this issue.

`<style src="@/assets/css/index.css"/>` will be applied to both `rawLoaders(vue-style-loader, css-loader)` and also `cloned rules` from `vue-loader`. 

`test` and `resourceQuery` in `VueLoaderPlugin` can also be passed for this kind of css file.

**Comment by clarkdo** [comment]
Point to reproduce the issue: 
1. add not null `options` on `vue-style-loader`
```js
{
        test: /\.css$/,
        use: [
          { loader: "vue-style-loader", options: { } },
          'css-loader'
        ]
      }
```
1. then run ssr.spec.js

**Comment by yyx990803** [comment]
Alternatively we need to at least include the following in the whitelist:

- css-loader
- (vue-)?style-loader
- postcss-loader
- extract-text-webpack-plugin's loader
- mini-css-extract-plugin's loader
