### ISSUE TITLE
Cannot apply scoped styles with dom generated by v-html

### ISSUE THREAD

**Issue by ycmjason** [vuejs/vue-loader#1237]
### Version
15.0.0-beta.1

### Reproduction link
[https://codesandbox.io/s/50734p45vk](https://codesandbox.io/s/50734p45vk)

### Steps to reproduce
1. `v-html` links to some html content that wants to be generated on the page
2. use scoped css in sfc
3. unable to style generated contents from `v-html`

### What is expected?
Since `v-html` generates dynamic html content, it makes sense that sfc scoped styles could apply to them as well. Imagine I want to generate some html-powered comments, and wish to style them without messing around with global styling, this is not possible now.

### What is actually happening?
`v-html` generates html without the hash which makes scoped styles not applicable to them. 

---
Not so sure if this is an issue but it does seem make sense to me.

**Comment by yyx990803** [comment]
`v-html` content are set verbatim and will not have the scoped attribute. This will not likely change. You can style content inside the element using the deep selector `>>>`.
