### ISSUE TITLE
[VueLoaderPlugin Error] No matching rule for .vue files found - when files have different extension than .vue

### ISSUE THREAD

**Issue by roysanchez** [vuejs/vue-loader#1238]
### Version
15.0.0-rc.1

### Reproduction link
N/A

### Steps to reproduce
    const path = require('path');
    const webpack = require('webpack');
    const { VueLoaderPlugin } = require('vue-loader')

    module.exports = (env) => {
       const isDevBuild = !(env && env.prod);

       return [{
           stats: { modules: false },
           context: __dirname,
           resolve: { extensions: [ '.js', '.ts' ] },
           entry: { 'main': './ClientApp/boot.ts' },
           module: {
                rules: [
                    { test: /\.vue\.html$/, loader: 'vue-loader' },  //Change this line to { test: /\.vue/, loader: 'vue-loader' } to make it work
                    { test: /\.ts$/, use: 'ts-loader?silent=true' }
                ]
            },
           output: {
               path: path.join(__dirname,  './wwwroot/dist'),
               filename: '[name].js',
               publicPath: 'dist/'
           },
           plugins: [
               new VueLoaderPlugin()
           ]
       }];
   };

### What is expected?
The bundle is successful

### What is actually happening?
Webpack throws the following error:
[VueLoaderPlugin Error] No matching rule for .vue files found.
Make sure there is at least one root-level rule that matches .vue files.

**Comment by yyx990803** [comment]
Why are you using `.vue.html` extension instead of just `.vue`?

**Comment by roysanchez** [comment]
It's the default extension on the aspnetcore vue template, I think they do it so you get autocomplete on visual studio.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yyx990803** [comment]
Well, Vue SFCs are not technically HTML. The recommended approach is using the proper `.vue` extension and VSCode (which has excellent SFC support) instead Visual Studio.

If you really want to stick with `vue.html`, you can workaround this by having both rules:

```
rules: [
  { test: /\.vue$/, loader: 'vue-loader' },
  { test: /\.vue\.html$/, loader: 'vue-loader' }
]
```

**Comment by roysanchez** [comment]
Thanks that worked even thought it looks like a hack 😅 as I don't have any `.vue` files in the project

**Comment by yyx990803** [comment]
@roysanchez I added a special case for `.vue.html`. Will work without the extra rule in the next release.

**Comment by BrainBacon** [comment]
@yyx990803 I have a similar issue. My `.vue` files have become `.pug` instead. Is there any chance we can have a configurable option instead of just handling special cases?

**Comment by Flamenco** [comment]
Why not just add an optional regex to the current instruction?
rules: [
  { test: /\.vue(\.html)?$/, loader: 'vue-loader' },
]

**Comment by dietergeerts** [comment]
Hi, I encountered the same error. The plugin is too restrictive in checking the rules. This is what I have:
```
        // We need to fool the VueLoaderPlugin, as that checks if a rule is available
        // for vue components, but it can't see our more restricted one....
        // It even checks the name of the loader, so aliasing also doesn't work.
        {
          test: /\.vue$/,
          include: path.resolve(__dirname),
          loader: 'vue-loader',
        },
        {
          test: /\.vue$/,
          include: options.sourceDirectory,
          issuer: /\.docs\.md$/,
          use: [
            { loader: 'fb-inject-vue-loader' },
            { loader: 'fb-vue-loader' },
          ],
        },
```
This comes from a package we make that is to be used with other packages, so we do aliasing to be sure that the others can use different versions of loaders etc...

**Comment by hzm131** [comment]
都是大神

**Comment by diadal** [comment]
I fund the cause of this issue in `/node_modules/vue-loader/lib/plugin.js` there is this checking point `vueLoaderUseIndex < 0 ` under `const vueUse = vueRule.use` I make this following changes 

```
let ListIndex = [];

    const vueLoaderUseIndex = vueUse.findIndex(u => {
      console.log(u)
      let vueChecker =  /^vue-loader|(\/|\\|@)vue-loader/.test(u.loader)

      console.log({u:u.loader})

      ListIndex[u.loader] = vueChecker
      return vueChecker
    })
    console.log({ListIndex:ListIndex['vue-loader']})

```
in my terminal I have this 

```
{ ListIndex: [ 'vue-loader': true ] }
{ ListIndex: [ 'html-loader': false ] }

```
this show to rules are been fire when I `npm run dev` and this `html-loader` is not defined in my web pack config file so `vueLoaderUseIndex < 0 ` stop the processing since `'html-loader': false`

am currently working on the solution or if there is fast fix for this please share

**Comment by diadal** [comment]
am able to bypass the error by doing this but I dont know if it right thing to do 

```

const vueLoaderUseIndex = vueUse.findIndex(u => {
      let vueChecker =  /^vue-loader|(\/|\\|@)vue-loader/.test(u.loader)
                       || /^babel-loader|(\/|\\|@)babel-loader/.test(u.loader)
                       || /^html-loader|(\/|\\|@)html-loader/.test(u.loader)
                       || /^file-loader|(\/|\\|@)file-loader/.test(u.loader)
                       || /^img-loader|(\/|\\|@)img-loader/.test(u.loader)
      return vueChecker
    })

```

**Comment by peterabarry** [comment]
I do not believe this is fixed.

**Comment by ArnolFokam** [comment]
I just encountered the same error on `vue-loader 15.8.3`. While inspecting the source for my webpack version at [plugin-webpack4.js](https://github.com/vuejs/vue-loader/blob/master/lib/plugin-webpack4.js)
https://github.com/vuejs/vue-loader/blob/21293bd32aefd1142a50737f1634d36f77da15e4/lib/plugin-webpack4.js#L32
I came to the conclusion that the matcher created for ``foo.vue`` allows a rule for `html-loader` to pass the test for some reasons I don't know. I was able to get it work by replace the line55 of the piece of code below with @diadal's comment https://github.com/vuejs/vue-loader/issues/1238#issuecomment-453752870
https://github.com/vuejs/vue-loader/blob/21293bd32aefd1142a50737f1634d36f77da15e4/lib/plugin-webpack4.js#L54-L56
But I can't do this on every `npm i --save-dev vue-loader`

**Comment by fathimamusnamuharis** [comment]
actually to me npm update corrected the error

**Comment by nsxr51** [comment]
also to me just npm update

**Comment by zilbert97** [comment]
For me the fix was to move the rule in my config to the top of the array of rules. Can't tell you why, but it did the trick!

- Webpack v5.52.0
- webpack-dev-server 4.1.0
- yarn v11.22.11

In my `webpack.common.js`:

```js
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
    entry: {
        main  : "./src/main.js",
        vendor: "./src/vendor.js",
    },

    module: {
        rules: [

            // Moved this to the top of all rules
            {
                test  : /\.vue$/,
                loader: "vue-loader",
            },

            {
                test: /\.html$/,
                use : ["html-loader"],
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                }
            },
            {
                test: /\.(svg|png|jpe?g|gif)$/,
                use : {
                    loader : "file-loader",
                    options: {
                        name      : "[name].[contentHash:8].[ext]",
                        outputPath: "assets/img",
                        esModule  : false,
                    },
                },
            },
        ],
    },

    plugins: [
        new VueLoaderPlugin(),
    ],
}
```

And my `webpack.dev.js` (just for reference since i'm using configs for different enviornments):
```js
const autoprefixer = require("autoprefixer")
const common       = require("./webpack.common")
const { merge }    = require("webpack-merge")
const path         = require('path')

const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = merge(common, {
    mode   : "development",
    devtool: "source-map",

    output: {
        filename: "[name].bundle.js",
        path    : path.resolve(__dirname, "dist", "index.html"),
    },

    module: {
        rules: [
            {
                test: /\.scss$/,
                use : [
                    "style-loader",
                    "css-loader",
                    {
                        loader: "postcss-loader",
                        options: {
                            plugins: () => [autoprefixer()],
                        },
                    },
                    "sass-loader",
                ],
            },
        ],
    },

    plugins: [
        new HtmlWebpackPlugin({
            template: "./src/template.html"
        }),
    ],
})
```
