### ISSUE TITLE
idea: modifying style tag refreshes only the page styles rather than whole app

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-loader#1240]
### What problem does this feature solve?
If we've modified only the `<style>` tag of a single-file-component, it would be great if only the styles on the page were updated, rather than refreshing the whole app (or whole component if hot reload). f.e., when modifying CSS files in create-react-app, the app is not refreshed, only styles on the page updated. It'd be niiiice to have this with style tags inside SFCs.

### What does the proposed API look like?
API looks the same to the user. If only changes happened inside the style tag, no refreshing of the page  would happen.

**Comment by yyx990803** [comment]
This is... already the behavior. You probably got some configurations wrong which leads to a runtime error that causes webpack to do a full reload.
