### ISSUE TITLE
`@import`ed styles in Stylus don't trigger refresh in dev mode when modified.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-loader#1241]
If I use `<style lang="stylus">` in a component, and write styles in there, f.e.

```html
<style lang="stylus">
  * {
  color: red;
}
</style>
```

then if I update the color to `blue`, the page will refresh and I will see the results.

However, if I `@import` a style, f.e. if my component is set up like this:

```stylus
// Foo.styl
* {
  color: red;
}
```

and

```html
<style lang="stylus">
  @import './Foo.styl'
</style>
```

then, if I make changes inside of `Foo.styl`, the page does not refresh, and I'll never see my changes. The dev server won't recompile. To see the changes, I have to kill the `npm run dev` process and restart it.

Is this a known issue?

All I did to get Stylus working was install the loader from NPM, then start using `lang="stylus"` in my component, so I haven't done anything special.

**Comment by yyx990803** [comment]
No this is not a known issue. It seems to work properly because we use stylus in both vue-devtools and vuepress.
