### ISSUE TITLE
bad regex to test against animation-name and its variant

### ISSUE THREAD

**Issue by mmis1000** [vuejs/vue-loader#1243]
### Version
15.0.0-beta.1

### Reproduction link
[https://codesandbox.io/s/o56vllrx89](https://codesandbox.io/s/o56vllrx89)

### Steps to reproduce
In https://github.com/vuejs/vue-loader/blob/6d3c5b2c6d9b4dd0f282c45e6a8d734ce38011ed/lib/style-compiler/plugins/scope-id.js#L57-L63
There are two regex regex /-?animation-name$/ and /-?animation$/
That will replace animation-name and animation to its scoped variant
Then you create a .vue file with scoped style and notanimation-name: test;

### What is expected?
It only matches animation-name and its vendor prefixed variant, so notanimation-name does not change at all.

### What is actually happening?

They match not only 'animation-name' and '-moz-animation-name'... etc but also 'notanimation-name'

**Comment by yyx990803** [comment]
fixed in https://github.com/vuejs/component-compiler-utils/commit/46447279aae47f6fc8394a1b9a65b423e5aeaba9
