### ISSUE TITLE
the result diffrenrt from expect

### ISSUE THREAD

**Issue by rianran1993** [vuejs/vue-loader#1244]
### Version
13.3.0

### Reproduction link
[https://jsfiddle.net/96ofj5jx/](https://jsfiddle.net/96ofj5jx/)

### Steps to reproduce
in a vue file, below Code run diffrent from my expects, but in run well not in a vue file
```
<script>
for (let i = 0; i < 5; i++  ) {
    let i = 'a'
    console.log(i) // 只打印出来一次, 期望打出5次， console 1 times， expect 5 times
}
export default {
    data() {
        return {}
    },
    async created() {
        for (let i = 0; i < 5; i++  ) {
            let i = 'b'
            console.log(i) // 打印5次， console 5 times
        }
        await this.prepareOptions()
    }
}
</script>
```

### What is expected?
should console 5 times 'a'

### What is actually happening?
 only 1

**Comment by rigor789** [comment]
Your fiddle seems to be working as expected, some consoles group prints into one line with a little number next to it that indicates how many times it has been printed, make sure you take that into consideration when looking at the output.

**Comment by yyx990803** [comment]
This has nothing to do with Vue....
