### ISSUE TITLE
vue-loader@next error

### ISSUE THREAD

**Issue by yiqianglin** [vuejs/vue-loader#1245]
![image](https://user-images.githubusercontent.com/15794229/39170615-c648da52-47ce-11e8-9107-b68098d5d6bb.png)

webpack.config:
![image](https://user-images.githubusercontent.com/15794229/39170654-e2552926-47ce-11e8-9c77-9e3cfa8b03ea.png)

![image](https://user-images.githubusercontent.com/15794229/39170666-ee819842-47ce-11e8-93f0-adf48c344180.png)

**Comment by 719media** [comment]
Sounds like you are missing the `plugins: [new VueLoaderPlugin()]` configuration in webpack

**Comment by Heartnett** [comment]
Why isn't the use of the **VueLoaderPlugin** not documented?

**Comment by matsp** [comment]
@719media Can you give a reference to look this up? Iam struggling with the same issue and can't find a note in the migration guide..

**Comment by matsp** [comment]
Oops had an older version in browser cache :laughing:
