### ISSUE TITLE
Karma, vue-loader and webpack don't work with vue-loader 15.0.0

### ISSUE THREAD

**Issue by ChristianStornowski** [vuejs/vue-loader#1250]
### Version
15.0.0

### Reproduction link
[https://codesandbox.io/s/0m8wjz8vn](https://codesandbox.io/s/0m8wjz8vn)

### Steps to reproduce
Create a project like https://codesandbox.io/s/0m8wjz8vn and execute npm test

### What is expected?
Karma will be correctly executed
Karma will execute tests correctly

### What is actually happening?
[preprocess]: Can not load "webpack"!
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.

---
This change causes the problem https://github.com/vuejs/vue-loader/compare/v15.0.0...master#diff-f85c36a1cc8952fb5e6fc7200a89ceaa (lib/plugin.js)

**Comment by mkastner** [comment]
l got the same problem in a working app.

After upgrade to 15.0.0 I got
Error in ./path/to/component-dir/documents-list.html?vue&type=template&id=6abc9e5&scoped=true&lang=html
Module parse failed: Unexpected token (1:0)
You may need an appropriate handler to handle this file type
etc. ...

After downgrading back to 14.2.2. everything worked fine again.

**Comment by LinusBorg** [comment]
I'm not sure If I hve a problem with codesandbox, but I can't look at any of the relevant files.

* karma.config.js is empty
* helloworld.spec.js is empty.

Also, what did you change in your webpack setup? Did you take care of the breaking changes in vue-loader 15 (a major version change)? Did you follow the migration guide?

**Comment by ChristianStornowski** [comment]
I didn't saved everything of my code in codesandbox.io. I updated it to https://codesandbox.io/s/0m8wjz8vn.

My previouse version of vue-loader was v15.0.0-rc.2. This was fine with karma.

**Comment by LinusBorg** [comment]
that project has incomplete dependencies (vue-loader is not included, for starters - but dozens of unrelated dependencies), and the errors in the test pane are not trhe ones you talk about.

So this is not a reproduction of the problem that you reported.

Can you please share a minimal repository that actually reproduces the problem?

**Comment by yyx990803** [comment]
Closing until a valid repro is provided. Please don't use CodeSandbox if the error cannot be reproduced in CodeSandbox. Use an actual repository instead.
