### ISSUE TITLE
Vue-loader migration guide may be incomplete.

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vue-loader#1251]
### Version
15.0.0

### Reproduction link
[https://pastebin.com/TyTEuT3m](https://pastebin.com/TyTEuT3m)

### Steps to reproduce
1. Have a working application on 14.x

2. Move to 15.x.

3. Explicitly separated scss and css config, copying what is described in the migration guide.

### What is expected?
I still have a working application.

### What is actually happening?

Everything errors with either

```
ERROR in ./src/common/key-value/simple-value.vue?vue&type=template&id=3cefb786
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
```

OR

```
ERROR in ./src/common/form/form.vue?vue&type=style&index=0&id=2fae5a64&scoped=true&lang=scss
Module parse failed: Unexpected token (314:0)
You may need an appropriate loader to handle this file type.
```

**Comment by robcresswell** [comment]
Basically I'm baffled by why templates no longer compile, and the error messages are so vague that I've no way of debugging this locally.

**Comment by yyx990803** [comment]
Yeah I forgot to mention a plugin is now required: https://vue-loader.vuejs.org/guide/#manual-configuration (added to the migration section as well)

**Comment by Gemorroj** [comment]
@yyx990803 after add `VueLoaderPlugin` plugin, got new error..
```
ERROR in ./assets/pages/Admin/Contact.vue?vue&type=script&lang=js (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/babel-loader/lib??ref--5-0!./assets/pages/Admin/Contact.vue?vue&type=script&lang=js)
Module build failed: SyntaxError: S:\OpenServer\domains\magazine.loc\assets\pages\Admin\Contact.vue: Unexpected token (1:0)

> 1 | <template>
    | ^
  2 |     <main>
```
