### ISSUE TITLE
broken build 15.0.0

### ISSUE THREAD

**Issue by Gemorroj** [vuejs/vue-loader#1252]
### Version
15.0.0

### Reproduction link
[https://github.com/Gemorroj/magazine](https://github.com/Gemorroj/magazine)

### Steps to reproduce
- install node.js 10
- install yarn 1.6
- install project (`yarn install --ignore-engines`)
- run project (`yarn run dev-build`)

### What is expected?
correct build

### What is actually happening?
error
```
ERROR in ./assets/pages/Admin/Contact.vue?vue&type=script&lang=js (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/babel-loader/lib??ref--5-0!./assets/pages/Admin/Contact.vue?vue&type=script&lang=js)
Module build failed: SyntaxError: S:\OpenServer\domains\magazine.loc\assets\pages\Admin\Contact.vue: Unexpected token (1:0)

> 1 | <template>
    | ^
  2 |     <main>
```

**Comment by yyx990803** [comment]
Why do you have `enforce: 'pre'` for your js rule? Does it work when you remove that?

**Comment by Gemorroj** [comment]
Hmm, yeah, if I'm removing this Directive, the project build works. Thank You!
It probably solved some other old problem, I don't remember which one anymore.
