### ISSUE TITLE
Problem with `selectBlock`

### ISSUE THREAD

**Issue by riophae** [vuejs/vue-loader#1253]
### Version
15.0.0

### Reproduction link
[https://github.com/riophae/vue-loader-bug](https://github.com/riophae/vue-loader-bug)

### Steps to reproduce
1. Clone the repo
2. Install dependencies
3. Run `npx webpack`

### What is expected?
It should build successfully.

### What is actually happening?
Got error:

```
ERROR in ./src/App.vue?type=template (./node_modules/vue-loader/lib!./src/App.vue?type=template)
Module build failed: TypeError: Cannot read property 'content' of null
    at selectBlock (/mnt/d/Projects/vue-loader-bug/node_modules/vue-loader/lib/select.js:6:27)
    at Object.module.exports (/mnt/d/Projects/vue-loader-bug/node_modules/vue-loader/lib/index.js:58:12)
 @ ./src/entry.js 4:17-62
```

---
The error is caused by this line: https://github.com/riophae/vue-loader-bug/blob/master/src/entry.js#L4

**Comment by yyx990803** [comment]
You are not supposed to use it like that.

**Comment by riophae** [comment]
With v14, it's possible to obtain content of `<template />` by: `require('vue-loader/lib/selector?type=template!./component.vue')`. How can I do the same with v15?

**Comment by yyx990803** [comment]
You need to do `require('!raw-loader!vue-loader!./App.vue?vue&type=template')`

The leading `!` disables all other loaders and `raw-loader` exports the selected content as a JavaScript string.

Note this is not part of the public API and may break without notice.

**Comment by sschneider-ihre-pvs** [comment]
I seem to get the same error like `<filename>.vue?vue&type=script&lang=ts&setup=true` in vue-loader@16.4.1

```
TypeError: Cannot read property 'content' of null

  - select.js:23 Object.selectBlock
    [<project>]/[vue-loader]/dist/select.js:23:45
```

**Comment by wsw70** [comment]
Same problem as @sschneider-ihre-pvs , in my case this is for a brand new component so I am sure that the error is on my side (something not initialized, ...) - but the error is completely cryptic and does no help to understand what is wrong:

```
 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 7134ms



 App •  ERROR  •  UI  in ./src/components/Toolbar.vue?vue&type=script&setup=true&lang=ts

TypeError: Cannot read property 'content' of null

  - select.js:23 Object.selectBlock
    [front]/[vue-loader]/dist/select.js:23:45

(...)
```

**Comment by tandrew** [comment]
Was this solved? If so, could someone be so kind to share the fix. Thanks.

**Comment by abskj** [comment]
Can this issue be reopened? It is still happening and we do not have a clear solution in the comments.

**Comment by LinusBorg** [comment]
I'm not sure what is to solve here, Evan's comments were quite clear, werent they?

If some of the comments refer to a similar but different  issue, independent of OPs initial report, please open a new issue with a proper report and reproduction

**Comment by abskj** [comment]
@LinusBorg
Agreed. Although its not very useful as replication repository is no longer visible. For me, I do not think this needs to be created a new issue as probably I was making minor mistake.

I faced the same issue and I was able to solve my issue with same error by modifying
`const props = withDefaults(defineProps<{
  a?: string;
  b?: string;
  c?: boolean;
}>(), {
  c: false,
});`
to
`const props = withDefaults(defineProps<{
    a: string;
    b: string;
    c: boolean;
  }>(), {
    a: '',
    b: '',
    c: false,
  });`

This is with script-setup/typescript/vue-loader@16.8.3/vue@3.2.29
Not sure what the actual cause but hope it helps someone.

**Comment by hariprasadiit** [comment]
@wsw70 @abskj 
I had the same problem.
I've debugged it and found that 

`type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.` is the actual error

I was passing `type` instead of an `interface`

ex.

!`Wrong way`
```ts
type Props = {
	a: string;
	b?: number;
}

defineProps<Props>()
```
`Correct way`

```ts
interface Props {
	a: string;
	b?: number;
}

// or

interface IProps extends Props {}

defineProps<IProps>()

// or

// Object literal
defineProps<{
	a: string;
	b?: number;
}>();
```

**Comment by AlphaJuliettOmega** [comment]
It would be nice if this error showed where the error came from instead of swallowing and erroring in `selectBlock`, it's not a useful error message.
