### ISSUE TITLE
Update to 15.0.1 version

### ISSUE THREAD

**Issue by bp91** [vuejs/vue-loader#1258]
### Version
15.0.0

### Reproduction link
[https://github.com/bp91/nginx-vue-docker.git](https://github.com/bp91/nginx-vue-docker.git)

### Steps to reproduce
Update version from 14.2.2 to 15.0.1

### What is expected?
That projects that works good with previous versions will continue to work even after an update

### What is actually happening?
In all my components (.vue files), the following exception is returned: 

```
./src/pages/Component.vue
vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config
```

**Comment by gaspoute** [comment]
A plugin is now required for vue-loader 15: https://vue-loader.vuejs.org/migrating.html#a-plugin-is-now-required :wink:

**Comment by yyx990803** [comment]
Do you know what a member major release mean?

**Comment by cisolarix** [comment]
我来翻译一下：大版本升级就这样，爱用用，不用滚
