### ISSUE TITLE
webpack4.0中使用happypack

### ISSUE THREAD

**Issue by chenyihao2621023** [vuejs/vue-loader#1264]
### Version
14.2.2

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
new HappyPack({
      id: 'vue-loader',
      threads: 4,
      loaders: [ {
        loader: "thread-loader",
        options: {
          threadMode: true
        }
      },'vue-loader' ]
    }),
    new HappyPack({
      loaders: [{
        path: 'vue-loader',
        query: {
          vueLoaderConfig
        }
      }]
    })
{
        test: /\.vue$/,
        loader: 'happypack/loader?id=vue-loader',
        options: vueLoaderConfig
      },

### What is expected?
正常运行

### What is actually happening?
无报错，但是打开页面，是空白页

**Comment by yyx990803** [comment]
重现不符合要求。
