### ISSUE TITLE
mini-css-extract-plugin not working with vue-loader   stylus

### ISSUE THREAD

**Issue by jamelt** [vuejs/vue-loader#1266]
### Reproduction link
[https://github.com/jamelt/vue-mecp-failure](https://github.com/jamelt/vue-mecp-failure)

### Steps to reproduce
Just run webpack on the prod config:

npx webpack  --config build/webpack.prod.conf.js

I'm using webpack merge for the production build. I'm using MCEP for css and stylus, it crashes.

---

Any generic project with Stylus and SFC with Vue Loader will fail with MCEP. 

### What is expected?
Expect to have css output files.

### What is actually happening?
It just fails to output the css or process.

---
I thought it should reported somewhere that this combination simply doesn't work as it stands today. It could be a MCEP bug or Vue-Loader bug. I'm not an expert on either of these modules but something is not working correctly.

**Comment by yyx990803** [comment]
FYI simply merging like that results in duplicated rules, that's why it breaks. Try `merge.smart()` and ensure the final config indeed only has one rule for each file type.

**Comment by jamelt** [comment]
Thanks for looking into this. The was precisely the problem. Cheers! :beers:
