### ISSUE TITLE
Parse error for SVG viewBox attribute

### ISSUE THREAD

**Issue by steffans** [vuejs/vue-loader#127]
The loader gives me a parse error for a camelcase `viewBox`attribute of a SVG tag.

`Found camelCase attribute: viewBox="0 0 50 50". HTML is case-insensitive. Use view-box="0 0 50 50" instead. Vue will automatically interpret it as camelCase in JavaScript.`

**Comment by yyx990803** [comment]
Thanks, update `vue-template-validator` (`vue-loader`'s dependency) to 1.1.1 and this should be gone.
