### ISSUE TITLE
Error: Can't resolve 'vue-loader/node_modules/vue-hot-reload-api'

### ISSUE THREAD

**Issue by yinxin630** [vuejs/vue-loader#1272]
### Version
14.2.2

### Reproduction link
[https://codepen.io/yinxin630/pen/jxybqZ](https://codepen.io/yinxin630/pen/jxybqZ)

### Steps to reproduce
我正在编写一个cli应用, 在cli中配置了webpack vue-loader, 当使用另一个目录(/xxx/vue-project)使用cli编译vue代码时, 出现错误`Error: Can't resolve 'vue-loader/node_modules/vue-hot-reload-api' in /xxx/vue-project`, 而且将vue-loader的options.hotReload设置为false就不会出现该错误了. 为什么没能正确的加载呢?

### What is expected?
期望webpack打包成功, 且代码支持hot reload

### What is actually happening?
打包失败

**Comment by yyx990803** [comment]
你意思是自己在写 cli 然后 npm link 到另一个目录？这是正常的，你要自己配好 webpack 的 resolve，但这不属于 vue-loader 的问题。

**Comment by yinxin630** [comment]
```js
{
    test: /\.vue$/,
    use: [
        {
            loader: require.resolve('vue-loader'),
            options: {
                hotReload: false,
                loaders: {
                    js: jsLoader,
                    css: [
                        require.resolve('vue-style-loader'),
                        require.resolve('css-loader'),
                    ],
                    less: [
                        require.resolve('vue-style-loader'),
                        require.resolve('css-loader'),
                        require.resolve('less-loader'),
                    ],
                },
            },
        },
    ],
},
```
我编写的cli应用是一个vue编译程序, 其中vue loader配置如上, 这些包我可以通过`require.resolve`调用cli项目内版本, 但是`vue-hot-reload-api`我没有找到能配置为使用`require.resolve`的方式引入, 因此使用cli应用编译vue项目得到报错找不到`vue-hot-reload-api`, 且报错信息显示它是在vue项目中寻找的而不是在cli应用目录. 我看`vue-loader`源码中是使用`require.resolve`引入的`vue-hot-reload-api`, 为啥这里没能正确的定位包位置呢?
