### ISSUE TITLE
Vue-Loader trying to load file extentions placed in node_externals

### ISSUE THREAD

**Issue by AtofStryker** [vuejs/vue-loader#1276]
### Version
15.0.0

### Reproduction link
[https://codesandbox.io/s/r4r19005om](https://codesandbox.io/s/r4r19005om)

### Steps to reproduce
in webpack config, have an external to ignore file extentions of certain types and require them at runtime.
,{
            externals: [
                function(context, request, callback) {
                    if (/^.*\.(png|jpg|gif|svg)/.test(request)){
                        return callback(null, 'commonjs '   request);
                    }
                    callback()}
                ]
        })

within a SFC, import a scss file from node_module that contains references to ignored file extentions (png, svg, etc)
<style lang="scss">
@import "~some_node_style.scss"
</style>

### What is expected?
svg, png, and other file extentions mentioned in the regular expression are ignored

### What is actually happening?
vue-loader is looking for a loader to process file extentions. It seems to fail to recognize the externals presented by webpack

---
I would like to add an example of the webpack configuration. Is there a way to do this without creating a github repo. I cant seem to add it to codeSandbox configurations? This bug works in v14 but not v15. Is there a post process that needs to be included as I know those have been stripped out. Could this be related to the new loading behavior? hopefully I am just missing something =)

**Comment by yyx990803** [comment]
Try null-loader instead.

**Comment by AtofStryker** [comment]
Looks to have fixed my issue! Something I missed with the webpack 4 upgrading. For those interested, I added the following to my webpack configuration:

module: {
            rules: [
                {
                    test: /^.*\.(png|jpg|gif|svg)/,
                    loader: 'null-loader'
                }
            ]
        }

Everything seems to process as expected. Thanks Evan!
