### ISSUE TITLE
vue-loader failing with new webpack-cli

### ISSUE THREAD

**Issue by Rajan** [vuejs/vue-loader#1285]
### Version
15.0.0

### Reproduction link
[https://github.com/Rajan/lesspod](https://github.com/Rajan/lesspod)

### Steps to reproduce
clone lesspod repo and cd to /client
npm install && npm run dev
It'll fail.

### What is expected?
The build should be successful.

### What is actually happening?
 error  in ./src/components/Newpost.vue?vue&type=template&id=0a0a8440

Module parse failed: Unexpected token (2:1)
You may need an appropriate loader to handle this file type.
| 
| 	<section class="section">
| 		<div class="container">
| 			<div class="columns is-centered is-multiline">

 @ ./src/components/Newpost.vue 1:0-85 10:2-8 11:2-17

---
    "vue-loader": "^15.0.6",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.6.0",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-dev-server": "^3.1.4",
    "webpack-merge": "^4.1.2"

**Comment by JounQin** [comment]
Configuration of `vue-loader` 14 and 15+ is not compatible, please follow https://vue-loader.vuejs.org/migrating.html to upgrade.

**Comment by Rajan** [comment]
I followed the new configuration. Now, It shows warnings and all vue code has stopped working.

`
vue.esm.js?a026:591 [Vue warn]: Property or method "logoClick" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Navbar> at src/components/Navbar.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:591
vue.esm.js?a026:591 [Vue warn]: Invalid handler for event "click": got undefined

found in

---> <Navbar> at src/components/Navbar.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:591
2vue.esm.js?a026:591 [Vue warn]: Property or method "email" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at src/components/Login.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:591
2vue.esm.js?a026:591 [Vue warn]: Property or method "password" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at src/components/Login.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:591
vue.esm.js?a026:591 [Vue warn]: Property or method "login" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at src/components/Login.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:591
vue.esm.js?a026:591 [Vue warn]: Invalid handler for event "click": got undefined

found in

---> <Login> at src/components/Login.vue
       <App> at src/App.vue
         <Root>
`

**Comment by Rajan** [comment]
Had to switch back to web pack 3 as of now.

**Comment by yyx990803** [comment]
Please provide a minimal reproduction.

**Comment by LoverMaker** [comment]
I got this error, too
