### ISSUE TITLE
`export default` suggests that normal export should also work

### ISSUE THREAD

**Issue by q42jaap** [vuejs/vue-loader#129]
Suppose we have a `.vue` file with:
```
export default {
  name: 'MyComponent'
}

export { myFunction }
```

If I understand correctly, the generate code does not add myFunction to the module.exports for the file.
Maybe I'm doing something wrong here, but if I'm correct, it's either weird that the function is not exported, or there should be a warning/error that vue-loader is not allowed.

If I'm making a mistake here, please let me know too!

**Comment by yyx990803** [comment]
`vue-loader` normalizes the final export so that one can `require('*.vue')` instead of `require('*.vue').default`, which is useful during code-splitting. I guess I'll add a warning that named exports in a Vue component will get discarded.

**Comment by yyx990803** [comment]
Implemented in cf7ae96b87528857e596f969dc1ea2e0f59b1b94

**Comment by DojoGeekRA** [comment]
Hi @yyx990803, i'm receiving the same warning and even though all the code run as expected, i can't quite understand what is happening.

My `.vue` file has the following code:

```
<template>
    <!-- Maybe not relevant -->
</template>

<script>
    export default {
        data() {
            // Maybe not relevant
        },
        methods() {
            // Maybe not relevant
        }
    }
</script>
```

Can you help me to understand to know if i am doing something wrong?, thanks for your time!

**Comment by LinusBorg** [comment]
Please open a new issue, with a repository containing minimum code that reproduces this issue.

**Comment by DojoGeekRA** [comment]
I'm sorry @LinusBorg, i wrote here because i thought that given that this issue was related, but you're right, an independant issue is more appropriate.
