### ISSUE TITLE
use sideEffects:fasle in package.json, ignore sass dependencies, generated css is missing in the output dir

### ISSUE THREAD

**Issue by gisshan2012** [vuejs/vue-loader#1295]
### Version
15.0.0

### Reproduction link
[https://github.com/gisboyshan/vue-loader-nocss.git](https://github.com/gisboyshan/vue-loader-nocss.git)

### Steps to reproduce
yarn build

### What is expected?
generated css

### What is actually happening?
generated css is missing in the output dir

**Comment by LinusBorg** [comment]
Css is a six effect
