### ISSUE TITLE
vue loader 15.0.10 is not compatible with webpack 4.8.3

### ISSUE THREAD

**Issue by sumitpateltech** [vuejs/vue-loader#1298]
I have try to implement vue loader in vue app with webpack 4.8.3 version and having error,

    ERROR in ./src/App.Vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
`| <template>
 |     <div>
 |   <p>Hello World!</p>`
 @ ./src/app.js 2:0-27 6:19-22
 @ multi ./src/app.js

**dependencies**

    "devDependencies": {
    "css-loader": "^0.28.11",
    "vue-loader": "^15.0.10",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.8.3",
    "webpack-cli": "^2.1.3"
    }

**In webpack.config.dev.js**

    const { VueLoaderPlugin } = require('vue-loader')
    module.exports = {
    mode: 'development',
    entry: [
    './src/app.js'
    ],
    module: {
    rules: [{
        test: /\.vue$/,
        use: 'vue-loader'
    }]
    },
    plugins: [
    new VueLoaderPlugin()
    ]
    }

**Comment by iksdatoo** [comment]
Anybody here who has working vue-loader with webpack 4.8
