### ISSUE TITLE
No matching use for vue-loader is found only on production env

### ISSUE THREAD

**Issue by greenscript** [vuejs/vue-loader#1301]
### Version
15.0.0

### Reproduction link
[https://github.com/greenscript/vue-presspack](https://github.com/greenscript/vue-presspack)

### Steps to reproduce
<ul>
  <li> Clone the repository </li>
  <li> npm install or yarn  </li>
 <li> npm start (to see it working on dev mode) </li>
  <li> npm run build (to see it not working on production mode) </li>
</ul>

### What is expected?
That the project compiles successfully in both production and development mode. 

### What is actually happening?
At the moment the project is compiling as desired on development mode, but, when it enters production mode it returns this message: 
No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
as it wasn't recognizing the .vue files, don't get why if it was indeed working on dev mode, my best guess would be that the rules are being overwritten somehow. 

---
Thanks before hand for reviewing the issue, and I just wanted to say that I'm a big fan of Vue.js, keep it up!

**Comment by yyx990803** [comment]
Try use a newer webpack version. I think v15 assumes webpack 3+

**Comment by greenscript** [comment]
Hello, yeah my bad there, forgot updating the dependencies that I'm using on the repository (just updated them), but it was because the output of the error was the same, I'm currently trying with Webpack 3+ and I'm still getting the error, but anyways I'll keep trying! thanks for the quick response, it could be a wrong configuration on my end tho, just felt like it could be some sort of bug with the rules
