### ISSUE TITLE
Migration Guide "Migrating from v14" is incomplete

### ISSUE THREAD

**Issue by kuechlerm** [vuejs/vue-loader#1303]
### What problem does this feature solve?
Migrating to v15 causes the following error if you target postcss:
"Module parse failed: Unexpected token (35:0)
You may need an appropriate loader to handle this file type."

### What does the proposed API look like?
Migration Guide should state that you have to change <style lang="postcss"> to <style> in .vue files.

**Comment by yyx990803** [comment]
This depends on your config. If following the new config and you have corresponding rules that test for `/\.postcss/` you don't have to remove `lang="postcss"`.

**Comment by kuechlerm** [comment]
That is also not obvious because it is missing in the migration guide.
