### ISSUE TITLE
Remove prop validation from live builds

### ISSUE THREAD

**Issue by dougalg** [vuejs/vue-loader#1315]
### What problem does this feature solve?
In order to further optimize live builds, can we filter out type, required, and validator from production builds if they are explicitly specified in the props definition?

This seems like a reasonable change since Vue will ignore them in production anyway, and would lead to a continued nice dev experience coupled with also a slightly more optimal build size in production.

### What does the proposed API look like?
Setting `mode: 'production'` in the webpack config should enable this, there could also be an option to disable this in the vue-loader options.

**Comment by yyx990803** [comment]
This can be done via a Babel plugin, but not in vue-loader.

**Comment by olivierkrener** [comment]
Could you please elaborate on what Babel plugin to use and how to add it to a webpack build?
