### ISSUE TITLE
build 后，部分组件的样式丢失。

### ISSUE THREAD

**Issue by JZLeung** [vuejs/vue-loader#1316]
异步组件1：
```js
<template>
  <li class="list-item">something in it.</li>
</template>

<script></script>

<style scoped lang="scss" src="@/scss/vue-tree.scss">
// @import '~@/scss/vue-tree.scss';
// Can't work properly
</style>
```
在开发模式中，style 被正常加载：
![image](https://user-images.githubusercontent.com/7995232/40553468-51218c82-6075-11e8-8548-630d009309b1.png)

但是打包后，样式却丢失了，js 中存在该 css 文件的样式，但是没有加载到页面当中，导致页面样式显示错误。而且是突然就这样了。
![image](https://user-images.githubusercontent.com/7995232/40553521-7fca7b20-6075-11e8-9ad0-d2221d204756.png)
打包后的 js：
![image](https://user-images.githubusercontent.com/7995232/40553582-ab7cd7f4-6075-11e8-86fe-ac626768873d.png)
能找到 class 为 vue-tree 的样式，但是在 element 面板中却查找不到。

**Comment by suedar** [comment]
这个问题有解决方法了吗
