### ISSUE TITLE
build 后，部分组件的样式丢失。

### ISSUE THREAD

**Issue by JZLeung** [vuejs/vue-loader#1317]
### Version
13.3.0

### Reproduction link
[http://none.com](http://none.com)

### Steps to reproduce
```js
<template>
  <li class="list-item">something in it.</li>
</template>

<script></script>

<style scoped lang="scss" src="@/scss/vue-tree.scss">
// @import '~@/scss/vue-tree.scss';
// Can't work properly
</style>
```

### What is expected?
在开发模式中，style 被正常加载：
![image](https://user-images.githubusercontent.com/7995232/40553468-51218c82-6075-11e8-8548-630d009309b1.png)

### What is actually happening?
但是打包后，样式却丢失了，js 中存在该 css 文件的样式，但是没有加载到页面当中，导致页面样式显示错误。而且是突然就这样了。
![image](https://user-images.githubusercontent.com/7995232/40553521-7fca7b20-6075-11e8-9ad0-d2221d204756.png)
打包后的 js：
![image](https://user-images.githubusercontent.com/7995232/40553582-ab7cd7f4-6075-11e8-86fe-ac626768873d.png)
能找到 class 为 vue-tree 的样式，但是在 element 面板中却查找不到。

**Comment by yyx990803** [comment]
只写了带前缀的 css，没写不带前缀的？

**Comment by JZLeung** [comment]
@yyx990803 
不是，而是整个 scss 都没有被添加到 html 的 style 中。有几个 style 标签中是空白，但是有些 style 中的 sourcemap 是 undefined。
![image](https://user-images.githubusercontent.com/7995232/40571731-bfcfab40-60d0-11e8-8169-c9d444282bfb.png)
正常应该是这样的吧。同样是异步加载的组件，这个组件的样式可以正常显示。
![image](https://user-images.githubusercontent.com/7995232/40571742-f5085528-60d0-11e8-8d2e-01d19f2147a5.png)

**Comment by Justineo** [comment]
你给的信息不足以排查问题。

**Comment by JZLeung** [comment]
@Justineo 
抱歉，因为重新写一个 demo，是可以加载 css 的。而且，同一个项目下，同样是异步加载的组件，就只有这个组件的样式无法被加载。

**Comment by yyx990803** [comment]
很抱歉，没有重现我们帮不了你。

**Comment by noney** [comment]
我也遇到了这个问题，我知道重现步骤，就是同一个组件被同步和异步两种方式在两个不同页面引用时，异步方式会丢失样式。请问有什么好的方式吗？

**Comment by bibichuan** [comment]
我遇到这个问题，是出现在npm build后，在el-dialog中的部分组件样式没加载上
