### ISSUE TITLE
Error: vue-loader was used without the corresponding plugin

### ISSUE THREAD

**Issue by indus** [vuejs/vue-loader#1331]
### Version
15.2.1

I'm getting the error in the title because [this if statement](https://github.com/vuejs/vue-loader/blob/master/lib/index.js#L18) is always false. And that's because the paths used to check for the existence of the plugin doesn't match. They have different separators:
```
value of NS:               "D:\<root>\node_modules\vue-loader\lib"
property of loaderContext: "D:\\<root>\\node_modules\\vue-loader\\lib"
```
It is hard to provide a reproduction link because this propably just depends on the OS you are using. Nevertheless this property-lookup-test is insuffiecent for me on windows 7.

ref: https://github.com/vuejs/vue-cli/issues/1345
(when I just uncomment the test, everything works as expected)

**Comment by yyx990803** [comment]
This is very weird... looks like the value was somehow escaped when being exposed on `loaderContext`? Can you try to modify `NS` to a constant string in your local `node_modules/vue-loader/lib/plugin.js` to see if that solves the problem?

**Comment by indus** [comment]
Windows and paths 😩
I can't reproduce the error on my own computer (Windows 10; node 8.6.0; npm 5.3.0) - but on Monday I'm back in the office and can tell you if a simple string fixes the problem (I would guess so).
Looks like this is somewhat specific to my environment - but I'm unaware of any strange aspects in my setup.
