### ISSUE TITLE
vue components use CommonJS 'module.exports'

### ISSUE THREAD

**Issue by cench** [vuejs/vue-loader#1337]
### Version
13.7.0

### Steps to reproduce
in vue component file, if i use the commonjs way to export
```
// error way
module.exports = {
    name: 'component-name'
}

// normal write
export default {

}
```
> Because of some historical writing

### What is expected?
compile is ok.

### What is actually happening?
find error

---
```
21:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader!../../../node_modules/vue-loader/lib/selector?type=script&index=0!./component-upload.vue'
```

**Comment by Justineo** [comment]
It should be `module.exports` instead of `module.export`.

**Comment by ulivz** [comment]
See breaking changes in [v13.0.0](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0).

> old CommonJS-style requires will also need to be updated:

``` js
// before
const Foo = require('./Foo.vue')

// after
const Foo = require('./Foo.vue').default
```

**Comment by ulivz** [comment]
BTW, I think you can upgrade your `vue-loader` to the 14 or higher version. because from [v14.0.0](https://github.com/vuejs/vue-loader/releases/tag/v14.0.0)

> esModules option has been removed. Built module is now always exposed as an ES module.

**Comment by cench** [comment]
@ulivz `vue-loader` has been updated to `v14.1.0`， question is the still.
so i need to do some for babel in vue-loader config ?

**Comment by ulivz** [comment]
Could you provide your webpack's version? or it would be better to also provide a minimal reproduction repo link.

**Comment by cench** [comment]
@ulivz use the vue-cli webpack config, webpack version is 3.6.0

**Comment by yyx990803** [comment]
14.0+ no longer supports `module.exports`. Use `export default` instead.

**Comment by sj82516** [comment]
Is anyway to support module.exports in vue-cli3 created project ?
Because I would like to share some common module with frontend and backend.
