### ISSUE TITLE
Style postcss sugarss syntax

### ISSUE THREAD

**Issue by lagden** [vuejs/vue-loader#1338]
### Version
15.2.1

### Reproduction link
[https://github.com/lagden/vue-postcss-sugarss](https://github.com/lagden/vue-postcss-sugarss)

### Steps to reproduce
`npm i`  
open `src/components/App.vue`  
add `<style module lang="postcss">`  
exec `npm run build`

### What is expected?
should build

### What is actually happening?
causing error when put `lang="postcss"`

---
the `lang="postcss"` just used to highlight syntax when use [sugarss](https://github.com/postcss/sugarss)...

**Comment by lagden** [comment]
I did a workaround, but I will still maintenance this issue opened waiting for alternative response.

https://github.com/lagden/vue-postcss-sugarss/tree/workaround
My workaround was:

Install `npm i -D postcss-import`

no `postcss.conf.js`
```js
module.exports = ({file, options, env}) => ({
	parser: 'sugarss',
	plugins: {
		'postcss-import': {},
		autoprefixer: {...options.autoprefixer, ...{grid: true}}
	}
})
```

no `src/components/App.vue`
```html
<style module>
@import './app.sss'
</style>
```

**Comment by yyx990803** [comment]
v15 lang="postcss" means it's being matched as *. postcss and you don't have any webpack module rules for it.

**Comment by lagden** [comment]
Understood...
Thank you for you response...
👍

**Comment by lagden** [comment]
update the example (if somebody comes here 😉)

take a look: https://github.com/lagden/vue-postcss-sugarss
