### ISSUE TITLE
Vue loader does not transpile coffeescript

### ISSUE THREAD

**Issue by redbulled** [vuejs/vue-loader#1347]
It's is doesn't compile coffee script inside tags `<script lang="coffee"></script>`
I even tried to do like that:
`     {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            'scss': [
              'vue-style-loader',
              'css-loader',
              'sass-loader'
            ],
            'sass': [
              'vue-style-loader',
              'css-loader',
              'sass-loader?indentedSyntax'
            ],
            'coffee': 'coffee-loader!babel-loader'
          }`

Also I tried to make as dicumentation of coffee-loader says: 

`{
        test: /\.coffee$/,
        use: [
          {
            loader: 'coffee-loader',
            options: { 
              transpile: {
                presets: ['env']
              }
            }
          }
        ]
      }`

Yes it transpiles .cooffee files. But Vue templates still with arrow function and anything like that

**Comment by dseeker** [comment]
@redbulled I'm having this issued, tried adding the transpile env preset in coffee-loader or vue-loader and still the arrow function is not transpiled. Everything else is compiled correctly, did you find some solution?

```
cognitoReadAttr: (attributes) ->
	@store.user.cognitoUser.getUserAttributes (err, result) =>
		# alert err.message or JSON.stringify(err) if err
		i = 0
```
```
 cognitoReadAttr: function(attributes) {
      return this.store.user.cognitoUser.getUserAttributes((err, result) => {
        var i, ref;
        // alert err.message or JSON.stringify(err) if err
        i = 0;
```
