### ISSUE TITLE
vue-loader is not importing components in webpack4 vue production mode

### ISSUE THREAD

**Issue by iksdatoo** [vuejs/vue-loader#1349]
### Version
15.2.1

### Reproduction link
[https://github.com/jinwyp/koa-user/blob/master/frontend-vue/](https://github.com/jinwyp/koa-user/blob/master/frontend-vue/)

### Steps to reproduce
Download the app and try to add typescript

### What is expected?
App needs to be run on production as it runs on development.

### What is actually happening?
I can't import .vue files

---
I have typescript, vue, vuex and vue-router app and everything works perfect in development mode. Here are some vue and webpack versions:

"webpack": "^4.12.0",
"webpack-dev-middleware": "^3.1.3",
"webpack-hot-middleware": "^2.12.2",
"vue": "2.4.1",
"vue-router": "^3.0.1",
"vuex": "^3.0.1",
"vue-loader": "^15.2.1",
"ts-loader": "^4.4.0",
I am using yarn run dev to run the command and on ./src/main.ts file I have imported a component and trying to console it:

import Master from './app/master/Master.vue'
console.log(Master)
The Master component is working fine in the development and in the production version the component is a empty object and I think vue-loader is not unable to import the component correctly.

`{}`
I have tried to use older versions of vue-loader but there some errors. The app is working on development here are my webpack configuration files listed from gist.

Build Configuration: https://gist.github.com/iksdatoo/492099d8147e8f60ee04b243426b799a
Base configuration: https://gist.github.com/iksdatoo/f9eda2bb81bc175cc59dac3879df2f28
Development configuration: https://gist.github.com/iksdatoo/522516c761b3422e7a1b5eafd0211bd8
Production configuration: https://gist.github.com/iksdatoo/5772a0517daf7463b98705396a1ce976
Package JSON File: https://gist.github.com/iksdatoo/a6883bddb37150dea00c22751e9aca06
Here is my entry point file: https://gist.github.com/iksdatoo/2d5f16159060a2d9d4cd8f7e02f984d7
Let me know what I am missing.

**Comment by LinusBorg** [comment]
This is very probably a configuration mistake. One thing that caught my eye immediately is that you use the mini-extract-css loader in production, but never add the corresponding plugin (of I not mistaken). 

Issues are not meant as support tickets for your configuration problems, we have forum.vuejs.org and chat.vuejs.org for that.
