### ISSUE TITLE
Error with livescript-loader

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-loader#135]
I have [a minimal app here](https://github.com/chrisvfritz/my-vue-project) to produce the error. This is what I'm getting:

``` output
ERROR in ./~/livescript-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module build failed: SyntaxError: unterminated regex on line 3
at /[...]/my-vue-project/node_modules/vue-loader/lib/selector.js?type=script&index=0!/[...]/my-vue-project/src/App.vue
    at SyntaxError (native)
    at carp (/[...]/node_modules/livescript/lib/lexer.js:1220:9)
    at Object.exports.carp (/[...]/node_modules/livescript/lib/lexer.js:1214:3)
    at Object.exports.doRegex (/[...]/node_modules/livescript/lib/lexer.js:498:10)
    at Object.exports.tokenize (/[...]/node_modules/livescript/lib/lexer.js:78:19)
    at Object.exports.lex (/[...]/node_modules/livescript/lib/lexer.js:4:26)
    at Object.exports.compile (/[...]/node_modules/livescript/lib/index.js:45:32)
    at Object.module.exports (/[...]/my-vue-project/node_modules/livescript-loader/index.js:22:23)
 @ ./src/App.vue 2:17-115
```

It seems that as soon as I include even an empty script tag for LiveScript, _the entire file_ is parsed as LiveScript, resulting in an error trying to parse this:

``` html
<template>
  <div id="app">
    <h1>Test</h1> <!-- ERROR HERE -->
  </div>
</template>

<script lang="livescript">
</script>
```

I have confirmed a similar setup with [`coffee-loader`](https://github.com/webpack/coffee-loader) works, which [`livescript-loader`](https://github.com/appedemic/livescript-loader) is based on. Any ideas?

**Comment by borestad** [comment]
Please try my package here and see if it works for you
https://www.npmjs.com/package/vue-livescript-loader

**Comment by chrisvfritz** [comment]
@borestad Thanks! It seems to be experiencing the same problem unfortunately. :confused: I updated [my example project](https://github.com/chrisvfritz/my-vue-project) to demonstrate the issue.

**Comment by laurentpayot** [comment]
+1, same issue here…

**Comment by BlackGlory** [comment]
Hi, @laurentpayot 
Please look at the https://github.com/vuejs/vue-loader/pull/289/files, solve the problem just need to modify one line of code, wait for merge.

**Comment by laurentpayot** [comment]
Thanks a lot @BlackGlory , it did the trick! :+1: Looking forward to your commit being merged.

**Comment by yyx990803** [comment]
Closing (outdated)
