### ISSUE TITLE
Question about template attrs

### ISSUE THREAD

**Issue by RoTerentev** [vuejs/vue-loader#1354]
https://github.com/vuejs/vue-loader/blob/791999a23cb8baa8f4bc38c162eb17fe51705140/lib/index.js#L81

> Module build failed (from ./node_modules/vue-loader/lib/index.js):
> TypeError: Cannot read property 'functional' of undefined

Should there always be attributes in the template?

**Comment by jianzhou520** [comment]
@RoTerentev I met the same problem, have you fix this?

**Comment by RoTerentev** [comment]
@jianzhou520 fixed by updating the vue-template-compiler to match the Vue version
