### ISSUE TITLE
SFC not recognized when using the include option

### ISSUE THREAD

**Issue by PierBover** [vuejs/vue-loader#1360]
### Version
15.2.4

### Reproduction link
[https://github.com/PierBover/vue-loader-repro](https://github.com/PierBover/vue-loader-repro)

### Steps to reproduce
```
npm i
npm run dev
```

When adding the `include` property in the loader config the error appears. It doesn't matter if it is empty or not.

```
{
	test: /\.vue$/,
	loader: 'vue-loader',
	include: [
	]
}
```

When removing `include` the loader works as expected. This problem is also present in v14.

### What is expected?
The SFC should be bundled.

### What is actually happening?
```
ERROR in ./src/App.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
| 	<div id="App">
| 		<h1>App</h1>
```

---
There is some background info here:

https://forum.vuejs.org/t/vue-loader-configuration-for-monorepo/38436/10

**Comment by LinusBorg** [comment]
`include` tells wepack to only apply the loader in question to paths that match anything in that array.

By providing an empty array, webpack won't ever apply this rule to anything.

What are you trying to do here?

**Comment by PierBover** [comment]
Thanks for your help on the forum @LinusBorg .
