### ISSUE TITLE
Cannot load a loader before pitcher loader

### ISSUE THREAD

**Issue by CKGrafico** [vuejs/vue-loader#1361]
### Version
15.2.4

### Reproduction link
[https://github.com/CKGrafico/Frontend-Boilerplates/commit/07508fbbe812790e2b67ebede83967fe811d1d2f](https://github.com/CKGrafico/Frontend-Boilerplates/commit/07508fbbe812790e2b67ebede83967fe811d1d2f)

### Steps to reproduce
![iamge](https://i.imgur.com/zdGrVLg.png)

### What is expected?
To be able to load any loader in 'pre' before pitcher

### What is actually happening?
if you add a console log inside pitcher and inside any other loader with pre, pitcher is always first

---
We want to modify some things from vue files before vue loader

**Comment by yyx990803** [comment]
This is intentional. Don't mess with the pitcher.

**Comment by CKGrafico** [comment]
Ok thanks for your help, I will try to find another way :)
    	
    	

    	Descarga Outlook para iOS
    
  




On Fri, Jul 13, 2018 at 3:33 PM +0200, "Evan You" <notifications@github.com> wrote:












This is intentional. Don't mess with the pitcher.
