### ISSUE TITLE
Support config options to `preLoaders` 

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/vue-loader#1365]
### What problem does this feature solve?
Up to now, options `preLoaders` and `postLoaders` in `vue-loader` only support string, not like other loaders config format

### What does the proposed API look like?
we want to add custom options in `preLoaders`  and `postLoaders` not only just a string
like this: 
```javascript
module.exports = {
  loaders: {
    // other common loaders
  },
  preLoaders: {
    html: {
      loader: 'path-or-name-of-loader',
      options: { /* custom options */ }
    }
  },
}

```

**Comment by lovetingyuan** [comment]
never mind, the latest version does not support some options like `preLoaders` and `postLoaders` any more

**Comment by pekonchan** [comment]
@lovetingyuan  I want to use the feature like `postLoaders`，but the latest version does not support , how can i do instead?

I just want to use a loader for the `template` in `.vue` file, when it is transformed into the `render` js code
