### ISSUE TITLE
scoped css does not work when a selector group has extra spaces

### ISSUE THREAD

**Issue by bimbiltu** [vuejs/vue-loader#1370]
### Version
15.2.6

### Reproduction link
[https://codesandbox.io/s/moqvvv0yvp?module=%2Fsrc%2FApp.vue](https://codesandbox.io/s/moqvvv0yvp?module=%2Fsrc%2FApp.vue)

### Steps to reproduce
If you have a Vue file with a style block like this:

```
<style scoped>
.foo , .bar {
  color: red;
}
</style>
```

Then the generated rules will look like `.foo [data-v-*], .bar[data-v-*]`. Notice that there is a space between `foo` and `[` which turns it into a descendant selector

### What is expected?
The generated CSS should be `.foo[data-v-*], .bar[data-v-*] { color: red }`

### What is actually happening?
The generated CSS is `.foo [data-v-*], .bar[data-v-*] { color: red }`

**Comment by yyx990803** [comment]
Fixed in `@vue/component-compiler-utils@2.1.1`.
