### ISSUE TITLE
Wrong order of global components styles

### ISSUE THREAD

**Issue by Ventore** [vuejs/vue-loader#1375]
### Version
15.3.0

### Reproduction link
[https://github.com/Ventore/vue-loader-bug](https://github.com/Ventore/vue-loader-bug)

### Steps to reproduce
1. npm  i && npm run serve
2. open localhost

### What is expected?
Styles applied to global component overwite default styles

### What is actually happening?
Default styles of global component overwrite local styles

**Comment by yyx990803** [comment]
You are misunderstanding how `scoped` works. `scoped` styles only affect the **current component itself**, not even its children.

**Comment by Ventore** [comment]
It not about scoped styles, if you remove scoped from both modules, you will get the same result. Styles from global component overwrite styles in component where it used
![bug](https://user-images.githubusercontent.com/24790414/43907645-a6decd64-9bfe-11e8-8eb8-582c9ebad62c.PNG)

**Comment by yyx990803** [comment]
This is the correct order because you imported the Global component after the HelloWorld component (imported by App.vue)

**Comment by Ventore** [comment]
Thanks a lot for explanation 🤗
