### ISSUE TITLE
No matching use for vue-loader is found.

### ISSUE THREAD

**Issue by gijsroge** [vuejs/vue-loader#1376]
### Version
15.3.0

### Reproduction link
[https://codesandbox.io/s/714pln61k1](https://codesandbox.io/s/714pln61k1)

### Steps to reproduce
Download the sandbox & run "yarn && yarn client:build"

### What is expected?
I assume this should compile without errors

### What is actually happening?
Error is thrown:
```
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
```

**Comment by yyx990803** [comment]
That's a problem of SandCodebox, not `vue-loader`.

**Comment by gijsroge** [comment]
Hi @yyx990803! Thanks for taking a look at this. I encountered this problem locally, I just used codesandbox to provide a reproducible setup. 

If there is any other way I can provide you with a reproducible setup let me know.

**Comment by yyx990803** [comment]
The codesandbox link has empty webpack config files...

**Comment by gijsroge** [comment]
@yyx990803 Super weird as I downloaded the files from sandbox an hour ago and they were not empty. Anyway I restored the webpack files. 

Last thing I want is to waste your time, my bad. I double checked by downloading the sandbox and reproduced the issue locally again.

**Comment by yyx990803** [comment]
You have two instances of `VueLoaderPlugin` applied in your config.

**Comment by gijsroge** [comment]
@yyx990803 oh… I would never though about that. Maybe the only positive thing about this thread is that it might be helpful for future idiots like myself :)

Thanks!
