### ISSUE TITLE
Resolve custom alias in .vue <script> imports

### ISSUE THREAD

**Issue by avizcaino** [vuejs/vue-loader#1377]
### Version
15.3.0

### Reproduction link
[https://github.com/avizcaino/vue-testing](https://github.com/avizcaino/vue-testing)

### Steps to reproduce
```
git clone https://github.com/avizcaino/vue-testing
npm install
npm run serve
```

### What is expected?
In *.vue files, imports from custom alias defined in webpack (such as: `$Home: path.resolve(__dirname, "src/modules/home")`), should work exactly as in *.ts files and shouldn't be marked as unable to find.

### What is actually happening?
In *.vue files, inside the script tag, the imports from custom alias are marked as unable to find:

`import services from '$Home/services/services'` ==> `Cannot find module '$Home/services/services'.`

**Comment by yyx990803** [comment]
Your repro works as intended...

**Comment by avizcaino** [comment]
Sorry, vscode issue... it works on Webstorm.
