### ISSUE TITLE
Vue components css always come before other imported css

### ISSUE THREAD

**Issue by tiagolr** [vuejs/vue-loader#138]
Using vue-cli webpack project, if i add the extract text plugin to `webpack.base.conf.js` like so: 

```
var ExtractTextPlugin = require('extract-text-webpack-plugin');
loaders: [
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
      ...
```
then on my main.js:line 1 i add this:
```
require('./assets/myfile.css')
```
and then `npm run build`

The generated css file has the concated css definitions in this order:
```
1 - vuecomponents,css
2 - myfile.css
```

What I'm looking for is to have myfile.css definitions at the beggining of the generated css file (useful for loading bootstrap theme first for example), but so far no chance. Am i missing something or is this a limitiation or issue with vue-loader? Thank you.

**Comment by yyx990803** [comment]
This is a limitation of the extract text plugin. To change it I will probably have to dig into the plugin's code a bit, but for now it seems the only solution is directly using a separate CSS file in the HTML.

**Comment by yyx990803** [comment]
Just did a test and it seems the CSS is extracted in the module import order. Are you requiring the CSS before importing your components?

**Comment by tiagolr** [comment]
Yes, this is my current main.js file:
```
require('expose?$!expose?jQuery!jquery');
require('bootstrap-webpack!../build/bootstrap.config.js');
require('src/assets/font/flaticon.css');

import Vue from 'vue';
import Router from 'vue-router';
....
```
I will try with again with a fresh vue-cli template tommorow, thank you for your time.

**Comment by tiagolr** [comment]
Okay, i actualy tested it with a fresh vue-cli:webpack project and the problem remains:

`require('./myfile.css')` is added at the top of main.js
`App.vue` has some css in it.

after compiling with `npm run build` this is the resulting css:

`body{font-family:Helvetica,sans-serif}.outside-css{background-color:#fff}`
where `body{}` is the component css, and outside css is the required css file.

So far I am not able to place css files before vue components css, am I doing something wrong or is this a limitiation with the extract text plugin? 
The project sc is at: 

https://gitlab.com/prog4mr/vue_loader.138

Thank you

**Comment by yyx990803** [comment]
Okay, here's the reason: you are using `require` instead of `import` syntax. According to ES2015 modules spec, `import` statements are resolved **before** running your code, so Babel hoists them to the top of your module, and thus the imported modules are evaluated before your CSS require runs.

To fix this simply use `import` every where - webpack requests can also work with `import`.

**Comment by tiagolr** [comment]
Perfect, thank you, no way i would figure that soon.

**Comment by Vivi-wu** [comment]
Thanks @yyx990803 again, I solve my problem. 

> the CSS is extracted in the module import order

Here is my solution, I paste here for anyone who may need:

`import 'bootstrap/dist/css/bootstrap.min.css'
import 'font-awesome/css/font-awesome.min.css'
import '@/assets/scss/main.css'`

Style for a single component, just write them between `<style scoped>` tag

**Comment by shahinit** [comment]
https://guides.github.com/features/mastering-markdown/
https://guides.github.com/features/mastering-markdown
https://help.github.com/articles/github-terms-of-service
https://github.com/site/privac
https://help.github.com/articles/github-security
https://help.github.com//y//

**Comment by Zalezale** [comment]
@yyx990803  when build  ，Css import in  main.js   after Css  in *.vue how to deel with this?

**Comment by freakzlike** [comment]
@Zalezale i got the same issue after upgrading from vue-loader 14.2.2 to 15.2.1. But i got no solution

**Comment by xyzdata** [comment]
# why this way it doesn't work?

![image](https://user-images.githubusercontent.com/29531779/48173319-3b780900-e33e-11e8-8a1f-979a9eec5a9f.png)
