### ISSUE TITLE
is it possible to support inner template tag to use "src" attribute?

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/vue-loader#1380]
### What problem does this feature solve?
as far as now, vue SFC only support the root `template` tag use `src` attribute, is it possible to support the children template tag under the root template tag use `src` attribute?

### What does the proposed API look like?
```html
<template>
  <div>
    <p>title</p>
    <!-- replace the next template tag with the content(html string) of file: './long-content.html' -->
    <template src="./long-content.html"/>
    <p>other content</p>
  </div>
</template>
```

**Comment by yyx990803** [comment]
Not really. Just use a component.
