### ISSUE TITLE
Start with deep selector in css scope

### ISSUE THREAD

**Issue by ShuZhong** [vuejs/vue-loader#1381]
### Version
15.2.5

### Reproduction link
[https://github.com/ShuZhong/vue_loader_test1](https://github.com/ShuZhong/vue_loader_test1)

### Steps to reproduce
```
<style scoped>

.appMain {
    background: #00ff00;
}

>>> .appChild {
    background: #ff0000;
}

</style>
```

### What is expected?
```
.appMain[data-v-0985873c] {
    background: #00ff00;
}
[data-v-0985873c] .appChild {
    background: #ff0000;
}
```

### What is actually happening?
```
.appMain[data-v-0985873c] {
    background: #00ff00;
}
 .appChild {
    background: #ff0000;
}
```

**Comment by yyx990803** [comment]
This is now supported via `@vue/component-compiler-utils` 2.2.0: https://github.com/vuejs/component-compiler-utils/blob/master/CHANGELOG.md#220-2018-08-16
