### ISSUE TITLE
HMR not working properly with typescript

### ISSUE THREAD

**Issue by rvhelden** [vuejs/vue-loader#1382]
### Version
15.3.0

### Reproduction link
[https://gitlab.com/kiltux/VueJS-Starter](https://gitlab.com/kiltux/VueJS-Starter)

### Steps to reproduce
npm install

npm run serve

goto localhost:9000

change App.Vue

changes are not applied

### What is expected?
The changes to propagate to the browser

### What is actually happening?
No propagating the changes to the browser, but instead gives the following output in the console:

[WDS] App updated. Recompiling...
client:80

[WDS] App hot update... client:224

[HMR] Checking for updates on the server... log.js:24

Ignored an update to unaccepted module ./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=ts& log.js:26

Ignored an update to unaccepted module ./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=template&id=7ba5bd90& log.js:26

Ignored an update to unaccepted module ./src/main.ts log.js:26

[HMR] The following modules couldn't be hot updated: (They would need a full reload!) log.js:26

[HMR]  - ./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=ts& log.js:26

[HMR]  - ./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=template&id=7ba5bd90& log.js:26

[HMR]  - ./src/main.ts log.js:26

[HMR] Nothing hot updated. log.js:24

[HMR] App is up to date. log.js:24

[Show/hide message details.] too much recursion[Learn More]

**Comment by yyx990803** [comment]
Please use the official Vue CLI 3 - we do not have the bandwidth to help debug arbitrary build setups.
