### ISSUE TITLE
Can't get extract plugin and styles from vue components with vue-loader

### ISSUE THREAD

**Issue by rafalolszewski94** [vuejs/vue-loader#1385]
### Version
15.3.0

### Reproduction link
[https://codesandbox.io/s/7jp4y17ypq](https://codesandbox.io/s/7jp4y17ypq)

### Steps to reproduce
1. Install https://github.com/webpack-contrib/mini-css-extract-plugin

2. Use this webpack config to get the extraction working, but then styles from vue components (i.e. `<style>....</style>` won't work, same for style with `lang="scss"`, `scoped` etc.)

### What is expected?
Have extraction working   style from vue components to work too.

### What is actually happening?
Only one of the wanted results are working (either extraction OR style from a component)

---
I was following https://vue-loader.vuejs.org/guide/extract-css.html   https://vue-loader.vuejs.org/guide/pre-processors.html#sass for my project but it doesn't say anywhere how to combine those two together (could be that I've missed something in between, or docs are lacking info)

**Comment by yyx990803** [comment]
The idea is replacing `vue-style-loader` with `MiniCssExtractPlugin.loader` for the production build.

**Comment by rafalolszewski94** [comment]
Does it mean that you can't have both: extracting, and vue styles inline from components as of webpack 4 ?
