### ISSUE TITLE
Order of CSS

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue-loader#1390]
### Version
15.4.0

### Reproduction link
[https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/745](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/745)

### Steps to reproduce
```
			{
				test: /\.css$/,
				use: [
					isDevelop ? 'vue-style-loader' : MiniCssExtractPlugin.loader,
					'css-loader',
					'postcss-loader',
				],
			},
```

### What is expected?
CSS from the components should be put at the end of the file. See https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/745 for the same issue reported with extract-text-webpack-plugin earlier.

### What is actually happening?
The CSS from the components gets put before the CSS from the standalone CSS files in the final generated file.

**Comment by yyx990803** [comment]
That's not a valid reproduction.
