### ISSUE TITLE
postcss does not work as expected with vue-loader

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-loader#1395]
### Version
15.4.0

### Reproduction link
[https://github.com/JounQin/test/commit/ba578d339b1b3bf3155c850192b8b460e7cede2c](https://github.com/JounQin/test/commit/ba578d339b1b3bf3155c850192b8b460e7cede2c)

### Steps to reproduce
Clone https://github.com/JounQin/test and checkout branch `vue-loader`, run `yarn build` and check `dist/main.*.css` file, it is minified. Change code back to Vue style version and run `yarn build` again, `dist/main.*.css` is not minified correctly.

### What is expected?
`dist/main.*.css` should be minified.

### What is actually happening?
`dist/main.*.css` is not minified.

**Comment by JounQin** [comment]
I find out it is caused by `https://github.com/vuejs/component-compiler-utils/blob/master/lib/stylePlugins/trim.ts#L7`. It is named `trim`, should it be `raws.before = raws.after = ''`?
@yyx990803

**Comment by JounQin** [comment]
It seems @yyx990803 you have came back to 'work', would like to check about this issue?

**Comment by manniL** [comment]
I'd love to see progress as well :relaxed:

**Comment by manniL** [comment]
@JounQin Could you change the title of the PR to something more descriptive? 🤔

**Comment by yyx990803** [comment]
I just ran your reproduction and can't seem to reproduce the problem. I'm not sure how your repo even is related to `vue-loader` since it's importing a `.scss` file which not handled by `vue-loader` at all.

Also not able to reproduce the minification issue via `vue-cli`, so I assume this has something to do with your specific setup.

**Comment by yyx990803** [comment]
FYI, the trim plugin has always worked like that for over a year. This has never been a problem and unlikely to be the root cause.

**Comment by yyx990803** [comment]
I was able to reproduce this via Vue CLI as I noticed this only happens for CSS inlined in JavaScript.
