### ISSUE TITLE
How to process the relative src in the <img> tag

### ISSUE THREAD

**Issue by kirkzwy** [vuejs/vue-loader#14]
when I use the relative src in the <img> tag just like below:
```
<img class="abs" src="media/V2.0_home_Kits1.1.png">
```

when compile the vue, it will report err, like

```
ERROR in ./~/html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/views/letsGuessIndexView.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./V2.0_home_Kits1.1.png in /Users/mingxinzhou/Documents/LetsCake-LetsGuess/app/src/views
 @ ./~/html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/views/letsGuessIndexView.vue 1:261-295
```
![image](https://cloud.githubusercontent.com/assets/1320903/8893613/0e803ad4-33ca-11e5-9dd6-859b1cc422c7.png)

how should I deal with

**Comment by Jinjiang** [comment]
Webpack will handle relative `img[src]` value as file resources by default. You can added [`file-loader`](https://www.npmjs.com/package/file-loader) or [`url-loader`](https://www.npmjs.com/package/url-loader) to get it through. Or if you don't want nothing happened, you can also use [`name-loader`](https://www.npmjs.com/package/name-loader) to just pass the module name (actually the whole module path) to bundle.

Hope helpful for you.

**Comment by kirkzwy** [comment]
Thanks for your help. Should I use the [file-loader](https://www.npmjs.com/package/file-loader) , or [url-loader](https://www.npmjs.com/package/url-loader) in the webpack config file like below
![image](https://cloud.githubusercontent.com/assets/1320903/8894141/5cd03e8c-33de-11e5-9ea2-1b03fc99ac61.png)

Because I write the tag in the .vue file.

**Comment by Jinjiang** [comment]
For example:

```
loaders: [
  { test: /\.vue$/, loader: 'vue'},
  { test: /\.json$/, loader: 'json'},
  { test: /\.(?:jpg|gif|png)$/, loader: 'file'}
]
```

**Comment by kirkzwy** [comment]
Thanks again. I think I have got the point .

**Comment by Haixing-Hu** [comment]
The same problem with mine: see #15 

A temporal solution is to use the "v-attr" directive,
```
<img class="abs" v-attr="src:'media/V2.0_home_Kits1.1.png'">
```
