### ISSUE TITLE
warn user if they use wrong attribute on <script>

### ISSUE THREAD

**Issue by gasparch** [vuejs/vue-loader#1405]
### What problem does this feature solve?
In case if developer overseen correct tag name in documentation
```
<script lang="ts"> 
```

on section definition and automatically typed in (which is default attribute name for HTML)
```
<script type="ts"> 
```

No reasonable errors are given (because it silently falls back to JavaScript) and it is very hard to notice that wrong attribute is used.

### What does the proposed API look like?
When selecting section - check that type attribute is present and has value `js` or `ts`. In that case - fail compilation and suggest user use `lang` attribute. 

Message like 
```
 [vue-loader] You are trying to set <script> language using 'type' attribute in file $path.
 This does not work, correct way is to use  'lang'  attribute - <script lang="ts"> or <script lang="js">

```

This may save hours of debugging webpack config/tsconfig, when actually it is just thinko by developer.

**Comment by posva** [comment]
The thing is someone could write a plugin/loader that handles a `type` attribute. This is really a niche case, documentation is clear about using the attribute `lang` so imo not worth adding
