### ISSUE TITLE
Allow a <tests></tests> element block in .vue single file components

### ISSUE THREAD

**Issue by sarmadbokhari** [vuejs/vue-loader#1413]
### What problem does this feature solve?
Allow users to write tests right inside their single file components. My co-worker and I were thinking how amazing it would be if we could write tests right where we were on our single file components instead of having to open the component in a separate tab and write tests for all the things the component does.

### What does the proposed API look like?
```
<template></template>
<script></script>
<style></style>
<tests lang="jest/chai/etc">
   WRITE TESTS HERE
</tests>
```

**Comment by kazupon** [comment]
You can use custom blocks.
See the docs: https://vue-loader.vuejs.org/guide/custom-blocks.html
