### ISSUE TITLE
Cannot pass plugins to babel for js within vue files

### ISSUE THREAD

**Issue by bcliffor** [vuejs/vue-loader#1419]
### Version
15.3.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/774179/](https://jsfiddle.net/50wL7mdz/774179/)

### Steps to reproduce
I need to tell babel to run specific plugins only for js within vue files. I am attempting to do that with a vue-loader setting of
```
module.exports = {
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      js: {
        loader: 'babel-loader',
        options: {
          plugins: [
            'transform-vue-jsx',
          ],
        },
      },
    },
  },
}
```

### What is expected?
The babel plugin should run.

### What is actually happening?
The babel plugin is not running.

---
Thank you!

**Comment by fbouliane** [comment]
Hi, We had the same problem. It seems that this way to pass options to babel is not working anymore. 
Sadly, we had to use a .babelrc to make it work. 
I really wish vuejs-loader would support this kind of configuration but it doesnt seems to be working.

**Comment by yyx990803** [comment]
Configuration for v15 has changed completely - refer to the new usage: `https://vue-loader.vuejs.org/guide/pre-processors.html#babel` - it picks up what you configure for normal js files.
