### ISSUE TITLE
css-loader  :local()

### ISSUE THREAD

**Issue by lilijialiang** [vuejs/vue-loader#142]
```js
// webpack 配置
        vue: {
            loaders: {
                sass: ExtractTextPlugin.extract('style', 'css?localIdentName=[local]___[hash:base64:5]!sass')
            }
        }
```

```html
<template>
<div class="button"></div>
</template>

<style lang="sass">
:local(.button) {
	width: 100%;
	height: 40px;
	background-color: red;
}
</style>
```

css-loader的local配置在vue文件中没有起到作用，请问应该怎样结合vue-loader进行优化呢？

**Comment by yyx990803** [comment]
建议用 vue-loader 本身的 scoped CSS。

CSS loader 的 local CSS 需要将 CSS 模块产生的类名导出到 JavaScript 然后再动态通过 Vue 的渲染机制渲染，而 vue-loader 的 scoped CSS 不需要考虑这些。

如果同时需要 local 和全局，可以用多个 `<style>` 标签。

**Comment by septs** [comment]
@yyx990803 请求支持 :local
由于现在不支持 :local 导致所有的 class name 都被视为 module
我只是想局部模块化

**Comment by septs** [comment]
https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L169

@yyx990803 我希望 modules 是可以设置为 false 的
因为 modules 会无差别处理所有 class 作为 module 这不是我期望的行为
当 modules 时为 false 时 此时之会处理 :local 为 module

由于您这里的设计导致 modules 被无差别覆盖为了 true 希望逻辑变更为
`Object.assign(query, OPTIONS, DEFAULT_OPTIONS, option)`

-----------

see https://github.com/vuejs/vue-loader/blob/master/docs/en/features/css-modules.md#configuring-css-loader-query
还是说原设定是不可覆盖的？

**Comment by JounQin** [comment]
需要全局的时候用 `:global` 就好了啊

**Comment by septs** [comment]
@JounQin 举个例子
```vue
<style module lang="less">
:local(.example):global {
      &.test:after {
           content: 'The is example.'
     }
}
</style>
```

这种情况下 less 是无法工作的

**Comment by JounQin** [comment]
@septs 

``` less
.example(.test):after {
  content: 'The is example.'
}
```

或者
``` less
.example:global {
  &.test:after {
    content: 'The is example.'
  }
}
```

https://github.com/JounQin/test/blob/less-module/src/App.vue 测试没有任何问题
