### ISSUE TITLE
Scoped css, better approach

### ISSUE THREAD

**Issue by morriq** [vuejs/vue-loader#1420]
### What problem does this feature solve?
Large output file size made smaller

### What does the proposed API look like?
Take a look on output from vue-loader `<div class="recommendation" data-v-49c1946c></div>`. It takes normal class from css but it also adding `data-v-hash`, so it requires two information for using scoped styles in code. 
In big DOM structure it gives serious extra bytes to load..

Why vue can not replace classname with random hash? It will reduce amount of code sending to user.

**Comment by Justineo** [comment]
Redundant `data-v-` will be eventually optimized by Gzip. Theoretically there won't be essential difference between class names and data attributes.

**Comment by nblackburn** [comment]
It might be worth taking a look at CSS modules which Vue also supports.
