### ISSUE TITLE
how to turn on debug mode

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-loader#143]
I write base on `vue-loader-example`,
but there is warning at my code,
I want to see more detail,
the console let me `Turn on debug mode to see stack trace.`
could u please tell me how to do that?

**Comment by yyx990803** [comment]
http://vuejs.org/api/#debug

**Comment by Drachenfels** [comment]
Link redirects to '#ref' which only adds more confusion to this (simple?) question.

**Comment by simplesmiler** [comment]
@Drachenfels in Vue 2 you no longer need it, see https://vuejs.org/v2/guide/migration.html#Vue-config-debug-removed

**Comment by rubensstarke** [comment]
in case of v1
https://v1.vuejs.org/api/#debug
