### ISSUE TITLE
Be allowed to alternate between raw-loader and vue-loader

### ISSUE THREAD

**Issue by Kamadake** [vuejs/vue-loader#1431]
### What problem does this feature solve?
I'm working on a project where all the *.vue files are HTML with vue attributes attached to the elements. So these files are at the moment imported through raw-loader. Also, instead of working through an alias, they use:

resolveLoader: {
    alias: {
        text: 'raw-loader',
    }
}

So vue templates are imported in the following - require("text!vuecomponent/button.vue")

I tried to see if i could use vue-loader as an alias in resolveLoader so I could do require("vue!vuecomponent/button.vue") but that's not possible since one rule is required for vue-loader to work. But I cannot work with that rule or else raw-loader becomes obsolete. Editing and renaming these existing .vue files is a definite no for this project.

### What does the proposed API look like?
resolvedLoader: {
       alias: {
           vue: 'vue-loader'
      }
}

Then, when you have an index file that requires components
require("vue!vue_component/button.vue") (Works with vue-loader)
require("text!vue_component/slider.vue") (Works with raw-loader)

**Comment by posva** [comment]
This isn't quite related to vue-loader 🤔 
You can already `require('!raw-loader!./components/component.vue')`. But this is a webpack feature

**Comment by Kamadake** [comment]
Hi @posva , thanks for your reply! Just to let you know that that did the trick 😄 cheers!
