### ISSUE TITLE
This feature would be a way to set / override a Sass variable for a page and all its child components

### ISSUE THREAD

**Issue by StefKors** [vuejs/vue-loader#1439]
### What problem does this feature solve?
It makes your components more reusable in different parts int he UI in different colours. Or it makes the components easier to theme. For example reusing a the same logo in different colours.

### What does the proposed API look like?
Set a global $font_color variable in your main.scss file which will be globally available.
Then on one specific component you can set the $font_color variable for every child component, thus making that part of the site easily themeable.

global variables
![Screenshot 2018-11-02 at 19.19.52.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/e9ff9a50-decb-11e8-afa1-eb3e20c89cf9.png)

overwritten variables
![Screenshot 2018-11-02 at 19.22.39.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/53556480-decc-11e8-afa1-eb3e20c89cf9.png)

**Comment by LinusBorg** [comment]
There's already a way to do that: https://vue-loader.vuejs.org/guide/pre-processors.html#sharing-global-variables

**Comment by rille111** [comment]
I did this, but doesn't work:
![image](https://user-images.githubusercontent.com/1324189/58119120-90a4a980-7c02-11e9-9dfd-30faf1c2346a.png)
and in Vue.config.js:
![image](https://user-images.githubusercontent.com/1324189/58119147-9f8b5c00-7c02-11e9-8485-a14f2ffbeae9.png)

Care to share? I don't have files split up, it's all in package.json and some in vue.config.js.
