### ISSUE TITLE
How to include external css library

### ISSUE THREAD

**Issue by swamikevala** [vuejs/vue-loader#144]
I'm unable to figure out how to include the Pure.css external css library into my projects. I have added css loader to my webpack conf:

    {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
    },

and requiring it my main.js file:

    import purecss from 'css!./assets/css/pure-0.6.0/pure-min.css'

but I'm not able to get it to work. Any help would be much appreciated

**Comment by taylorzane** [comment]
Are you getting an error or is the CSS simply not showing up? My first thought would be to remove the `css!` from your import string. The test that you put in your webpack config will handle the stylesheet properly, when you specify `css!` webpack assumes you meant to override the default behavior.

**Comment by rbvea** [comment]
You could just link it as a style tag

`<style src="/assets/css/pure-0.6.0/pure-min.css">`

**Comment by transtone** [comment]
try
```var purecss = require('css!./assets/css/pure-0.6.0/pure-min.css')```

**Comment by jyjunyz** [comment]
you can try it like this:
import  './assets/css/pure-0.6.0/pure-min.css'

**Comment by nueverest** [comment]
I put this inside of index.html: 

`<link rel="stylesheet" type="text/css" href="/assets/css/pure-0.6.0/pure-min.css">`

It works, but strangely I get a 404 if I try to navigate here: `/assets/css/pure-0.6.0/pure-min.css`. Maybe I need to configure a url router.

Only the import method from @jyjunyz removes all error messages I've seen.  

However, importing CSS via javascript could result in dependency errors that are annoying to debug.  Let's say I have a big project and place `import './assets/css/pure-0.6.0/pure-min.css'` inside main.js and one of the `*.vue` component files.  Now I comment out the css import statement inside of main.js, but the styling remains. The reason is that the same `import` is still living in a component.

**Comment by kristianmandrup** [comment]
I have a library `css-circle-menu` I installed via `npm`. It includes css in `node_modules\css-circle-menu/css/circle-menu.css`

I tried using `<style src="node_modules/css-circle-menu/css/circle-menu.css"></style>` in my `src/circle-menu.vue` file, but I'm told it can't resolve it correctly.

**Comment by LinusBorg** [comment]
this should also work: 

`<style src="css-circle-menu/css/circle-menu.css"></style>`

**Comment by kristianmandrup** [comment]
Thanks :) Much better!

**Comment by kristianmandrup** [comment]
@LinusBorg  How can I make it include a SASS file which is dynamic with respect to my props. 
I'd like to make the SASS variables/calculations reflect the number of items in my menu :)

**Comment by LinusBorg** [comment]
That't not possible. CSS/SASS is created at build time, your props are only available later during runtime in the browser.

**Comment by kristianmandrup** [comment]
So I guess the only way would be to either pre-generate for various combinations or better to use dynamic styles like in React

**Comment by jameskandau** [comment]
if using webpack try this  :  require('./assets/css/bulma.css') am using bulma

**Comment by jameskandau** [comment]
Else add it to the static folder then add it to the index.html

**Comment by mchikhaoui** [comment]
@nueverest are you using vue-router without history mode ?
I have resolved it by setting vue-router mode to history.

**Comment by Dreampie** [comment]
how can import from node_modules in .vue style tag,  import '~bootstrap/dist/bootstrap.css' not work
```js
{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        'stylus': ExtractTextPlugin.extract({
                            use: 'css-loader!stylus-loader',
                            fallback: 'vue-style-loader'
                        })
                    }
                    // other vue-loader options go here
                }
            }
```

**Comment by tatsujb** [comment]
everyone seems to love this answer : https://github.com/jyjunyz but I can't get it to work.
https://stackoverflow.com/questions/46907059/vue-js-and-scss-or-sass

**Comment by Erbolking** [comment]
You can also include external styles in webpack config:

```javascript
  entry: {
    app: './src/main.js',

    'styles': [
      './node_modules/bootstrap/dist/css/bootstrap.min.css',
      './src/assets/css/design.css'
    ]
  },
```

**Comment by harrikrishnan** [comment]
convert sass into css using some loaders sass-loader, css-loader, node-sass. Then link it to index html,
or import css in js using style-loader.

**Comment by ojaynico** [comment]
Don't forget to add rel="stylesheet" in your link tag

**Comment by work1000** [comment]
for those who want to do the same thing for bootstrap css files i performed the following
- `npm i bootstrap-vue`
- included `import BootstrapVue from 'bootstrap-vue'` in entry point
- `npm install --save-dev style-loader css-loader` - [https://webpack.js.org/guides/asset-management/#loading-css](https://webpack.js.org/guides/asset-management/#loading-css)
- finally added `import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'` in entry point


my main.js looks like 

```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'
import App from './App.vue'
import router from './router'
import store from './store'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

**Comment by GanchoDanailov** [comment]
<style src="file.css"></style> is good workaround but how to load it scoped? 
Its seems <style scoped src="file.css"></style> does not work.

**Comment by equinusocio** [comment]
@GanchoDanailov Import it inside the style tag:

```html
<style lang="postcss">
  @import '~/file.pcss';
</style>
```

**Comment by nineSean** [comment]
> @GanchoDanailov Import it inside the style tag:
> 
> ```
> <style lang="postcss" scoped>
>   @import '~/file.pcss';
> </style>
> ```

but `file.pcss` will be global, how can I import style file and use locally

**Comment by nineSean** [comment]
@equinusocio 
But `file.pcss` will be global, how can I import style file and use locally?

**Comment by equinusocio** [comment]
@nineSean No, there is the `scoped` attribute.

**Comment by yarcowang** [comment]
This does't work for me, when someone said scss also works in the [stackoverflow post](https://stackoverflow.com/questions/44621052/how-to-do-scoped-external-css-in-vue-js)

![problem-database____Documents_php_laravel_problem-database__-_____resources_js_components_SolutionEditormdForm_vue__problem-database_](https://user-images.githubusercontent.com/1576504/59976609-8444af80-95f9-11e9-9ead-2ca7e67558e6.png)

I'm wondering the right way on to do this...

**Comment by camslice** [comment]
The issue as far as I can tell, is that the `data-v-###` attributes are not being added to the HTML for scoped CSS that is added via a `src` attribute, or using `@import`.

Both scenarios successfully modify the CSS selectors, from `.a { foo: bar }` to `.a[data-v-###] { foo: bar }`, but neither add the `data-v-###` attributes to the HTML.

Without any additional postcss plugins:
```
<style scoped src="file.css"></style>
```

As @equinusocio mentioned, this technique requires a postcss plugin like `postcss-easy-import` or `postcss-advanced-variables`
```
<style scoped>
    @import '~/file.css';
</style>
```

But again, neither of these techniques result in the HTML being update with the appropriate `data-v-###` for the scoped CSS to target.

**Comment by camslice** [comment]
Previous assertion that the `data-v-###` attributes are not being added to the HTML for scoped CSS that is added via a `src` attribute, or using `@import` is _*not correct*_.

I'm leaving it there, along with this clarification, in case others run into a similar problem and find it useful.

The issue I'm facing is that the imported CSS is only scoped to the current component — as it should be, by design — so child components are not inheriting the styles. Will require some processing to prefix all the selectors in the imported library with `#app` so that the CSS can properly cascade to HTML inside the child components.

The result should be more like `#app[data-v-###] a { foo: bar; }` which will result in all child HTML elements in all child components will be targeted. As mentioned here: https://vue-loader.vuejs.org/guide/scoped-css.html#also-keep-in-mind

**Comment by ImsirovicAjdin** [comment]
Why complicate? Inside the `style` tag in `App.vue`:
@import "https://unpkg.com/purecss@1.0.1/build/pure-min.css";

**Comment by negativems** [comment]
`@import` style not working with scoped style.
The `<style scoped>` tag not affect to the style imported with `@import`.

If you `@import` a style which contains for example `body { background-color: red; }` and you goes to another component you will see the body red.
