### ISSUE TITLE
css modules do not support extends in dev env: TypeError: Cannot redefine property: $style

### ISSUE THREAD

**Issue by wmzy** [vuejs/vue-loader#1449]
### Version
15.4.0

### Reproduction link
[https://see.below](https://see.below)

### Steps to reproduce
1. Create project by vue-cli
2. Create two components and mount the `Bar``.
Foo:

```
......
<style module lang="scss">
.root {
  color: red;
}
</style>
```
Bar:

```
<template>
  <div :class="$style.root">
      There should be black.
  </div>
</template>

<script>
import GameCard from './GameCard.vue';

export default {
  extends: Foo
};
</script>
<style module lang="scss">
.root {
  color: black;
}
</style>
```
3. Run `npm run serve`.

### What is expected?
No error and the color is black.

### What is actually happening?
TypeError: Cannot redefine property: $style

---
I think [here](https://github.com/vuejs/vue-loader/blob/9eb208f4c951508963b4b677e6f1233d821d663f/lib/codegen/styleInjection.js#L50-L54) should be:

```js
        Object.defineProperty(this, ${name}, {
          configurable: true, // !
          get: function () {
            return cssModules[${name}]
          }
        })
```

**Comment by wmzy** [comment]
Thanks for reply.
I send a pr for this, you can see the unit test.

**Comment by kazupon** [comment]
oh, sorry.
I'll try to see it later.
