### ISSUE TITLE
CSS modules mapping is present in bundle in Production mode.

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [vuejs/vue-loader#1458]
### Version
15.4.0

### Steps to reproduce
1. Enable CSS modules in webpack config
2. Enable "module" mode in styles of vue template file

### What is expected?
Mapping of css classes is not present in the resulting bundle, e.g. 'header' -> '_RgtY'

### What is actually happening?
Mapping is present in the resulting bundle

**Comment by posva** [comment]
You can customize that. Please check https://cli.vuejs.org/guide/css.html#css-modules

**Comment by lubomir-chatoryiskyi** [comment]
Could you please share a link with more detailed info? What should I configure? CSS-Loader? Thanks

**Comment by lubomir-chatoryiskyi** [comment]
By the way, I've created a fresh test project using the last vue-cli (3.3.0), enabled css modules (in vue.config.js), run 'npm run build' and the result still the same - mapping is present in output js bundle `ad35:function(e,t,r){e.exports={hello:"HelloWorld_hello_1ae9G"}}`. Is it expected behaviour and is it necessary for the production build when CSS is extracted into a separate file? Can I remove this mapping somehow?
