### ISSUE TITLE
Problem with sourcemaps

### ISSUE THREAD

**Issue by ThinkRealize** [vuejs/vue-loader#1459]
### Version
15.3.0

### Reproduction link
[https://github.com/ThinkRealize/vue-sourcemap-error.git](https://github.com/ThinkRealize/vue-sourcemap-error.git)
[https://github.com/ThinkRealize/vue-typescript-sourcemap-error.git](https://github.com/ThinkRealize/vue-typescript-sourcemap-error.git)

### Steps to reproduce
1. Git clone [normal project](https://github.com/ThinkRealize/vue-sourcemap-error.git). 
2. yarn start
3. open chrome.
4. open devtool.
![image](https://user-images.githubusercontent.com/13347370/50638050-45616580-0f97-11e9-86a9-c89e38f72398.png)

5. Git clone [typescript project](https://github.com/ThinkRealize/vue-typescript-sourcemap-error.git).  
6. yarn start
7. open chrome.
8. open devtool.
![image](https://user-images.githubusercontent.com/13347370/50638063-501bfa80-0f97-11e9-80e1-70bbdebde115.png)

### What is expected?
Normal project has src directory.
Typescript project has src directory.

### What is actually happening?
Normal project has src directory.
Typescript project src directory does not exist.

**Comment by sodatea** [comment]
![image](https://user-images.githubusercontent.com/3277634/51801214-b84bbc80-2275-11e9-9044-5f75aaa0f707.png)
It's under the `.` directory.
