### ISSUE TITLE
scoped priority in parent-component and  children-component with class

### ISSUE THREAD

**Issue by matisha001** [vuejs/vue-loader#1460]
### Version
15.4.0

### Reproduction link
[https://matisha001.gitee.io/demo/vue-cli3/](https://matisha001.gitee.io/demo/vue-cli3/)

### Steps to reproduce
https://matisha001.gitee.io/demo/vue-cli3/

https://matisha001.gitee.io/demo/vue-cli2/

<template>
  <div id="app">
    <img src="./assets/logo.png">
    <HelloWorld class="test"/>
  </div>
</template>

### What is expected?
Add "scoped" attribute to limit CSS to this component only

### What is actually happening?
it doesn't work in vue-loader 15.4.0

**Comment by posva** [comment]
The text should be blue in this scenario
I don't know your real use case but you can augment the specificity of the selector `.hello` to prevent a single class to override it
