### ISSUE TITLE
尤大大，函数多次调用错误

### ISSUE THREAD

**Issue by For-me** [vuejs/vue-loader#147]
额，，可以中文吧。在我用vue-loader时，使用webpack-dev-server进行热替换
npm运行webpack-dev-server --inline --hot。未被{{}}包裹的数值能被正常替换，但是{{}}里面的值未被解析。代码如下：
<template>
  <div class="example">sss{{ msg }}</div>
</template>
<script>
export default {
  data () {
    return {
      msg: 'asdasdsa world!'
    }
  }
}

</script>
<style>
.example {
  color: red;
}
</style>

config配置：
var wpServer = require('webpack-dev-server');
var webpack = require('webpack')

module.exports = {
  entry: [
		'./src/main.js',//输入JS
		//'webpack/hot/only-dev-server',
		//'./node_modules/webpack-dev-server/client?http://127.0.0.1:8080/'
				 ],
  output: {						
    path: './static',			//输出
    publicPath: '/static/',
    filename: 'build.js'
  },
  module: {//模块加载
    loaders: [
      {
        test: /\.vue$/,//正则匹配
        loader: 'vue'
      },
      {
        test: /\.js$/,
        // excluding some local linked packages.
        // for normal use cases only node_modules is needed.
        exclude: /node_modules|vue\/dist|vue-router\/|vue-loader\/|vue-hot-reload-api\//,
        loader: 'babel'
      }
    ]
  },
 //plugins: [new webpack.HotModuleReplacementPlugin()],
//    watch: true,
	devtool:'source-map',
	resolve: {
		//开启自动补全
		extensions: ['','.js','.json']
	},

  babel: {
    presets: ['es2015'],
//    plugins: ['transform-runtime']
  }
}

**Comment by For-me** [comment]
![qq 20160127171538](https://cloud.githubusercontent.com/assets/10767438/12608866/7d964752-c519-11e5-8e90-faf3e4e807e2.png)

**Comment by For-me** [comment]
{{}}里面的变量不能被热替换，这是我在开启了 plugins: [new webpack.HotModuleReplacementPlugin()],之后

**Comment by yyx990803** [comment]
看不出来是什么问题。要么开个重现的仓库，要么直接用 vue-cli 的模板吧。

**Comment by For-me** [comment]
我关闭了plugins: [new `webpack.HotModuleReplacementPlugin()]就不会报错，报错的原因应该是在执行命名时同时使用了--hot；但是{{}}里面的值在我修改后不会热替换，是否现在我的配置只支持局部刷新？
`<template>
  <div class="example" @click="getMsg">{{ msg }}</div>
	<div class="list">
		<span v-for="item in items" data-id={{item.id}}>{{item.message}}</span>
	</div>
</template>
<script>
export default {
	name: 'ViewA',
	components: {
    Items:[],
    Msg:''
  },
	
  data () {
    return {
			msg:'nimabi',
     	items:[
				{message:'i',id:1},{message:'love',id:2},{message:'us',id:3}
			
			],
			getMsg:function(event){
			alert(event.target.tagName)
		}
			
    }
  }
}

</script>`
现在不方便repo，烦请尤大大看看了

**Comment by yyx990803** [comment]
data 函数是初始状态，热重载保留当前状态，所以修改初始状态看上去是无效的。
