### ISSUE TITLE
Add a attribute deep to style tags to make all scoped css to be recursively applied to child components.

### ISSUE THREAD

**Issue by debjeetmaj** [vuejs/vue-loader#1474]
### What problem does this feature solve?
Currently we can apply /deep/ selectors by using `/deep/` as solved in [#661]( https://github.com/vuejs/vue-loader/issues/661 )

I can declare styles from external 3rd party style sheets using `src` attribute which will not be applied to nested elements. 
The new attribute `deep` to the style tag  could apply the css to nested components, directly 

This can be bypassed by having the nested components also include the external css, but when using a 3rd party lib it is not under our control.

This will achieve less hassle of writing the css in multiple places, by just including a css in main sections of the app and declaring them deep and scoped , to be applied in same section only.

### What does the proposed API look like?
```
<style deep scoped>
.cls{
}
</style>
// and
<style scoped deep src="/css/bootstrap.min.css" ></style>
```

**Comment by posva** [comment]
That would pretty much add `*[data-v-somechecksum]` in front of every class created by the 3rd library...
CSS libraries are meant to be included as regular CSS. `scoped` is meant to be used to style specific parts of 3rd party components as well as your own components in specific scenarios where you are also using `scoped`

**Comment by guptaaditya13** [comment]
```
scoped is meant to be used to style specific parts of 3rd party components
```
@posva how can parent component's scoped CSS style specific parts of 3rd party nested component, can u please elaborate?

**Comment by posva** [comment]
using the deep selector https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by guptaaditya13** [comment]
@posva in that case also this will happen
`
That would pretty much add *[data-v-somechecksum] in front of every class created by the 3rd library...
`
so why can't we directly add a support for it like <style src="" scoped deep> and implement it for general use?

**Comment by posva** [comment]
No, that won't happen since you would be styling specific classes in specific use cases so it would add that, it would only add the necessary CSS and prepend that for the specific CSS you wrote:

`.my-class >>> .btn` -> `.my-btn[data-v-75bc] .btn`
whereas the other solution would actually require us to prepend `*[data-v-75bc]` to anything.

If you have further questions please use the appropriate channels (forum, discord) 🙂
