### ISSUE TITLE
Native Coffeescript support

### ISSUE THREAD

**Issue by chiboreache** [vuejs/vue-loader#1479]
### What problem does this feature solve?
JS is just tires my eyes, extremely annoying...

### What does the proposed API look like?
<script lang="coffee">

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Vue Loader already supports coffescript. You probably want to open the issue in another repository

**Comment by LinusBorg** [comment]
Adding the loader takes 2 lines of code. 

I don't think we want to add it as it's not really relevance anymore except for legacy projects, judging from questions, feedback and code we are seeing.

**Comment by chiboreache** [comment]
and after adding that two lines, you steel getting

> `Module parse failed: Unexpected token`

legacy, huh... even after es3000 - js would be pleasure for eyes `))};`
