### ISSUE TITLE
Error with css-loader

### ISSUE THREAD

**Issue by wei-ones** [vuejs/vue-loader#148]
There will be some error while load(file-loader) font files with `relative path`.
` Config. `
```
{
    test: /\.(ttf|eot|svg|woff(2)?)(\?.*)?$/,
    loader: 'file-loader'
}
```
` Error. `
```
Failed to decode downloaded font: http://localhost:3000/
OTS parsing error: invalid version tag
``` 
` Info. `
[webpack/css-loader](https://github.com/webpack/css-loader)
```
SourceMaps

To include SourceMaps set the sourceMap query param.

require("css-loader?sourceMap!./file.css")

I. e. the extract-text-webpack-plugin can handle them.

They are not enabled by default because they expose a runtime overhead and increase in bundle size (JS SourceMap do not). In addition to that relative paths are buggy and you need to use an absolute public path which include the server url.
```

[vue-loader/lib/loader.js](https://github.com/vuejs/vue-loader/blob/master/lib/loader.js)
```
if (this.sourceMap) {
   defaultLoaders.css = 'style-loader!css-loader?sourceMap'
 }
```

**Comment by yyx990803** [comment]
Cannot reproduce. Please provide a repo.

**Comment by wei-ones** [comment]
wei-ones/css-loader-error-repo

**Comment by yyx990803** [comment]
Why are you importing the entire semantic.css in your Vue component? Just import it in your entry js file without source map. Also it's probably better to load it separately so it can be better cached.

**Comment by wei-ones** [comment]
先感谢你的回复和建议~
 ^ ^, 我的英文比较蹩脚, 还是用中文吧~
我的项目结构类似这样
```
<app>
    # 导航
    <slot></slot>
    # 页脚
</app>
```
我只在 APP 组件里引用一次 semantic.css, 跟在入口文件引用类似, 只不过不大喜欢把 css 的资源引用写在 main.js 里~
可能我没有很好地说明我的意愿, 现在用中文尽量描述清楚:

` ------ 分割下 ------ `

我的 webpack 配置在生产环境下 devtool 为 'source-map', 7.5.0 版本以后默认的 css 加载模式变成了 'style-loader!css-loader?sourceMap', 之后在我的工程里加载  css 就出现了一些问题, 可能不仅是字体, 一些常规 css 的效果也出现了异常, 经过追踪发现是 css-loader 的 sourceMap 配置问题导致的, 我发这个 issue 的意愿其实是表达对 css-loader 启用 sourceMap 的一些疑惑, 
这些疑惑主要基于一下几点: 

- css 启用 sourceMap 后文件体积增大不少, js 文件的 sourceMap 会进行分离, 但是 css 并不会, 7.5.0之前, 我的 build.js 文件大小约 1.2MB, 7.5.0之后增大到了 2MB 左右
- css 启用 sourceMap 后如官方说明变得较不稳定, 很多第三方库并不能直接引用或出现各种 bug
- 可能是我不够专业(我后端稍强于前端, 虽然也算不上多好^ ^) css 的 sourceMap 并没怎么用上

我发这个 issue 意愿就是起源于上述的疑惑, 如果能得到解答, 感激不尽~
多番打搅, 实在抱歉, ^ ^

**Comment by yyx990803** [comment]
你可以参考一下这里的配置，最终会把 CSS 抽取出来，source map 也是分离的。https://github.com/vuejs-templates/webpack/tree/master/template

第三方库不需要 source map 的话就直接在 js 里面 import，这样你可以自己控制 loader 的参数而不是受限于 vue-loader。

**Comment by wei-ones** [comment]
多谢~^ ^
这确实是一种解决方案, 我正在这样做~
但是, css-loader 官方有声明启用 sourceMap 可能带来的一些风险以及一些未知的 bug, 
在框架中启用是否也相当于把这种风险直接引入了进来~
我应该不是唯一可能遇到这个问题的(如果是...那实在惭愧= =)
收益于 Vue 的灵活性的同时, 有什么好的建议来规避这类问题吗?

**Comment by yyx990803** [comment]
vue-loader 8.1.0 可以在 webpack.vue 下面添加 cssSourceMap: false 来 disable css sourcemap 了

**Comment by wei-ones** [comment]
这正是我想要的, 多谢了~
