### ISSUE TITLE
Improve error message when `vue` and `vue-template-compiler` mismatched

### ISSUE THREAD

**Issue by fastfedora** [vuejs/vue-loader#1481]
### What problem does this feature solve?
It makes the solution for fixing mismatched versions between `vue` and `vue-template-compiler` clearer. 

Currently, if there is a mismatch between the versions, the following error is thrown:

```
[vue-loader] vue-template-compiler must be installed as a peer dependency, 
or a compatible compiler implementation must be passed via options.
```

This is appropriate when `vue-template-compiler` is not installed, but confusing when `vue-template-compiler` is already installed.

This is an additional change to help the confusion caused in issue #560 and partially resolved with the [update to the documentation](https://github.com/vuejs/vue-loader/commit/9beed01b62568a272d8e1ad7f5c1b9f1fe95c18a). 

### What does the proposed API look like?
Change the error message located [here](https://github.com/vuejs/vue-loader/blob/001382dad684b409082b7196b40a5c52a3a3169e/lib/index.js#L17) from 

```
function loadTemplateCompiler () {
  try {
    return require('vue-template-compiler')
  } catch (e) {
    throw new Error(
      `[vue-loader] vue-template-compiler must be installed as a peer dependency, `  
      `or a compatible compiler implementation must be passed via options.`
    )
  }
}
```

```
function loadTemplateCompiler () {
  try {
    return require('vue-template-compiler')
  } catch (e) {
    throw new Error(
      `[vue-loader] vue-template-compiler must be installed as a peer dependency `  
      `with the same version number as the vue dependency, or a compatible `  
      `compiler implementation must be passed via options.`
    )
  }
}
```

Alternatively, the details of the error thrown by `vue-template-compiler` can be included in the error:

```
    throw new Error(
      `[vue-loader] vue-template-compiler must be installed as a peer dependency `  
      `with the same version number as the vue dependency, or a compatible `  
      `compiler implementation must be passed via options. Details: `   e.message
    )
```

**Comment by yyx990803** [comment]
Fixed in fdd0338
