### ISSUE TITLE
Render static HTML

### ISSUE THREAD

**Issue by meodai** [vuejs/vue-loader#149]
Thank you for your work on the vue-loader its really amazing to play with it. Feels like black magic ;)

Im playing around with to try to generate a static styleguide. I was wondering if there is an easy way to "prerender" HTML files using vue.js -> webpack -> gulp

I had partial success doing so here:
https://github.com/meodai/bonescss/tree/documentation

The only thing that get generated is the JS, would be nice if [index.html](https://github.com/meodai/bonescss/blob/documentation/demo/index.html) could be the result of [demo](https://github.com/meodai/bonescss/blob/documentation/demo/demo.html) and the already applied [main.js](https://github.com/meodai/bonescss/blob/documentation/demo/src/main.js)

Any idea how I could achieve this?

**Comment by rbvea** [comment]
@meodai you could get the html in a similar way to how you test with karma: http://vuejs.github.io/vue-loader/workflow/testing.html

```
var componentA = require('a-component.vue');
var vm = new Vue({
      template: '<div><test></test></div>',
      components: {
        'test': ComponentA
      }
    }).$mount()
console.log(vm.$el); // should output html
```

**Comment by chrisvfritz** [comment]
@meodai You can achieve this with [prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin) for Webpack. I use it for Vue apps all the time with great success. 😃
