### ISSUE TITLE
npm run docs error

### ISSUE THREAD

**Issue by ljquan** [vuejs/vue-loader#1490]
### Version
15.6.0

### Reproduction link
[https://github.com/vuejs/vue-loader](https://github.com/vuejs/vue-loader)

### Steps to reproduce
npm run docs

### What is expected?
success

### What is actually happening?
ERROR in ./node_modules/vuepress/lib/app/app.js 11:6
Module parse failed: Unexpected token (11:6)
You may need an appropriate loader to handle this file type.
| import themeEnhanceApp from '@temp/themeEnhanceApp'; // generated from user config
|
> import('@temp/style.styl'); // built-in components
|
| import Content from './components/Content';
 @ ./node_modules/vuepress/lib/app/clientEntry.js 4:0-34 8:17-26
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js

---
package.json 显示的版本号是 15.6.2

**Comment by sodatea** [comment]
We use `yarn` rather than `npm` for developing.

**Comment by alajfit** [comment]
> We use `yarn` rather than `npm` for developing.

Not sure this is a suitable answer, I am also having the same issue and have seen other issues raised about this as well

<img width="599" alt="screenshot 2019-02-23 at 17 12 42" src="https://user-images.githubusercontent.com/5589282/53289483-5015cb00-378e-11e9-9e17-c330a04932b7.png">

**Comment by polyphonic13** [comment]
@alajfit did you ever resolve this? I'm now getting the same error when attempting to use VuePress.
