### ISSUE TITLE
Multiple root nodes throwing RangeError instead of Component template should contain exactly one root element

### ISSUE THREAD

**Issue by tyteen4a03** [vuejs/vue-loader#1491]
### Version
15.6.0

### Reproduction link

```vue
<template>
    <div>
        <section id="section-HelloWorld">
            <h2>Hello World!</h2>
        </section>
    </div>
    <div></div>
    <div></div>
</template>
```

### Steps to reproduce
Compile the codesandbox with webpack  and vue-loader (don't know how to get webpack to work online - sorry!).

### What is expected?
Error should be: Cannot use <template> as component root element because it may contain multiple nodes.

### What is actually happening?
Actual error thrown: RangeError: Invalid string length

**Comment by Flyingmana** [comment]
can second this.
template code to replicate the error:
```
<template>
    <div>
        <section id="section-HelloWorld">
            <h2>Hello World!</h2>
        </section>
    </div>
    <div></div>
    <div></div>
</template>
```

**Comment by tyteen4a03** [comment]
It looks like even forgetting to close a string literal in a `v-bind` will also trigger this error.

**Comment by yyx990803** [comment]
This should have been fixed by an update to the error range function (confirmed via tests from #1510)
