### ISSUE TITLE
vue-loader tells me I want vue-template-compiler, vue-template-compiler tells me I do not

### ISSUE THREAD

**Issue by Julian** [vuejs/vue-loader#1494]
### Version
15.6.0

### Reproduction link
[http://example.com](http://example.com)

### Steps to reproduce
This is essentially a doc bug --

As a new user, reading the docs from vue-loader tells me to install vue-template-compiler:

https://vue-loader.vuejs.org/guide/#manual-setup

vue-template-compiler on the other hand, tells me not to install it:

https://www.npmjs.com/package/vue-template-compiler

"You will only need it if you are writing build tools with very specific needs. In most cases you should be using vue-loader or vueify instead, both of which use this package internally."

So which is it (obviously I can see that likely vue-loader's docs are the correct ones, and that it doesn't declare the transitive dep for the reasons I see documented, but then vue-template-compiler shouldn't warn me not to install it)

### What is expected?
Likely removing the warning from vue-template-compiler's page.

### What is actually happening?
Not that.

---
[META] -- clearly the "Please do not just fill in a random link." is inappropriate for this sort of bug, so I've ignored it and done exactly that, but if you're going to create a custom way to file issues it might be nice to support these as well.

**Comment by ulivz** [comment]
I just create a pull request to update the doc: https://github.com/vuejs/vue/pull/9508

**Comment by Julian** [comment]
@ulivz that was quick! Thanks! Will keep an eye on it.
