### ISSUE TITLE
Build file size twice bigger than with vueify

### ISSUE THREAD

**Issue by zigomir** [vuejs/vue-loader#150]
We have a trivial app which build file size will yield 300K with `webpack` + `vue-loader` and 131K with `browserify` + `vueify`. Am I missing something or `vue-loader` does something wrong?

This is our `webpack.config.js`

```js
const path = require('path')
const webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build-wp.js'
  },
  resolveLoader: {
    root: path.join(__dirname, 'node_modules')
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    new webpack.optimize.OccurenceOrderPlugin()
  ]
}
```

And I have this in `package.json`

```json
"scripts": {
  "build": "NODE_ENV=production browserify src/main.js | uglifyjs -c warnings=false -m > dist/build.js",
  "build-wp": "NODE_ENV=production webpack --progress --hide-modules"
}
```

**Comment by yyx990803** [comment]
This might have to do with css source map with style-loader.

Can you try (upgrade vue-loader to latest) and (add `cssSourceMap: false` to the `vue` field in your webpack config)?

**Comment by zigomir** [comment]
I tried, but it doesn't help. I also checked [disable css sourcemap if minimizing or in production mode commit](https://github.com/vuejs/vue-loader/commit/ada24f2e50fee00b664db184e8bb4059e91f1ddd)  and never get into 

```js
defaultLoaders.css = 'vue-style-loader!css-loader?sourceMap'
```

or

```js
opts.map = {
  inline: false,
  annotation: false,
  prev: map
}
```

also because I have `NODE_ENV` set to `production`.

**Comment by yyx990803** [comment]
Can you provide a repo exhibiting this behavior?

**Comment by zigomir** [comment]
@yyx990803 I added you as collaborator on repo. More info in readme file.

**Comment by yyx990803** [comment]
This is actually a gotcha between Webpack and moment.js... see http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack

**Comment by zigomir** [comment]
Ah, I see. Thank you very much for tackling this one.
