### ISSUE TITLE
new version of vue-loader lost ability to compile /deep/ selector in scss style tag

### ISSUE THREAD

**Issue by mannok** [vuejs/vue-loader#1502]
### Version
15.7.0

### Reproduction link
[https://github.com/mannok/vue-loader-deep-style](https://github.com/mannok/vue-loader-deep-style)

### Steps to reproduce
Clone from the reproduction git and run "npm i, npm run dev"

OR

1. run "npx create-nuxt-app test-vue" ()
2. run npm i --save-dev node-sass sass-loader
3. open index.vue and change original <style> tag to <style lang="scss">
4. add /deep/ * { background-color: red; } in .container{  }
5. run npm run dev to observe in chrome and IE

### What is expected?
- Both Chrome and IE can see a red background on Vue logo
- Check page source and search for "/deep/" with no result since vue-loader should have compiled it and trim all "/deep" selector

### What is actually happening?
- Only Chrome can see a red background on Vue logo
- "/deep/" selector is appeared on page source

---
Seems that the new version of vue-loader removed the codes of processing /deep/ selector. 

After checking the difference between 13.7.3 and 15.7.0    I see that the piece of code which processing /deep/ selector is appeared in '/lib/style-compiler/plugins/scope-id.js' in 13.7.3. However, there is no any code involved with /deep/ selector processing in 15.7.0

**Comment by sodatea** [comment]
It is because it's not a **scoped** stylesheet.
Also that piece of code has moved to https://github.com/vuejs/component-compiler-utils/
