### ISSUE TITLE
can't import vue single file component which is in node_modules directory

### ISSUE THREAD

**Issue by zjlhope** [vuejs/vue-loader#1506]
### Version
13.3.0

### Reproduction link
[https://github.com/vuejs/vue-loader/issues/1504]

### Steps to reproduce
使用()=>import()加载处于node_modules中的vue单文件组件时，babel-loader报错，我的vue-loader版本为13.3.0，项目用vue init webpack xxxx创建的

### What is expected?
希望和加载其他不处于node_modules里的单文件组件一样能成功

### What is actually happening?
These dependencies were not found:

* !!babel-loader!../../project/node_modules/_vue-loader@13.7.3@vue-loader/lib/selector?type=script&index=0!./list.vue in ../user/modules/list.vue
* vue-loader/node_modules/vue-hot-reload-api in ../user/modules/list.vue, ./node_modules/_vue-loader@13.7.3@vue-loader/lib/template-compiler?{"id":"data-v-54e85568","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=template&index=0!../user/modules/list.vue

To install them, you can run: npm install --save !!babel-loader!../../project/node_modules/_vue-loader@13.7.3@vue-loader/lib/selector?type=script&index=0!./list.vue vue-loader/node_modules/vue-hot-reload-api

**Comment by posva** [comment]
Hey, stop opening questions on the repository. If you want to report a bug provide a boiled down repro. Maybe this is what you are looking for https://vue-loader.vuejs.org/guide/pre-processors.html#excluding-node-modules

**Comment by zjlhope** [comment]
> Hey, stop opening questions on the repository. If you want to report a bug provide a boiled down repro. Maybe this is what you are looking for https://vue-loader.vuejs.org/guide/pre-processors.html#excluding-node-modules

thank you for you answer,but my vue-loader's version is 13.3.0,I do as same as the document ,but no use,please help me

**Comment by Justineo** [comment]
https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L56

You need to add paths you want to transpile to `babel-loader`'s `include` option.
