### ISSUE TITLE
image not found for version 7.5.x

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-loader#151]
there is a bug on `vue-loader`
when I use `<img src="../img/heart.png">` it's works well,
change it to `<img src="background:url(../img/heart.png)"`,
there is an error to said not found.

I guess the reason is module require is not ready for `style url`

by the way, It doesn't metter when I use `vue-loader` month ago

**Comment by yozman** [comment]
when I change `vue-loader@^7.3.0` to `vue-loader@~7.4.0`
it work right, I think the bug is on version `vue-loader@7.5.x`

**Comment by yyx990803** [comment]
`<img src="background:url(../img/heart.png)">` is not even valid.

**Comment by yozman** [comment]
一直好使的代码，今天拉下来 `npm install`
突然用 background 方式写到 style 里的所有图片都不显示，
依赖用的是 `vue-loader@^7.3.0`,
执行 `npm ls vue-loader` 版本是 `7.5.3`,
换到了 `vue-loader@~7.4.0`,
结果符合预期，估计是 7.5.x 的问题，
麻烦修复一下～～

**Comment by yyx990803** [comment]
你是说这样？

``` html
<div style="background:url(../img/heart.png)"></div>
```

**Comment by yozman** [comment]
@yyx990803 
嗯，是的，还有顺带一个问题就是
`<img src="images/icon.png">`
看文档之后默认是 `require('./images/icon.png')`
我觉得可能 `require('images/icon.png')` 才更恰当，
当前目录可以用 `<img src="./images/icon.png">` 来弄。
因为有时候设置 `root path` 之后，
想引用图片得一层一层网上找挺麻烦的，

**Comment by yyx990803** [comment]
为什么要在 Vue 组件里面用 inline style？内联 style 里面的 url 不会被处理的，这个应该从来都不会正常工作。

**Comment by yozman** [comment]
@yyx990803 
css 里也是一样～
7.5.3 应该是，
`style lang="stylus"` 里写的
都不行，感觉应该是转换成 require 解析错误

**Comment by yozman** [comment]
我把版本定到到 `~7.4.0` 就没事了，
经测试使用 `^7.x.x` 的项目，
从新安装依赖，都会中招，

**Comment by yyx990803** [comment]
css 中 background url 我测试下来正常工作，vue-loader 7.5.2 + stylus。请给重现。

**Comment by yozman** [comment]
@yyx990803 
重现有什么工具么？
还是说要用图文的方式口述？

**Comment by yyx990803** [comment]
开一个 repo
