### ISSUE TITLE
建议增加路径是绝对路径 (例如 /images/foo.png)，是否需要会原样保留条件设定

### ISSUE THREAD

**Issue by lxyg06** [vuejs/vue-loader#1514]
### What problem does this feature solve?
希望能有个参数可以开启 绝对路径是否需要原样保留还是需要进行目录结构进行解析设定
图片地址/images/foo.png
图片地址希望改成/login/images/foo.png
现在图片地址就是/images/foo.png 因为是绝对路径
现在我只能添加很多的‘../../../’才能解决

### What does the proposed API look like?
absolutePath:[true|false]

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
