### ISSUE TITLE
why did css render dealy when i'm in development mode ?

### ISSUE THREAD

**Issue by chentianyuan** [vuejs/vue-loader#1515]
### Version
14.2.1

### Reproduction link
[https://github.com/chentianyuan/prerender](https://github.com/chentianyuan/prerender)

### Steps to reproduce
1、i used my company owner UI - component with node_modules
2、webpack 3.x && vue-loader 14.2.1 && server-renderer
3、i try to upload vue-loader 15.x but it was still reappear
4、i find it will be show right when i degrade width client-renderer

### What is expected?
css load before page show

### What is actually happening?
page show and css load dealy

---
when i use webpack4.x and vue-loader 15.x , i fixed it, must i use vue-loader 15.x with webpack4?

**Comment by posva** [comment]
Yes, use recent versions

**Comment by chentianyuan** [comment]
@posva  you mean to use vue-loader15 and webpack4 together ?

**Comment by posva** [comment]
yes

**Comment by chentianyuan** [comment]
@posva thx
