### ISSUE TITLE
Support Vuetify's 'v-img' 'src' attribute in 'transformToRequire` defaults

### ISSUE THREAD

**Issue by brianhelba** [vuejs/vue-loader#1518]
### What problem does this feature solve?
`vue-loader` does not automatically `require` assets referenced in the `src` attribute of [Vuetify's `v-img`](https://vuetifyjs.com/en/components/images) tag.

Given that Vuetify is a prominent part of Vue's ecosystem and `v-img` is often a drop-in replacement for `img`, supporting this natively would be desirable.

[Current workarounds to this problem](https://stackoverflow.com/a/53411531) are not seamless and have a more awkward syntax.

### What does the proposed API look like?
No API surface changes are required.

Template markup looking like `<v-img src="@/assets/logo.png">` will now compile properly.

**Comment by brianhelba** [comment]
A fix to this issue will be very similar to https://github.com/vuejs/component-compiler-utils/pull/45 .

We should be sure to also update the documentation of `vue-loader` and `vue-component-compiler` when this change is made. We can also fix those docs to incorporate the change from https://github.com/vuejs/component-compiler-utils/pull/45 .

**Comment by Justineo** [comment]
You can use Vue Loader's `transformAssetUrls` option to configure your own element/attribute combinations to be transformed. If you want that out-of-the-box, I think it's better to let Vuetify integrate this feature into their Vue CLI plugin.

* [Modifying options for Vue Loader with Vue CLI](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader)
* [Vue Loader's `transformAssetUrls`](https://vue-loader.vuejs.org/options.html#transformasseturls)

/cc @johnleider

**Comment by posva** [comment]
I was about to paste the same link hehe

We cannot just add default support for one single lib (there are multiple big ui libs out there that would ask for this too). So use the options referred by @Justineo

**Comment by brianhelba** [comment]
I've already been able to modify loader options locally to fix this, but I was looking to contribute something out-of-the-box to benefit the user community.

However, I didn't think of adding this to https://github.com/vuetifyjs/vue-cli-plugin-vuetify . This is a great idea, which I'll pursue.

I appreciate the rationale for not wanting to add features to support a single (popular) downstream library.

Thanks for the quick feedback.

**Comment by brianhelba** [comment]
Note, it is still a very minor bug that https://github.com/vuejs/component-compiler-utils/pull/45 never downstreamed documentation updates to  `vue-loader` and `vue-component-compiler`.
