### ISSUE TITLE
Loaders defined in .js rule are not applied to <script> block

### ISSUE THREAD

**Issue by mzdr** [vuejs/vue-loader#1520]
### Version
15.7.0

### Reproduction link
[https://github.com/mzdr/vue-loader-script-block-issue](https://github.com/mzdr/vue-loader-script-block-issue)

### Steps to reproduce
1. `npm install`
2. `npm run build`

### What is expected?
The `<script>` Block within the `App.vue` file should cause linting errors.

### What is actually happening?
Linting errors only occur for the `index.js` file.

---
As you see in the `webpack.config.js`, if you enable the `eslint-loader` for the `.vue` rule, everything works as expected. If it’s disabled, linting for the `App.vue` does not happen at all. I somehow would accept this for the `<template>` block, but the docs say the `<script>` block uses the same loaders as the ones that are defined in the `.js` rule. This seems not to work.

**Comment by yyx990803** [comment]
When using `eslint-plugin-vue`, make sure to apply `eslint-loader` to both `.js` and `.vue` files.
