### ISSUE TITLE
Using vue-loader in NodeJS without Wepack

### ISSUE THREAD

**Issue by Boycce** [vuejs/vue-loader#1523]
### What problem does this feature solve?
Compiling .vue files in NodeJS without the use of Wepack. Is this supported? I can't seem to find any documentation, only closely knit references to Webpack.

### What does the proposed API look like?
Something maybe like this: `let module = require('vue-loader').compile('path/to/file.vue')`

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-component-compiler

**Comment by vedmant** [comment]
Also stumbled upon this problem, this link https://github.com/vuejs/vue-component-compiler doesn't explain how to use it without Webpack.
