### ISSUE TITLE
conflict with flowtype generics

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue-loader#153]
We are using [facebook flowtype](http://flowtype.org/docs/quick-reference.html) to get some type safety in vue scripts. We have found that if the type declaration contains generics vue-loader will throw 'Unexpectec token' error. For example: 

```es6
export default {
  props: {
      xs: Array<number>
  }
}
```
Guess it's the `<` and `>` that cause this problem. The following code transpiles just fine: 

```es6
export default {
  props: {
      xs: Array
  }
}
```

**Comment by yyx990803** [comment]
You need this: https://www.npmjs.com/package/babel-plugin-syntax-flow

**Comment by Centaur** [comment]
Yes. Part of `package.json`:

```json
  "devDependencies": {
    "babel-cli": "^6.4.5",
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-syntax-flow": "^6.3.13",
    "babel-plugin-transform-flow-strip-types": "^6.4.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-plugin-typecheck": "^3.6.1",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-runtime": "^5.8.0",
   ...
}
```

**Comment by yyx990803** [comment]
Hmm, this is actually because what you wrote is not a flow type declaration:

``` js
export default {
  props: {
      xs: Array // this is valid JavaScript, where Array is simply the global. Not a type declaration!
  }
}
```

**Comment by Centaur** [comment]
Alright，I understand vue has its own way for type annotation. Then the next question is: is it possible to utilize flow type check upon vue props?
