### ISSUE TITLE
Vue template compiles with Object.assign with browserslist at IE11

### ISSUE THREAD

**Issue by jackysee** [vuejs/vue-loader#1532]
### Version
15.7.0

### Reproduction link
[https://github.com/jackysee/VueBabelTest](https://github.com/jackysee/VueBabelTest)

### Steps to reproduce
1. checkout the demo repo
2. npm install
3. npm run build
4. check dist/main.js for output code

### What is expected?
As `.babelrc` is configured to target IE11, the output should have no `Object.assign`.

### What is actually happening?
`Object.assign` is found in the compiled template.

---
babelrc:
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false,
                "targets": {
                    "browsers": [ "ie >= 11" ]
                },
                "useBuiltIns": "usage",
                "corejs": 3,
                "debug": true
            }
        ]
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
```

app.vue:
```
<template>
    <div :class="{ hi: true, ...obj() }"></div>
</template>
<script>
export default {
    methods: {
        obj() {
            return { b: true };
        },
        obj2() {
            return {
                a: true,
                ...this.obj()
            };
        }
    }
};
</script>

```

In the generated output, the template section is using `Object.assign` while `objc2()` method is using the polyfilled `_objectSpread`, so the polyfill did work but just not on the template section.

![image](https://user-images.githubusercontent.com/30516/55375353-60b02280-553e-11e9-93dc-ce19b53aab12.png)

![image](https://user-images.githubusercontent.com/30516/55375368-6efe3e80-553e-11e9-981a-c38ae34c8408.png)

**Comment by yyx990803** [comment]
Vue template outputs go through a separate compilation pipeline (https://github.com/vuejs/vue-template-es2015-compiler) so you need to configure it via [transpileOptions](https://vue-loader.vuejs.org/options.html#transpileoptions) or include an `Object.assign` polyfill.
