### ISSUE TITLE
WHERE do I disable hot reload?

### ISSUE THREAD

**Issue by danlynkew** [vuejs/vue-loader#1534]
I created a Vue project using Vue CLI 3.

I want to disable hot reload. [The docs tell me](https://vue-loader.vuejs.org/guide/hot-reload.html#disabling-hot-reload) exactly what I need to type. But **where do I type it?** In which file?

[This guy](https://stackoverflow.com/questions/51844289/turn-off-hot-reload-on-project-started-with-vue-cli-3-webpack-4-15-1) has the same issue.

**Comment by yyx990803** [comment]
https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader
