### ISSUE TITLE
Url transformation (transformAssetUrls) does not work with v-bind

### ISSUE THREAD

**Issue by shameleo** [vuejs/vue-loader#1538]
### Version
15.7.0

### Reproduction link
[https://github.com/shameleo/vue-loader-bug](https://github.com/shameleo/vue-loader-bug)

### Steps to reproduce
```
npm install
npm run build
```
Open /dist/index.html and look value of `<img src>` attributes

### What is expected?
The second image should have same `src` value as the first one.  Both `src` values should be result of `require` call.

### What is actually happening?
If v-bind is used, url transformation is not applied.

---
I guess transformation can't be implemented in general case for this: `:src="'~Icons/ok.png'"`, as expression can't be evaluated by vue-loader. But should be easy to make smth like this: `:src="~'Icons/ok.png'"`. Bounded expression should always return string (because some url is expected), so when we see something like `:src="~path"`, we can definitely say than `~` is not part of expression and can be handled by vue-loader.

**Comment by LinusBorg** [comment]
This is not a bug, it's expected behaviour. You say yourself that vue-loader can't evaluate expressions.

> But should be easy to make smth like this: :src="~'Icons/ok.png'". Bounded expression should always return string (because some url is expected), so when we see something like :src="~path", we can definitely say than ~ is not part of expression and can be handled by vue-loader.

* If `path` i that example is supposed ot be a literal string, we can jsut remove the v-bind altogether as it's static.
* if it's supposed to be a variable identifier, then it can't work as webpack has to find a `require()` call with a literal string as it's argument:
```javascript
require('some/path.png') // works
require('path) // doesn't work
```
... which again would reuire vue--loader to evaluate the expression, which, as we agree, is not possible.

**Comment by shameleo** [comment]
Oh, I forgot Webpack needs compile time value as well. Could you mention this in docs, as some people like me are also confused: https://forum.vuejs.org/t/v-bind-svg-image-xlink-with-string-variable/35377?

**Comment by shameleo** [comment]
@LinusBorg 
I made some investigation and found out that `require` __does not__ expect literal string. I modified my demo project to highlight it: https://github.com/shameleo/vue-loader-bug/commit/8b4e1e8f82ef4be651b3283e1bf8a49ef28dcdf4
When Webpack sees
```
require(`Icons/${icon}.png`)
```
To be able to resolve nessesary module at runtime it loads **all** files matching pattern `icons/*.png` and having appropriate loader.
