### ISSUE TITLE
Imported CSS partials assembled out of order

### ISSUE THREAD

**Issue by pdot86** [vuejs/vue-loader#1540]
### Version
15.7.0

### Reproduction link
[https://codesandbox.io/embed/1z7vz1z3lq](https://codesandbox.io/embed/1z7vz1z3lq)

### Steps to reproduce
- View the code sandbox, or run `npm run build`
- View the output css file or see the preview on the sandbox
- Compare the output with the source and see that imports are were moved above where they were

### What is expected?
The expected output has imported partials exactly where the the import statement is located. In the specific example, it is expected to have a yellow background color.

### What is actually happening?
The imported partials are inserted at the top of the output. In this specific example the background color is not yellow because imported _yellow.css file was not kept in place of the @import- it was moved above the rule in main.css that sets it to red which gives the precedence to red as it is the last rule in the output.

**Comment by pdot86** [comment]
To be a bit more clear this is only an issue if you have rules before any import- to work around this issue you can refactor to either only import at the top before defining any rules.

**Comment by LinusBorg** [comment]
This behaviour is defined in the CSS spec. @import statements have to be at the top of the file, so the ones deeper down are hoisted upwards to the top, leaving the inline selector as the last definition.

In other words: this is just how CSS works.
