### ISSUE TITLE
Vue-loader without webpack

### ISSUE THREAD

**Issue by Diaskhan** [vuejs/vue-loader#1545]
### Version
15.7.0

### Reproduction link
[https://github.com/vuejs/vue-loader](https://github.com/vuejs/vue-loader)

### Steps to reproduce
It possible to implement vue-loader without webpack dependency ?
I dont wanna use webpack as bundler because is huge!

Maybe have another options to use Vue files without webpack bundler ?

### What is expected?
To use vue loader with others bundle tools!

### What is actually happening?
Webpack dependecy!

**Comment by Diaskhan** [comment]
Maybe have some examples how to use with other bundlers ?

**Comment by yyx990803** [comment]
https://github.com/vuejs/component-compiler-utils

**Comment by Diaskhan** [comment]
Thanks Evan!
