### ISSUE TITLE
How to remove whitespace between element tag and its inner text

### ISSUE THREAD

**Issue by bowencool** [vuejs/vue-loader#1548]
![image](https://user-images.githubusercontent.com/20217146/58149203-77e4d400-7c94-11e9-990b-5651028746b2.png)

![image](https://user-images.githubusercontent.com/20217146/58149276-c8f4c800-7c94-11e9-91ad-12b60f22b7e5.png)

### What problem does this feature solve?
Make the file smaller

### What does the proposed API look like?
```
preserveWhitespace: {
  tag: false,
  text: false,
}
```

**Comment by Justineo** [comment]
https://vue-loader.vuejs.org/options.html#compileroptions
https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options

You can use `whitespace: 'condense'` since `2.6.0`.
