### ISSUE TITLE
 Can't resolve '@'

### ISSUE THREAD

**Issue by endytc** [vuejs/vue-loader#1549]
### Version
15.4.0

### Reproduction link
[https://codepen.io/fendi-tri-cahyono/pen/wbXKMZ?editors=0010](https://codepen.io/fendi-tri-cahyono/pen/wbXKMZ?editors=0010)

### Steps to reproduce
```
ERROR in ./node_modules/vue-extend-layout/vue-extend-layout.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-extend-layout/vue-extend-layout.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@' in '/Users/fenditricahyono/Projects/titipbeliin/titipbeliin-vue/node_modules/vue-extend-layout'
 @ ./node_modules/vue-extend-layout/vue-extend-layout.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-extend-layout/vue-extend-layout.vue?vue&type=script&lang=js&) 50:19-96
 @ ./node_modules/vue-extend-layout/vue-extend-layout.vue?vue&type=script&lang=js&
 @ ./node_modules/vue-extend-layout/vue-extend-layout.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
```

### What is expected?
can resove for 
import Something from '@/something.vue', 
not only 
import Something from '../../something.vue', 

### What is actually happening?
Module not found: Error: Can't resolve '@' in '/Users/fenditricahyono/Projects/titipbeliin/titipbeliin-vue/node_modules/vue-extend-layout'

**Comment by posva** [comment]
you are missing a resolve option in your config: https://webpack.js.org/configuration/resolve/

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first, specially when it isn't related to Vue. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by endytc** [comment]
Thank's @posva for your attention, for next time I will forum
But I have added resolve option, and can't resolve `import bisnis from '@/layouts/bisnis.vue'`
```
resolve: {
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      bisnis$: 'src/layouts/bisnis.vue',
      default$: 'src/layouts/default.vue',
    },
    extensions: ['*', '.js', '.vue', '.json'],
  },
```
but can't resolve
![image](https://user-images.githubusercontent.com/1209684/58526952-fb557680-81fa-11e9-9d7d-895e5d1b437c.png)

**Comment by Justineo** [comment]
You should add an alias for `@`.

**Comment by endytc** [comment]
can you give me an example @Justineo :D 
this is not working, and I confuse ✌️ 
```
resolve: {
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      '@': 'src/',
      // default: '@/layouts/default.vue',
    },
    extensions: ['*', '.js', '.vue', '.json'],
  },
```

**Comment by Justineo** [comment]
Please use the channel @posva mentioned above. Issues are only for bug reports/feature requests. Thanks for your cooperation.
