### ISSUE TITLE
Can't use ESLint's `fix` config

### ISSUE THREAD

**Issue by NeonPaul** [vuejs/vue-loader#155]
ESLint has an autofix option that automatically fixes formatting-related errors and saves them to disk

When it's used with vue-loader the saved files have `// ` added to the beginning of each line in the template and style sections.

**Comment by yyx990803** [comment]
If you want to fix the file then you should apply eslint-loader to the vue file directly with eslint-html-plugin. Update to `vue-loader@8.1.3` and follow the config here: http://vuejs.github.io/vue-loader/workflow/linting.html (the webpack template from vue-cli has also been updated)

**Comment by RalfZhang** [comment]
Update:
The link shared by @yyx990803 has been changed to https://vue-loader.vuejs.org/en/workflow/linting.html
