### ISSUE TITLE
.vtt not handled properly

### ISSUE THREAD

**Issue by tvld** [vuejs/vue-loader#1551]
If I try to resolve a video track:
```js
<track label="English" kind="subtitles"  srclang="en"  src="@/assets/video/my.en.vtt">
```
It fails with:
``Module parse failed: Invalid number (5:0) You may need an appropriate loader to handle this file type.``

In ``vue.config.js`` I have:
```js
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(options => {
        options['transformAssetUrls'] = {
          // [...]
          'b-embed': ['src', 'poster'],
          'source': 'src',
          'track': 'src',
        }

        return options
      })
```
I suppose it should be able to handle normal ``.vtt`` files?

**Comment by LinusBorg** [comment]
> I suppose it should be able to handle normal .vtt files?

vue-loader doesn't handle any of the file types that you may reference in `src` depedencies, Webpack does, with other loaders such as file-loader.

You probably should have a webpack rule somewhere that uses file loader to handle image imports. It can also handle your video file, just add the file extension to that rule's `test` RegExp.

If you are using Vue CLI 3, you can modify the existing loader config through vue.config.js, but those details are outside of the scope here.

Ping me in the chat or the forum and we can work it out.

**Comment by fogdingding** [comment]
check rules and media
- npx vue-cli-service inspect --rules
- npx vue-cli-service inspect --rule media

then, we will change 
`config.module.rule('media').test(/\.(vtt|mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/)`

by source [link](https://forum.vuejs.org/t/vtt-handling/65657/2)
