### ISSUE TITLE
sourcemap: two files with same name will only have one original source displayed

### ISSUE THREAD

**Issue by jasontianxie** [vuejs/vue-loader#1554]
### Version
15.7.0

### Reproduction link
[https://github.com/jasontianxie/vue-hello-world.git](https://github.com/jasontianxie/vue-hello-world.git)

### Steps to reproduce
1.npm install && npm run serve

2.open 'source' tab in Chrome debug panel
you can only see one HelloWorld.vue:HelloWorld.vue?140d
(if it is not shown ,please refresh browser )
![1811](https://user-images.githubusercontent.com/24238063/59424952-82b00600-8e07-11e9-9e0d-eccdb475a68b.png)

but actually there are two of them, componens/HelloWorld.vue and componens/test/HelloWorld.vue
![191](https://user-images.githubusercontent.com/24238063/59424973-8e033180-8e07-11e9-9dac-a76e09b454d0.png)

3.check webpack:// directory

### What is expected?
there should be two helloworld.vue

### What is actually happening?
there is only one helloworld.vue

**Comment by jasontianxie** [comment]
use webpack devtool with qulity of 'original source' not with 'lines only'(like eval-source-map, source-map ....)

**Comment by roblues** [comment]
遇到同样的问题，求解

**Comment by FranklyCai** [comment]
> 遇到同样的问题，求解

楼主描述的是啥问题呀？ 可以简单翻译一下吗

**Comment by Baozi2** [comment]
> lines only

将webpack的的配置参数`devtool`修改为source-map
