### ISSUE TITLE
vue-html-loader 中的 htmlMinifier 不读取其他选项

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue-loader#156]
vue-html-loader 调用 `htmlMinifier.minify` 只能选择开关固定的选项，不能添加其他选项。
https://github.com/vuejs/vue-html-loader/blob/master/index.js#L59

vue-html-loader 开启了 `collapseWhitespace` 选项，
html 代码被压缩后 `inline-block` 元素之间的间隙会被去掉，dev和build后的页面效果就会有区别。
使用 html-minifier 的 `conservativeCollapse` 选项可以保留1个空格，让 html 压缩前后页面显示一致。

**Comment by yyx990803** [comment]
已经更新了 https://github.com/vuejs/vue-html-loader

现在默认开启的选项更为保守，并且可以在 webpack 配置的 `vue.html` 下设置 vue-html-loader 的选项。
