### ISSUE TITLE
Does not work with babel-esm-plugin

### ISSUE THREAD

**Issue by wzc0x0** [vuejs/vue-loader#1562]
### Version
15.7.0

### Reproduction link
[https://github.com/wzc0x0/webpack-boilerplate](https://github.com/wzc0x0/webpack-boilerplate)

### Steps to reproduce
`npm run test`

### What is expected?
No errors!

### What is actually happening?
some errors: 

```
UnhandledPromiseRejectionWarning: Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/Users/wzc0x0/Desktop/MySpace/webpack-boilerplate/node_modules/vue-loader/lib/plugin.js:65:13
)
    at compiler.hooks.make.tapAsync (/Users/wzc0x0/Desktop/MySpace/webpack-boilerplate/node_modules/babel-esm-plugin/src/in
dex.js:66:18)
```

---
May be in conflict with the babel-esm-plugin!

**Comment by sodatea** [comment]
Now that the issue on the babel-esm-plugin repo is resolved https://github.com/prateekbh/babel-esm-plugin/issues/23
I'm closing this one.
