### ISSUE TITLE
(Emitted value instead of an instance of Error) the "scope" 

### ISSUE THREAD

**Issue by cybermerlin** [vuejs/vue-loader#1567]
Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

What is wrong with that(?):
```
      <template slot="item" slot-scope="prop">
        <configuration-form v-model="prop.item" @input="isValid"></configuration-form>
      </template>
```

**Comment by cybermerlin** [comment]
Are you seriously? - it is disrespect to your customers

**Comment by yyx990803** [comment]
1. You are not a customer. You are using open source software for free.
2. Not following the guidelines is disrespectful to the maintainers.
