### ISSUE TITLE
yarn.lock not consistency within package.json

### ISSUE THREAD

**Issue by wmzy** [vuejs/vue-loader#1570]
### Version
15.7.0

### Reproduction link
[http://need.not](http://need.not)

### Steps to reproduce
yarn install --frozen-lockfile

### What is expected?
install dependencies success

### What is actually happening?
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

---
not version 15.7.0 see 6a05115ddf3ea680ab2b00862b2891da2e98a41c

The package.json change commit: https://github.com/vuejs/vue-loader/commit/c359a38db0fbb4135fc97114baec3cd557d4123a

**Comment by sodatea** [comment]
Fixed.
