### ISSUE TITLE
vue-loader fails to work with local "npm link"-ed modules

### ISSUE THREAD

**Issue by agonbina** [vuejs/vue-loader#158]
The default `js` loader string is hardcoded to: `babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false` which fails to work with npm link-ed modules, because webpack can't find the `transform-runtime` plugin(or any other one if you were to add more).
I'm aware that it is possible to override this option via `vue.loaders.js`, but unfortunately it seems like to get the `babel-loader` to work with `npm link`-ed modules the configuration needs to be set as an object. The following, for example, works for `js` files:
```js
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules\/(?!@myPrivateScope)/,
        query: {
          presets: [ 'es2015', 'stage-2' ],
          plugins: [
            'transform-runtime'
          ],
          comments: false
        }
      }
```
and then you have to set `resolveLoader.fallback = 'fullPathToYourNodeModules'`

It could also be that `vue-loader` is ignoring the `resolveLoader` configuration? 

Would it make sense if the default `vue-loader` behavior for javascript is to use the custom `babel-loader` configuration for regular `js` files(if there is one), and if not consider accepting an object definition for the `vue.loaders.js` option?

**Comment by yyx990803** [comment]
`vue-loader` would respect the global `babel` option in webpack configs, so instead of query under `babel-loader`, you can do:

``` js
module.exports = {
  // ...
  babel: {
    presets: [
      require.resolve('babel-preset-es2015'),
      require.resolve('babel-preset-stage-2')
    ],
    plugins: [
      require.resolve('babel-plugin-transform-runtime')
    ],
    comments: false
  }
}
```

Note just using shorthands won't work either - you need to provide the full resolved paths with `require.resolve`.

**Comment by agonbina** [comment]
![](http://gifs.joelglovier.com/done/hand-wipe.gif)
