### ISSUE TITLE
提供类似 html-minifier 的 `collapseWhitespace: true, conservativeCollapse: false` 功能

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue-loader#1582]
### What problem does this feature solve?
现在的压缩方案，对于文本标签，始终会保留一个空格：
https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options

```html
<!-- source -->
<div>
  <span>
    foo
  </span>   <span>bar</span>
</div>

<!-- whitespace: 'preserve' -->
<div> <span>
  foo
  </span> <span>bar</span> </div>

<!-- whitespace: 'condense' -->
<div><span> foo </span> <span>bar</span></div>
```

在很多时候，这会带来并不期望的空格

```html
<!-- source -->
<span>
  一段很长的文字………………，
<span>

<!-- 会被转化为：-->
<span> xx </span>

<!-- 如果把 source 写成这样： -->
<span>一段很长的文字………………，<span>

<!-- 会被 prettier 之类的代码美化工具转化为这样，非常糟糕： -->
<span
  >一段很长的文字…</span
>
```

我们的规范一直是：构建工具会消灭所有标签两边的空格，如果需要空格，手动添加 `&nbsp;`。即：

```
<!-- 如果不需要空格 -->
<span>
    <i class="icon"></i>
    文本
<span>

<!-- 如果需要空格 -->
<span>
    &nbsp;
    <i class="icon"></i>
    &nbsp;文本&nbsp;
<span>
```

这在 react 和 vue@1.x （自己压缩 html）时期用的很好。

现在使用单文件组件，vue-loader 并没有提供这个支持，一定会保留标签旁边的空格，希望增加一个删除这些空格的选项。

### What does the proposed API look like?
```js
compilerOptions: {
  whitespace: 'collapse'
}
```

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-loader/issues/1583#issuecomment-525144996

如果你觉得使用 deprecated 的选项不自在，需要在 `whitespace` 选项里实现 `preserveWhitespace: false` 的功能的话，也请在 vue 的主仓库里提 issue。
