### ISSUE TITLE
Cannot find module 'webpack/lib/RuleSet'

### ISSUE THREAD

**Issue by Sebi2020** [vuejs/vue-loader#1586]
### Version
15.7.1

### Steps to reproduce
1. Install webpack globally
2. Install vue-loader locally (webpack does not respect global vue-loader installs)

3. Create a webpack.js.config like this:

```javascript
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
	entry: './main.js',
	mode: 'development',
	module: {
		rules: [
			{
			test: /\.vue$/,
			loader: 'vue-loader'
			}
		]
	},
	plugins: [
		new VueLoaderPlugin()
	]
}
```

4. Create an entry point (main.js in code snippet)
5. Run `npx webpack`

### What is expected?
Correct module imports

### What is actually happening?
Wrong import paths are used

`Cannot find module 'webpack/lib/RuleSet`

**Comment by sodatea** [comment]
A local webpack package is required. It's listed in the package.json:
https://github.com/vuejs/vue-loader/blob/d3fa467815c0a2da87fd3062ab8bb182cfa84264/package.json#L35-L38

**Comment by IBICF** [comment]
重新安装webpack依赖解决了

**Comment by Sebi2020** [comment]
@sodatea Shouldn't it be added as a proper dependency when it's a required dependency for vue-loader?

**Comment by sodatea** [comment]
Peer dependency *is* a proper type of dependency.
Webpack plugin/loader is the exact intended use case for the peer dependency semantic.
See https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by IBICF** [comment]
i solved it by install vue-loader@15.9.7
`const VueLoaderPlugin = require('vue-loader/lib/plugin-webpack5');`

**Comment by wheatup** [comment]
Running this solves my problem
```
npm i webpack@4 -D
```

It installs
```
"webpack": "^4.46.0"
```

**Comment by GAS0968** [comment]
> Running this solves my problem
> 
> ```
> npm i webpack@4 -D
> ```
> 
> It installs
> 
> ```
> "webpack": "^4.46.0"
> ```

i solve my same problem in your way，thanks
