### ISSUE TITLE
[docs] Mention top-level comments syntax in specs

### ISSUE THREAD

**Issue by jbruni** [vuejs/vue-loader#159]
I miss top-level comments syntax specified at
https://github.com/vuejs/vue-loader/blob/master/docs/start/spec.md

As far as I know, we must use HTML syntax. Is this correct?

I will try. I just want to add a "header comment" in a `.vue` file...

Thank you.

**Comment by yyx990803** [comment]
Yes, top-level html comments works just fine. You can add a PR to specify that in the docs.
