### ISSUE TITLE
可以提供一下plugin部分的文档吗？

### ISSUE THREAD

**Issue by tu6ge** [vuejs/vue-loader#1597]
### What problem does this feature solve?
plugin

### What does the proposed API look like?
plugin docs

**Comment by sodatea** [comment]
https://vue-loader.vuejs.org/zh/guide/#webpack-配置
> **这个插件是必须的！** 它的职责是将你定义过的其它规则复制并应用到 `.vue` 文件里相应语言的块。例如，如果你有一条匹配 `/\.js$/` 的规则，那么它会应用到 `.vue` 文件里的 `<script>` 块。

我不明白你还需要什么样的文档。
