### ISSUE TITLE
Webpack 5 compatibility: Missing module RuleSet

### ISSUE THREAD

**Issue by Lyrkan** [vuejs/vue-loader#1599]
### Version
15.7.1

### Reproduction link
[https://github.com/Lyrkan/repro-vue-loader-webpack5](https://github.com/Lyrkan/repro-vue-loader-webpack5)

### Steps to reproduce
* Create a project that uses Webpack 5 and vue-loader 15.7.1
* Try to run Webpack

### What is expected?
No error

### What is actually happening?
Error: Cannot find module 'webpack/lib/RuleSet'

---
Hi there,

Webpack 5 (that just got into beta) removed the `RuleSet` class that is [currently used by the `vue-loader` plugin](https://github.com/vuejs/vue-loader/blob/e1c11cf87dfab6e57a17b0707686f389de04dec2/lib/plugin.js#L2) in the following PR: https://github.com/webpack/webpack/pull/9138

This makes any attempt to use the plugin fail with a "Cannot find module webpack/lib/RuleSet" error.

**Comment by danyadev** [comment]
Any updates?

**Comment by 18566246732** [comment]
webpack5 has rewrited the ruleset module, which means the VueLoaderPlugin cannot use class Ruleset any more, instead, it should using the RuleSetCompiler.

here is my pr #1607, there are too many changes in VueLoaderPlugin,  I think vue-loader needs a major version update to support webpack5.  hope can get you guys attention, thanks

**Comment by 18566246732** [comment]
as a workaround, you can use this node package only for webpack5 [https://www.npmjs.com/package/vue-loader-plugin](url)

**Comment by 18566246732** [comment]
@sodatea Hi, I made a new pr according to your suggestions #1613

**Comment by lovetingyuan** [comment]
npm latest version is still 15.7.2, is it not released to npm?

**Comment by sodatea** [comment]
Seems an npm issue, as I've found several similar complaints on Twitter:
- https://twitter.com/dsuket/status/1206457571814473728
- https://twitter.com/itsmequinn/status/1206246890427297802

It seems to have taken effect after I've published v15.8.1
