### ISSUE TITLE
Tree shaking: styles are included from all of the file's exported components

### ISSUE THREAD

**Issue by alexgrozav** [vuejs/vue-loader#1600]
### Version
15.7.1

### Reproduction link
[https://codesandbox.io/embed/vue-tree-shaking-styles-are-included-for-all-exported-components-deodw](https://codesandbox.io/embed/vue-tree-shaking-styles-are-included-for-all-exported-components-deodw)

### Steps to reproduce
1. Export multiple components inside a single file.
```javascript
// @inkline/inkline/src/components/index.js

export { default as IAlert } from './Alert';
export { default as IButton } from './Button';
export { default as ICard } from './Card';
```

2. Import a single component from the given file:
```javascript
import {IButton} from '@inkline/inkline/src/components/index.js
```

### What is expected?
Only the SCSS file for the button component together with the template an script should be present.

### What is actually happening?
The SCSS files for Alert and Card are also imported, without the associated template and script.

---
I've noticed this while trying to improve the tree shaking capabilities of the UI Framework that I'm developing, https://github.com/inkline/inkline. 

As stated above, importing the button from a larger number of exported components will automatically include the scss files of the other components (not imported) into the bundle.

I'm not sure if this is actually related to `vue-loader` but it seems like the right place to start.

**Comment by sodatea** [comment]
Styles are side-effects so they are not tree-shakable.
