### ISSUE TITLE
[Feature Request]Plugin system for vue-loader like babel

### ISSUE THREAD

**Issue by NE-SmallTown** [vuejs/vue-loader#1603]
### What problem does this feature solve?
I want to parse a vue file(SFC) and modify(add/change/delete) some code within it, but it seems not easy for me to do that, but for a js file, you could do that easily due to the babel plugin system(it provides more simpler ways to do that).

I notice that there are a few repos which wanted to do this, like [vue-sfc-parser](https://github.com/ktsn/vue-sfc-parser), [vue-parser](https://github.com/prograhammer/vue-parser), but is not enough to write a plugin.

So, based on the doc "you will only need it separately if you are writing build tools with very specific needs." in https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler, I think there is no anything like a plugin system, but that is really helpful for some specific needs if we have.

### What does the proposed API look like?
I don't know to be honest, maybe something like babel plugin is good enough

**Comment by yyx990803** [comment]
There is a `modules` option. As an example, the internal `class` transform is a module: https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/modules/class.js

You can pass the `modules` option via [compilerOptions](https://vue-loader.vuejs.org/options.html#compileroptions) in `vue-loader`.

**Comment by NE-SmallTown** [comment]
Thanks, I will try

**Comment by NE-SmallTown** [comment]
I have a little question, when [component-compiler-utils](https://github.com/vuejs/component-compiler-utils/blob/master/lib/compileTemplate.ts#L139) call `vue-template-es2015-compiler` to compile, it doesn't pass its options.

So if I only want to execute `postTransformNode` for some directories(like `src/pageA/**`), it seems there is no way to do this because I don't have something like `filename` of current processing file(it's in `options` but doesn't pass into `vue-template-es2015-compiler` like said above)

**Comment by NE-SmallTown** [comment]
@yyx990803 Sorry to bother in the closed thread, another question is, could I do `methods` transform with the `template` transform? E.g:

After `postTransformNode`, `<div @click="myAlert">foo</div>` -----> `<div @click="newAlert">foo</div>`, but seems I can't add new method like `newAlert` to the component methods(I can't do that in `Vue.prototype` because every element will be different according to its attrs), because `postTransformNode` is only for `template` rather than `scripts/style` of the SFC

**Comment by yyx990803** [comment]
If you want to transform both templates and JavaScript at the same time, then what you really need is an extra loader before vue-loader that transforms the whole file. You can do that with a generic HTML transform tool (like [posthtml](https://github.com/posthtml/posthtml)) plus a generic JS transform toolchain (like acorn + estree-walker + astring). This is out of scope for `vue-loader`.

**Comment by NE-SmallTown** [comment]
Gotcha, thanks!
