### ISSUE TITLE
Use `type=<tag>` instead of `blockType=<tag>`

### ISSUE THREAD

**Issue by IlCallo** [vuejs/vue-loader#1608]
### Version
15.7.1

### Reproduction link
[https://vue-loader.vuejs.org/guide/custom-blocks.html#example](https://vue-loader.vuejs.org/guide/custom-blocks.html#example)

### Steps to reproduce
Create a webpack loader managing Vue files, print to console the resource name.

### What is expected?
As stated by the docs (https://vue-loader.vuejs.org/guide/custom-blocks.html), blocks should be referenced using `resourceQuery: /blockType=template/`.

### What is actually happening?
Resource name shows that `resourceQuery: /type=template/` should be used instead.
Into your loader file you are using `query.type === 'template'` too, so I guess the docs are out of sync.
Eg: `my-component.vue?vue&type=template&id=5633df48&scoped=true&`

---
I'm using this into Quasar framework, if this can make any difference.
Adding docs issues with the custom form isn't really dev friendly, is there some other mechanism I missed out?

**Comment by LinusBorg** [comment]
The docs your are referrring to are about **custom** blocks. That does *not* include the default blocks `<template>`, `<script>` and `<style>`.

**Comment by IlCallo** [comment]
The custom blocks documentation is the only one I found where is mentioned a way to target a `template` block by `resourceQuery`, that's why I thought that was the same way for all blocks.
Did I miss a section in the documentation? I checked it 2-3 times.
Or it's not mentioned because you consider it an implementation detail and don't want it to be used?

**Comment by LinusBorg** [comment]
The latter. You can "get" the template block by adding a loader for a file extension that matches the `lang` set on the `<template>`, which is the official way to apply a loader to any of the default blocks

**Comment by IlCallo** [comment]
Which is how it is explained [here](https://vue-loader.vuejs.org/guide/#manual-setup) and [here](https://vue-loader.vuejs.org/guide/pre-processors.html#sass) I think.

While there are examples for `.js` and `.css`, targeting normal `.html` isn't explicitly covered. Adding it would probably help webpack newbies (like me in this moment).

In my case, I want to specifically target only `.html` into Vue `<template>` blocks, that's why I was searching for a way to specifically select them.

Would a rule like this, inspired by the one in pug section, be a more "safe" way to obtain what I need, from your point of view?

```js
{
  test: /\.html$/,
  resourceQuery: /^\?vue/,
  loader: ...
}
```

Sorry for continuous bothering, I'm just making everything explicit here for the next one who's gonna search for this stuff :)

**Comment by LinusBorg** [comment]
You only need that resourceQuery if you need a `oneOf`  config that treats actual .html files differently than html coming from a .vue file.

If you don't need to handle actual physical .html files at all, you can just do:
```javascript
{
  test: /\.html$/,
  loader: '...'
}
```
like in the pug example.

**Comment by mrleblanc101** [comment]
Hi,
Sorry, this might not be the right place. But how would I target a svg inside SFC script only ?
I want svg inside script to be loaded using `vue-svg-loader` as component but I want SVG inside `<img :src="file.svg" />` to be treated as normal.
