### ISSUE TITLE
Render with Jade no escape

### ISSUE THREAD

**Issue by zheng1** [vuejs/vue-loader#161]
```vue
<template lang="jade">
td(title='{{{skillsView()}}}') hover
</template>

<script>
export default {
  data() {
    return {};
  },
  methods: {
    skillsView() {
      var str = [1,2,3];
      return str.join('&#013;');
    },
  },
};
</script>
```

correct result is `<td title="1&#013;2&#013;3">hover</td>`

but now is `<td title="1&amp;#013;2&amp;#013;3">hover</td>`.

**Comment by yyx990803** [comment]
`{{{ }}}` doesn't work inside attribute values, so it's treated as a plain string (which then gets escaped). Also there's no need to HTML escape inside attributes... just use whatever actual character you want to use.
