### ISSUE TITLE
16.0.0-alpha.1 running error

### ISSUE THREAD

**Issue by doter1995** [vuejs/vue-loader#1623]
### Version
15.8.3

### Reproduction link
[https://github.com/doter1995/vue3-test/tree/this_bug_demo](https://github.com/doter1995/vue3-test/tree/this_bug_demo)

### Steps to reproduce
 con't choose `16.0.0-alpha.1`,so I select  `15.8.3`
```
TypeError: Cannot read property 'length' of undefined
```

```javascript
//dist/index.js line 42
const { descriptor, errors } = compiler_sfc_1.parse(source, {
        filename: resourcePath,
        sourceMap
});
```
but `compiler_sfc_1.parse` will return `descriptor`

### What is expected?
无

### What is actually happening?
无

**Comment by yyx990803** [comment]
Your `@vue/compiler-sfc` version should be `3.0.0-alpha.1`.
