### ISSUE TITLE
有没有可以供pracel使用的loader

### ISSUE THREAD

**Issue by Polaris-z** [vuejs/vue-loader#1628]

**Comment by sodatea** [comment]
https://parceljs.org/vue.html
Parcel 默认就支持 Vue

**Comment by Polaris-z** [comment]
> https://parceljs.org/vue.html
> Parcel 默认就支持 Vue

3.0 不行吧？

**Comment by sodatea** [comment]
3.0 还在 alpha 阶段，工具生态确实很多都没能及时跟进，欢迎贡献代码。
Parcel 的 Vue 支持就几百行代码，应该不难加。
https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/assets/VueAsset.js

**Comment by Polaris-z** [comment]
> https://parceljs.org/vue.html
> 包裹默认就支持Vue
老哥 我昨天试着改了源码 但是还有报错  所以才来问问 - -~~

**Comment by sodatea** [comment]
😅Parcel 不是 Vue 团队维护的，所以目前我们也没有排期去实现 3.0 支持……建议去他们的 GitHub 仓库问问。

**Comment by Polaris-z** [comment]
我今天晚上回去再改下试试  说不定就成了呢~😅  谢谢老哥 知乎关注你很久了~
