### ISSUE TITLE
Any plan to support 'rollup' loader?

### ISSUE THREAD

**Issue by zjhiphop** [vuejs/vue-loader#163]
Currently, it works very nice with WebPack. But the webpack bundle files are too large to use in mobile platform. So i'd like try to use 'rollup' to bundle vue modules. That's why i come here to ask the question.

**Comment by rbvea** [comment]
There's this: https://github.com/znck/rollup-plugin-vue

Since vue-loader uses webpack, I think webpack 2 would be the way to go.

**Comment by jetiny** [comment]
But both rollup-plugin-vue and rollup-plugin-vue2 does not working fine.

**Comment by LinusBorg** [comment]
Then you should probably open an issue in their respective repositories.
