### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by vankop** [vuejs/vue-loader#1631]
### What problem does this feature solve?
Prevents loader speed regression.

### What does the proposed API look like?
I think benchmarks can be run with fixed webpack versions 4.x.x and 5.x.x

**Comment by yyx990803** [comment]
`vue-loader` itself is almost never the bottleneck for build performance. In real apps majority of build time is spent in Babel/TS/minifiers.

**Comment by vankop** [comment]
I wanted suggest to use instead of `loaderContext.resourcePath` use new syntax https://webpack.js.org/api/loaders/#inline-matchresource , but I don't know will it impact on loader performance..

Also loader speed could be improved when you don't parse SFC in each chain (template, script, style), see https://github.com/webpack/webpack/issues/9791

**Comment by yyx990803** [comment]
The SFC parser has its own cache, so repeated parsing of the same content won't cause perf issues.
