### ISSUE TITLE
[next] Absolute and HTTP asset URLs are not ignored

### ISSUE THREAD

**Issue by sisou** [vuejs/vue-loader#1632]
### Version
16.0.0-alpha.2

### Reproduction link
[https://github.com/sisou/vue-next-webpack-preview](https://github.com/sisou/vue-next-webpack-preview)

### Steps to reproduce
1. (Fork and) clone https://github.com/vuejs/vue-next-webpack-preview
2. Run `yarn upgrade` to have the latest versions (e.g. vue-loader@16.0.0-alpha.2)
3. Replace the relative src to the Vue logo in `App.vue` with a HTTP URL: `https://vuejs.org/images/logo.png`
4. Try to compile with `yarn dev` or `yarn build` and receive an error.

### What is expected?
The project compiles without errors, because absolute and HTTP URLs are ignored (or rather preserved-as-is) by vue-loader.

### What is actually happening?
Vue-loader throws an error during compilation that it could not find dependencies.

---
I hope I have interpreted the [Transform Rules](https://vue-loader.vuejs.org/guide/asset-url.html#transform-rules) correctly. I think I have, because it is working fine with Vue 2 and a lower version of vue-loader.

**Comment by sisou** [comment]
I did a bit more digging and I think this issue actually concerns the `compiler-sfc` package in vue-next, somewhere around this code:
https://github.com/vuejs/vue-next/blob/master/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L49

Do you want me to open an issue there instead?

**Comment by yyx990803** [comment]
closed via vue-next#628
