### ISSUE TITLE
@import in scope style turn un-scoped

### ISSUE THREAD

**Issue by mathias22osterhagen22** [vuejs/vue-loader#1637]
### Version
15.8.3

### Reproduction link
[https://github.com/mathias22osterhagen22/import-scoped-sample](https://github.com/mathias22osterhagen22/import-scoped-sample)

### Steps to reproduce
1. `npm install`
2. `npm run serve`

Navigate and see

### What is expected?
The CSS file imported with @import should stay in the vue "About" and not be accessible from the "Home" vue.
![image](https://user-images.githubusercontent.com/60438474/73952381-1d150a80-48ff-11ea-9abc-0e3091d4a929.png)

### What is actually happening?
The class of the CSS file is accessible from the "Home" vue.
![image](https://user-images.githubusercontent.com/60438474/73952464-3c139c80-48ff-11ea-85c6-ee1be799a004.png)

---
The class "viewer-navbar" is accessible from the "Home" page that made the box with a black background.

I tryed to replace 
```js
<style lang="css" scoped>
  @import "~viewerjs/dist/viewer.css";
</style>
```

By: 
```js
<style lang="css" src="../../node_modules/viewerjs/dist/viewer.css" scoped></style>
```
Or:
```js
<style lang="css" src="viewerjs/dist/viewer.css" scoped></style>
```
But then `viewerjs` doesn't work anymore.
![image](https://user-images.githubusercontent.com/60438474/73952592-70875880-48ff-11ea-990d-b70dbc67b9d1.png)

PS: I think linked with 'less @import can't work fine with scoped #235 '
@LinusBorg (I think this is what you ask for)

**Comment by satyen95** [comment]
@LinusBorg Is there any solution for the above unscoped CSS import?
Have been facing the some for quite some time, any workarounds? @mathias22osterhagen22 
v15.10.0

**Comment by LinusBorg** [comment]
This is not a bug in my book. `@import`ing CSS does not inline it into the style block, so scoping it would not be a good idea.

If you want to inline some CSS from another file and have it scoped, use a separate style block with `src`, like OP showed (they said "broke" that libary but that's because that library's styles were now scoped - so it did what they asked for).

**Comment by satyen95** [comment]
@LinusBorg Tried importing it via `src` too, the result is the same unscoped CSS
<style lang="css" src="../../node_modules/xyz/xyz/dist/xyz.css" scoped>
</style>

**Comment by HusseinAlawieh-BIMPOS** [comment]
@mathias22osterhagen22 how did you solve the issue?? I have been stuck on the same problem for days

**Comment by wesley3295** [comment]
Any updates?

**Comment by castrix** [comment]
I've just met this issue and I found the solution

you can use `useHead` for the stylsheet so it will only load on that component:

```
useHead({
link: [
{ rel: 'stylesheet', href: "~viewerjs/dist/viewer.css"}
]
})
```

more information: https://nuxt.com/docs/getting-started/styling#dynamically-adding-stylesheets
