### ISSUE TITLE
Support webpack@5

### ISSUE THREAD

**Issue by vankop** [vuejs/vue-loader#1643]
### Version
16.0.0-alpha.3

### Reproduction link
[https://github.com/vankop/vue-next-webpack-preview](https://github.com/vankop/vue-next-webpack-preview)

### Steps to reproduce
This already done for `vue-loader@15`, will be great to do this for `next` branch as well

### What is expected?
build completed

### What is actually happening?
Error: Cannot find module 'webpack/lib/RuleSet' [here](https://github.com/vuejs/vue-loader/blob/next/src/plugin.ts#L4)

**Comment by diy4869** [comment]
I also encountered this problem. Is there any good solution? Webback4 is normal, and 5 will report this error
![image](https://user-images.githubusercontent.com/29079700/79535335-ba36b100-80af-11ea-9ba2-061bac7c36c9.png)

**Comment by foxxyz** [comment]
I can confirm Webpack 5 support is working in the [`next` branch](https://github.com/vuejs/vue-loader/commits/next) (see ddc9f5d691e5eabc0de5ca553a8caacea2d2ffda), so at this point it's just waiting for @yyx990803 to make `16.0.0-beta.1` into an official release.

**Comment by yyx990803** [comment]
@foxxyz `vue-loader@next` now points to `16.0.0-beta.1`! It's a bit untested, so I'll keep this open for now.

**Comment by skjnldsv** [comment]
What about vue 2.x.x support on webpack5 ?
It seems it doesn't work for me with  `vue-loader@next` :disappointed:

**Comment by alcaitiff** [comment]
@skjnldsv may you share a webpack.dev.conf.js file working in webpack 5? Mine is taking to much time to build on dev mode. Something like 10x slower than webpack 4 for vue.

**Comment by skjnldsv** [comment]
> @skjnldsv may you share a webpack.dev.conf.js file working in webpack 5? Mine is taking to much time to build on dev mode. Something like 10x slower than webpack 4 for vue.

Sure https://github.com/nextcloud/webpack-vue-config/pull/41

**Comment by alcaitiff** [comment]
Thank you i got my problem. 

The eslint-webpack-plugin: "2.1.0" was making it slow. Changing it to 2.2.1 makes the build several times faster.

**Comment by sodatea** [comment]
Both v15 (for Vue 2) & v16 (for Vue 3) have supported webpack 5, and corresponding tests have been added. So I'm closing this issue.
