### ISSUE TITLE
Removed style tag not registered for hotloading

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-loader#166]
As @jbruni [reported here](https://github.com/vuejs-templates/webpack/issues/17):

> Fresh install. Playing with Hello.vue, under npm run dev.
> 
> I've added
> 
> ``` html
> <style>
> h1 { color: red }
> </style>
> ```
> 
> and saved the file. The style has been hot-loaded and applied. Great!
> 
> Then, I've undone the change (removed the <style> I've added), and saved again. No change in the browser...
> 
> I had to add an empty <style></style> and save the file to see the styles removed in the browser.
> 
> Then, I could finally remove the tag, since the "undo" was done.

**Comment by jbruni** [comment]
@chrisvfritz - Thank you for taking care and moving the issue to the correct place.

**Comment by kazupon** [comment]
I reproduced in 8.x version (Vue 1.x).
BTW, I did not reproduce in 9.x later.

**Comment by eeerrrttty** [comment]
im with the problem. Holly fuck. I uninstaled all my dependencies, than worked, now stoped again. Do i will have to reinstall everytime? omg my dependencies have almost 300mb.

**Comment by AielloChan** [comment]
@eeerrrttty yarn plz, it will cache all your installed package
