### ISSUE TITLE
No named VueLoaderPlugin export in TypeScript webpack config

### ISSUE THREAD

**Issue by davelsan** [vuejs/vue-loader#1667]
### Version
16.0.0-alpha.3

### Reproduction link
File of interest:
[https://github.com/davelsan/vue-next-starter/blob/master/webpack.config.ts](https://github.com/davelsan/vue-next-starter/blob/master/webpack.config.ts)
Full repo:
[https://github.com/davelsan/vue-next-starter](https://github.com/davelsan/vue-next-starter)

### Steps to reproduce
Simple version:
1. Create a `webpack.config.ts` file
2. Try to `import { VueLoaderPlugin } from 'vue-loader'`

Using the provided repro
1. Comment `lines [13-15]` in `webpack.config.ts`

### What is expected?
There should be a named export or a type definition for the default export that allows creating a `new VueLoaderPlugin()` object.

### What is actually happening?

> webpack.config.ts:8:10 - error TS2305: Module '"./node_modules/vue-loader/dist"' has no exported member 'VueLoaderPlugin'.

Additional Comments
---
The [repro](https://github.com/davelsan/vue-next-starter) repository is a working Vue application built without the CLI toolchain. To work around the errors listed above, I augmented the 'vue-loader' plugin as described in the TypeScript [documentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation):

```ts
declare module 'vue-loader' {
  export class VueLoaderPlugin extends Plugin { }
}
```

This is only an issue when using a `webpack.config.ts`, the [js version](https://github.com/davelsan/vue-next-starter/blob/master/___webpack.config.bak.js) works fine.

**Comment by davelsan** [comment]
Taking #1542 as inspiration, I tried adding the export directly to `index.d.ts` and it does fix the issue.

```diff
  import { TemplateCompiler, CompilerOptions, SFCTemplateCompileOptions } from '@vue/compiler-sfc';
+ import { Plugin } from 'webpack';
+ export class VueLoaderPlugin extends Plugin { }
  export interface VueLoaderOptions {
      transformAssetUrls?: SFCTemplateCompileOptions['transformAssetUrls'];
      compiler?: TemplateCompiler;
      compilerOptions?: CompilerOptions;
      hotReload?: boolean;
      exposeFilename?: boolean;
      appendExtension?: boolean;
  }
```

My uneducated guess is that the problem might be in the way `VueLoaderPlugin` is imported and re-exported?

https://github.com/vuejs/vue-loader/blob/356f6866b27444a8159bf47d8c9f1f55687d8d2d/src/plugin.ts#L12

https://github.com/vuejs/vue-loader/blob/356f6866b27444a8159bf47d8c9f1f55687d8d2d/src/index.ts#L28

https://github.com/vuejs/vue-loader/blob/356f6866b27444a8159bf47d8c9f1f55687d8d2d/src/index.ts#L249

**Comment by davelsan** [comment]
Simplified the issue a bit. The current work-around is to use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) in `webpack.config.ts`.

**Comment by sodatea** [comment]
Fixed in beta 2
