### ISSUE TITLE
[ vue-loader/next ] HMR not triggering on changes to slot content

### ISSUE THREAD

**Issue by davelsan** [vuejs/vue-loader#1669]
### Version
16.0.0-beta.3

#### Vue-CLI version
[https://github.com/davelsan/vue-next-starter/tree/cli-version](https://github.com/davelsan/vue-next-starter/tree/cli-version)

#### Webpack version

[https://github.com/davelsan/vue-next-starter/tree/master](https://github.com/davelsan/vue-next-starter/tree/master)

### Steps to reproduce
Using the repro:
1. start development server (`npm run dev`) and open `localhost:8080`
2. below the logo there is a test message with the content `This is a static HMR test message`
3. go to file [`src/modules/home/home.vue`](https://github.com/davelsan/vue-next-starter/blob/cli-version/src/modules/home/home.vue) and edit the test message (`line 9`)
4. verify that the page content is not updated
5. reload the page to see the changes

### What is expected?
Edits to slot content called from the parent should auto-update the page content

### What is actually happening?
The page does not update the static content in the template. However, content returned by the `setup()` function appears to be correctly observed, and updates on change.

---
The provided repro is a simple repository created with the official [Vue CLI](https://cli.vuejs.org/) and [vue-cli-plugin-vue-next](https://github.com/vuejs/vue-cli-plugin-vue-next). I've used that format because that is where I am testing the beta; please, let me know if this is not an acceptable repro.

#### Update

- The issue occurs only for static template content. Any object returned by `setup()` is correctly observed and the page updates on changes.
- Updated the `vue-loader` version where this applies to `16.0.0-beta.3`.
- Added the same issue for a non-CLI build. It still uses `webpack`, but this also happens with `vite`.

**Comment by davelsan** [comment]
This issue only happens for static content in the template, i.e. not happening for content that is returned by the `setup()` function.

To demonstrate this, I've added a dynamic content message to the `home.vue` template in the repro (`line 10`).
https://github.com/davelsan/vue-next-starter/blob/1d3df964b76702ef3b1d9fdfc6ba3bb9b4cb9327/src/modules/home/home.vue#L10

Changes in `line 34` trigger a page update.
https://github.com/davelsan/vue-next-starter/blob/1d3df964b76702ef3b1d9fdfc6ba3bb9b4cb9327/src/modules/home/home.vue#L34

I suspect this might not be the proper repository to post the issue, and it might even be an intended side effect of how the new composition API works.

Either way, I am proposing to close this issue. I'll keep it open a bit longer (1-2 days?) to give time for any objection / answer.

**Comment by yyx990803** [comment]
This has been fixed in vue-next and will get a release soon.
