### ISSUE TITLE
Remove dependence of template-html-loader

### ISSUE THREAD

**Issue by kxxoling** [vuejs/vue-loader#167]
template-html-loader package has long time not being maintained, and has little code to rewrite. Should we rewrite it to replace the third part package?

**Comment by yyx990803** [comment]
Yeah, sounds like a good idea. We probably should just fold it into `vue-loader` so that users don't have to install an extra dependency: just `npm install jade` and you can use jade.

**Comment by yyx990803** [comment]
done in 8.2.0

**Comment by kxxoling** [comment]
Nice job!
