### ISSUE TITLE
Scoped has no effect

### ISSUE THREAD

**Issue by frangio** [vuejs/vue-loader#1677]
### Version
16.0.0-beta.2

### Reproduction link
[ https://github.com/frangio/vue-next-example]( https://github.com/frangio/vue-next-example)

### Steps to reproduce
Run `npm run build` and look at `dist/main.css`.

### What is expected?
The `.title` style block should be scoped.

### What is actually happening?
It has no scope, as if it had been just copied from the source file.

**Comment by Arman19941113** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/35905177/82758141-668a5680-9e17-11ea-92e2-d5568de5b7c2.png)

**Comment by sodatea** [comment]
Got it. It's due to the wrong export in `pitcher.ts`. Will fix it tomorrow.

**Comment by sodatea** [comment]
Considering it's quite a serious bug. I've released v16.0.0-beta.3 to address it. Tests will be added later in the day.
