### ISSUE TITLE
Regression: CSS src file produces compilation errors

### ISSUE THREAD

**Issue by jods4** [vuejs/vue-loader#1679]
### Version
16.0.0-beta.2

### Reproduction link
[http://See.below](http://See.below)

### Steps to reproduce
Use webpack, vue-loader and templates that use external stylesheet such as:
```html
<style src="./test.css"></style>
```

### What is expected?
Until 16.0-beta.1, it worked fine

### What is actually happening?
Since 16.0-beta.2 there is a build error.
Looking at the stack carefully, it is clear that the `css-loader` has been incorrectly inserted twice, notably _after_ `style-loader`.

(this stack comes from my project that uses PostCSS, but it reproduces with a plain vanilla css file as well)
```
./node_modules/css-loader/dist/cjs.js!
./node_modules/style-loader/dist/cjs.js!
./node_modules/css-loader/dist/cjs.js!
./node_modules/postcss-loader/src??postcss!
./ClientApp/Components/Forms/input.scss?vue&type=style&index=0&lang=css
```

**Comment by sodatea** [comment]
Should have been fixed in beta.3. Could you have a try?

**Comment by jods4** [comment]
I can confirm this works again in beta.3.
