### ISSUE TITLE
 ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found. Make sure the rule matching .vue files include vue-loader in its use.

### ISSUE THREAD

**Issue by starSmallDream** [vuejs/vue-loader#1687]
vue create创建的项目，集成webpack ,,,添加 vue-loader的时候，不停出现这个报错  ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
，，，，已经按 vue-loader的文档操作，还是不行 
![image](https://user-images.githubusercontent.com/28866025/85084383-3744ea80-b207-11ea-9f96-47aa00374798.png)
![image](https://user-images.githubusercontent.com/28866025/85084397-4035bc00-b207-11ea-8443-ec36cf155f1c.png)

第二个问题是  
![image](https://user-images.githubusercontent.com/28866025/85084457-6c513d00-b207-11ea-9f21-594b047d60db.png)

出这个错误，
![image](https://user-images.githubusercontent.com/28866025/85084518-9c98db80-b207-11ea-80cb-11f5ec6bc98a.png)

**Comment by LP1994** [comment]
When you use "webpack v5.0.0", if you encounter "error error: [vueloaderplugin error] no matching use for Vue loader is found. Make sure the rule matching. Vue files include Vue loader in its", If other loaders appear before "Vue loader", for example, "HTML loader" appears before "Vue loader", then just add an "enforce" option in the rules of "HTML loader", and its value is the string "post". In this way, the original loader can be used normally without changing the order of the original loader.
The configuration example code is as follows:

module: {
rules: [

// first loader
{
test: /\.(html|htm)$/i,
enforce: 'post',
use: [
{
loader: 'html-loader',
},
],
},

// other loader...

{
test: /\.vue$/i,
use: [
{
loader: 'vue-loader',
},
],
},

],
}

**Comment by LP1994** [comment]
Today, while updating the configuration of webpack 5, I explored this problem and verified that this method is ok.

**Comment by LP1994** [comment]
> vue create创建的项目，集成webpack ,,,添加 vue-loader的时候，不停出现这个报错 ERROR Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
> Make sure the rule matching .vue files include vue-loader in its use.
> ，，，，已经按 vue-loader的文档操作，还是不行
> ![image](https://user-images.githubusercontent.com/28866025/85084383-3744ea80-b207-11ea-9f96-47aa00374798.png)
> ![image](https://user-images.githubusercontent.com/28866025/85084397-4035bc00-b207-11ea-8443-ec36cf155f1c.png)
> 
> 第二个问题是
> ![image](https://user-images.githubusercontent.com/28866025/85084457-6c513d00-b207-11ea-9f21-594b047d60db.png)
> 
> 出这个错误，
> ![image](https://user-images.githubusercontent.com/28866025/85084518-9c98db80-b207-11ea-80cb-11f5ec6bc98a.png)

When you use "webpack v5.0.0", if you encounter "error error: [vueloaderplugin error] no matching use for Vue loader is found. Make sure the rule matching. Vue files include Vue loader in its", If other loaders appear before "Vue loader", for example, "HTML loader" appears before "Vue loader", then just add an "enforce" option in the rules of "HTML loader", and its value is the string "post". In this way, the original loader can be used normally without changing the order of the original loader.
The configuration example code is as follows:

module: {
rules: [

// first loader
{
test: /\.(html|htm)$/i,
enforce: 'post',
use: [
{
loader: 'html-loader',
},
],
},

// other loader...

{
test: /\.vue$/i,
use: [
{
loader: 'vue-loader',
},
],
},

],
}

Today, while updating the configuration of webpack 5, I explored this problem and verified that this method is ok.
