### ISSUE TITLE
Issue with ES6 import inside vue component

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#169]
Hi. I have some unusual problem with importing default export of a module inside **.vue** component which can't quite figure out. First of all I want to say that I am using Webpack 2 + tree-shaking configuration - http://www.2ality.com/2015/12/webpack-tree-shaking.html and i think it
would be best to if I show you what I mean in example.

I have the following file structure:

/components/ - Vue components
/auth/ - auth utils
index.js - entry point

my auth/index.js looks like this:

```
const API_URL = 'http://localhost:3000';
export const AUTH_LOGIN_URL = '/auth/login';
export const AUTH_LOGOUT_URL = '/auth/logout';

export default {
  user: {},
  ...
};
```

In app entry point (index.js) I am importing auth module like so:

`import { default as auth } from './auth';`

so auth is my default export:

```
user: {},
...
```

But strange thing happens when i try to import auth module inside .vue component.

```
<script>
  import UserNav from './UserNav';
  import { default as auth } from '../auth';

  console.log(auth);

  export default {
    components: {
      UserNav,
    },
    data() {
      return {};
    },
    methods: {},
  };
</script>
```

now my import looks like this:

![screenshot](http://i.imgur.com/BjfmNaF.png)

Why is this happening? Am i doing something wrong here? I opened this issue here because I noticed this problem occurs with **.vue** components only, otherwise it works as expected. i would appreciate any help with this. Thanks.

**Comment by sqal** [comment]
Hey again. Just wanted to ask if Is there any progress on this issue?

**Comment by guillaumevincent** [comment]
@sqal do you have the same issue with a `package.json` in `auth` folder file instead of an `index.js` ?

    {
        "name": "auth",
        "private": true,
        "main": "./auth.js"
    }
