### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by nspeedzy** [vuejs/vue-loader#1690]
### Version
16.0.0-beta.4

### Reproduction link
[https://codesandbox.io/s/nostalgic-tu-osi62?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/nostalgic-tu-osi62?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Created a new project with the vue cli
2. Added a `<script lang="ts">` in the `App.vue`
3. Tried declaring a variable with a type
4. Faced the `Unexpected token` error on compilation

### What is expected?
No parsing errors like that should have occurred and the app should be compiled and ready to be viewed in the browser

### What is actually happening?
I get the unexpected token error. The error logs are shown in the codesandbox

---
If you check the sandbox i have linked, you will see that the sandbox outputs an error: `Unexpected token`

**Comment by sodatea** [comment]
The unexpected token error is from ESLint. You need to configure the `parser` for ESLint, following https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser or use https://github.com/vuejs/eslint-config-typescript/
