### ISSUE TITLE
Published beta version as latest

### ISSUE THREAD

**Issue by tomrav** [vuejs/vue-loader#1691]
### Version
16.0.0-beta.4

### Reproduction link
[https://www.npmjs.com/package/vue-loader?activeTab=versions](https://www.npmjs.com/package/vue-loader?activeTab=versions)

### Steps to reproduce
Add vue-loader as a dependency to any project.

### What is expected?
Latest version tag should probably be 15.9.3?
![image](https://user-images.githubusercontent.com/6399886/85946015-32d8aa00-b94a-11ea-9f9d-b41d9078379c.png)

### What is actually happening?
Because it's the beta version it forces other beta versions, and generally causes breakage due to mis-matching versions.

**Comment by sodatea** [comment]
Oops. Thank you so much!
It's fixed now.
