### ISSUE TITLE
vue-loader网站手动配置里vue-style-loader版本过低，造成css解析了不渲染到页面

### ISSUE THREAD

**Issue by leer561** [vuejs/vue-loader#1709]
https://vue-loader.vuejs.org/guide/#manual-setup

vue-style-loader版本过低，现在最新的css-loader一起使用，有问题，CSS无法渲染，建议换成style-loader
误导了很耽误时间

**Comment by Justineo** [comment]
Confirmed the problem reported is valid from other sources so I'll reopen this one. (Please follow the issue template next time.)

**Comment by aZilberstein** [comment]
@leer561 谢谢您的帮助!!! Your comment has saved me a lot of time I'd been wasting trying to figure out why wouldn't **vue-style-loader** work.

I tried to Google Translate the comment made by @leer561 and in a few words it means that the newest version of **css-loader** is incompatible with an outdated **vue-style-loader** package, so as of now only using the regular **style-loader** seems to work fine.

**Comment by gluons** [comment]
Seem **vue-style-loader** is broken on **css-loader** v4.

See vuejs/vue-style-loader#46.

**Comment by rookiebulls** [comment]
Saved my day!!

**Comment by loving0606** [comment]
谢谢，找了半天都没找到问题
