### ISSUE TITLE
computed内支持直接return jsx

### ISSUE THREAD

**Issue by wsi18n** [vuejs/vue-loader#1713]
### What problem does this feature solve?
now:

computed: {
    foo: vm => {
      // eslint-disable-next-line no-unused-vars
      const h = vm.$createElement
      return <div on={{ click: console.log }}>{vm.bar)</div>
    }
}

----------------------------------------------------------------------------------------------
expect:

computed: {
    foo: vm => <div on={{ click: console.log }}>{vm.bar)</div>}
}

### What does the proposed API look like?
expect:

computed: {
    foo: vm => <div on={{ click: console.log }}>{vm.bar)</div>}
}

**Comment by sodatea** [comment]
现在的 [`@vue/babel-preset-jsx`](https://github.com/vuejs/jsx) 是默认支持这种用法的，但不能用箭头函数。
