### ISSUE TITLE
Error resolving webpackConfig Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.

### ISSUE THREAD

**Issue by juancu8** [vuejs/vue-loader#1717]
### Version
15.9.2

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
 Error resolving webpackConfig Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.
09:33:07      at Object.<anonymous> (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/node_modules/vue-loader/dist/index.js:10:11)
09:33:07      at Module._compile (internal/modules/cjs/loader.js:816:30)
09:33:07      at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
09:33:07      at Module.load (internal/modules/cjs/loader.js:685:32)
09:33:07      at Function.Module._load (internal/modules/cjs/loader.js:620:12)
09:33:07      at Module.require (internal/modules/cjs/loader.js:723:19)
09:33:07      at require (internal/modules/cjs/helpers.js:14:16)
09:33:07      at api.chainWebpack.webpackConfig (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/lib/config/base.js:110:16)
09:33:07      at webpackChainFns.forEach.fn (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/lib/Service.js:236:40)
09:33:07      at Array.forEach (<anonymous>)
09:33:07      at Service.resolveChainableWebpackConfig (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/lib/Service.js:236:26)
09:33:07      at Service.resolveWebpackConfig (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/lib/Service.js:240:48)
09:33:07      at Object.<anonymous> (/home/jenkins/agent/workspace/census-frontend-ci-job/sources/frontendproject/node_modules/@vue/cli-service/webpack.config.js:12:26)
09:33:07      at Module._compile (internal/modules/cjs/loader.js:816:30)
09:33:07      at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
09:33:07      at Module.load (internal/modules/cjs/loader.js:685:32)

### What is expected?
run correctly

### What is actually happening?
when jenkins execute 'npm run lint'. Try downgrading vue-loader from cli and not worked, any suggested?
(in local it works)

**Comment by sodatea** [comment]
Please report to the Vue CLI repo and fill in the issue template, so that we can have enough information to reproduce the issue.

**Comment by vospascal** [comment]
packageExtensions:
  vue-loader@*:
    peerDependencies:
      '@vue/compiler-sfc': '*'
      webpack: '*'

when your using yarn berry
