### ISSUE TITLE
Documentation is inconsistent

### ISSUE THREAD

**Issue by mjmnagy** [vuejs/vue-loader#1719]
### Version
16.0.0-beta.5

### Reproduction link
[https://github.com/mjmnagy/vue-error-2020-08-26](https://github.com/mjmnagy/vue-error-2020-08-26)

### Steps to reproduce
`npm run prod`

### What is expected?
Create a component lirbary

### What is actually happening?
errors - didnt get a result from child compiler

---
From reading webpack.config.js is no longer supported and the extension of webpack should be in the vue.config.js. However, I get an error on all my components
https://vue-loader.vuejs.org/guide/extract-css.html#webpack-4

**Comment by sodatea** [comment]
The documentation is for raw webpack configuration, and you are clearly not using it.

For Vue CLi configuration, see https://cli.vuejs.org/config/#css-extract
