### ISSUE TITLE
当template里的svg包含style标签时会报错

### ISSUE THREAD

**Issue by fancyboynet** [vuejs/vue-loader#1721]
### Version
15.9.2

### Reproduction link
[http://null](http://null)

### Steps to reproduce
<template>
<svg>
<style></style>
</svg>
</template>

### What is expected?
正常编译出svg图标

### What is actually happening?
报错:
Errors compiling template:

  Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.

---
Errors compiling template:

  Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.

**Comment by sodatea** [comment]
报错说得很明确了吧。不要在 template 里面写 style

**Comment by fancyboynet** [comment]
额，是svg里的style啊，也不允许吗，那个提bug的页面把svg部分的代码给去了。。。

**Comment by sodatea** [comment]
不允许，svg 里的 style 也应该拆出来放到单独的 style 区块里。

**Comment by fancyboynet** [comment]
可是，svg一般都是软件自动导出来的，用到的地方还很多，如果每个都拆出来，是不是不太现实额

**Comment by sodatea** [comment]
1. （推荐做法）放到单独的文件里，用 `img src=""` 或者 [`vue-svg-loader`](https://vue-svg-loader.js.org/) 引入
2. 替换 `<style>` 为 `<svg:style>`
