### ISSUE TITLE
vue3   ts-loader use decorators will error

### ISSUE THREAD

**Issue by haishengXie0712** [vuejs/vue-loader#1724]
### Version
16.0.0-beta.5

### Reproduction link
[https://github.com/haishengXie0712/test](https://github.com/haishengXie0712/test)

### Steps to reproduce
npm i && npm run dev

### What is expected?
decorators it work

### What is actually happening?
This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (4:0)

---
My loader version you are beta.7, but can not select.so i select bats.5.

**Comment by MKGaru** [comment]
compile error since 16.0.0-beta.6~ :face_with_head_bandage: 

https://github.com/vuejs/vue-loader/commit/fb09c8b1755086c4e0627d0e83035e8ef53ed5c3#diff-f41e9d04a45c83f3b6f6e630f10117feR134

**Comment by MKGaru** [comment]
@haishengXie0712 check this solution: https://github.com/vuejs/vue-cli/pull/5868/files#diff-6ec9cc910e3a24f805cd6d69c2b5c0c9R136

https://github.com/haishengXie0712/test/blob/master/build/base.js#L49

**Comment by sodatea** [comment]
Should be fixed in upstream: https://github.com/vuejs/vue-next/pull/2088

Temporary workaround: set the `babelParserPlugins` option, like here: https://github.com/vuejs/vue-cli/pull/5868/files#diff-6ec9cc910e3a24f805cd6d69c2b5c0c9R138

**Comment by haishengXie0712** [comment]
@MKGaru @sodatea 
That's it. Thank you for your answers!
