### ISSUE TITLE
Fail to work with vue 3.0.0 and webpack 4.44.1

### ISSUE THREAD

**Issue by plantain-00** [vuejs/vue-loader#1727]
### Version
16.0.0-beta.7

### Reproduction link
[https://github.com/plantain-00/types-as-schema/tree/vue-loader-failure](https://github.com/plantain-00/types-as-schema/tree/vue-loader-failure)

### Steps to reproduce
1. clone the project
2. yarn && yarn build

### What is expected?
No error

### What is actually happening?
Plenty of errors:
https://travis-ci.org/github/plantain-00/types-as-schema/builds/729529993

**Comment by sodatea** [comment]
- the alias of `vue` in the config file is incorrect
- Vue 3 does not provide a default export, please use either `import * as Vue from 'vue'` or `import { defineComponent } from 'vue'`

**Comment by plantain-00** [comment]
- Still same failure: https://travis-ci.org/github/plantain-00/types-as-schema/builds/729577637
- Maybe a clearer error message can help users.

**Comment by sodatea** [comment]
And you forgot the `options: { appendTsSuffixTo: [/\.vue$/] }` option for ts-loader.
https://vue-loader.vuejs.org/guide/pre-processors.html#typescript

**Comment by plantain-00** [comment]
It's good now.
