### ISSUE TITLE
Webpack@5 asset generator property not supported

### ISSUE THREAD

**Issue by kevinvalk** [vuejs/vue-loader#1729]
### Version
16.0.0-beta.8

### Reproduction link
[https://github.com/kevinvalk/vue-loader-generator-issue](https://github.com/kevinvalk/vue-loader-generator-issue)

### Steps to reproduce
- npm install
- webpack

### What is expected?
```
asset main.js 20 bytes [compared for emit] [minimized] (name: main)
./index.js 21 bytes [built] [code generated]
webpack 5.0.0-rc.0 compiled successfully in 253 ms
```

### What is actually happening?
```
[webpack-cli] Error: Compiling RuleSet failed: Properties generator are unknown (at clonedRuleSet-1: [object Object])
[webpack-cli] TypeError: Cannot read property 'compilers' of undefined
```

---
This is related to the new feature from webpack 5 called Asset Modules (https://webpack.js.org/guides/asset-modules/)

Whenever I add:
```js
...
generator: {
	filename: `images/[name][ext]`,
},
...
```
to a rule, vue-loader fails with the error mentioned above.

**Comment by LinusBorg** [comment]
Seems this new property is missing as the rules set right here: 

https://github.com/vuejs/vue-loader/blob/edd1037742a8b8332c3afae4a83b61e5319e518f/src/pluginWebpack5.ts#L63

**Comment by tianyingchun** [comment]
what's progress of this issue? for `webpack@5.3.0` with `assetModule` configuration.
```
Compiling RuleSet failed: Properties generator are unknown (at ruleSet[0]: [object Object])
```

**Comment by LinusBorg** [comment]
Thanks for the bump, just did 2 PRs, for vue-loader v15 and v16.

**Comment by tianyingchun** [comment]
When will it be released? for v16 alpha

**Comment by tianyingchun** [comment]
This fixed has not been used in v16? i have tried `v16`+ `webpack@5` it throw this error.
https://github.com/vuejs/vue-loader/pull/1754

**Comment by tianyingchun** [comment]
@LinusBorg

**Comment by LinusBorg** [comment]
Which exact Version are you using? It's been parr of the beta.10 release

**Comment by LinusBorg** [comment]
It's back in rc.1

**Comment by tianyingchun** [comment]
thanks, it works fine `vue-loader@16.0.0-rc.1` + `webpack@5.4.0` + `vue-router@4.0.0-rc.1`
