### ISSUE TITLE
sass loading failed: Invalid CSS after "html {": expected "}", was "{"

### ISSUE THREAD

**Issue by aguegu** [vuejs/vue-loader#174]
With a bran-new webpack project created by vue-cli@1.4.0.

If the style section of [App.vue](https://github.com/vuejs-templates/webpack/blob/master/template/src/App.vue#L33) is modified to 

```
<style lang="sass">
```

And then I got `node-sass` and `sass-loader` installed. 

eslint would complain
<img width="1440" alt="screen shot 2016-03-09 at 09 12 22" src="https://cloud.githubusercontent.com/assets/1559791/13622082/338445b8-e5d7-11e5-9184-efae92df375b.png">

I can eliminate this error by making the style section `inline`

<img width="825" alt="screen shot 2016-03-09 at 09 14 12" src="https://cloud.githubusercontent.com/assets/1559791/13622122/842b1d5c-e5d7-11e5-95c0-8ea9a6747e53.png">

According to [this sass issue](https://github.com/sass/sass/issues/450), something may be appended to the style text. So I consider it as a vue-loader issue.

My environment:

<img width="519" alt="screen shot 2016-03-09 at 09 18 52" src="https://cloud.githubusercontent.com/assets/1559791/13622195/075e9898-e5d8-11e5-9cf8-b519d9d60dac.png">
<img width="477" alt="screen shot 2016-03-09 at 09 19 05" src="https://cloud.githubusercontent.com/assets/1559791/13622199/0c868a42-e5d8-11e5-91fd-9b9dc9ea9fc9.png">

**Comment by yyx990803** [comment]
`lang="sass"` uses the indented syntax, if you want the CSS-superset syntax, use `lang="scss"`.

**Comment by aguegu** [comment]
Cool, it fixed. 

This error just popped up on when I upgrade my project templates that generated 2 months ago by vue-cli@1.0.x to the latest. I did not get this error before, so I figured that it could be some updates in vue-loader cause the problem. 

There are lots of updates. Great job. :)

**Comment by baixiaosh** [comment]
您好，我在scss语法里面加rgba写法的颜色，会直接编译报错。不用这个写法就不会报错，正常编译。

**Comment by baixiaosh** [comment]
![image](https://cloud.githubusercontent.com/assets/8230480/20510063/7f38fc14-b0a8-11e6-9823-b1d452a51c49.png)

**Comment by jm-david** [comment]
Replacing `sass` with `scss` fixes the compiling error, but it seems to drop the syntax highlighting :( I'm using https://github.com/vuejs/vue-syntax-highlight with Sublime Text.
<img width="195" alt="screen shot 2016-12-13 at 12 12 08 pm" src="https://cloud.githubusercontent.com/assets/17976057/21124901/733c2c02-c12d-11e6-9f7c-ae09b1b9aed4.png">
<img width="196" alt="screen shot 2016-12-13 at 12 12 17 pm" src="https://cloud.githubusercontent.com/assets/17976057/21124902/733f6386-c12d-11e6-984d-f1733521ae2d.png">
Am I missing something really obvious? Here's a list of all my dependencies for reference:
```
"dependencies": {
  "bootstrap": "^4.0.0-alpha.5",
  "gsap": "^1.19.0",
  "scrollmagic": "^2.0.5",
  "vue": "^2.1.0",
  "vue-router": "^2.0.3"
},
"devDependencies": {
  "autoprefixer": "^6.4.0",
  "babel-core": "^6.0.0",
  "babel-loader": "^6.0.0",
  "babel-plugin-transform-runtime": "^6.0.0",
  "babel-preset-es2015": "^6.0.0",
  "babel-preset-stage-2": "^6.0.0",
  "babel-register": "^6.0.0",
  "chalk": "^1.1.3",
  "connect-history-api-fallback": "^1.1.0",
  "css-loader": "^0.25.0",
  "eventsource-polyfill": "^0.9.6",
  "express": "^4.13.3",
  "extract-text-webpack-plugin": "^1.0.1",
  "file-loader": "^0.9.0",
  "function-bind": "^1.0.2",
  "html-webpack-plugin": "^2.8.1",
  "http-proxy-middleware": "^0.17.2",
  "json-loader": "^0.5.4",
  "node-sass": "^3.13.0",
  "opn": "^4.0.2",
  "ora": "^0.3.0",
  "sass-loader": "^4.0.2",
  "semver": "^5.3.0",
  "shelljs": "^0.7.4",
  "url-loader": "^0.5.7",
  "vue-loader": "^10.0.0",
  "vue-style-loader": "^1.0.0",
  "vue-template-compiler": "^2.1.0",
  "webpack": "^1.13.2",
  "webpack-dev-middleware": "^1.8.3",
  "webpack-hot-middleware": "^2.12.2",
  "webpack-merge": "^0.14.1"
}
```

**Comment by kedcomsci** [comment]
<img width="825" alt="842b1d5c-e5d7-11e5-95c0-8ea9a6747e53" src="https://user-images.githubusercontent.com/23306577/37820267-a9c8d240-2eb2-11e8-9d68-839611e35837.png">

SASS SYNTAX is incorrect. https://sass-lang.com/guide
