### ISSUE TITLE
Vue loader bug with class field

### ISSUE THREAD

**Issue by snigle** [vuejs/vue-loader#1740]
### Version
16.0.0-beta.8

### Reproduction link
[https://github.com/snigle/vue3Webpack](https://github.com/snigle/vue3Webpack)

### Steps to reproduce
Create webpack project from scratch with vue@next and vue-loader@next.
Make project working with simple vue component single file.
Declare a typescript class in the <script lang="ts">
Compilation will fail 

### What is expected?
compilation OK

### What is actually happening?
ERROR in ./src/App.vue?vue&type=template&id=7ba5bd90&bindings=undefined (./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[1]!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[3].use[0]!./src/App.vue?vue&type=template&id=7ba5bd90&bindings=undefined)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
SyntaxError: Unexpected token u in JSON at position 0

---
I put a simple application in my repo to reproduce

**Comment by snigle** [comment]
the code which break is here : 
https://github.com/snigle/vue3Webpack/blob/main/src/App.vue
```typescript
<script lang="ts">
import {defineComponent, ref} from "vue";
// This class break the webpack vue-loader
class Test {
    myTest = "ok"
}
export default defineComponent({
// ...
});
</script>
```

**Comment by sodatea** [comment]
Fixed in beta.9
