### ISSUE TITLE
Referring to javascript variables defined on main page of SPA within loaded components?

### ISSUE THREAD

**Issue by pradia** [vuejs/vue-loader#175]
Hi guys, if we're dynamically loading our components in and out of an SPA, how do we refer to javascript variables we've defined in the "global" scope from within these components?

Example:

- I statically define `let id = 3` in `index.html`. 

- I pull in a Vue component called `Payment` with a combination of vue-loader and vue-router.

- I now want to access `id` from within `Payment's` scope, but simply calling `id` does not work.

Any ideas?

Thanks!

**Comment by yyx990803** [comment]
I don't think `let` defines globals. Try `var` instead.

**Comment by pradia** [comment]
`var` doesn't seem to work either. Any other ideas?

**Comment by yyx990803** [comment]
Closing (outdated)
