### ISSUE TITLE
 vue-loader get can not resolved  after install any loader, I have to reinstall vue-loader

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vue-loader#1755]
### Version
15.9.4

### Reproduction link
[http://nothing.com](http://nothing.com)

### Steps to reproduce
webpack@ 4.44.0 
webpack-cli@4.1.0

vue-loader @15.9.4
"vue-template-compiler": "^2.6.12",

### What is expected?
run successfully

## Vue packages version mismatch:
``` 
- vue@3.0.3 (/Users/wanghongye/Desktop/HomyeeKing/vue/vue3-ui-design/node_modules/vue/index.js)
- vue-template-compiler@2.6.12 (/Users/wanghongye/Desktop/HomyeeKing/vue/vue3-ui-design/node_modules/vue-template-compiler/package.json)
`Cannot read property 'parseComponent' of undefined`

```

**Comment by sodatea** [comment]
Please provide a valid reproduction.

**Comment by HomyeeKing** [comment]
@sodatea  

vue-loader : "^16.0.0-beta.8"
 
```js
const { VueLoaderPlugin } = require('vue-loader-v16');
const { VueLoaderPlugin } = require('vue-loader');
const  VueLoaderPlugin  = require('vue-loader/lib');
const VueLoaderPlugin = require("vue-loader/lib/plugin");
```
I've tried every one ,but always happens error ....

which one is the exact way to import this loader  😫

![image](https://user-images.githubusercontent.com/49113249/97961154-bd944e80-1ded-11eb-8094-d6a247d7ca10.png)

**Comment by sodatea** [comment]
Please please provide a reproduction repo.
I don't even understand what you are trying to achieve here. Are you trying to use vue 3 or vue 2?

**Comment by HomyeeKing** [comment]
> Please please provide a reproduction repo.
> I don't even understand what you are trying to achieve here. Are you trying to use vue 3 or vue 2?

it need webpack command, hard to repo,

in short:
I'm using vue3,
how to import vue-loader correctly and which is the proper version of vue-template-compiler

**Comment by HomyeeKing** [comment]
https://codesandbox.io/s/lively-https-hz0mo?file=/webpack/webpack.dev.config.js  @sodatea 

![image](https://user-images.githubusercontent.com/49113249/97968528-b96e2e00-1df9-11eb-80ce-57c1aec5c555.png)

**Comment by HomyeeKing** [comment]
and everytime I install new loader, the vue-loader get can not be resolved...

**Comment by sodatea** [comment]
Install `vue-loader@next` & `@vue/compiler-sfc`, and uninstall `vue-template-compiler`.

See https://github.com/vuejs/vue-next-webpack-preview for reference.

**Comment by HomyeeKing** [comment]
> @vue/compiler-sfc

excellent!  problem solved
