### ISSUE TITLE
Assets paths are not resolved with webcomponents

### ISSUE THREAD

**Issue by thomasnaudin** [vuejs/vue-loader#1766]
### Version
16.1.1

### Reproduction link
[https://github.com/thomasnaudin/vue-loader-webcomponent](https://github.com/thomasnaudin/vue-loader-webcomponent)

### Steps to reproduce
Just cloning the repo, `npm install`, `npm run dev`.

The relevant details are in `webpack.config.js` :

```javascript
{
    test: /\.vue$/,
    loader: "vue-loader",
    options: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith("sl-"),
      },
    },
 }
```

And in `src/components/MainMenu.vue` :

```html
<sl-avatar image="../assets/images/some-avatar.jpg"></sl-avatar>
```

### What is expected?
The image path should be resolved to the resource managed by Webpack.

### What is actually happening?
Vue loader doesn't resolve the path for the resource (the app tries to load `http://localhost:8080/assets/images/some-avatar.jpg`).

**Comment by thomasnaudin** [comment]
As an alternative, I can import and bind image to the component : 

```typescript
import avatar from "../assets/images/avatar.jpg";

export default defineComponent({
  name: "Menu",
  data() {
    return {
      avatar,
    };
  },
});
```

And

```html
<sl-avatar :image="avatar"></sl-avatar>
```

Works perfectly.

I understand this example is probably not the most relevant, as an avatar would be loaded dynamically, but should static resources be loaded the same way ?

**Comment by LinusBorg** [comment]
https://vue-loader.vuejs.org/options.html#transformasseturls

**Comment by thomasnaudin** [comment]
My bad, I guess I should had RTFM a bit better.
Thanks a lot anyway, for the response and for your great work ;)
