### ISSUE TITLE
能否添加一个是否使用rewriter的配置项？

### ISSUE THREAD

**Issue by lrdbzs** [vuejs/vue-loader#177]
1、有个需求，把所有*.vue中的`<style>[scss内容]</style>`（不需要对scss内容进行postcss执行），单独放到一个文件中；
2、使用了“extract-text-webpack-plugin”
```javascript
vue: {
  loaders: {
     css: extractSCSS.extract('raw')
  }
}
```
但提示说css语法错误
3、目前解决方法是，修改vue-loader源码中的loader.js 103行
```javascript
// loader = ensureBang(loader) + rewriter
loader = ensureBang(loader)
```

**Comment by yyx990803** [comment]
使用方法有误吧，这为什么和 style rewriter 有关系？
抽取请参照文档：http://vuejs.github.io/vue-loader/configurations/extract-css.html
