### ISSUE TITLE
Pure JS version?

### ISSUE THREAD

**Issue by TJKoury** [vuejs/vue-loader#178]
I'm using vue-loader for a project; it's great, but I'm trying to make my code as isomorphic as possible.

I'd like an option to specify a .vue file that is valid ECMA6 using template literals, something like:

```javascript

export  template = 
`<h1>
  <p>Title</p>
</h1>`;
export component {
  components:{},
  data() {
    return {
      msg: 'msg'
    }
  }
}
export style = 
`<style>

  h1{
   font-size:-webkit-xxx-large !important
 }

</style>`;

```
I'll gladly work on a pull request if this is a feature you'd consider.

**Comment by rogue780** [comment]
I was just looking to do something similar on an unrelated project. This would be very useful.

**Comment by yyx990803** [comment]
If you just want pure js why use `vue-loader`? You can just do this:

``` js
import insertCSS from 'insert-css'
insertCss(`
h1{
   font-size:-webkit-xxx-large !important
 }
`)

export default {
  template:
    `<h1>
      <p>Title</p>
    </h1>`,
  data() {
    return {
      msg: 'msg'
    }
  }
}
```

`vue-loader`'s parsing logic is based on parse5 and assumes the input is valid HTML. I don't think it's worth it to introduce a completely different format in the same loader - it's probably better to live as a separate loader instead. That said, I don't think I have the time to implement it, but feel free to implement one yourself!

**Comment by TJKoury** [comment]
Great suggestions, thanks for taking the time to address the issue.
