### ISSUE TITLE
Fix 'css-loader' uses in documentation

### ISSUE THREAD

**Issue by joaohaas** [vuejs/vue-loader#1785]
### What problem does this feature solve?
Not exactly a feature request, but also not a bug.

Currently `<style>` tags do not work if following any of the documentation examples. This is due to the fact that `vue-style-loader` does not support `css-loader` 4.x.x or 5.x.x (https://github.com/vuejs/vue-style-loader/issues/50, https://github.com/vuejs/vue-style-loader/issues/46).

### What does the proposed API look like?
 It seems it can easily be fixed by disabling `esModule`:

```js
{
    loader: 'css-loader',
    options: {
        esModule: false
    }
}
```

I can open a PR to fix these issues, but I'm not sure if that's wanted, since it's a issue with `vue-style-loader`, and it adds a bit of complexity to new users. At the same time, the current examples are not working at all, and `vue-style-loader` repo's last commit was in 2018... so not sure if those issues are going to be fixed.

EDIT: We can also change the `npm install ...` lines to install `css-loader@3`, and add an explanation on why you need to use an older version.

**Comment by fredgan** [comment]
Sounds good. Why not open a PR to record it the docs. ^_^

**Comment by euoia** [comment]
This also caught me out!

**Comment by sodatea** [comment]
ES module interop added in `vue-style-loader` 4.1.3. So I'm closing this issue.
