### ISSUE TITLE
.vue files trigger watch but not hot reload

### ISSUE THREAD

**Issue by chris-schmitz** [vuejs/vue-loader#179]
I'm running into an issue while using the webpack-dev-server to hot swap components where changes to `.vue` files will trigger the webpack watch but not the hot swap. 

![vuefilesnothotreloading](https://cloud.githubusercontent.com/assets/2437424/13899743/4b5200b0-edc3-11e5-8c60-9d3fea10bd4f.gif)

_Note that in the gif above, I'm having to manually refresh the browser to get the changes to the `.vue` file to show. I just wanted to show that the file that I'm editing in the text editor definitely is the one being referenced in the browser._

[Here's a repository with my setup that reproduces the issue](https://github.com/chris-schmitz/VueLoaderNotHotReloading).

When I make changes to the `.js` files the dev server will do the hot swap as normal, but the vue-loader will not. 

I double checked my `package.json` file and `node_modules` directory and the `vue-hot-reload-api` is definitely installed: 

![screen shot 2016-03-19 at 11 14 11 am](https://cloud.githubusercontent.com/assets/2437424/13899760/cfee094a-edc3-11e5-9346-0765cb3d1575.png)

I've also compared against [the vue-loader's documentation example](http://vuejs.github.io/vue-loader/start/tutorial.html) and it looks like I did everything that should trigger the reload. 

All of that said, I am still learning webpack and this is my first brush using the vue-loader instead of vueify via browserify, so there is a chance I could have missed something. 

Thanks!

**Comment by yyx990803** [comment]
Hot reload preserves current state, so editing data (which is the initial state) has no effect.

**Comment by chris-schmitz** [comment]
Ah ok that makes sense. I'll take that into consideration while building the app. Thanks for pointing that out.
