### ISSUE TITLE
Recursive component becomes Fragment Instance

### ISSUE THREAD

**Issue by thgh** [vuejs/vue-loader#180]
Test case:
https://github.com/thgh/vuejs-recursive-bug/blob/master/src/components/CompA.vue

Expected: A > B > A > B > A

    A1
    B11
    A111
    B1111
    A11111

Actual: A > A

    A1

And console warns
`Attribute`` ":level" is ignored on component <comp-a> because the component is a fragment instance: `

**Comment by hjkcai** [comment]
Have you solved this problem? I have encountered the same problem. The `this.$options.components` trick doesn't seem to work.

**Comment by thgh** [comment]
Yes, you must declare at least one of the components globally with `Vue.component('CompA', CompA)`. That one will be available everywhere.

The reason for this "bug" is just how javascript works: the components are initialized one by one and you can only reference initialized components. Solution is to add components afterwards:
https://github.com/vuejs/vue/issues/2519

**Comment by simplesmiler** [comment]
Another solution is to use async components:
``` js
var A = {
  components: {
    B: function() { return B; },
  },
};

var B = {
  components: {
    A: function() { return A; },
  },
};
```
