### ISSUE TITLE
vue3 使用vue-loader16 编译自定义指令无效

### ISSUE THREAD

**Issue by zhaowenlin** [vuejs/vue-loader#1815]
### Version
16.1.2

### Reproduction link
[https://codepen.io/zhaowenlin-the-selector/pen/PoWPeWX](https://codepen.io/zhaowenlin-the-selector/pen/PoWPeWX)

### Steps to reproduce
vue create vue3-demo
选择vue3 
touch vue.config.js
然后在chainWebpack里加入链接中的配置

### What is expected?
在tap里修改了options能传到到对应的逻辑里

### What is actually happening?
修改了options过后没有按照预期执行逻辑

**Comment by zhaowenlin** [comment]
vue create vue3-demo
选择vue2
touch vue.config.js
然后在chainWebpack里加入链接中的配置
vue2这样是没有问题的

**Comment by zhaowenlin** [comment]
vue create vue2-demo
选择vue2
touch vue.config.js
然后在chainWebpack里加入链接中的配置
vue2这样是没有问题的

**Comment by sodatea** [comment]
Vue 2 和 Vue 3 的 compilerOptions 不一样。
Vue 3 编译用的 compiler-sfc，可用的选项参见 https://github.com/vuejs/vue-next/blob/master/packages/compiler-core/src/options.ts
