### ISSUE TITLE
How to compile vue2 file and vue3 file

### ISSUE THREAD

**Issue by BlackCubeNo99** [vuejs/vue-loader#1817]
### Version
16.1.2

### Steps to reproduce
I installed `vue-loader`、`vue-template-compiler`、`@vue/compiler-sfc`、`vue2`、`vue3`

```json
// package.json
"devDependencies": {
  "vue-loader": "16.1.2",
  "vue-template-compiler": "2.6.12",
  "@vue/compiler-sfc": "3.0.7"
},
"dependencies": {
  "vue": "2.6.12",
  "vue3": "npm:vue@3.0.7"
}
```

How to set vue2 and vue3 config ?

```javascript
// webpack.config.js
module.exports = {
  entry: ['a.js', 'b.ts'],
  resolve: {
    alias: {}
  }
}
```

a.js use vue2
```javascript
// a.js
import Vue from 'vue'
import App from './App.vue'

new Vue({
  el: '#app',
  render: h => h(App)
})
```

b.ts use vue3
```typescript
// b.ts
import { createApp } from 'vue3'
import App from './App.vue'

createApp(App).mount('#app')
```

### What is expected?
compile Vue2 and Vue3 at the same time

### What is actually happening?
Cannot compile Vue2 and Vue3 at the same time

**Comment by privatenumber** [comment]
AFAIK this isn't possible and something I'd like as well, especially for a smooth migration path.

I made [vue-2-3](https://github.com/privatenumber/vue-2-3/) to make migration easy, but this is one of the remaining problems that make it hard to do it in one build.
