### ISSUE TITLE
A prop naming 'disabled' will be parsed into disabled=disabled

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-loader#182]
That brings a problem that I have to use my component like this:

``` html
<my-component :disabled=true></my-component>
```

instead of:

``` html
<my-component disabled></my-component>
```

The problem comes from  the dependency: `html-minifier`

https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L84

So anyway to fix this or do I have to use another prop name?

----

Another problem, the disabled prop is defined like this:

``` js
{
 type: Boolean,
 default: false
}
```

So even the raw value is "disabled", it should be coerced to `True`?

**Comment by yyx990803** [comment]
This is now fixed in Vue core: https://github.com/vuejs/vue/commit/c915cf424ae42be6d83d65f9c1330d9e6fbfbb3d

**Comment by airyland** [comment]
Cool. :+1:
