### ISSUE TITLE
在.vue文件中写less样式编译后背景图片超过url-loader配置大小的路径找不到图片无法显示

### ISSUE THREAD

**Issue by zhipenglin** [vuejs/vue-loader#183]
把less文件在script里面import进来使用less loader编译就无此问题了，猜测是vue-loader的问题

**Comment by yyx990803** [comment]
无法重现，请确定是 vue-loader 的问题给出基本定位和详细重现。

**Comment by zhipenglin** [comment]
每次都能重现啊，比如：
.vue文件中这样定义
<style lang="less">
    .page.task{
        .head{
            height: 110em/16;
            background-image: url('../../images/index_icon.png');
        }
    }
</style>
编译后图片不显示，生成图片名669fc052c8b0e90a5cf8c8cfcc1a53ee.png，在编译后的文件中找到改图片function(e,t,i){e.exports=i.p+"669fc052c8b0e90a5cf8c8cfcc1a53ee.png"}，不明白前面的i.p是什么
在浏览器中 新的页面浏览该图片，图片地址为chrome-devtools://devtools/bundled/669fc052c8b0e90a5cf8c8cfcc1a53ee.png，无法打开此图片
将以上代码单独放到.less文件中在.vue文件的script标签里面import './style/lucky.less'这样引用通过less-loader编译，则能正常显示图片
群里有其他同学也遇到过该问题

**Comment by yyx990803** [comment]
『重现』的意思是让你给出可以直接跑起来重现你描述的 bug 的代码。我按你说的不能重现，说明问题出在其他地方。
