### ISSUE TITLE
Syntax Error: TypeError: this.getOptions is not a function with sass-loader v11

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/vue-loader#1831]
### Reproduction link
[https://github.com/Oleksii14/vue-v2.6.12-sass-loader-v11](https://github.com/Oleksii14/vue-v2.6.12-sass-loader-v11)

### Steps to reproduce
run the project, see the error in the console

### What is expected?
Vue v2 supports new versions of sass-loader

### What is actually happening?
vue v2.6.12 does not work with sass-loader v11

**Comment by sodatea** [comment]
sass-loader v11 dropped support for webpack 4. So please either use sass-loader v10 or upgrade to Vue CLI v5 beta

**Comment by nimpossible** [comment]
> sass-loader v11 dropped support for webpack 4. So please either use sass-loader v10 or upgrade to Vue CLI v5 beta

Created a new issue here as the error still persists with cli v5: https://github.com/vuejs/vue-loader/issues/1905
