### ISSUE TITLE
vue-loader resulting a error on webpack runtime

### ISSUE THREAD

**Issue by taoche** [vuejs/vue-loader#184]
I use vue-cli generate a project using Object.assign when an error has occurred ..

```
ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/assign' in /Users/Documents/project/src/components
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue 7:14-60
```
When I put vue-loader version 8.0.0 fall back to normal when you can work.

I guess this should be a question of vue-loader

node -v  4.2.1                                                                                                                                                                                         
npm -v   2.14.7                                                                                                                                                                                             

```
project@0.1.0 /Users/taowei/Documents/project
├── babel-core@6.7.4
├── babel-loader@6.2.4
├── babel-plugin-transform-runtime@6.6.0
├── babel-preset-es2015@6.6.0
├── babel-preset-stage-2@6.5.0
├── babel-runtime@5.8.38
├── chromedriver@2.21.2
├── connect-history-api-fallback@1.2.0
├── cross-spawn@2.1.5
├── css-loader@0.23.1
├── eslint@2.4.0
├── eslint-config-standard@5.1.0
├── eslint-friendly-formatter@1.2.2
├── eslint-loader@1.3.0
├── eslint-plugin-html@1.4.0
├── eslint-plugin-promise@1.1.0
├── eslint-plugin-standard@1.3.2
├── eventsource-polyfill@0.9.6
├── express@4.13.4
├── extract-text-webpack-plugin@1.0.1
├── file-loader@0.8.5
├── function-bind@1.1.0
├── html-webpack-plugin@2.14.0
├── http-proxy-middleware@0.12.0
├── inject-loader@2.0.1
├── isparta-loader@2.0.0
├── jasmine-core@2.4.1
├── json-loader@0.5.4
├── karma@0.13.22
├── karma-coverage@0.5.5
├── karma-jasmine@0.3.8
├── karma-phantomjs-launcher@1.0.0
├── karma-sourcemap-loader@0.3.7
├── karma-spec-reporter@0.0.24
├── karma-webpack@1.7.0
├── nightwatch@0.8.18
├── ora@0.2.0
├── phantomjs-prebuilt@2.1.6
├── selenium-server@2.53.0
├── shelljs@0.6.0
├── url-loader@0.5.7
├── vue@1.0.18
├── vue-hot-reload-api@1.3.2
├── vue-html-loader@1.2.0
├── vue-loader@8.0.0
├── vue-style-loader@1.0.0
├── webpack@1.12.14
├── webpack-dev-middleware@1.5.1
├── webpack-hot-middleware@2.10.0
└── webpack-merge@0.8.4

```

**Comment by yyx990803** [comment]
I can't reproduce this...

**Comment by taoche** [comment]
I'm on my computer or my company's computers are experiencing this problem。
I switched multiple versions for node and npm,  are experiencing this problem

I will be in a more pristine environment to test this issue
Thank you for your reply

**Comment by taoche** [comment]
I try again to solve this problem, I repeat these operations on a new computer, but it is still not resolved...

At the same time I discovered a phenomenon..

i'm run npm install and npm run dev ... show this error

```
ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/assign' in /Users/tao/testzone/test/src/components
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue 7:14-60
```

When I run npm rm vue-loader  && npm install vue-loader@8.0.0...  then do not have this problem
carry on... i run run npm rm vue-loader  && npm install vue-loader@8.2.1, the same is not the problem

i guess is not what's missing some modules

OS  Mac OS X
node -v 4.2.1
npm -v 2.14.7

**Comment by yyx990803** [comment]
Hmmm looks like this is because you are using npm2 so `babel-runtime` is not present...

**Comment by yyx990803** [comment]
Just do `npm install babel-runtime` and it should work. Or upgrade to npm3.

**Comment by yyx990803** [comment]
Are you sure you have `babel-runtime` installed?

**Comment by taoche** [comment]
I'm sorry, I've just been doing npm3
I just updated to 8.2.2 version This issue has been resolved.
Thank you fix this problem

**Comment by taoche** [comment]
before I tried to use npm3... like to have this problem....

But now it has been resolved

**Comment by yanlee26** [comment]
ERROR in ./~/.6.2.5@babel-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue
Module not found: Error: Cannot resolve module 'style.css' in C:\Users\立\Desktop\myapp\src\components
 @ ./~/.6.2.5@babel-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue 7:0-20

**Comment by yanlee26** [comment]
help,please!! I have no idea what is wrong

**Comment by andrietri** [comment]
how to solve your problem @taoche ?

**Comment by janat08** [comment]
installing babel runtime or if npm3 is npm version 3.x.x than update npm.

**Comment by HienNguyen711** [comment]
@janat08 thanks, this works for me 😸

**Comment by chisumo2016** [comment]
For some reason I can't import .vue files on a completly fresh vue init webpack-simple folder.
I can run npm run dev initially, but as soon as I try to import a .vue component, this error occurrs:


./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve './components/Header.vue' in 'C:\laragon\www\vue-tutorials\vue-cli-tutorial\vuejs-router-vue-router\src'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 16:0-45
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./src/main.js

**Comment by DeekshaPandit** [comment]
@chisumo2016 , Did you get your issue solved?, I am also facing the same issue.

**Comment by nanijiayou** [comment]
It's work
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: {
              loaders: {
                js: {
                  loader: 'babel-loader',
                  options: {
                    presets: [
                      '@babel/preset-env',
                      ['@babel/preset-stage-0', { "decoratorsLegacy": true }],
                      '@babel/preset-react',
                      '@babel/preset-es2015',
                    ]
                  }
                },
              }
            }
          }
        ]
      },

**Comment by nanijiayou** [comment]
It's work

**Comment by nanijiayou** [comment]
it's wrok
`      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: {
              loaders: {
                js: {
                  loader: 'babel-loader',
                  options: {
                    presets: [
                      '@babel/preset-env',
                      ['@babel/preset-stage-0', { "decoratorsLegacy": true }],
                      '@babel/preset-react',
                      '@babel/preset-es2015',
                    ]
                  }
                },
              }
            }
          }
        ]
      },`

**Comment by jpcmf** [comment]
I'm getting this error in Netlify. Anyone solved it?

**Comment by jhonatanfaber** [comment]
I also have the same problem :(

**Comment by abduallahnoorsayket** [comment]
I also have the same problem :(

**Comment by savcisa** [comment]
Folks, I also have the same problem  🔢

**Comment by serriam** [comment]
I also have the same problem with @chisumo2016

**Comment by Emanhusseinn** [comment]
i have the same problem none of the above answers worked
