### ISSUE TITLE
Recursive loop while compiling SFC containing <script> tag? (16.2.0)

### ISSUE THREAD

**Issue by ryno1234** [vuejs/vue-loader#1843]
### Version
16.1.2

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPHNjcmlwdCB0eXBlPVwidGV4dC90ZW1wbGF0ZVwiPlxuICBcdHNkZiAgXG4gIDwvc2NyaXB0PiBcbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPHNjcmlwdCB0eXBlPVwidGV4dC90ZW1wbGF0ZVwiPlxuICBcdHNkZiAgXG4gIDwvc2NyaXB0PiBcbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=)

### Steps to reproduce
Include a script tag within a `<template></template>` section of a .vue file eg:

```
<template>
    <script>
        any content at all
    </script>
</template>
```

In my actual scenario, I'm trying to use this:

```
<template>
    <script id="some-id" type="text/template">
        <div>
                My html content
        </div>
    </script>
</template>
```

### What is expected?
The exact markup output to the component

### What is actually happening?
Webpack loader gets stuck spinning during compiling:

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./dist
i ｢wdm｣: wait until bundle finished: /

(above waits forever)

---
The SFC playground shows an output message complaining about the actual issue:

(3:3) Tags with side effect (<script> and <style>) are ignored in client component templates.

```

1  |  <template>
2  |    <h1>{{ msg }}</h1>
3  |    <script type="text/template">
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4  |    	sdf  
   |  ^^^^^^^^
5  |    </script> 
   |  ^^^^^^^^^^^

```

However, when running Webpack with vue-loader and attempting to do a compile, the compilation step gets hung up.

**Comment by sodatea** [comment]
Can't reproduce. The error is correctly thrown in Vue CLI. Please check your webpack configuration.
