### ISSUE TITLE
Any block elements in <label></label> is removed when after building

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-loader#185]
The problem is brought by `html-minifier`, again. It treats `label` as an inline element and removes any block elements inside it.

But everything is fine when running `npm run dev`

So I wonder is that necessary to use `html-minifier`? 
And can I disable it?

**Comment by phanan** [comment]
What `html-minifier` is doing is correct to W3C specs, that is, inline elements may contain only data and other inline elements. I'd suggest not to disable `html-minifier` or find a way to work around the problem, but fix the root of the cause – for example, use `span` instead of `div` inside your `label`.

**Comment by airyland** [comment]
@phanan 

If `html-minifier` is necessay, why not enable it in developing env?  So I may know the issue before building and publishing.

Label is a special element can provide better interaction for a form element.

And anything inline element can also displays like a `block` element when setting `display` to 'block'.

**Comment by phanan** [comment]
> If `html-minifier` is necessay, why not enable it in developing env?

Because it doesn't help much if your HTML is minified into a bunch of unreadable characters during development, no?

> And any inline element can also displays like a `block` element when setting `display` to `block`.

Amen to that, hence my point of using `span` earlier.

**Comment by airyland** [comment]
Because of this issue, my project has a bug that can't show anything inside the label but I didn't know, so yes, I think it helps a lot.

It's too strict as most browsers also allow this.

**Comment by azamat-sharapov** [comment]
@airyland that was html-minifier bug, that bite me couple of days ago. It is fixed now, update to v1.3.1.

**Comment by airyland** [comment]
@azamat-sharapov 

Thx, I found the commit https://github.com/kangax/html-minifier/commit/d767ac9c205f21af53db07a0b708efa1178c238d#diff-6041927ff3475da14e6a01e7dfdad8a9R1235

But @yyx990803 @phanan  will you fix that?

**Comment by azamat-sharapov** [comment]
@airyland it's not vue-loader problem, leave them alone :smile: 
Just do: `npm install html-minifier` (or `npm update html-minifier` if that doesn't work). You could also add it in package.json with latest version and run `npm install`.

**Comment by azamat-sharapov** [comment]
Here you get more info: https://github.com/kangax/html-minifier/issues/565

**Comment by airyland** [comment]
@azamat-sharapov
 vue-html-plugin depends on `html-minifier`

**Comment by azamat-sharapov** [comment]
[Yeah, I know, that vue-html uses html-minifier version 1 and **up**](https://github.com/vuejs/vue-html-loader/blob/master/package.json#L9). Did you try `npm uninstall vue-html --save-dev && npm install vue-html --save-dev`

**Comment by airyland** [comment]
@azamat-sharapov Thx, the problem is fixed at the moment.
