### ISSUE TITLE
Vue-loader used together with TS-Loader

### ISSUE THREAD

**Issue by LongJinCen** [vuejs/vue-loader#1857]
### Version
15.9.6

### Reproduction link
[https://github.com/LongJinCen/vue-loader-error-demo](https://github.com/LongJinCen/vue-loader-error-demo)

### Steps to reproduce
1. git clone https://github.com/LongJinCen/vue-loader-error-demo
2. npm i
3. npm run dev
4. Edit a file and save it, wait for the compile to complete, and then you'll see errors

### What is expected?
without any errror

### What is actually happening?
The first time I compiled it, there were no errors, and when I saved the file and compiled it the second time, An error was reported:
```
Cannot find module '!../../node_modules/vue-loader/lib/runtime/componentNormalizer.js' or its corresponding type declarations
```
However, I found that this file actually exists under vue-loader

---
webapck config：
```
{
        test: /\.ts$/,
        use: [
          'babel-loader',
          {
            loader: 'ts-loader',
            options: {
              appendTsSuffixTo: [/\.vue$/], 
            }
          }
        ],
        exclude: /node_modules/
      },
      {
        test: /\.tsx$/,
        use: [
          'babel-loader',
          {
            loader: 'ts-loader',
            options: {
              appendTsxSuffixTo: [/\.vue$/],
            }
          }
        ],
        exclude: /node_modules/
      }
```
tsConfig.json：
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "jsx": "preserve",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "*": ["./src/types/*"],
      "Src/*": ["./src/*"],
    },
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "traceResolution": false
  }
}
```
version：
```
"webpack": "^5.46.0"
"vue": "^2.6.14"
"ts-loader": "^9.2.4"
"vue-loader": "^15.9.6"
```

**Comment by mokone91** [comment]
faced with same problem, solved by moving type check to ForkTsCheckerWebpackPlugin

**Comment by LongJinCen** [comment]
> faced with same problem, solved by moving type check to ForkTsCheckerWebpackPlugin in dev mode

Thank you very much. I solved the problem the way you said
