### ISSUE TITLE
How to include other template in template

### ISSUE THREAD

**Issue by lilijialiang** [vuejs/vue-loader#186]
i want to  include other template in template,  but it can not work

```html
<template>
        <div>hello</div>
        <template src="./base.html"></template>
        <div>world</div>
</template>
```

**Comment by yyx990803** [comment]
This is not supported. Just use components or partials.

**Comment by wisetc** [comment]
Now <https://vuejs.org/v2/guide/render-function.html#Functional-Components>

**Comment by yuanyazhen** [comment]
> This is not supported. Just use components or partials.

Is any methods to pass upper's instances to the child components? Maybe like the blow
