### ISSUE TITLE
dev is ok, but build failed

### ISSUE THREAD

**Issue by liujb** [vuejs/vue-loader#188]
ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/littleboy/HomePage.vue
Module build failed:
 @ ./src/components/littleboy/HomePage.vue 4:19-135

**Comment by taoche** [comment]
I hope you can provide more information and convenience to find the bug
For example, homePage content
I guess the problem among the template syntax

**Comment by sagarjauhari** [comment]
Getting the same error

**Comment by sagarjauhari** [comment]
How can I know at what line of the template the error is?

**Comment by fabdrol** [comment]
This issue is a duplicate of https://github.com/vuejs/vue-loader/issues/154

**Comment by liujb** [comment]
@taoche Thanks for your remainder. Template file `HomePage.vue` have an extra  `<`.

**Comment by liujb** [comment]
@sagarjauhari Have you solved this problem. I `HomePage.vue` have extra `>`.

**Comment by liujb** [comment]
@fabdrol Thanks
