### ISSUE TITLE
Make vue-loader "framework agnostic"

### ISSUE THREAD

**Issue by QuentinFchx** [vuejs/vue-loader#189]
vue-loader is a super cool idea, I used it a lot when trying vue for the first time.

Now that I'm working on an angular2 project, I tried to have something similar. I ended up with a fork of vue-loader, [ng2-loader](https://github.com/QuentinFchx/ng2-loader) (this is still **work in progress**).

Given the few modifications I had to make, don't you think if it would be great to have a generic loader, and "plugins" for different usecases (vue/angular/...), especially around template/style injection ?

**Comment by yyx990803** [comment]
I like the idea, but it is relatively easy to adapt for Angular 2 because the component model is similar. I'm not sure how applicable it is to other frameworks.

I don't think that's part of the scope for `vue-loader` - feel free to fork and create it though.
