### ISSUE TITLE
想通过babel修改template编译后的render函数

### ISSUE THREAD

**Issue by wulinsheng123** [vuejs/vue-loader#1898]
### Version
16.8.3

### Reproduction link
[github.com](https://github.com/wulinsheng123/vue/blob/main/src/App.vue)

### Steps to reproduce
npm run serve

### What is expected?
需要通过babel修改template编译后的render函数，通过webpack的buildModule钩子拦截住render函数，然后通过babel修改render函数

### What is actually happening?
希望babel编译后的render函数能够替换webpack的source

---
公司内部有2个ui框架elementUI和Ivivew，现在希望通过编译将elementUI转义为Iview UI框架。现在想法是通过拦截到render函数，然后通过babel编译，将ELementUI 转为IviewUI。只能通过webpack hook去拦截vue的render函数，但是vue生产的render时间比较特别，我想修改这个render就会报错
之前已经留言给了webpack，但是webpack觉得应该问vue-loader开发 ,

https://github.com/webpack/webpack-sources/issues/141

**Comment by sodatea** [comment]
不一定非要在 webpack 体系里做。可以考虑参考 https://github.com/JuniorTour/vue-template-babel-compiler，替换掉 vue-template-compiler

**Comment by wulinsheng123** [comment]
> 不一定非要在 webpack 体系里做。 可以考虑参考 https://github.com/JuniorTour/vue-template-babel-compiler 替换掉 vue-template-compiler

谢谢

**Comment by pekonchan** [comment]
@wulinsheng123 你好。 请教下，如何可以拦截到vue文件里的template转换为render js代码这部分。我想用一个loader再去转译这部分。

以前在v14版中的，还是使用postLoaders来配置，现在这个配置项废弃了，想不到什么办法可以做到类似的

**Comment by wulinsheng123** [comment]
> @wulinsheng123 你好。 请教下，如何可以拦截到vue文件里的template转换为render js代码这部分。我想用一个loader再去转译这部分。
> 
> 以前在v14版中的，还是使用postLoaders来配置，现在这个配置项废弃了，想不到什么办法可以做到类似的

https://github.com/wulinsheng123/elementTransform
看看这个？希望有所帮助，具体怎么做的我给忘了

**Comment by pekonchan** [comment]
> > @wulinsheng123 你好。 请教下，如何可以拦截到vue文件里的template转换为render js代码这部分。我想用一个loader再去转译这部分。
> > 以前在v14版中的，还是使用postLoaders来配置，现在这个配置项废弃了，想不到什么办法可以做到类似的
> 
> https://github.com/wulinsheng123/elementTransform 看看这个？希望有所帮助，具体怎么做的我给忘了

十分感谢，看了有点思路了。
