### ISSUE TITLE
Nested routes cannot work correctly with webpack + vue-loader+vue-router

### ISSUE THREAD

**Issue by DanielZhu** [vuejs/vue-loader#19]
Hi

I take this repo(https://github.com/OpenSISE/game-app) as the example to build up my new website.
But I found that when I try to setup the nested routes, it cannot render the template.
eg:
  ```
'/user': {
      // component: require('./views/user.vue'),
      subRoutes: {
        '/register': {
            component: require('./views/user/register.vue')
        },
        '/login': {
            component: require('./views/user/login.vue')
        }
}```
But if I define a new route like ```    
'/test/register': {
     component: require('./views/user/register.vue')
 }```
it can work and render this nested page.

It's my first time using Vuejs. Thanks.

**Comment by azamat-sharapov** [comment]
You use subRoutes, when a route has another `<router-view>` in it. So, in user component's template, add: `<router-view>` and then sub routes will manipulate with it.

**Comment by DanielZhu** [comment]
@azamat-sharapov Many thanks. I was wondering why the content of user.vue always show up before. Currently, I understand.
