### ISSUE TITLE
Syntax Error: TypeError: this.getOptions is not a function with sass-loader v12.x!

### ISSUE THREAD

**Issue by nimpossible** [vuejs/vue-loader#1906]
### Version
16.8.3

### Reproduction link
[github.com](https://github.com/vuejs/vue-loader/issues/1905)

### Steps to reproduce
Details here...
https://github.com/vuejs/vue-loader/issues/1905

### What is expected?
It must work fine!

### What is actually happening?
Not working!

---
Not sure why the robot closed the issue on GIT automatically.

**Comment by LinusBorg** [comment]
You need to update the `@vue/cli-* ` packages to 5.0 in your project, not just the global package which generates new projects.
