### ISSUE TITLE
Unhandled jade error

### ISSUE THREAD

**Issue by KuroGuo** [vuejs/vue-loader#192]
![image](https://cloud.githubusercontent.com/assets/8684548/14133881/7a84413e-f685-11e5-900f-bcbcbc6a423e.png)

**Comment by dajnz** [comment]
Try to split attributes in your jade file by commas instead of spaces. In [jade docs](http://jade-lang.com/reference/attributes/) you can see examples with comma separated attributes. This works fine for me, when I use terse directive format for **v-bind**.

**Comment by yyx990803** [comment]
Yep, always split attrs with commas. when using shorthand.
