### ISSUE TITLE
Final entrypoint contains const 

### ISSUE THREAD

**Issue by Earlopain** [vuejs/vue-loader#1963]
### Version
16.8.3

### Reproduction link
[https://github.com/](https://github.com)

### Steps to reproduce
I'm using babel to transpile my code down to es5. This code is introducing const into my final application bundle.

https://github.com/vuejs/vue-loader/blob/6a293dff5f2ed3167eb3b448f1d714091185a44e/src/index.ts#L280-L287 
I understand that Vue 3 has dropped support for older browsers, but I would like for the non-vue parts of the code to still work. As it stands now Safari 9 can't parse the result because the js contains const.

I couldn't figure out how to make babel also transpile this piece of code, I imagine it doesn't since vue-loader runs somewhere after babel-loader. Prior to [this commit](https://github.com/vuejs/vue-loader/commit/bacc6a9eeca40d6028a2d9a5f6ee02e6c8574abd) it would have worked fine, but for now I have made a fork which replaces those consts. Any help on how to solve this properly is appreciated.

### What is expected?
The resulting babel bundle does not contain const.

### What is actually happening?
The resulting babel bundle does contain const.

**Comment by yyx990803** [comment]
I don't understand this. v16+ only works with Vue 3, so the bundle will not work in any browser that does not support `const`. How can vue-loader generated code be "non-vue" when it can only be used for Vue 3?

**Comment by Earlopain** [comment]
I might have worded that a bit unfortunate, my bad. The project has many pages, but only two actually are using vue. It's clear that those two vue pages will only work in browsers that are actually supported by vue.

But since it's all one bundle the rest of the pages which are in theory vue-free are broken in browsers that are unable to parse the resulting bundle because of const. The result is that instead of only the vue pages not working, everything is broken.

The solution would be to split the code up into multiple bundles, but this is unfortunately pretty involved, just replacing const with var like I did in my fork was the more painless solution.

I hope this makes more sense.

**Comment by Earlopain** [comment]
Enough time has passed that I don't consider this a problem anymore. I accidentally introduced const through some other dependency and complains about that were minimal. The fork I have been using until now is available under https://github.com/e621ng/vue-loader. I won't be updating that anymore, though the actual change is only two lines so easily doable yourself if someone actually still needs that.
