### ISSUE TITLE
EJS templates don't work?

### ISSUE THREAD

**Issue by taoeffect** [vuejs/vue-loader#197]
So... having looked at the docs it seems that the thing that gets stuffed into `lang` for templates is not a webpack loader, which is cool because I'm currently using browserify.

However, after doing `npm install ejs --save-dev`, and then trying it out, this doesn't work:

```vue
<!-- File: App.vue -->

<template lang="ejs">
  <div><%- include views/included %></div>
<template>
```

There's no error message or anything. The file gets rendered, but `<%- include views/included %>` is displayed as a literal.

Relevant folder hierarchy looks like this from the root of the project:

```
frontend/
+ simple/
|-- App.vue
|-+ views/
  |-- included.ejs
```

**Comment by yyx990803** [comment]
You are using `vueify` right? It handles things differently from `vue-loader`... you should look at the docs over there (registering custom compilers)
