### ISSUE TITLE
Can't find module vue-template-compiler

### ISSUE THREAD

**Issue by Adventuroa** [vuejs/vue-loader#1976]
## Version
[15.10.0](https://www.npmjs.com/package/vue-loader)

## Situation

I update the vue-loader@15.10.0 and dev my project.
It throws an error: `can't find module vue-template-compiler`
Then I try  to figure out the reason. I found in vue-loader@15.10.0, change the logic of loading modules `vue-template-loader`.

In previous versions，vue-loader load the modules `vue-template-compiler` just by using require
However, I found in 15.10.0, vue-loader import `vue-template-compiler` specifies the context(the project root)

![image](https://user-images.githubusercontent.com/108782850/177476703-84638877-82a2-4e87-ac94-486f67970693.png)

![image](https://user-images.githubusercontent.com/108782850/177476590-2028b0c9-a3c1-4e24-8af7-b9aebbdd9255.png)

In my case, the `vue-loader` and `vue-template-compiler` are not install in project.  The `vue-loader` and `vue-template-compiler` installed in User directory. When execute the command we will load the user directory then dev/build the project. 

So I have two doubts. I would be grateful if you could give me an answer

1. Why when load the `vue-template-compiler` specifies the ctx ?
2. Is there any possibility when load the `vue-template-compiler` not specifies the ctx ? (just require like before)

> My English are not so good! So please

Thanks for your reading !

**Comment by lizy-CZ** [comment]
[15.10.0](https://www.npmjs.com/package/vue-loader) version for vue 2.7 specifily
