### ISSUE TITLE
Cannot read properties of undefined (reading 'styles')    

### ISSUE THREAD

**Issue by danielmlc** [vuejs/vue-loader#1987]
在vue3项目中使用webpack5打包引入的问题

Module build failed (from ../../node_modules/.pnpm/vue-loader@17.0.0/node_modules/vue-loadees/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (E:\project\webpack\new\webpages-packer\node_modules\.pnpm\vue-loader@\vue-loader@17.0.0\node_modules\vue-loader\dist\index.js:70:34)
 @ ./modules/login/index.ts 1:0-28 2:24-27

**Comment by JanMalte** [comment]
@danielmlc do you use VueJS v2? If you do so, you need to stick with `vue-loader<=15`

Maybe this issue helpful for you: https://github.com/vuejs/vue-loader/issues/1973#issuecomment-1183982271
