### ISSUE TITLE
main.js Parsing error: Illegal import declaration

### ISSUE THREAD

**Issue by bulldog478** [vuejs/vue-loader#199]
i try to build the vue-loader-example, but a error : Parsing error: Illegal **import ** declaration block me,
i keep the babel-* with the same version 6.1.2 except the babel-loader 6.1.0,.

this is all info:
E:\bulldog\blog\Webpack&Vue\src\main.js
  1:2  error  Parsing error: Illegal import declaration

✖ 1 problem (1 error, 0 warnings)

ERROR in ./src/main.js
Module parse failed: E:\bulldog\blog\Webpack&Vue\node_modules\babel-loader\index.js!E:\bulldog\blog\Webpack&Vue\node_modules\eslint-loader\index.js!E:\bulldog\blog\Webpack&Vue\src\main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Vue from 'vue';
| import App from './App.vue';

thanks for your reply.

**Comment by yyx990803** [comment]
That example is deprecated. Use `vue-cli` instead: `npm install -g vue-cli && vue init webpack-simple myapp`
