### ISSUE TITLE
Jade error when used with vue-loader

### ISSUE THREAD

**Issue by karevn** [vuejs/vue-loader#20]
Environment: latest vue beta, jade template in .vue file. When trying to instantiate a component from that file, Vue shows a warning:

```
[Vue warn]: Invalid template option: function template(locals)
```

As far as I understand, it's because Jade loader returns a function that evaluates to the template text, not template string. It looks like a check if the template is a function is required somewhere in this file: https://github.com/vuejs/vue-loader/blob/master/lib/loader.js

**Comment by karevn** [comment]
Or may be just make it at the vue side? It may make sense....

**Comment by yyx990803** [comment]
See this section: https://github.com/vuejs/vue-loader#a-note-on-dependencies

For template pre-processors, use `template-html-loader` + the raw template engine.
