### ISSUE TITLE
Missing tag v15.10.0

### ISSUE THREAD

**Issue by peschuster** [vuejs/vue-loader#2005]
### Version
15.9.8

### Reproduction link
[github.com/vuejs/vue-loader/](https://github.com/vuejs/vue-loader/)

### Steps to reproduce
Missing tag and release

### What is expected?
Tag 15.10.0 in git and Release in Github

### What is actually happening?
15.10.0 is only metioned in package.json and Changelog.md on master branch and published in npmjs.com

---
Is there a reason 15.10.0 is not tagged or documented as release? Or is this just an oversight?

**Comment by thedamon** [comment]
LOL this also makes it impossible to submit issues using the issue helper for 15.10.0 ;)

**Comment by sodatea** [comment]
Fixed now.
