### ISSUE TITLE
Path problems after iconfont package

### ISSUE THREAD

**Issue by pencil2014** [vuejs/vue-loader#201]
**Before packing directory structure and css code：**
![1](https://cloud.githubusercontent.com/assets/10042880/14426079/c5a52e9c-001e-11e6-9c96-829214cb13ec.png)
**After packing：**
![2](https://cloud.githubusercontent.com/assets/10042880/14426080/c5b1238c-001e-11e6-9b6d-4cb7dd5e76bf.png)

**Error loading iconfont：**
![3](https://cloud.githubusercontent.com/assets/10042880/14426430/8cf3a8c8-0021-11e6-88c1-51deac1986af.png)

How to solve this problem need?

**Comment by azamat-sharapov** [comment]
What have you tried so far?

**Comment by yyx990803** [comment]
http://vuejs-templates.github.io/webpack/static.html

**Comment by pencil2014** [comment]
使用vue cli webpack 生成的，css的font路径怎么改都无法显示，这个真是没看懂
![4](https://cloud.githubusercontent.com/assets/10042880/14448978/c845a190-00a0-11e6-953c-607070116098.png)

这个在哪修改？

**Comment by yyx990803** [comment]
Use relative paths in your CSS urls...

**Comment by pencil2014** [comment]
Solved, thank you!
