### ISSUE TITLE
Another webpack loader: .vue folder structure

### ISSUE THREAD

**Issue by skyrpex** [vuejs/vue-loader#202]
I'm trying to implement a webpack vue loader that expects a vue component with this structure:
- MyComponent.vue/
- |-- index.js
- |-- template.html

It would be required like `import MyComponent from './MyComponent.vue'`.

I added a loader like this:

``` js
loaders: [
      {
        test: /\.vue\/index\.js$/,
        loader: 'vue!vue-directory'
      },
      // ...
]
```

This loader wraps the script content:

``` js
// vue-directory-loader.js
module.exports = function (script) {
    return '<template src="./template.html"></template>\n\n<script>\n'+script+'</script>\n'
}
```

But, of cource, it doesn't work. An error is thrown (I guess it has to do with sourcemaps). 

```
ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Editor.vue/index.js
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.module.exports (/home/cpallares/Inbenta/settings_editor/node_modules/vue-loader/lib/selector.js:11:27)
 @ ./src/components/Editor.vue/index.js 2:17-184
```

Can I get some help? Thanks!

**Comment by lebornjose** [comment]
can't  find file  './src/components/Editor.vue/index.js'

**Comment by jasonsanjose** [comment]
Directory-based loading would be really useful for text editors that don't support `*.vue` files yet. Also, this would be helpful for editor implementations only support syntax highlighting, but not code completion. 

This https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue extension for vscode doesn't support code hints (beyond token-based hinting) in any of the language blocks for `template`, `script` and `style`.

**Comment by michaelkrupp** [comment]
@skyrpex any progress on your attempts to implement your loader? I'd like to see this feature as well.
My current work-around is to place a `component.vue` into the directory which simply includes the script, template and style via the `src` attribute and adding `/component.vue` to webpack's `resolve.extensions`.

**Comment by skyrpex** [comment]
@michaelkrupp I didn't invest time into this since then.

**Comment by kazupon** [comment]
Close (inactivity)
