### ISSUE TITLE
vue-loader triggers "componentchanged" forever in .vue files 

### ISSUE THREAD

**Issue by alexcheninfo** [vuejs/vue-loader#203]
1. Install Vue CLI: `npm install -g vue-cli`
2. Create the app: `vue init webpack-simple app`
3. Install aframe: `npm install aframe`
4. Add `import 'aframe'` inside the `script` tags of `App.vue`

5. Add this inside `<template>`:

```
<a-scene>
  <a-entity>
    <a-camera @componentchanged="onChange()">
    </a-camera>
  </a-entity>
</a-scene>
```

and this inside `export default:`

```
methods: {
    onChange: function () {
     console.log('Changed!')
  }
}
```

You will see `Changed!` in the console being logged forever.

Here's a demo: https://desolate-island-90618.herokuapp.com/#!/5EfhFj+R3DY1zo8JIGGQhosrSqn7p0t8pON9y5asxnM= (see console).

This only happens in `.vue` files. The problem doesn't occur in vanilla Vue: http://codepen.io/anon/pen/PNQdwO

(_Note:_ The event is being triggered even if `oldData` is the same as `newData`. It's supposed to trigger only when you [rotate the scene](https://aframe.io/docs/core/entity.html#Events) with the mouse.)

**Comment by alexcheninfo** [comment]
By the way, I noticed a similar behavior with others non-traditional DOM events. For instance, [resize](https://developer.mozilla.org/en-US/docs/Web/Events/resize):

It's normal behavior is to trigger when changing the size of the window: http://codepen.io/alexcheninfo/pen/YqaPdE

But in a `.vue` file/`vue-loader` setup it also triggers on page load:

```
  created () {
    window.addEventListener('resize', function () {
      console.log('This will also trigger on pageload')
    }, false)
  },
```

**Comment by LinusBorg** [comment]
@alexcheninfo 

Is this still an issue?

**Comment by alexcheninfo** [comment]
@LinusBorg Okay, I'll close it. I think this isn't a Vue issue.
