### ISSUE TITLE
vue cli3 在打包到时候会把项目中没有使用的图片文件打包输出到dist目录。

### ISSUE THREAD

**Issue by bertms** [vuejs/vue-loader#2055]
项目中使用图片的所有地方代码都删除了，打包任然会输出到所有目录
尝试了很多办法
1 移除所有require.context 引用文件夹的地方
2 vue.config.js 配置Tree Shaking
3 分析项目中import中动态导入的文件夹
。。。
都没有解决，求助解决方向。

**Comment by sodatea** [comment]
请提供可以运行的复现代码
