### ISSUE TITLE
同一页面有两个不同scopeid

### ISSUE THREAD

**Issue by wuhaoxiangfau** [vuejs/vue-loader#2056]
我在同一页面 并未使用父子组件的情况下，生成的js文件使用了两个scopeid
vue：3.2.36
vue-loader：16.0.0
![image](https://github.com/vuejs/vue-loader/assets/30434214/63a21091-6fe1-4f50-85ab-383d52789674)
![image](https://github.com/vuejs/vue-loader/assets/30434214/893d502e-29ac-45a2-8744-8d7138d4b18a)

但生成的css文件只有一个scopeid 导致页面样式无法生效。

**Comment by sodatea** [comment]
请提供可以运行的复现代码。

**Comment by wuhaoxiangfau** [comment]
升到17.2.2就好了，是16.0.0  有bug吗

**Comment by sodatea** [comment]
16.0.0 到 17.2.2 之间修了非常多的 bug。
