### ISSUE TITLE
Build error: Cannot read properties of null (reading 'lang')

### ISSUE THREAD

**Issue by freedomlang** [vuejs/vue-loader#2059]
After update to v15.11.0, i'm facing error: Cannot read properties of null (reading 'lang'). Everything is fine, if i downgrade to v[15.10.2](https://www.npmjs.com/package/vue-loader/v/15.10.2)

**Comment by canjianx** [comment]
I met this also.
`  if (script || scriptSetup) {
    const lang = script.lang || (scriptSetup && scriptSetup.lang)`

script can bu null.

**Comment by sodatea** [comment]
Fixed in v15.11.1
