### ISSUE TITLE
Suggestion: Extension attribute

### ISSUE THREAD

**Issue by pespantelis** [vuejs/vue-loader#207]
What do you think about an attribute at the `<script>` tag, which will return an extended constructor created by `Vue.extend()`?

```html
<script extension>
  //...
</script>
```

Does this make sense?

**Comment by blake-newman** [comment]
I think this is nice,  however it can easily be done in 'user land' where imported.  

By introducing this you are making testing more difficult,  as it would no longer return as a simple Object.

**Comment by pespantelis** [comment]
Thanks for the quick response @blake-newman!

I agree that this is more difficult to test, but in practice it is more 'clean` for anyone who wants to export an extended constructor.

```html
<script extension>
  export default {}
</script>

<!-- instead of -->
<script>
  export default Vue.extend({})
</script>
```

**Comment by simplesmiler** [comment]
@pespantelis slightly tangent, but what is the benefit of extended constructor over plain description?

**Comment by pespantelis** [comment]
Sometimes I want to extend my components. So, I need to move on like this:

```html
<!-- Component.vue -->
<script>
  import Vue from 'vue'

  export default Vue.extend({
    // ..
  })
</script>

<!-- MyComponent.vue -->
<script>
  import Component from './Component.vue'

  export default Component.extend({
    // ..
  })
</script>
```
http://www.webpackbin.com/E1Fyzuggb

Firstly, I thought that the `Vue.extend()` can be called **behind the scenes** so that it is not needed every time to `import` the `Vue` and call the `extend` (the reason I raised this issue).

Your comments have put me into thoughts and I figured a different way:

```html
<!-- Component.vue -->
<script>
  import Vue from 'vue'

  export default {
    // this is the function which will be attached behind the scenes
    extend (extendOptions) {
      return Vue.util.mergeOptions(this, extendOptions)
    },
    // ..
  }
</script>
```
http://www.webpackbin.com/E1q4BKlgZ

As the object is exported from the `vue-loader`, a function `extend(extendOptions)` can be attached which will merge that `object` with what was given as an argument.

This way since it remains as an `object`, testing is not difficult to perform.

Your thoughts? :)

**Comment by yyx990803** [comment]
@pespantelis that seems like a pretty smart solution. Alternatively we can have an `extends` option which makes this easier:

``` js
export default {
}
```

**Comment by pespantelis** [comment]
It sounds nice @yyx990803!

Is there already such an option or are you thinking of implementing one?

**Comment by pespantelis** [comment]
I just saw your edit.
I’ll try to make an implementation and I'll pull the request.

Thanks :)

**Comment by thebluefish** [comment]
Is there any official implementation of this extends method as mentioned by @pespantelis? I'm looking for a clean way to extend components to make it as easy as possible for people to hook in custom functionality within an open source app.

**Comment by pespantelis** [comment]
@thebluefish, please check [here](https://vuejs.org/v2/api/#extends).
