### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by loranger** [vuejs/vue-loader#21]
I'm afraid some dependencies are missing :

```bash
$ npm install --save-dev vue-loader
/Users/loranger/Developer/projects/fairechier
├── UNMET PEER DEPENDENCY css-loader@*
├── UNMET PEER DEPENDENCY style-loader@*
├── UNMET PEER DEPENDENCY vue-html-loader@^1.0.0
└─┬ vue-loader@3.0.4
  ├── hash-sum@1.0.2
  ├─┬ loader-utils@0.2.11
  │ └── big.js@3.1.3
  ├── parse5@1.5.0
  ├── postcss-nested@0.3.2
  └─┬ postcss-selector-parser@1.3.0
    ├── flatten@0.0.1
    ├── indexes-of@1.0.1
    └── uniq@1.0.1

npm WARN EPEERINVALID vue-loader@3.0.4 requires a peer of vue-html-loader@^1.0.0 but none was installed.
npm WARN EPEERINVALID vue-loader@3.0.4 requires a peer of css-loader@* but none was installed.
npm WARN EPEERINVALID vue-loader@3.0.4 requires a peer of style-loader@* but none was installed.
```

Did I miss something ?

**Comment by yyx990803** [comment]
Are you using npm3? Starting in npm3 it no longer auto-install peer dependencies for you. You have to install these peer dependencies yourself (with `--save` so they are included in your `package.json`).

**Comment by timwis** [comment]
Shouldn't these be regular dependencies then? Seems like a lot of steps to get vue-loader up and running, and they're not documented :/ Perhaps I'm not understanding peer dependencies well enough.

**Comment by yyx990803** [comment]
@timwis the easiest way is really just clone https://github.com/vuejs/vue-loader-example and tweak it for your needs. It has everything set up.

**Comment by dipen7** [comment]
would someone post a sample project that is working and accessible .
will be good help to most of the people includeing me :)

**Comment by timwis** [comment]
@dipen7 I recommend using [vue-cli](https://github.com/vuejs/vue-cli/tree/master) (the current stable version, 2.x) with the [webpack-simple](https://github.com/vuejs-templates/webpack-simple) template:

```
npm install --global vue-cli
vue init webpack-simple project-name-here
```

**Comment by dipen7** [comment]
Thanks for the reply and Actually i've already started a project can i use
this for the prebuild project?  If yes then how?
