### ISSUE TITLE
vue-loader support mp3

### ISSUE THREAD

**Issue by zhangsanshi** [vuejs/vue-loader#211]
In the vue file, I have a audio tag and write in  config, but It's not work.

**Comment by Jinjiang** [comment]
try `file-loader` or `url-loader` https://webpack.github.io/docs/loader-conventions.html

**Comment by jmaister** [comment]
I am having the same problem. Tried with .ogg and it didn't work. Also with .mp3 to follow the conventions and **file-loader/url-loader** are not processing the **audio** tag.

    <audio src="./assets/ding.ogg" type="audio/ogg"></audio>
    <audio src="./assets/test.mp3" type="audio/mpeg"></audio>

**Comment by fmopin** [comment]
@jmaister I have the same problem, can you explain how you did please?

**Comment by jmaister** [comment]
In webpack.config.js:

    module: {
        rules: [{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    // other vue-loader options go here
                    loaders: {
                    },
                    **transformToRequire**: {
                        "audio": "src"
                    }
                }
            },

**Comment by life4ants** [comment]
@jmaister That isn't working for me....

**Comment by jmaister** [comment]
Hi, @fmopin  @life4ants 
What kind of error or message do you get ?

**Comment by life4ants** [comment]
```
Module parse failed: src/assets/sound.mp3 Unexpected character '' (1:3)
You may need an appropriate loader to handle this file type.
```
I tried what you wrote above, but it doesn't help. Do you really use `**`'s?

**Comment by LinusBorg** [comment]
You have to inlcude the `mp3` extension in the config of file-loader (where `png` etc are handled).

**Comment by life4ants** [comment]
Ok, I figured it out now. I tried it with `url-loader` instead of `file-loader` as I had before:
```
     {
        test: /\.mp3$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('audio/[name].[hash:7].[ext]')
        }
      },
```
