### ISSUE TITLE
Replace "jade" with "pug"

### ISSUE THREAD

**Issue by stephanedemotte** [vuejs/vue-loader#213]
Jade has been renamed to "pug" due to a trademark problem.

See: [pugjs/pug#2184](https://github.com/pugjs/pug/issues/2184)

-> you should replace "jade" with "pug" in the package.json and support "pug" templates:

```
<template lang="pug">
.hello
  h1 {{ msg }}
</template>
```
lang="jade" still should be allowed.

®@eschmid72
Same as : https://github.com/vuejs/vueify/issues/79

Thanks !

**Comment by paulpflug** [comment]
vue-loader uses [consolidate.js](https://github.com/tj/consolidate.js), which doesn't support pug yet: https://github.com/tj/consolidate.js/pull/232

**Comment by doowb** [comment]
`pug` is now in `consolidate@0.14.1`

**Comment by yyx990803** [comment]
Now that `consolidate` has support for `pug` in a patch release, I don't think there's anything we need to do in `vue-loader`. Just do a fresh install to get latest deps, and then `npm install pug` should suffice.

**Comment by happierall** [comment]
:class="variable" doesn't work with pug...
":" is not valid as the start or end of an un-quoted attribute.
[Proof](https://www.bountysource.com/issues/33938870-attribute-names-starting-with-are-not-allowed-anymore?show_profile_modal=1)

**Comment by eschmid72** [comment]
-> https://github.com/pugjs/pug-lexer/issues/61

**Comment by Vivi-wu** [comment]
@happierall Maybe you can try this:
`':class='variable'`

**Comment by kakuevn** [comment]
Writing in full, i.e. `v-bind:class` worked for me in `pug`.

**Comment by wildpixeldesign** [comment]
both shortcut and full syntax worked for me.
:class="{ visible: !isStart }"
