### ISSUE TITLE
[HMR] vue-loader hot reload is only compatible with Vue.js 1.0.0+. 

### ISSUE THREAD

**Issue by stephanedemotte** [vuejs/vue-loader#214]
I want to try vue 2 :)

Thanks a lot !

**Comment by stephanedemotte** [comment]
sorry it's just a warn...

**Comment by yyx990803** [comment]
vue-loader has not been updated for Vue 2.0 yet, please check back in a few weeks!

**Comment by guidobouman** [comment]
@yyx990803 This still appears to be an issue in a project I recently upgraded to Vue2. Is that right? Or am I doing something wrong? (Running vue-loader 9.5.1 with vue 2.0.1)

**Comment by guidobouman** [comment]
Nevermind.

Note to self:
- Make sure to always run `npm install` after updating a package version to get it's dependencies. 
- And then restart webpack to reload the freshly updated dependencies...
