### ISSUE TITLE
npm run build CSS styles rules have different order then in dev

### ISSUE THREAD

**Issue by PrimozRome** [vuejs/vue-loader#216]
When I am running `npm run build` the dist files mix the order of my CSS styles rules which breaks rendering of my web app. I have no clues if this is the vue-loader issue or anything else. Any help appreciated...

`npm run dev`
https://dl.dropboxusercontent.com/u/1207859/npm_dev.png

`npm run build`
https://dl.dropboxusercontent.com/u/1207859/npm_build.png

**Comment by yyx990803** [comment]
Outdated, but general advice is that do not write CSS in a way that relies on the order of your component appearance.
