### ISSUE TITLE
vue-router subroutes has bug with vue-hot-module-replacement

### ISSUE THREAD

**Issue by GilbertSun** [vuejs/vue-loader#217]
demo: https://github.com/GilbertSun/vue-debug-demo

repeat: 
1. 

```
npm install && npm run dev
```
1. open browser navigate `http://localhost:8080`
2. change `./src/index.vue`

```
<template>
    <div>
        <header>i am header</header>
        <main>
            <router-view></router-view>
        </main>
    </div>
</template>
```

to 

```
<template>
    <div>
        <header>i am header change</header>
        <main>
            <router-view></router-view>
        </main>
    </div>
</template>
```

it will apply hot module replacement

i got the result

![image](https://cloud.githubusercontent.com/assets/1615364/15009314/4a54a374-1218-11e6-8058-30490623579d.png)

dom structure is

![image](https://cloud.githubusercontent.com/assets/1615364/15009340/70dfa3fe-1218-11e6-84f5-0c9048d17d39.png)

it looks like hmr inject the whole app into a sub router-view

ps: i'm not sure this is a vue-loader bug, but in the https://github.com/vuejs/vue-router/tree/dev/example/advanced   this bug didn't appear, so i think this bug may the difference version  in vue-loader or vue-hot-reload-api

**Comment by GilbertSun** [comment]
i init this project with `vue init webpack-simple`

**Comment by mrzzcn** [comment]
same problem

**Comment by antoniputra** [comment]
I have similar problem.
I start with `vue init webpack`

![vue-router and hmr issue](https://cloud.githubusercontent.com/assets/3622084/15205795/8f3b583e-1844-11e6-9277-627e22a6e6d2.gif)

**Comment by gbdematos** [comment]
+1 Also with this problem... It's cascading the Parent into the Parent's router-view. :(

**Comment by vagusX** [comment]
+ 1 same problem

**Comment by rjoo** [comment]
Also having this problem. Downgrading vue-loader to 8.3.1 didn't do it for me. Which version of vue-hot-reload-api are you using?

**Comment by vagusX** [comment]
@rjoo  vue-hot-reload-api's version is 1.3.2, but I found in another project this problem still existed
@yyx990803 can you solve it?

**Comment by zheeeng** [comment]
Same Problem. Searching for some solutions.

**Comment by zheeeng** [comment]
@antoniputra Sorry for mentioning you in an old issue, have you solved this problem?

**Comment by antoniputra** [comment]
@zheeeng  not yet :(
I don't have any idea how to solve it.

because this is in development environment, I just skip, and continue my development.

**Comment by zheeeng** [comment]
@antoniputra I also have to skip this problem and perform the page refreshing manually.

**Comment by xierenyuan** [comment]
- -。   +1

**Comment by aristidesfl** [comment]
+1

**Comment by cycold** [comment]
+1

**Comment by skyrpex** [comment]
I can reproduce the problem in the following situation:

```html
<router-link :to="{ name: 'home' }" tag="li">Home</router-link>
```

The `tag="li"` is preventing the HMR to work. If I don't use it, it reloads perfectly fine.

I'm using:

* `"vue": "^2.0.0-rc.4",`
* `"vue-loader": "^9.4.2",`
* `"vue-router": "^2.0.0-rc.4",`

**Comment by laander** [comment]
+1  :'-(

**Comment by LinusBorg** [comment]
This is also tracked on the vue-router repo here: https://github.com/vuejs/vue-router/issues/662

**Comment by boogerlad** [comment]
Same bug but broader scope. Seems to affect all components? https://github.com/vuejs/vue-loader/issues/370

**Comment by LinusBorg** [comment]
Does not seem like the same problem. I'm #370 you say nothing abiut duplicattion if replaced modules, you talk about changes not being applied at all.

**Comment by vanhoavn** [comment]
+1

**Comment by notflip** [comment]
+1 Still in 2017
