### ISSUE TITLE
postcss-px2rem 插件 build bug？

### ISSUE THREAD

**Issue by aidenzou** [vuejs/vue-loader#227]
在项目中用到了 postcss 的 postcss-px2rem 插件，作用就是把 css中的 px 处理成 rem
- [px2rem]9(https://github.com/songsiqi/px2rem)
- [postcss-px2rem](https://www.npmjs.com/package/postcss-px2rem)

webpack.base.conf.js：
```
  vue: {
    // loaders: utils.cssLoaders(),
    postcss: [require('postcss-px2rem')({
      baseDpr: 2,             // base device pixel ratio (default: 2)
      threeVersion: false,    // whether to generate @1x, @2x and @3x version (default: false)
      remVersion: true,       // whether to generate rem version (default: true)
      remUnit: 75,            // rem unit value (default: 75)
      remPrecision: 6         // rem precision (default: 6)
    })],
    autoprefixer: {
      browsers: ["Android >= 2.3", "ChromeAndroid > 1%", "iOS >= 4"],
      cascade: false  // 不美化输出 css
    }
  }
```

scss源码
```
.selector {
    width: 150px;
    height: 64px; /*px*/
    font-size: 28px; /*px*/
    border: 1px solid #ddd; /*no*/
}
```

预期是 默认 px处理成rem； /*px*/ 按媒体查询处理成 px；/*no*/ 不处理还是原有的px
在 npm run dev 阶段 OK，在 npm run build 的时候所有的 px都被处理成 rem

是不是在 postcss-px2rem 插件处理之前，已经把 css 中的 注释给排除了？

@yyx990803 大大,我这个问题该怎么处理呢

**Comment by aidenzou** [comment]
发现 .vue 文件设置 <style lang="scss"> 的时候会出现此问题

而 <style> 默认的 css 则OK

**Comment by yyx990803** [comment]
应该是因为 sass-loader 在 NODE_ENV=production 的时候把注释去掉了。这个我也没办法...

**Comment by Jinjiang** [comment]
@songsiqi please check it out. Thx.

**Comment by aidenzou** [comment]
已解决。
确实是 sass-loader 给去掉的
更改 /build/util.js 配置：
scss: generateLoaders(['css', 'sass'])   // old
scss: generateLoaders(['css', 'sass?outputStyle=expanded'])   // new

@yyx990803 tks

**Comment by EvanHunt** [comment]
琢磨了半天时间，发现这个问题好像修复了`"postcss-px2rem": "^0.3.0"`  `vue-cli`7月20号下载最新的（vue-cli大概这一周时间我玩了2个版本的 －－！,配置都不一样了）；总之不知道是哪一方面修改了这个BUG，但是问题也解决了；

**Comment by PuYart** [comment]
@EvanHunt 我也遇到了一些情况下（不知道什么情况） /*px*/ 不生效的问题，请问你是否已经解决了？

**Comment by yuanoook** [comment]
使用 webpack 的时候发现这个问题，同时发现一个牛逼的插件解决了这个问题 https://www.npmjs.com/package/postcss-plugins-px2rem

**Comment by Sapphire2k** [comment]
@yuanoook 这个插件 怎么用的？ 我在vue loader里面加了这个 还是直接把字体直接转换成rem了

**Comment by yuanoook** [comment]
@Sapphire2k 里面可以使用三种单位 px, dpx, rpx 。 px 会转成 rem； dpx 会转成设备像素；rpx 会转成 px；

**Comment by yuanzhaohao** [comment]
@yuanoook 这个插件明显是抄袭了这个吧：https://github.com/songsiqi/px2rem，连代码都没有改动哦

**Comment by Sapphire2k** [comment]
@yuanzhaohao 不算抄袭啊，只是封装了一层。。

**Comment by yuanzhaohao** [comment]
@Sapphire2k 我看基本上都是一样的吧，何来封装了一层这个说法呢？

**Comment by Sapphire2k** [comment]
@yuanzhaohao 
`
'use strict';

var postcss = require('postcss');
var Px2rem = require('px2rem');
module.exports = postcss.plugin('postcss-px2rem', function (options) {
  return function (css, result) {
    var oldCssText = css.toString();
    var px2remIns = new Px2rem(options);
    var newCssText = px2remIns.generateRem(oldCssText);
    var newCssObj = postcss.parse(newCssText);
    result.root = newCssObj;
  };
});`
具体实现是以px2rem为核心，只是postcss-px2rem作为postcss插件，可以实现自动转换..

**Comment by season19840122** [comment]
我先开始也遇到这个问题，google 上搜找到这里，但是只知道原因，还是没办法解决，后来灵机一动，把打包配置文件改成先执行 sass-loader，再执行 postcss-loader，就没有这个问题了，也不需要配置什么 sass expended！
![qq 20190115155541](https://user-images.githubusercontent.com/3078392/51166320-052aad00-18de-11e9-9ee1-10ae39ee829c.png)

**Comment by zxyue25** [comment]
> 我先开始也遇到这个问题，google 上搜找到这里，但是只知道原因，还是没办法解决，后来灵机一动，把打包配置文件改成先执行 sass-loader，再执行 postcss-loader，就没有这个问题了，也不需要配置什么 sass expended！
> ![qq 20190115155541](https://user-images.githubusercontent.com/3078392/51166320-052aad00-18de-11e9-9ee1-10ae39ee829c.png)

我这样做无效呀

**Comment by zxyue25** [comment]
> 已解决。
> 确实是 sass-loader 给去掉的
> 更改 /build/util.js 配置：
> scss: generateLoaders(['css', 'sass']) // old
> scss: generateLoaders(['css', 'sass?outputStyle=expanded']) // new
> 
> @yyx990803 tks

我这样也不行
