### ISSUE TITLE
Can multiple scripts be concatenated together?

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vue-loader#228]
Currently, only one `<script>` is allowed in a Vue component. I think (theoretically) we can just concat multiple `<script>`s if it has, and a `<script src lang>` equals to `require(url?lang)` in main generated javascript code. If we do so, the restrict could be opened.

**Comment by yyx990803** [comment]
What's the use case for this? I think it's conceptually more clear to treat each Vue file as a single module (thus with a single `<script>` tag).

If you want to mix in other langs just import it directly with corresponding Webpack loader.

**Comment by Jinjiang** [comment]
```vue
<template>...</template>

<style>...</style>

<script>
const config = {...} // generated data / config from CMS or somewhere else
</script>

<script lang="coffee">
module.exports =
  data: () -> config
  ...
</script>
```

Just saw the restrict in source code and thought that might be not necessary for some cases like this. Not a big matter.

**Comment by LinusBorg** [comment]
Thanks for the proposal, but we will close this issue and keep the limitation for one script tag.
