### ISSUE TITLE
Module build failed: TypeError: this._init is not a function

### ISSUE THREAD

**Issue by johnwonder** [vuejs/vue-loader#23]
vue-strap is a  vuecomponent , and  i want to use it like this:

require('vue-strap').alert

but it report errors below:

Module build failed: TypeError: this._init is not a function
    at Object.Vue (E:\vue\vue-strap1\node_modules\vue-strap\node_modules\vue\src
\vue.js:19:8)

the code  in the vue-strap/src/main.js  file:

var _AlertVue = require('./Alert.vue');

exports.alert = _AlertVue;

**Comment by bradstewart** [comment]
I'm seeing the same thing with custom components.

**Comment by yyx990803** [comment]
@bradstewart Are you exporting a constructor created by `Vue.extend()` instead of a plain object?

**Comment by bradstewart** [comment]
@yyx990803 So I can't quite figure out why the error printed to the console was from `require('component.vue')`, the call stack led me back to `Vue.use(VueRouter)` which was the actual problem. After updating`vue-router` and `vue-loader`, everything looks good. (I am only exporting plain objects though).

**Comment by davidrunger** [comment]
FWIW, the error referenced in this issue's title is what I was getting simply because I hadn't run `npm install --save vue-loader` (and then I had to first manually install all of the peer dependencies, since I am using npm v3, and then retry `npm install --save vue-loader` and then it installed successfully and then my webpack bundle built successfully without the error).

It might be worth adding a reminder about actually installing the loader to the README.md, for slow folks like me... :grin:

**Comment by tilleps** [comment]
@davidrunger was my issue/resolution also.  Thanks!

For anyone else that needs the list of the peer dependencies:
```
vue
vue-loader
vue-html-loader
css-loader
style-loader
babel-loader
babel-core
babel-plugin-transform-runtime
babel-preset-es2015
babel-runtime
vue-hot-reload-api
```

Or copy/paste version for your convenience:
```
npm install --save vue vue-loader vue-html-loader css-loader style-loader babel-loader babel-core babel-plugin-transform-runtime babel-preset-es2015 babel-runtime vue-hot-reload-api
```

(Without --save)
```
npm install vue vue-loader vue-html-loader css-loader style-loader babel-loader babel-core babel-plugin-transform-runtime babel-preset-es2015 babel-runtime vue-hot-reload-api
```

**Comment by karol-f** [comment]
Removing node_modules and installing it again helped.

**Comment by blackwood** [comment]
I think this is important enough to warrant being in the README -- all that's there is to use the CLI, there should be probably be additional "vanilla" instruction for combining with existing webpack projects. Should I make a pull?

**Comment by felixzh0u** [comment]
#409 is helped
