### ISSUE TITLE
add markdown-loader

### ISSUE THREAD

**Issue by transtone** [vuejs/vue-loader#231]
how about add a markdown-template-loader to format ```<template lang="md">#Headline</template>```

**Comment by Jinjiang** [comment]
Interesting. But I don't think markdown-loader work well with vue-loader. It doesn't have data binding and directive syntax. Do you have any more details of this plan?

**Comment by transtone** [comment]
勾神，仙森的这个项目是这样的：https://github.com/okoala/vue-antd/blob/master/docs/components/button.vue
他用了自己写的一个  https://github.com/okoala/vue-antd-docs-loader/blob/master/index.js 来处理。

因为这个项目已经停更一段时间了，很多组件已经不能用，我在尝试修复它。但因为vue-loader升级，按照原来的处理方法已经不生效，提示：Template engine 'md' isn't available in Consolidate.js。 

一直没有找到很好的在 ```<template />``` 中插入 markdown 格式文件的方法。
如果官方能直接处理markdown也不失为一个好方法。
