### ISSUE TITLE
My app.js is 9 MB. How do I analyze the bundle size?

### ISSUE THREAD

**Issue by jakobrosenberg** [vuejs/vue-loader#232]
Is it possible to analyze the bundle size when running npm run dev?

**Comment by yyx990803** [comment]
The production build size should be different from dev bundle size, I don't think analyzing dev bundle is useful. Why not disable minification for the production build and see what's included in the bundle?

**Comment by jakobrosenberg** [comment]
Thanks,  that was fast. How would I disable the minification?

**Comment by jakobrosenberg** [comment]
I think I got it.

**Comment by jakobrosenberg** [comment]
Sorry, I'm completely lost.  I tried disabling various options, but no luck.

**Comment by yyx990803** [comment]
I will need more information - are you using a template from `vue-cli`?t

**Comment by jakobrosenberg** [comment]
Yes, the full fledged webpack template.

I was looking at this, but had no idea how to implement it.
https://github.com/robertknight/webpack-bundle-size-analyzer

**Comment by yyx990803** [comment]
Are you saying the resulting js from `npm run build` is 9MB?

**Comment by jakobrosenberg** [comment]
No, the js alone is about 2 MB.

**Comment by jakobrosenberg** [comment]
Solved it.

```
webpack(webpackConfig, function (err, stats) {
  fs.writeFileSync('./stats.json', JSON.stringify(stats.toJson()));
  ...
```

**Comment by yubarajshrestha** [comment]
after build my file size is: 14 mb. Help :(
