### ISSUE TITLE
vue-loader autoprefixer config

### ISSUE THREAD

**Issue by aidenzou** [vuejs/vue-loader#234]
在项目中用到了 postcss 的 autoprefixer 插件，

webpack.base.conf.js：

```
    vue: {
    loaders: utils.cssLoaders(),
    autoprefixer: {
      browsers: ["Android >= 2.3", "ChromeAndroid > 1%", "iOS >= 7"],
      cascade: false  // 不美化输出 css
    }
  }
```

scss源码
```
.selector {
    display: flex;
}
```

dev 模式下输出：
```
.selector {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}
```

build 模式下输出：
```
.selector {
  display: -webkit-box;
  display: flex;
}
```

webpack.base.conf.js  中的 vue.autoprefixer 配置  在build 的时候没有起效

@yyx990803 大大,我这个问题该怎么处理呢

**Comment by aidenzou** [comment]
巨坑  如下方式解决
   
    css: generateLoaders(['css?-autoprefixer']),
    postcss: generateLoaders(['css?-autoprefixer']),
    less: generateLoaders(['css?-autoprefixer', 'less']),
    sass: generateLoaders(['css?-autoprefixer', 'sass?indentedSyntax']),
    scss: generateLoaders(['css?-autoprefixer', 'sass?outputStyle=expanded']),
    stylus: generateLoaders(['css?-autoprefixer', 'stylus']),
    styl: generateLoaders(['css?-autoprefixer', 'stylus'])

**Comment by tonyc726** [comment]
@aidenzou 按照你的方法处理了，不过没有明白为何这么处理就可以了，请问能否详细的说明一下

**Comment by zhe-he** [comment]
当我使用 `browsers: ['last 7 versions']`  也可以。

**Comment by wszgxa** [comment]
一样的问题。按照楼上的方法解决了。。。好坑啊。

**Comment by wszgxa** [comment]
@aidenzou 为啥那样就可以了啊？

**Comment by weishijun14** [comment]
我也是，只有-ms-的前缀，-webkit-根本不出来，用了last 7 versions才好了。 真心坑。。

**Comment by pspgbhu** [comment]
完美的解决了我的问题

**Comment by kaysonli** [comment]
webpack 2.0里怎么配置autoprefixer？跟webpack1区别好大，找不到配置的地方了。

**Comment by zhe-he** [comment]
@kaysonli  `The best you speak English, so that more people can help you.`

`autoprefixer({browsers: ['last 7 versions']})`

**Comment by kaysonli** [comment]
@zhe-he Thanks.

**Comment by zhaoqize** [comment]
cool！今天也遇到类似问题

**Comment by lenvonsam** [comment]
how to solve this problem of auto del -webkit prefix in prod evn.  @kaysonli  @zhe-he

**Comment by yuxizhe** [comment]
@lenvonsam   if you use vue-cli .  you can open package.js. change "last 2 versions"  to "last 7 versions",

```js
  "browserslist": [
    "> 1%",
    "last 7 versions",
    "not ie <= 8"
  ],
```

**Comment by lltemplar** [comment]
When I delete optimize-css-assets-webpack-plugin in webpack.prod.conf.js the -webkit is not be removed.
I guess optimize-css-assets-webpack-plugin remove -webkit because it use cssnano.
Change "last 2 versions" to "last 7 versions" in  package.json can solve this problem

**Comment by xiaojingzhao091** [comment]
Hi @lltemplar 
 I've tried add '-autoprefixer' and your suggestion. Unfortunately, both of them are not working. Still no prefix in build css

I've tried to deleted  optimize-css-assets-webpack-plugin. And the autoprefixer works properly. But I hope I could keep this plugin. Does anyone know how to fix this?

**Comment by xiaojingzhao091** [comment]
@lltemplar  Yes, the file -- package.json is now modified as what you described, but nothing changed
```
"browserslist": [
    "> 1%",
    "last 7 versions",
    "not ie <= 8"
  ]
```
And I tried `"last 20 versions` as well, nothing changed :(

**Comment by wuwb** [comment]
not woking
