### ISSUE TITLE
scoped style 如何处理动态的html标签?

### ISSUE THREAD

**Issue by hanai** [vuejs/vue-loader#239]
如下，text是从服务起获取的，里面可能包含 em 标签，怎么样让scoped里的em样式应用的动态获取的数据里的em标签?

``` vue
<template>
<div class="book-info">
  <p>{{{text}}}</p>
</div>
</template>

<style lang="scss" scoped>
.book-info {
  overflow: hidden;
}

p {
 font-size: 18px;
}

p em {
  color: red;
}
</style>
```

**Comment by yyx990803** [comment]
加一个非 scoped 的 style tag

**Comment by L-TMC** [comment]
我发现貌似对于在method中动态生成并注册的partial，scoped的样式样式不能生效。

**Comment by jazoom** [comment]
I think (my Chinese isn't so good) I'm having this same issue. I have an <em> tag that is dynamically inserted into html. I cannot apply styles due to the 'scoped' tag adding the data attribute. Is there a solution to this that doesn't involve removing 'scoped' from the entire containing component?
