### ISSUE TITLE
How can I get access to current template?

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue-loader#24]
I want to create component which extends another one:
```js
<script>
var table = require('../../../components').datatable

module.exports = table.extend({
   template: ?
})
</script>

<template>
...
</template>
```

How can I get access to current template?

**Comment by sjoerdvisscher** [comment]
Hmm, this isn't going to work because vue-loader generates the exports line for you.

**Comment by OEvgeny** [comment]
So, I tried it, but `Vue.extend` (as well as `table.extend`) returns a function, not object. And it hasn't field `template`.

`'../../../components/index.js'` looks like:
```js
var components = {
  datatable: require('./datatable.vue'),
}

Object.keys(components).forEach(function (name) {
  module.exports[name] = Vue.extend(components[name])
})
```

**Comment by yyx990803** [comment]
vue-loader assumes you are using single inheritance, that is, you create all components as a direct sub class of `Vue`. No multiple inheritance between each other.

If you need to reuse a bunch of logic, make a mixin. Prefer composition over inheritance.

**Comment by OEvgeny** [comment]
@yyx990803 thanks for clarification! But I can't understand now, where to use inheritance?

**Comment by yyx990803** [comment]
@OEvgeny every component is implicitly used with `Vue.extend`. So you don't need to call it yourself.
