### ISSUE TITLE
Asset urls should be interpolated before being resolved

### ISSUE THREAD

**Issue by jingman** [vuejs/vue-loader#251]
vue-loader is trying to resolve the path to my asset before it's been interpolated:
```
// data.foo = 'bar'
<template>
  <img src="./{{foo}}.jpg"/>
</template>
```
It tries to resolve `./{{foo}}.jpg` instead of the interpolated `./bar.jpg`.

**Comment by repsac-by** [comment]
try this
```html
<img :src="'./'+foo+'.jpg'" />

**Comment by yyx990803** [comment]
There is an explicit warning telling you that you should use `:src` instead of interpolations in `src`.

**Comment by jingman** [comment]
@yyx990803 thanks for the explanation, links, and your work on Vue!

In this particular case I think I'll just switch to using `/static` paths instead.
