### ISSUE TITLE
*.vue能用百度地图的lbs-nearby标签方式吗？

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue-loader#254]
*.vue组件

<template>
<lbs-nearby enable-geo="true" city="北京" num="10" query="美食" radius="5000" type="map" style="height:100%"></lbs-nearby>
</template>

**Comment by wuchuguang** [comment]
可以看出，这货已经是外国人了，中国写的问题，就鸟都不鸟。哈哈。反倒是外国人问的倒是及时回应。

**Comment by yyx990803** [comment]
@wuchuguang 傻逼，伸手党不管是中国人外国人我都不鸟，尤其是你这样的。
