### ISSUE TITLE
[bug] Scoped CSS not work with "v-if"

### ISSUE THREAD

**Issue by niceue** [vuejs/vue-loader#259]
```html
<template>
<div class="box1" v-if="true"></div>
<div class="box2"></div>
</template>

<style scoped>
.box1 {height:100px;}
.box2 {height:100px;}
</style>
```

**Comment by LinusBorg** [comment]
Hello @niceue 

Thanks for filing this issue.

Could you elaborate what is "not working" (What is the result unexpected behavior in the browser?), and maybe reproduce the behaviour on webpackbin.com?

**Comment by niceue** [comment]
Sorry, I can't repeat it. May be I used improperly
