### ISSUE TITLE
Hot reload, cannot apply update. Need to do a full reload!

### ISSUE THREAD

**Issue by BirdEggegg** [vuejs/vue-loader#26]
<img width="1245" alt="screen shot 2015-10-16 at 14 35 15" src="https://cloud.githubusercontent.com/assets/4584859/10535211/5fc4f9b4-7413-11e5-8bb5-142a8a5947c9.png">

I clone the vue-hackernews and use vue@1.0.0-rc.1

**Comment by yyx990803** [comment]
This is expected when used on the root component. The hot-reload only works for child components.

**Comment by carlina425** [comment]
正遇到同样的问题

**Comment by sliechti** [comment]
I'm adding the error as text so it gets indexed and it may help other developers understand why hot-reload is not working.

```
TypeError: "record.Ctor.super is undefined"
    reload webpack:///./node_modules/vue-hot-reload-api/dist/index.js?:228
    tryWrap webpack:///./node_modules/vue-hot-reload-api/dist/index.js?:119
```
