### ISSUE TITLE
CSS duplicate

### ISSUE THREAD

**Issue by fundon** [vuejs/vue-loader#261]
**vue-loader@8.5.2**

Component A:

```vue
<template>
  <div></div>
</template>
<style lang="scss">
@import "~bulma";

/* do something */
</style>
```

Component B:

```vue
<template>
  <div></div>
</template>
<style lang="scss">
@import "~bulma";

/* do something *
</style>
```

Problem:

The **bulma** library will be import twice.

How to fix this?

Real show case, see http://vue-admin.fundon.me/#!/ui/notifications.

![screen shot 2016-06-22 at 3 31 39 am](https://cloud.githubusercontent.com/assets/27926/16243442/df4f3d72-3829-11e6-89d2-adee86cdea73.png)

**Comment by yyx990803** [comment]
Are you using mixins from the lib? If not you should import it only once in your root component.

If not, this should be deduped by cssnano when you are building for production.

**Comment by airyland** [comment]
I also encountered the problem. I split WeUI's less styles into Vux's every component, so some less files are imported more than once. This works fine when developing. But after building, the duplicate styles remain. So I simply created a script to compress it(142k -> 90k). But I wonder if there is a easier way?

``` js
const cssnano = require('cssnano')
const fs = require('fs')
const path = require('path')

const code = fs.readFileSync(path.resolve(__dirname, '../dist/vux.css'))
cssnano.process(code.toString(), {zindex: false}).then(function (result) {
  fs.writeFileSync(path.resolve(__dirname, '../dist/vux.min.css'), result.css)
})
````

I try to config vue loader's postcss option, but it doesnot work.
``` js
vue: {
    postcss: [require('cssnano')({zindex:false})]
 }
```

**Comment by fundon** [comment]
@airyland I sloved it.

Using mixins from the lib. 
Like   https://github.com/fundon/vue-admin/blob/master/src/components/Sidebar.vue#L78.

**Comment by mrg0lden** [comment]
@fundon Hello, the provided URL gives error 404, can you explain the solution?

**Comment by c4milo** [comment]
I ran into the same issue, cssnano did indeed remove it when compiling for production. @yyx990803 is there anyway to achieve de-duplication in development mode?

**Comment by mrg0lden** [comment]
@c4milo when using scss or sass,  import the variables and mixins only. For styles, you can import them once in the main file

**Comment by christophwolff** [comment]
I would also like to know how to avoid dublicate styles in development.

**Comment by mrg0lden** [comment]
@christophwolff as I said, separate your variables from your styles, import your variables everywhere you need them. Import your styles once in the root component. Good luck.

**Comment by christophwolff** [comment]
@mrg0lden Thank you. But my Problem is, i want to use the grid system from bootstrap in some components. And these are mixins. `@include media-breakpoint-up` i.e. So there is no other way around that.
