### ISSUE TITLE
[HMR] TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by b12k** [vuejs/vue-loader#265]
```javascript
[HMR] TypeError: Cannot read property '0' of null
```
Here are screen shots:
http://prntscr.com/bjkpdj.
http://prntscr.com/bjkq5b

HMR not working. But I'm not able to find out why. Please guide me where to search for errors?

**Comment by yyx990803** [comment]
Please provide the versions of both Vue and vue-loader.

**Comment by b12k** [comment]
Vue 1.0.24
vue-loader 8.5.2

**Comment by yyx990803** [comment]
Do you happen to use Vue files but not naming them with the `*.vue` extension?

Anyway this should be fixed with the latest `vue-hot-reload-api` - try reinstalling `vue-loader`.

**Comment by b12k** [comment]
Yes. I name them filename.vue.html and use vue-loader to load them. I need it to get some kind of syntax highlight in VisualStudio for my Asp.Net team mates.

Thank you! Will check it asap.

**Comment by yyx990803** [comment]
Should've been fixed in latest version.
