### ISSUE TITLE
Dependencies required by components can't be mocked by proxy-loader

### ISSUE THREAD

**Issue by qt911025** [vuejs/vue-loader#266]
e.g.
```javascript
let myComponentMock = requrie('proxy!./myComponent.vue');
let stubs = {
  foo: sinon.stub();
};
let myComponent = myComponentMock(stubs);
```

The real dependency is still be used instead of the mocked one.

https://github.com/qt911025/vue-component-test-demo

Relevant post
http://forum.vuejs.org/topic/4390/proxy-loader%E5%AF%B9-vue%E6%96%87%E4%BB%B6%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8

**Comment by yyx990803** [comment]
Use inject-loader instead.

**Comment by qt911025** [comment]
Thx!
