### ISSUE TITLE
autoprefixer 相关问题

### ISSUE THREAD

**Issue by chengwangping** [vuejs/vue-loader#269]
![image](https://cloud.githubusercontent.com/assets/5220595/16374876/139cb108-3c8b-11e6-9c79-2125b9950127.png)
base.config.js 里面设置了这个 我 dev环境下会正常  build 里面却不正常，什么情况 公用一个loader
![image](https://cloud.githubusercontent.com/assets/5220595/16374925/5b56abde-3c8b-11e6-8955-7692e2441f9a.png)
用的vue－cli脚手架

**Comment by chengwangping** [comment]
补充一下，dev环境会给我添加一个私有属性，而build 却不会添加这个属性，我需要这个属性

**Comment by lzx1022** [comment]
同碰到这个问题

**Comment by Foxing-wong** [comment]
同碰到这个问题

**Comment by NightCatSama** [comment]
同碰到这个问题
