### ISSUE TITLE
webpack-dev-server --hot  Error: Module not found

### ISSUE THREAD

**Issue by Runsing** [vuejs/vue-loader#27]
Hi. Can you speak Chinese? : )

下面是场景：
dev-env：win7 x64
node-version：v4.2.0
cmd：webpack-dev-server --hot
error info： ERROR in ./src/components/a.vue
Module not found: Error: Cannot resolve module 'E:
odewwwdevspaceapp
ode_modulesue-loaderlibhot-reload-api.js' in E:\nodewww\devspace\app\src\compon
ents
 @ ./src/components/a.vue 6:13-93

经分析发现是转义符的问题..

@./libs/loader.js  中的 141行：

'var hotAPI = require("' + require.resolve('./hot-reload-api') + '")\n' +
替换成：
'var hotAPI = require("' + require.resolve('./hot-reload-api').replace(/\\\\/g, "\\\\\\\\") + '")\n' +

就ok了.. 第一次反馈问题，说的有点混乱。

框架很好用，谢谢。

**Comment by yyx990803** [comment]
多谢，已经加入到 4.0.4
