### ISSUE TITLE
Hot reload just replaces state, no way detecting hotreload event.

### ISSUE THREAD

**Issue by vird** [vuejs/vue-loader#275]
I had some issues with hotreload. 
https://github.com/vuejs/vue/issues/3225
Main reason: right now hotreload just renders new element and just replaces state. This state can store DOM links, which must be updated. There is no possible way to handle hotreload event.

I created some pull requests for hotreload hook
https://github.com/vuejs/vue-hot-reload-api/pull/34
https://github.com/vuejs/vue/pull/3227

Any other ideas for same behaviour?

**Comment by yyx990803** [comment]
See my explanation in https://github.com/vuejs/vue/pull/3227
