### ISSUE TITLE
问个问题，叫伸手党。开源个框架的人叫什么？造轮牛人？

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue-loader#276]

**Comment by wuchuguang** [comment]
认为别人问一个问题前没试验？问题一定是你牛人都避开的了。文档/源码里清清楚楚了。
感觉牛人方方面面具到 0bugs,无需升级。是我们这些菜⻦看不懂文档，看不懂源码。

**Comment by yyx990803** [comment]
你问题里写你试验了吗？你就一个标题我怎么知道你试验了个毛？提问的基本信息都不全还指望别人搭理你，你以为你他妈谁啊？有多远滚多远，谢谢。
