### ISSUE TITLE
Vue live component swapping fails when launching webpack with Atom text editor

### ISSUE THREAD

**Issue by Kingdaro** [vuejs/vue-loader#277]
When launched from a normal command window, the hot reload shim will replace edited live components as expected.

When launched from [build](https://atom.io/packages/build), or from a terminal opened with [atom-terminal](https://atom.io/packages/atom-terminal), edits to components in the source will trigger a full reload of the page every time.

[I have a repository set up here](https://github.com/Kingdaro/atom-hot-reload-example/) to demonstrate. Steps to reproduce:

1. Clone the repository, `npm install`, then open the project folder with Atom text editor, with the `build` and `atom-terminal` plugins installed.
1. Select the `dev` target in build, then run the build and open up a browser to localhost:3000.
1. Edit the message in App.vue. The page performs a full reload instead of hot swapping the component.
1. Stop the build.
1. Open a terminal with atom-terminal.
1. Run `npm run dev` in the terminal, and open a browser to localhost:3000.
1. Edit the message in App.vue. The page performs a full reload and does not swap the component.
1. Open a new terminal from outside of Atom.
1. Navigate to the project folder and run `npm run dev`. Hot reloading works as expected.

It's using Vue 2.0, but this applies to all versions of Vue that I've tested, and this happens in both Chrome and Firefox. Running Windows 10.

**Comment by Eden-Sun** [comment]
You'd better generate you project via vue-cli.
There are lots of webpack config settings for hot reload.

**Comment by Kingdaro** [comment]
> You'd better generate you project via vue-cli.
That's what I did.
> There are lots of webpack config settings for hot reload.
I've tried fiddling with a bunch, including ones I didn't think would be relevant to the issue, but I haven't found a solution yet. I honestly don't know what could be causing this.

**Comment by Kingdaro** [comment]
Figured it out. It's because something is setting the `NODE_ENV` environment variable to production, which causes vue-loader hot reload to stop working. I'm not sure what, but I'll just assume this is my problem for now, and not Atom's.
