### ISSUE TITLE
I split up  *.vue components into multiple file, ESlint dose not work to .js.

### ISSUE THREAD

**Issue by zkboys** [vuejs/vue-loader#291]
I split up  *.vue components into multiple file, just like:
```
<template src="./template.html"></template>
<style src="./style.css"></style>
<script src="./script.js"></script>
```
ESlint dose not work , but if I use `import SomeName from './script.js'` in some other .js file, ESlint works well. do you have any ideas?

webpack.conf.js:
```
...
preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      }
    ],
...
```

**Comment by LinusBorg** [comment]
Hello @zkboys 

Thanks for filing this issue, we will look into it.

Quick side question: Why would you do that?

I mean, I get that some might want to extract the HTML and / or CSS if it's too big, but why also the JS? Now you essentially only have an extra file that does nothing.

Simply put the js back into the .vue file and you're fine.

**Comment by zkboys** [comment]
OK,Thank you! I'll put js back to *.vue.

**Comment by Kehao** [comment]
```javascript
{
        test: /.vue$/,
        loader: 'vue',
        // exclude: /node_modules/,
        options: {
          loaders: {js: 'babel!eslint'},
          postcss: [
            autoprefixer({ browsers: ['last 7 versions'] }),
            px2rem({
              remUnit: 75
            })
          ]
        }
}
```
覆盖vue-loader的js-loader是不是就可以了

**Comment by akopchinskiy** [comment]
@LinusBorg > Quick side question: Why would you do that?
Maybe because single-file components sucks?

**Comment by yyx990803** [comment]
@akopchinskiy then just don't use `vue-loader`.
