### ISSUE TITLE
nested components A>B>A

### ISSUE THREAD

**Issue by vird** [vuejs/vue-loader#292]
Similar to https://github.com/vuejs/vue/issues/2519
Setting name doesn't help.

https://gist.github.com/vird/4a22d30cd6a5e876dd4df0e9a106b69a
usage
   
    <ca level="5"></ca>

error:

    vue.common.js?e881:1019[Vue warn]: Attribute "v-bind:level" is ignored on component <ca> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment-Instance

**Comment by yyx990803** [comment]
This is a usage problem, `vue-loader` can't fix it for you.
