### ISSUE TITLE
Lazy Loading Routes not work

### ISSUE THREAD

**Issue by lomotony** [vuejs/vue-loader#293]
![screenshot - 07282016 - 05 22 14 pm](https://cloud.githubusercontent.com/assets/6621024/17211410/eee90742-54fb-11e6-9e15-8e004b01a6c3.png)
我把component的function写成了一个通用的函数，但是打包之后就没有做代码分割，整个就是一个文件，这是为什么？

**Comment by JounQin** [comment]
动态参数 webpack 无法分析，就打包整个目录 *views* 了，可以试试 `bundle-loader` .

**Comment by lomotony** [comment]
@JounQin webpack是如何分析的？webpack的执行过程和js的执行过程还不一样吗

**Comment by yyx990803** [comment]
webpack bundle split 是通过解析文件的 AST 来分析的，不是通过执行。
