### ISSUE TITLE
Can't install: peerinvalid The package vue-hot-reload-api does not satisfy its siblings

### ISSUE THREAD

**Issue by cho-is** [vuejs/vue-loader#296]
Trying to do the basic tutorial and I got:

```npm ERR! peerinvalid The package vue-hot-reload-api does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vue-loader@8.5.3 wants vue-hot-reload-api@^1.2.0```

**Comment by cho-is** [comment]
solved!

**Comment by cho-is** [comment]
Sorry guys but no matter what I do, I get:
`vue-loader@8.5.3 requires a peer of vue-hot-reload-api@^1.2.0 but none was installed.`

**Comment by yyx990803** [comment]
You need to explicitly `npm install vue-hot-reload-api@^1.2.0` because its latest version is higher than that.

**Comment by cho-is** [comment]
Tried that but for some reason did not work. 

It works with vue cli though. Thank you.

**Comment by vaindil** [comment]
@yyx990803 That command does not work. The package `vue-hot-reload-api@1.2.0` is invalid, npm won't install it. I did install with `npm install vue-hot-reload-api@^1.2.0` as you specified.

**Comment by josueadelima** [comment]
Same error not installing package even with `npm install vue-hot-reload-api@^1.2.0`
