### ISSUE TITLE
两台机器是不是生成的所有文件都应该是一样的，包括hash值？

### ISSUE THREAD

**Issue by lomotony** [vuejs/vue-loader#297]
我两台一样的机器，生成的chunk文件有差异，这是什么原因，按道理应该一样的啊
![screenshot - 08022016 - 11 10 04 am](https://cloud.githubusercontent.com/assets/6621024/17315851/b745e6d0-58a1-11e6-8bb2-d6fb1bcfb196.png)

@yyx990803

**Comment by yyx990803** [comment]
你确定 vue-loader 版本一样么

**Comment by lomotony** [comment]
@yyx990803 版本是一样的，都是`npm install`的

**Comment by kazupon** [comment]
Close (inactivity)
