### ISSUE TITLE
Multiple styles lang not supported

### ISSUE THREAD

**Issue by denismars** [vuejs/vue-loader#3]
Only one style tag and lang per .vue file is support. Be nice to support any number of styles/lang per .vue page.

e.g.
```
<style lang="stylus">
body
  color yellow
</style>

<style lang="less">
 body {
  background: blue;
 }
</style>

```
will only return an output containing the second ("less") style tag contents and not incorporate the first ("stylus") style contents.

**Comment by yyx990803** [comment]
It's now supported via vue-component-compiler@1.1.3: https://github.com/vuejs/vue-component-compiler/commit/c3a9c74b478c19c8e77f33e195b49bc1d098ab5b
