### ISSUE TITLE
有在windows下测试过loader是否可用吗

### ISSUE THREAD

**Issue by hizhengfu** [vuejs/vue-loader#30]
项目初始是在mac下构建的，一切正常，但是同事在windows下就不能正常构建了，显示错误信息为
>ERROR in ./src/admin/views/404.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/vue-loader/lib/selector.js in C:\usr\assert/src\admin\views
 @ ./src/admin/views/404.vue 1:26-130

>ERROR in ./src/admin/views/home/index.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../node_modules/vue-loader/lib/selector.js in C:\usr\assert/src\admin\views\home
 @ ./src/admin/views/home/index.vue 1:17-140

**Comment by hizhengfu** [comment]
抱歉，测试了下提供的例子，在window下应该是可用的，应该是我用了webpack中
 resolve:alias引起的问题

**Comment by gongzhen1027** [comment]
遇到了同样的问题，请问解决了吗？

**Comment by hizhengfu** [comment]
resolve: {
        root: path.join(__dirname, 'src/'),
        alias: {
            //组件目录
            components: path.join(__dirname, 'src/components'),
            services: path.join(__dirname, 'src/services'),
            utils: path.join(__dirname, 'src/utils'),
            views: path.join(__dirname, 'src/views')
        }
    },

这个是我的配置 ，就是每一个路径都要写全路径就可以了

**Comment by gongzhen1027** [comment]
我先试一下，多谢！

**Comment by gongzhen1027** [comment]
原因是mac下路径是正斜杠“/”，windows下是反斜杠“\”，解决方法是处理路径时全部用path处理，不要直接相加
