### ISSUE TITLE
A nice way to lint `.vue` files with Stylelint?

### ISSUE THREAD

**Issue by dan-gamble** [vuejs/vue-loader#303]
I noticed this was attempted: https://github.com/vuejs-templates/webpack/pull/154 and closed (For good reason)

But i wondered if anyone has a setup for this currently?

**Comment by xmoki** [comment]
I think is possible to do it with htmlhint, but currently only supports jshint and csslint, maybe if someone can make a htmlhint rule for stylelint.

**Comment by JounQin** [comment]
Actually we could use `<style src="/path/of/style/file"/>` then just lint the style file as usual.

**Comment by yisibl** [comment]
1. Touch `.stylelintrc`

  ```json
  {
    "processors": ["stylelint-processor-html"],
    "extends": "stylelint-config-standard"
  }
  ```
2.   Install

  ```json
    npm i stylelint -D
    npm i stylelint-processor-html -D
    npm i stylelint-config-standard -D
  ```
3. Add

  ```json
  "scripts": {
    "lint:css": "stylelint '**/*.vue' --syntax scss"
  },
  ```

4. `npm run lint:css`

**Comment by dan-gamble** [comment]
@yisibl that works for me, swear i tried this before!

**Comment by scottsandersdev** [comment]
I'm wondering if there's a way to get stylelint to report this to sublimelinter, although it works great from the command line, it doesn't work actively while typing in sublime. Have you or anyone else had any luck with that? Also, @yisibl thanks for posting this, helped me get started.

**Comment by bkzl** [comment]
For the record, this is the same working configuration for webpack:

1. Install:

```sh
npm i --save-dev stylelint stylelint-processor-html stylelint-config-standard stylelint-webpack-plugin
```

2. Create `.stylelintrc`

```js
{
 "processors": ["stylelint-processor-html"],
 "extends": "stylelint-config-standard"
}
```

3. Load the plugin (in `build/webpack.dev.conf.js` for Vue webpack template)

```js
//...
var StylelintPlugin = require('stylelint-webpack-plugin')

{
  //...
  plugins: [
    //...
    new StylelintPlugin({
      files: ['**/*.vue']
    })
  ]
}
```

I published [an article](https://medium.com/lost-bananas/linting-css-in-vue-files-6bb20faac0f2) which includes both solutions and explains two additional things (configuration rules and errors when starting the dev server).

**Comment by wenkanglin** [comment]
@bkzl i follow your config, use the `stylelint-webpack-plugin`, it can work, but the line number of error reporter is incorrect for `.vue` file.

![qq 20170214151913](https://cloud.githubusercontent.com/assets/21100124/22919258/c4aa316a-f2c9-11e6-9695-a0ec8ee54cca.png)

**Comment by bkzl** [comment]
@wenkanglin I immediately fix these errors when I code so I didn't even notice that. There is a corresponding issue: ccbikai/stylelint-processor-html/issues/1

**Comment by repsac-by** [comment]
try `@mapbox/stylelint-processor-arbitrary-tags`   instead   `stylelint-processor-html`

**Comment by jing2si** [comment]
> "scripts": {
>     "lint:css": "stylelint '**/*.vue' --syntax scss"
> },

Can not add single quotation marks in windows. Otherwise it will report the following error.
> Error: '**/*.vue' does not match any files
>  at globby.then.filePaths

The following setting worked well in windows 10

```
"scripts": {
  "lint:css": "stylelint **/*.vue"
},
```

**Comment by gucong3000** [comment]
#839
stylelint/stylelint#2596

**Comment by evecalm** [comment]
Issue moved to [vuejs/011.vuejs.org #6](https://github.com/vuejs/011.vuejs.org/issues/6) via [**ZenHub**](https://www.zenhub.com/)

**Comment by equinusocio** [comment]
Using the @yisibl  solution i can't make it works using postcss.

**Comment by equinusocio** [comment]
@gucong3000 Thank you man. This did the trick. There is a documentation somewhere about that?

**Comment by gucong3000** [comment]
> Thank you man. This did the trick. There is a documentation somewhere about that?

Not at the moment.

**Comment by hiendv** [comment]
@gucong3000 Hi, I cannot get stylelint autofix to work with .vue files? Any idea why?

**Comment by gucong3000** [comment]
@hiendv please update `stylelint` >= v9 then try this command:
```bash
stylelint --fix `src/**/*.vue`
```

**Comment by gucong3000** [comment]
> There is a documentation somewhere about that?

https://vue-loader.vuejs.org/guide/linting.html#stylelint

**Comment by equinusocio** [comment]
@gucong3000 This solution doesn't works anymore
https://github.com/vuejs/vue-loader/issues/303#issuecomment-412399156

postcss.config.js
```js
module.exports = {
  syntax: require("postcss-syntax"),
  plugins: {
    // ....
  }
};
```

Defining the `syntax` package break all the plugins.

**Comment by gucong3000** [comment]
@equinusocio
Maybe you can upload a zip package that contains these errors so I could help you debug them.

**Comment by mudin** [comment]
After trying many things, I got stylelint autofix to work with .vue files in vscode using [SaveOnRun](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extension.
added below config in the `settting.json`:

```
"emeraldwalk.runonsave": {
    "commands": [
      {
        "match": ".vue",
        "cmd": "stylelint --fix ${file}"
      }
    ]
  },
```

Better solution would be appreciated!

**Comment by humoyun** [comment]
@mudin good job, saved the day

**Comment by VictorPulzz** [comment]
Hey guys, can you help me?
I setup stylelint, and try fix my files use this command:
``` "lint:style": "stylelint --fix **/*.{vue,css,scss,sass}" ```
I got this message:
```Autofix is incompatible with processors and will be disabled. Are you sure you need a processor?```
my config:
```
module.exports = {
  "processors": ["stylelint-processor-html"],
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-prettier-scss"
  ],
  "rules": {
    "no-empty-source": null,
    "block-no-empty": null,
    "color-no-invalid-hex": true,
    "comment-empty-line-before": [
      "always", {
        "ignore": [
          "stylelint-commands",
          "after-comment"
        ]
      }
    ],
    "declaration-colon-space-after": "always",
    "indentation": [
      "tab", {
        "except": [ "value" ]
      }
    ],
    "max-empty-lines": 2,
    "rule-empty-line-before": [
      "always",
      {
        "except": [ "first-nested" ],
        "ignore": [ "after-comment" ]
      }
    ],
  }
};
```
