### ISSUE TITLE
Update NPM package to target vue 2.0.0-beta.7

### ISSUE THREAD

**Issue by gbisheimer** [vuejs/vue-loader#305]
Latest 9.3.2 version NPM package targets vue beta.6 and gives a `Vue packages version mismatch` error when using beta.7.

Needs and update. Thanks!

**Comment by yyx990803** [comment]
Just re-install and you'll get the latest.

**Comment by gbisheimer** [comment]
It works. Thanks!

**Comment by alliuca** [comment]
I've just encountered the same error with 9.4.2 and rc.4; tried to reinstall vue-loader, no luck
