### ISSUE TITLE
Image-Paths are now from root-path?

### ISSUE THREAD

**Issue by CinKon** [vuejs/vue-loader#306]
# Versions

vuejs: 2.0.0-beta.7
vue-loader: 9.3.0

---

Hi,

I used to load images directly from the component Folder in webpack:

/src
-- /components
---- /_organism
------- /Devices
--------- Devices.vue
--------- /_assets
----------- myImage.jpg

**Devices.vue:**
```
<template lang="pug">
    img(src="./_assets/myImage.jpg", alt="")
</template>
```
This worked great so far, but today I updated to vue2.0.0-beta.7 and vue-loader9.3.0, and now webpack wants to load the file from absolute domain: `http://localhost:8080/_assets/myImage.jpg`

**Comment by yyx990803** [comment]
Should've been fixed in latest, please let me know if it persists with ^9.4.0
