### ISSUE TITLE
Allow disable transpilling .js files

### ISSUE THREAD

**Issue by makbol** [vuejs/vue-loader#317]
It'd be nice to have possibility to disable Babel transpiling script tags inside .vue files.

Currently it's possible to use different transpiler using `lang` attr. My proposition to disable Bable is:

```js
<script lang="vanilla">
  # Vanilla JS here!
</script>
```

**Comment by yyx990803** [comment]
From 9.x up if babel is installed then `<script>` blocks will just be treated as plain js. 8.x will preserve current behavior though.
