### ISSUE TITLE
vue-loader 0.8 giving a js error instead of a console.error when used with Vue 2

### ISSUE THREAD

**Issue by posva** [vuejs/vue-loader#319]
Created from vuejs/vue#3490

**Comment by yyx990803** [comment]
8.x is not compatible with Vue 2.

**Comment by posva** [comment]
Yep. Sorry, that was not very clear. I thought the title was enough. Let me add more context:

When updating your dependencies, vue-loader gets updated to 9.0.0. This breaks since v9 is meant to be used alongside Vue 2. However, this is only stated in the release notes and people forget about it.
I propose we add a check so that we can display an error (if that's possible) to the user about using v9. Something like:

> You're using vue-loader^9.0.0 which only supports Vue 2. Please install vue-loader^9.0.0

We can also add a note about this in the readme:

>### Compatibility
>
>- `vue@^1.0.0` => `vue-loader@^8.0.0`
>- `vue@^2.0.0` => `vue-loader@^9.0.0`

**Comment by yyx990803** [comment]
Probably better to add a `peerDependency` constraint
