### ISSUE TITLE
Problem integrating vue-router 2

### ISSUE THREAD

**Issue by fkaempfer** [vuejs/vue-loader#320]
When I try to access the $route or $router properties or any of the <router-* tags in a vue component loaded by vue-loader they are not defined when I run "npm run dev" from the webpack template.

I get: [Vue warn]: Property or method "$route" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 

It works fine however if I do a npm build and simply open the project in the browser (I assume that then it is running in production mode) or if I change the dev script in package.json to production:
 
 "scripts": {
    "dev": "cross-env NODE_ENV=production webpack-dev-server --inline --hot",
   

It also works fine for any component written in plain ES2015 and imported using webpack js loader.

I'm not sure what the cause for this is, or if this is the right project to file it under. In any case, if you need more info let me know!

**Comment by LinusBorg** [comment]
Do you import the standalone build `import Vue from 'vue/dist/vue'` instead of the runtime-only build (`import Vue from 'vue'`)?
Read this, especially the end of the linked section: https://github.com/vuejs/vue/wiki/Vue-2.0-RC-Starter-Resources#standalone-vs-runtime-builds

**Comment by fkaempfer** [comment]
Sorry for the late response. Thank you very much for the suggestion, I indeed imported vue/dist/vue instead of vue. Changing it and adding a resolve webpack configuration option for vue to vue/dist/vue did fix the problem while allowing me to use the template option for some components.

**Comment by niallobrien** [comment]
I seem to be having the same issue, is there a solid fix for this issue? Thanks in advance.

**Comment by LinusBorg** [comment]
There is now, for the webpack and browserify templates:

https://github.com/vuejs-templates/browserify/pull/13
https://github.com/vuejs-templates/webpack/pull/256 (i *just* merged this one)
