### ISSUE TITLE
Can the reserved <component> element be used in jsx?

### ISSUE THREAD

**Issue by zyy7259** [vuejs/vue-loader#324]
Can the reserved <component> element be used in jsx like this?

```js
render (h) {
  return (
    <Wrapper>
      <component is='type' />
    </Wrapper>
  )
}
```

Currently, there is an error printed in the console (the following is wrapped for typeset):

```
vue.common.js:2233 [Vue warn]: Unknown custom element: <component> - 
did you register the component correctly? For recursive components, 
make sure to provide the "name" option. (found in anonymous component - 
use the "name" option for better debugging messages.)
```

**Comment by ktsn** [comment]
Why do you want to use `<component>` in render function?
I think you don't need to use `<component>` in render function because we can achieve the same thing with native JS feature.

```js
render (h) {
  return (
    <Wrapper>
      {h('type')}
    </Wrapper>
  )
}
```

**Comment by zyy7259** [comment]
@ktsn, thanks, I'm new to jsx.

I check the [Vue jsx docs](https://github.com/vuejs/babel-plugin-transform-vue-jsx), but could not find this syntax. Where can I find this syntax in Vue docs.

**Comment by ktsn** [comment]
Please see http://rc.vuejs.org/guide/render-function.html

`h` is just the createElement function.
