### ISSUE TITLE
functional not supported

### ISSUE THREAD

**Issue by zyy7259** [vuejs/vue-loader#325]
I try to write a functional component, but only get an error (the following is wrapped for typeset):

```
webpack:///./src/js/component/anchored-heading.vue?:26 
[vue-loader] anchored-heading.vue: functional components are not supported and 
should be defined in plain js files using render functions.
```

**Comment by yyx990803** [comment]
As it says, it's not supported.

**Comment by zyy7259** [comment]
will it be supported in the future

**Comment by eshell** [comment]
it should be supported. gonna have to use something else if i have to switch between jsx/templates all the time.

**Comment by scottbedard** [comment]
I would like this feature as well, it would be nice if we didn't have to give up scoped css to write a functional component.
