### ISSUE TITLE
Can not load jade files with complex conditional expressions with ~0.9

### ISSUE THREAD

**Issue by imrefazekas** [vuejs/vue-loader#327]
Using my existing vuejs 1.x project, I made some experiements with Vuejs 2.0RC3 and vue-loader 0.9 and webpack 2.10beta21 and I have issues with the new version.
I have the following jade file

    .block(v-if="origin.progLanguage !== 'nodejs' && !image.enabled")
        span Enabled

And the error message I receive is this:

    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-6!./~/vue-loader/lib/template loader.js?raw&engine=jade!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/entity/entityData.vue
    template syntax error - invalid expression: v-if="origin.progLanguage !== 'nodejs' &amp;&amp; !image.enabled"

Complex conditional expressions were accepted in the previous loader version with vuejs 1.0 but not it runs to errors.

Any help is much appreciated!

**Comment by ktsn** [comment]
This is because Jade escapes `&&` to `&amp;&amp;` in attributes and Vue 2.0's template compiler cannot handle it.
The workaround is using `!=` to avoid this escape.
http://jade-lang.com/reference/attributes/#unescaped

```jade
.block(v-if!="origin.progLanguage !== 'nodejs' && !image.enabled")
```

@yyx990803 Do you think template compiler should handle escaped attributes?

**Comment by billbuilder** [comment]
@ktsn : thanks for the feedback. I was wondering why previous load version was immune to this nature of Jade compiler. Jade compiler is outdated, renamed to pug some time ago...

I try to reconstruct my conditional expressions meanwhile. :)

**Comment by imrefazekas** [comment]
@ktsn : thanks for the feedback. I was wondering why previous load version was immune to this nature of Jade compiler. Jade compiler is outdated, renamed to pug some time ago...

I try to reconstruct my conditional expressions meanwhile. :)

**Comment by ktsn** [comment]
@imrefazekas Because previous version (vue-loader < 9) does not compile a template for a component.
But in vue-loader >= 9, templates will be compiled to JavaScript string by Vue 2.0's template compiler and the compiler cannot parse escaped value.

**Comment by imrefazekas** [comment]
Understood, thanks
