### ISSUE TITLE
Vue-loader removes type="text" from inputs

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue-loader#33]
Maybe related to this https://github.com/webpack/webpack/issues/752

**Comment by azamat-sharapov** [comment]
Yeah, old problem, I do like this:

```js
{
	test: /\.vue$/,
	loader: vue.withLoaders({
		jade: 'html?-removeRedundantAttributes!template-html?raw&engine=jade'
	})
}
```

**Comment by yyx990803** [comment]
Note since 1.0 you should use `vue-html-loader` instead of `html-loader`

**Comment by yyx990803** [comment]
This has been disabled by default now in `vue-html-loader@1.1.0`. It's enabled by the `removeRedundantAttributes` flag in `html-minifier` and now needs to be enabled explicitly via loader query.
