### ISSUE TITLE
vue-loader strip out html comments in <template> section?

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue-loader#330]
Under dev environment, i'd like to keep the comments information in both template and style and script section in .vue file.
Unfortunately, it seems that all the comments(html,js,css) are stripped out in webpack dev environment.
How can i disable that?
For example, in following del-container.vue file, i add html comments within the root div of the component, when inspecting in chrome dev tool, that comment 
 is not available
`<template>
	<div :class=" containerClass ">
        
		<slot></slot>
		<span class="m-del-container__close" @click="deleteIt"><span >x</span></span>
	</div>
</template>`

**Comment by LinusBorg** [comment]
Please provide a reproduction with your actual config.

**Comment by cnweibo** [comment]
sorry, i do not know how to move that onto jsfiddle.  This is a normal webpack vue build phenomenon.

**Comment by LinusBorg** [comment]
Then please use the forums (forum.vuejs.org) for further support. This is likely a usage/ config problem and not a bug, so it does not belong here.
