### ISSUE TITLE
.vue文件里面的样式中的url要怎么解析？

### ISSUE THREAD

**Issue by kevin1220** [vuejs/vue-loader#333]
### 使用webpack打包的时候，url的链接是可以通过`url-loader`或者是`file-loader`来解析的，但是在使用`vue-loader`来解析.vue文件的时候，发现**vue文件中的样式里面的url没法成功的解析并打包到发布路径中**，我现在只能手动的把文件放到发布路径上面，才能访问到图片，请问这个问题有没有什么解决的办法呢？

**Comment by xjchenhao** [comment]
同问

**Comment by yyx990803** [comment]
无法重现。

**Comment by kevin1220** [comment]
我使用file-loader打包成功了，但是还有个问题，我用url-loader打包PNG小图的时候，查看浏览器里面生成的最终html发现小图成功转成了base64编码，但是却无法成功读到base64编码的图片，我使用浏览器直接访问，图片是一个空白的框框，我追踪图片的路径发现最终打包成的图片有损坏。这是怎么回事，我打包配置的loader是这样的 
``{ test: /\.(jpg|png)$/, loader: "url-loader?name=[path][name].[ext]&limit=8192" },
    { test: /\.(png|jpeg|gif)$/, loader: 'file-loader?name=[path][name].[ext]' }
``
如果只是用webpack 不整合vue就不会有这个问题。不知道有没有人遇到和我一样的问题

**Comment by yyx990803** [comment]
原始问题已解决，其他问题请去论坛

**Comment by baishiup** [comment]
哪里就解决了。。。
