### ISSUE TITLE
Template compiler for vue@next as independent loader

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue-loader#335]
I think use [template compiler](https://github.com/vuejs/vue-loader/blob/next/lib/template-compiler.js) as independent loader it will be good experience for development with vuejs.

**Comment by airtonix** [comment]
yep, will allow us to apply this transform to npm installed vue components (ie: http://appcomponents.org/material-components)

**Comment by yyx990803** [comment]
A separate loader is welcome, but this doesn't seem to relate to `vue-loader` itself.
