### ISSUE TITLE
Scoped CSS doesn't apply to render function

### ISSUE THREAD

**Issue by foray1010** [vuejs/vue-loader#336]
example:
```html
<script>
export default {
  data() {
    return {
      msg: '12453'
    }
  },
  render(h) {
    return (
      <div class='hello'>
        {this.msg}
      </div>
    )
  }
}
</script>

<style scoped>
h1 {
  color: #42b983;
}
</style>
```

I was expecting it will be rendered as:
```html
<div class='hello' some-random-id>
 12453
</div>
```
but it renders like:
```html
<div class='hello'>
 12453
</div>
```

**Comment by LinusBorg** [comment]
Scoping happens during the compile step when vue-loader transforms the string-tem´plate into a render function.

If you define the render function yourself, you have to take care of scoping your CSS yourself (e.g. by using [CSS modules](https://github.com/css-modules/css-modules) which are achievable with [css-loader](https://github.com/css-modules/css-modules#css-modules).

Iff you need further assistance with that, please use our  [forum ](http://forum.vuejs.org) or [gitter chat](http://gitter.im/vuejs/vue).

**Comment by ktsn** [comment]
Actually, scoping for render function happens during runtime. (scoping for style is during compile time)
https://github.com/vuejs/vue-loader/blob/next/lib/loader.js#L202
https://jsfiddle.net/o8z180xb/

So, I think scoped CSS for render function should work, also the provided code was scoped successfully in my machine...

**Comment by LinusBorg** [comment]
Oh. You never cease to lean.. 💨

**Comment by foray1010** [comment]
thanks @ktsn and @LinusBorg 

I can confirm that the reason that it is not working for me is because I was using vue-loader 8.x
This issue is not exist in vue-loader 9.x
