### ISSUE TITLE
[2.0]SSR with scoped style after refresh page in NODE_ENV=production

### ISSUE THREAD

**Issue by sarik93** [vuejs/vue-loader#338]
### Vue.js version
2.0.0-rc-1 - 2.0.0-rc.4
vue-loader: 9.4.0 and less

### Reproduction Link

https://github.com/vuejs/vue-hackernews-2.0

### Steps to reproduce
If write scoped style in any component, for example UserView.vue add scoped - 
```html
<style lang="stylus" scoped></style>
``` 
After they:
```sh
npm run build && npm start
```
Open project to home page and go to user page (route in client-side) you can see normal style and normal attr data-v-#, but if you refresh user page you can see style not working and data-v-# changed.

### What is Expected?
After refresh page expected data-v-# not change and scoped style work.

### What is actually happening?
Scoped style not work because change data-v-#.

**Comment by speedornothing** [comment]
found the reason, using hash-sum module to [generate the moduleId](https://github.com/vuejs/vue-loader/blob/1fc953aff2c84956404224332d5fbc7176d5ef0f/lib/gen-id.js) should resolve this problem.

**Comment by egoist** [comment]
@yyx990803 Maybe revert this commit https://github.com/vuejs/vue-loader/commit/bd581dc48fd3deca0ea9edf2eaf80826d575b96f, how do you think?

**Comment by yyx990803** [comment]
Reverted in 488a078
