### ISSUE TITLE
$set method doesn't seem to be working within components

### ISSUE THREAD

**Issue by matt-sanders** [vuejs/vue-loader#346]
Hi all. 

I've been getting errors when trying to use `$set` from within a component. As an example, start with the [webpack-simple](https://github.com/vuejs-templates/webpack-simple) template and edit App.vue to become:

```html
<template>
  <div id="app">
    <button @click.prevent="checkSet">Some Text</button>
  </div>
</template>
```
```js
<script>
export default {
   methods: {
      checkSet: function(){
         this.$set('test', 'testing');
      },
  } 
   data() {
      return{
         foo: 'bar'
      }
   }
}
</script>
```
Whenever checkSet is run I get the following:
`vue.common.js?e881:1117 Uncaught TypeError: Cannot create property 'testing' on string 'test'`

Am I just missing something here?
Thanks for your help.

**Comment by JounQin** [comment]
You should use `Vue.$set` instead in `Vue2.0`.
https://github.com/vuejs/vue/issues/2873

**Comment by matt-sanders** [comment]
I did try but got the same error
```js
import Vue from 'vue';
...
checkSet: function(){
   Vue.set('test', 'testing');
}
```

**Comment by matt-sanders** [comment]
thanks to tribex for the solution on gitter:
```js
export default {
   methods: {
      checkSet: function(){
         this.$set(this.form, 'test', 'testing');
         //or Vue.set
      },
  } 
   data() {
      return{
         form: {
            foo: 'bar'
         }
      }
   }
}
```

**Comment by Tribex** [comment]
For future reference everyone, the syntax is now:
```javascript
Vue.set(object, key, value) // this.$set is now an alias to the global Vue.set
```

Fixed version of @matt-sanders example:
```javascript
import Vue from 'vue';
...
checkSet: function(){
   Vue.set(this.data, 'test', 'testing');
}
```

Hope that helps!
