### ISSUE TITLE
Pass data to template pre-processor

### ISSUE THREAD

**Issue by paglias** [vuejs/vue-loader#352]
When using a template pre-processor like Jade or Pug is it possible to pass data / options to the rendering function?

For example

```
<template lang="pug">
    p Hello #{name}!
</template>
```

I want to pass, through a webpack option, an object like this 

```
{
  name: 'World'
}
```

so that the template gets compiled into `<p>Hello World!</p>`

Is it possible?

**Comment by yyx990803** [comment]
You are mixing two template systems together, imo this just makes things more complicated than they should be. Just use Vue to render dynamic content.

**Comment by paglias** [comment]
@yyx990803 the use case would be to create the dom structure for static content in the compiling step instead that at runtime to reduce the calculations made on the browser to what's really needed

**Comment by LucasLeandro1204** [comment]
@paglias Did you find a solution?

**Comment by paglias** [comment]
@LucasLeandro1204 unfortunately not
