### ISSUE TITLE
use props in style

### ISSUE THREAD

**Issue by mxm145** [vuejs/vue-loader#354]
anyone knows how to use props in the style scope?like this:
![image](https://cloud.githubusercontent.com/assets/869702/18621104/45d06dc4-7e51-11e6-9ece-a64cf2b149ac.png)

`<template>`
`<div class="a"></div>`
`</template>`
`<script>`
`export default {`
`  props: {`
`    width: {`
 `           type: Number,`
  `          default: 100`
   `     }`
`  }`
`}`
`</script>`
`<style>`
`.a{`
 ` width: {{width}}`
`}`
`</style>`
thanks
I get an error

**Comment by jbruni** [comment]
Check "Binding Inline Styles" section at http://rc.vuejs.org/guide/class-and-style.html

**Comment by jbruni** [comment]
The "style" scope of the "vue" file does not belong to the template, where stuff like `{{ width }}` is parsed.

**Comment by mxm145** [comment]
I know this way, but I also want to get all css property in a single file like index.css

**Comment by ktsn** [comment]
We cannot use component instance data in `<style>` because `<style>` is static and shared with all instance.

**Comment by mxm145** [comment]
@ktsn got it. thanks
