### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#355]
I am getting this error after updating vue-loader from 9.4.0 to 9.5.0. I am not quite sure what i supposed to do. I i already had name option in every component I use.

```
[Vue warn]: Failed to mount component: template or render function not defined. (found in anonymous component - use the "name" option for better debugging messages.)
```

http://prntscr.com/ck9nm1

**Comment by sqal** [comment]
Ok. I've tracked this down. I had enabled option esModule and modules: false in babelrc

**Comment by kevinlvhsl** [comment]
router config
 ```
routes: [
        {
          path: '/',
            components: {
                component: App,
            }
        },]  
```  
not
```
  components: {
        default: {component: App},
    }
```

**Comment by matiastucci** [comment]
@sqal I'm having the same issue (http://forum.vuejs.org/t/vue-2-failed-to-mount-component-template-or-render-function-not-defined/2306). Can you post your `babelrc` and `webpack.conf`, please?
