### ISSUE TITLE
SASS variables in style blocks

### ISSUE THREAD

**Issue by ericcirone** [vuejs/vue-loader#356]
I am using Vue 2, vue-loader, Foundation 6, and webpack. I have everything all working where all my scss files go into a app.css with the ExtractTextPlugin. I would like to use Foundations sass variables inside of the vue-loader `<style>` blocks. I have found the only way to do this, is to do an @import in the `<style>` block. This works, but then my whole Foundation css gets repeated for each Component i use it in. This stinks.

Is there any way to use SASS variables inside of `<style>` blocks without having to export out the resulting SASS code for each component?

**Comment by LinusBorg** [comment]
fouindation, as any other CSS framework, has all variables inside a partial - if i remember correctly, it's called _variables.scss

Import that from the npm package.
