### ISSUE TITLE
'v-show' Toggle inside Component Doesn't Work

### ISSUE THREAD

**Issue by d88pak** [vuejs/vue-loader#357]
On normal vue script toggling show data works but inside a component it doesn't work.

```
<template>

    <div v-show="show">
        <p>{{ show }}</p>
    </div>

</template>




<script>
    export default
    {

        data: function()
        {
            return { show: true }; // this initial condition is respected
        },

        methods:
        {
            doSomthing: function()
            {

                this.$http.get('/someurl')
                    .then(
                        (response) => 
                        {
                            this.show = false; // this one is also bound properly but component doesn't hide itself
                        });
            }
        }

    }
</script>

```

Instance of this component doesn't hide itself.

I have a thread on this issue on Laracast

https://laracasts.com/discuss/channels/vue/custom-component-how-to-self-showhide

and

https://laracasts.com/discuss/channels/vue/v-show-toggle-on-component-doesnt-work-bug

It doesn't seem to me like its bug on Vue but somewhere in the vue-loader chain.

I might be wrong.

Thanks!

**Comment by Tatikyan** [comment]
Hi,
How did you solve the problem ?
