### ISSUE TITLE
can‘t not support webpack2.1.0-beta.25 well

### ISSUE THREAD

**Issue by nqdy666** [vuejs/vue-loader#360]
vue Options can not support well in  webpack2.1.0-beta.25

**Comment by ktsn** [comment]
It should work when we use LoaderOptionPlugin.
https://github.com/angular/angular-cli/pull/2237/files#diff-d85c71bf928fadd8cda87cb456e03d30R14

**Comment by yyx990803** [comment]
See how to use the plugin to provide Vue options: https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/webpack.base.config.js#L38-L40

**Comment by nqdy666** [comment]
Thanks
