### ISSUE TITLE
How to use "scss" in *.vue?

### ISSUE THREAD

**Issue by geekingin** [vuejs/vue-loader#363]
I'm using vue2.0 rc.7 and vue-loader 9.5.
I cannot figure out how to use scss in vue file.
If i write like this `<style lang="scss">`, there will be an error saying Cannot resolve module 'scss' in xxxxx.

![image](https://cloud.githubusercontent.com/assets/5032143/18825637/028dccc2-83fc-11e6-8446-f909b23bf7a2.png)

I can only use scss with` <style lang="sass">`
However, webstorm's inspection will not accept it.
![image](https://cloud.githubusercontent.com/assets/5032143/18825680/2b3ee6e2-83fc-11e6-9d13-1f6a33c1ccaf.png)

So, how can i use scss syntax directly in *.vue

**Comment by LinusBorg** [comment]
Hi @geekingin 

thanks for filing this issue.

1. Can you format your post in a way we can read?
2. you likely have not set up the right loaders in you webpack config.

**Comment by geekingin** [comment]
@LinusBorg Sorry for the broken format.

I'm not sure, here is my loaders in webpack config.
```javascript
module: {
		loaders: [{
			test: /\.js$/,
			loader: 'babel',
			exclude: /node_modules/
		}, {
			test: /\.vue$/,
			loader: 'vue'
		}, {
			test: /\.s[a|c]ss$/,
			loader: 'style!css!sass'
		}]
	}
```
Is it right?

**Comment by LinusBorg** [comment]
vue-loader infers the loader to use from the `lang` attribute's value, but there is no "scss-loader", only "sass-loader" (which handles both `.scss` and `.sass` styles).

So you have to tell vue-loader to use sass-loader for `scss`:
```js
module: {
  loaders: [{
    test: /\.js$/,
    loader: 'babel',
    exclude: /node_modules/
  }, {
    test: /\.vue$/,
    loader: 'vue'
  }, {
    test: /\.s[a|c]ss$/,
    loader: 'style!css!sass'
  }]
},
vue: {
  loaders: {
  	scss: 'style!css!sass'
  }
}
```

**Comment by geekingin** [comment]
That's exactly what i'm looking for, thanks a lot!

**Comment by earlymeme** [comment]
great resolution!!! thanks!

**Comment by weepy** [comment]
trying this .. I get

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
```

any ideas ?

**Comment by LinusBorg** [comment]
You are using webpack 2, which changed how to pass config to loaders:

https://vue-loader.vuejs.org/en/configurations/advanced.html

**Comment by fabd** [comment]
More to the point for my fellow googler's looking for **scss** and **Vue 2** config:

https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js

**Comment by DmacMcgreg** [comment]
The newest Vue-Cli with webpack is missing the sass-loader in order for this to work. 
Like mentioned above, you will be able to use <style lang="scss"> but only after installing sass-loader and node-sass

`npm install sass-loader node-sass webpack --save-dev`

**Comment by LinusBorg** [comment]
> The newest Vue-Cli with webpack is missing the sass-loader in order for this to work.

We never included any of the preprocessor loaders - neither sass-loader, not less-loader or any other - because people probably only need one of those, so why install all of them?

**Comment by DmacMcgreg** [comment]
It is missing, though. In order for this to work, it needs to be included manually.
I understand the reasoning, but to get what the OP is asking to work, something that is missing needs to be added.

**Comment by keydone** [comment]
u can see this : https://github.com/keydone/newBlog/blob/master/build/webpack.base.conf.js

**Comment by PeterA1** [comment]
After...

npm install sass-loader node-sass webpack --save-dev

I found <style land="scss"> to work just fine.

**Comment by weishaoqiang** [comment]
i also have this probrem,and i can't resolve it

**Comment by weishaoqiang** [comment]
i have installed node-sass and sass-loader. my webpack config :

{
       test: /\.s[a|c]ss$/,
       loader: 'style!css!sass'
}
vue: {
	loaders: {
                      scss: 'css-loader!sass-loader' // <style lang="scss"
         }
 }

**Comment by tyrw** [comment]
I had a similar runaround, seems to work in webpack 2.5.1, vue-loader 7.3.0 with:

`*.vue` uses `scss-loader` (not `scss`)
```
<style lang="scss-loader">
```

config uses:
```
module: {
  rules: {
    ...
    {
      test: /\.vue$/,
      loader: 'vue-loader',
      options: {
        loaders: {
          html: 'html-loader',
          js: 'babel-loader',
          scss: 'vue-style-loader!css-loader!sass-loader',
          // sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax',
        }
      }
    }
  }
},
resolve: {
  alias: {
    'vue$': 'vue/dist/vue.common.js'
  }
},
resolveLoader: {
  alias: {
    'scss-loader': 'sass-loader',
  },
}

**Comment by Johnson27** [comment]
In my case, it still occurs when i use style-loader in vue-loader options, like this
             `{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        scss: 'vue-style-loader!css-loader!sass-loader'
                    }
                }`
Then i resolve this problem by replacing style-loader with vue-style-loader!
Hope this helps!

**Comment by parzh** [comment]
Shouldn't the `test:` regexp be `/.s[ac]ss/` (without the vertical line)?

**Comment by zgayjjf** [comment]
@parzh You are right. However, `/.s[a|c]ss/` also works, just a little redundancy. It's not "right", but it works.
And I'm sure you know why I wrote like that...

**Comment by parzh** [comment]
The reason why it works is because the character `|` never appears in file extension, so it gets ignored (not really). But following this logic, you might have had a regexp like this: `/.s[ac%$*\}~:;|#!@^]ss/`. This too will work just fine.

**Comment by ManarElshorbagy** [comment]
ahahhahahahahahahahahh

**Comment by xgqfrms** [comment]
```js

{
      {
        test: /\.s(a|c)ss$/,
        // test: /\.sass$/,
        loaders: ['style', 'css', 'sass']
      },
}

```

**Comment by ZehuaZhang** [comment]
Got it 

> ```js
> {
>       {
>         test: /\.s(a|c)ss$/,
>         // test: /\.sass$/,
>         loaders: ['style', 'css', 'sass']
>       },
> }
> ```

Got it working only by above solution, with only one change - appending `-loader` to `loaders` entry
i.e. `loaders: ['style-loader', 'css-loader', 'sass-loading']`

I'm using Vue 2, Webpack 4, Typescript, and all other packages updated to latest version

**Comment by dsldiesel** [comment]
Where do you place that? webpack.config is not accesible now, only vue.config.js!

**Comment by webfacer** [comment]
Hi this is my current configuration of webpack.config.js
```js
import * as webpack from "webpack";
import { VueLoaderPlugin } from "vue-loader";
import UglifyJsPlugin from "uglifyjs-webpack-plugin";

const nodeExternals = require("webpack-node-externals");
// const miniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  plugins: [new VueLoaderPlugin()],
  entry: "./src/main.ts",
  output: {
    path: path.resolve(__dirname, "./dist"),
    publicPath: "/dist/",
    filename: "build.js"
    //devtoolModuleFilenameTemplate: "[absolute-resource-path]",
    //devtoolFallbackModuleFilenameTemplate: "[absolute-resource-path]?[hash]"
  },
  resolve: {
    alias: {
      vue$: "vue/dist/vue.esm.js",
      "@": path.resolve(__dirname, "src")
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: "vue-loader"
        /*options: {
          loaders: {
            scss: "vue-style-loader!css-loader!sass-loader" // <style lang="scss">
            // sass: "vue-style-loader!css-loader!sass-loader?indentedSyntax" // <style lang="sass">
          }
        }

         */
      },
      {
        test: /\.scss$/,
        use: ["style-loader", "css-loader", "sass-loader"]
      },
      {
        test: /\.js$/,
        loader: "babel-loader",
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: "file-loader",
        options: {
          name: "[name].[ext]?[hash]"
        }
      }
    ]
  },
  /*resolveLoader: {
    alias: {
      "scss-loader": "sass-loader"
    }
  },

   */
  devServer: {
    historyApiFallback: true,
    noInfo: true
  },
  performance: {
    hints: false
  },
  devtool: "#eval-source-map"
};

if (process.env.NODE_ENV === "production") {
  module.exports.devtool = "#source-map";

  module.exports = {
    optimization: {
      minimizer: [
        new UglifyJsPlugin({
          cache: true,
          parallel: true,
          uglifyOptions: {
            ecma: 6,
            compress: false,
            mangle: true
          },
          sourceMap: true
        })
      ]
    }
  };

  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: '"production"'
      }
    }),
    new UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ]);
}

// test specific setups
if (process.env.NODE_ENV === "test") {
  module.exports.externals = [nodeExternals()];
  module.exports.devtool = "eval";
}

```
where you can see that i tried a few configurations of the above solutions, but none of them helped me. i get everytime this error
```
 WEBPACK  Failed to compile with 1 error(s)

Error in ./src/components/Partials/Header/AutoCompleteSuggestion.vue?vue&type=style&index=0&lang=scss

  Module parse failed: Unexpected character '#' (2:0)
  File was processed with these loaders:
   * ./node_modules/vue-loader/dist/index.js
  You may need an additional loader to handle the result of these loaders.
  | 
  > #suggestion {
  |   width: calc(100% - 44px);
  | }

npm ERR! Test failed.  See above for more details.
```

**Comment by webfacer** [comment]
@dsldiesel sorry never mind what i posted before, i had to different configs
webpack.config.development.js and webpack.config.test.js :( and i do not know when this happend but i had to same codes with to different env. never mind this issue of mine

**Comment by Ditavonpita** [comment]
I still got the same problem when I use lang="scss" in the style-tag. Can someone help me? I'm using @vue/cli 4.5.4...

It says: 

![image](https://user-images.githubusercontent.com/67364473/91730983-bf038980-eba6-11ea-82df-9f65551b52f2.png)

and this is my webpack.config.js File:

var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader'
        ],
      },      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['*', '.js', '.vue', '.json']
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true,
    overlay: true
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}


I've already installed this $ **npm install sass-loader node-sass webpack --save-dev** as well

Thank you in advance for your help.

**Comment by shetaraven** [comment]
> I still got the same problem when I use lang="scss" in the style-tag. Can someone help me? I'm using @vue/cli 4.5.4...
> 
> It says:
> 
> ![image](https://user-images.githubusercontent.com/67364473/91730983-bf038980-eba6-11ea-82df-9f65551b52f2.png)
> 
> and this is my webpack.config.js File:
> 
> var path = require('path')
> var webpack = require('webpack')
> 
> module.exports = {
> entry: './src/main.js',
> output: {
> path: path.resolve(__dirname, './dist'),
> publicPath: '/dist/',
> filename: 'build.js'
> },
> module: {
> rules: [
> {
> test: /.css$/,
> use: [
> 'vue-style-loader',
> 'css-loader'
> ],
> }, {
> test: /.vue$/,
> loader: 'vue-loader',
> options: {
> loaders: {
> }
> // other vue-loader options go here
> }
> },
> {
> test: /.js$/,
> loader: 'babel-loader',
> exclude: /node_modules/
> },
> {
> test: /.(png|jpg|gif|svg)$/,
> loader: 'file-loader',
> options: {
> name: '[name].[ext]?[hash]'
> }
> }
> ]
> },
> resolve: {
> alias: {
> 'vue$': 'vue/dist/vue.esm.js'
> },
> extensions: ['*', '.js', '.vue', '.json']
> },
> devServer: {
> historyApiFallback: true,
> noInfo: true,
> overlay: true
> },
> performance: {
> hints: false
> },
> devtool: '#eval-source-map'
> }
> 
> if (process.env.NODE_ENV === 'production') {
> module.exports.devtool = '#source-map'
> // http://vue-loader.vuejs.org/en/workflow/production.html
> module.exports.plugins = (module.exports.plugins || []).concat([
> new webpack.DefinePlugin({
> 'process.env': {
> NODE_ENV: '"production"'
> }
> }),
> new webpack.optimize.UglifyJsPlugin({
> sourceMap: true,
> compress: {
> warnings: false
> }
> }),
> new webpack.LoaderOptionsPlugin({
> minimize: true
> })
> ])
> }
> 
> I've already installed this $ **npm install sass-loader node-sass webpack --save-dev** as well
> 
> Thank you in advance for your help.
> 
> P.S.: I wanted to implement this: https://codesandbox.io/s/basetimer-no-parent-control-forked-y08vs?file=/src/components/BaseTimer.vue

is there a solution for this problem? i also have the same problem.
