### ISSUE TITLE
ES6 fat arrow function in template

### ISSUE THREAD

**Issue by SaidTayebi** [vuejs/vue-loader#364]
Hi,
When building for production and Uglifying, this does not work.
`<Topic-Item :topic='topic'
                        :onParticipate='() => participateToTopic(topic.id)'
                        :onVote='() => followTopic(topic.id)'
                        :onUnvote='() => unfollowTopic(topic.id)'
  />
`
error: SyntaxError: Unexpected token: punc ())

**Comment by LinusBorg** [comment]
This is expected. you can't define function in template expressions.

**Comment by caeus** [comment]
any es6 expression inside a vue template such as fat arrow functions and destructuring and spread operator and string templates are not gonna be supported? Can I, somehow tell the vue-loader to use the babel loader after?

**Comment by LinusBorg** [comment]
[These ES6 features](https://github.com/vuejs/vue-loader/releases/tag/v9.4.0) work in template expressions, nothing else basically.
