### ISSUE TITLE
how to use vue-loader in webpack2.0? 

### ISSUE THREAD

**Issue by Tara-lover** [vuejs/vue-loader#365]
I want to use vue-loader in webpack2.0 with autoprefixer, I config something following document of vue-loader, but it is no use. Could you give me some suggestions?

**Comment by LinusBorg** [comment]
Loader options have to be impoerted with a new LoaderOptionsPlugin in the latest webpack beta.

This tweet might help you: https://twitter.com/vuejs/status/780059106862333952

**Comment by Tara-lover** [comment]
thanks a lot
