### ISSUE TITLE
Can we add a scoped name?

### ISSUE THREAD

**Issue by rachardking** [vuejs/vue-loader#377]
Can we add a scoped name to define the same scoped, and the css can influence the same scope

**Comment by yyx990803** [comment]
When making a feature request, please be more specific and provide a detailed use case. What are you trying to achieve and why do you need this feature?

**Comment by rachardking** [comment]
because we can't define css in page to affect the component style which write in other file with the scope

**Comment by rachardking** [comment]
sorry i have found the way in document , the issue closed
