### ISSUE TITLE
template compiling while loading

### ISSUE THREAD

**Issue by druppy** [vuejs/vue-loader#381]
Now that we have a Vue template compiler, it would be nice if this nice `vue-loader` optionally could compile templates while building, and output a render function in stead of templates that needs runtime compilation.

This would make 

 * resulting code independent of the runtime compiler (also in future npm packages)
 * burst performance (no compilation)
 * push error handling to a more suitable place along with other static errors.

**Comment by ktsn** [comment]
vue-loader => 9 already has the functionality.

**Comment by druppy** [comment]
That is so nice, thanks, is this the default action or are some options needed ?

That way we end up having same performance characteristics for both the TSX vue model :-)

**Comment by LinusBorg** [comment]
>  is this the default action or are some options needed ?

default
