### ISSUE TITLE
Template syntax error Component template should only contain exactly one root element

### ISSUE THREAD

**Issue by junerockwell** [vuejs/vue-loader#384]
Using:
````
Node v6.6.0.
vue-loader v9.5.1
Vue v2.0.1
Vue-Router 2.0.0
Vuex 2.0.0
Vuex-Router-Sync 2.1.1
````

The error says it all:
![screen shot 2016-10-07 at 8 33 00 am](https://cloud.githubusercontent.com/assets/5051574/19196176/5033b958-8c69-11e6-982f-073e65895cec.png)
I fixed it by enclosing everything inside `Page1.vue` by a `<div>` without `class` and `id` attributes. **This enclosing `<div>` or root element wasn't required in Vue@1.x. Does it really have to be required? Can it be optional like before?** Thanks.

**Comment by yyx990803** [comment]
Yes, this is required in 2.0.

**Comment by XiaoLiz** [comment]
Me too!  Your vue-loader version problem!   try  npm install --save-dev  vue-loader@8.3.0

**Comment by shanoor** [comment]
I just wasted my afternoon because of this. It was working fine with Webpack dev server but when deployed on a nginx server, no component was displayed and no error displayed (normal behaviour for a production build I guess). Weirder, using **http-server** node package inside the dist folder worked just fine. I then cleaned my project, ran Webpack again and this unique root element error showed despite my (pug) template having exactly one root element...

@XiaoLiz, thank you, changing vue-loader version solved the issue.

**Comment by solidevolution** [comment]
Got this error too with 

```
"vue": "^2.0.3",
"vue-cookie": "^1.0.0",
"vue-resource": "^1.0.3",
"vue-router": "^2.0.2"
```

with 9.* versions of vue-loader in devDependencies ...

**Comment by shanoor** [comment]
@solidevolution You should try to downgrade vue-loader version, it solved the issue for me. You'll also need to install 2 other packages: 
    
    "vue-hot-reload-api": "^1.2.0",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^8.3.0",

**Comment by solidevolution** [comment]
Surely we did that but now we have to decide

1. Use jade/pug but vue-loader 8.3 which means, no hot refresh feature ...
2. Don't use jade/pug

Both options aren't what we want. We hope you'll find a solution for this fast.

**Comment by anyexinglu** [comment]
@solidevolution , can't agree more, seems that the version of vue-loader isn't backward-compatible.

**Comment by guillermovs** [comment]
What's the reason why this is required in 2.0?
It doesn't feel right to add unnecessary root elements to components just to get rid of the error.

**Comment by xchz** [comment]
`<template>
  <el-button @click="refreshTable" >button</el-button>
  <el-table :data="tableData" stripe fit style="width: 100%">
    <el-table-column v-for="columnInfo in hospitalThead" :prop="columnInfo.name" :label="columnInfo.label" width="180"></el-table-column>
  </el-table>
</template>`
 An error has occurred in this template.
error info : component template should contain exactly one root element

solve problem with this:
`<template>
  <div>
  <el-button @click="refreshTable" >button</el-button>
  <el-table :data="tableData" stripe fit style="width: 100%">
    <el-table-column v-for="columnInfo in hospitalThead" :prop="columnInfo.name" :label="columnInfo.label" width="180"></el-table-column>
  </el-table>
    </div>
</template>`

**Comment by solidevolution** [comment]
@xchz This is not the problem. I think anyone here knows that. 
We all had version conflicts in special cases, me as example while using pug/jade and the newest vue-loader version.

**Comment by xchz** [comment]
@solidevolution ok....

**Comment by yordis** [comment]
@yyx990803 could you explain the reasons why this is required on 2.0? I just want to learn about  the core.

**Comment by gholol** [comment]
Ping @yyx990803 as I would like to know it as well.

**Comment by nbdavies** [comment]
I'm trying to create a component consisting of two table rows (<tr>), and then have that component repeated for a collection of things. So it isn't a situation where they can neatly have a single parent element, or I would've used the simpler iteration (using <tr v-for="thing in things>).

**Comment by harrywong** [comment]
I also try to add two component into one table row, but with this limitation, i can't easily do this. so please give some options. thanks.

**Comment by LinusBorg** [comment]
This issue is closed, Please use the forum for questions.

forum.vuejs.org
