### ISSUE TITLE
script module can not be compiled

### ISSUE THREAD

**Issue by rachardking** [vuejs/vue-loader#385]
like this, there are may comment， and can not be comiled
` 
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //
    //

```
export default {

   }
```

`

**Comment by yyx990803** [comment]
Cannot reproduce. **Make sure to at least provide the webpack and vue-loader versions in your bug reports. We cannot help you without sufficient information.**

**Comment by woota** [comment]
vue.js 从 1.x 升级到 2.0.1 时出现了类似的问题：
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	
	import SideBar from './sidebar.vue';

webpack 和 vue-loader 的版本分别是：1.13.2 和 9.5.1。

**Comment by woota** [comment]
我暂时通过把 ES2015 的模块写法换成 CommonJS 的写法，避免了这个问题。

**Comment by zhangfisher** [comment]
同样的问题，es6写法的vue文件不能编译
webpack.config配置如下:
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            }, 
            {
                test: /\.js$/,
                exclude: [/(node_modules)/,/(jquery)/,/(semantic)/],
                loader: 'babel',
                query: {
                    presets: ['es2015','stage-0']
                }
            }
package.json安装的包如下：
    "babel-core": "^6.18.0",
    "babel-loader": "^6.2.7",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-register": "^6.18.0",
    "bundle-loader": "^0.5.4",
    "css-loader": "^0.23.1",
    "echarts": "^3.2.3",
    "file-loader": "^0.9.0",
    "imports-loader": "^0.6.5",
    "jquery": "^3.1.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "rxjs": "^5.0.0-rc.1",
    "scriptjs": "^2.5.8",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue": "^2.0.3",
    "vue-loader": "^9.7.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1",
    "vue-style-loader": "^1.0.0",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^2.1.1",
    "ztree": "^3.5.24"


如果将vue-loader降级到7.x则是可以正常编译的，但7.x又不支持vue2，所以问题还不知道怎么解决。

**Comment by zhangfisher** [comment]
猜想可能是vue-loader因为某些原因，比如与babel冲突等，导致js没有被转成es5，而原样输出es6语法。

**Comment by zhangfisher** [comment]
问题已经解决!

原因是我没有配置.babelrc文件，而在7.x时，貌似不需要依赖.babelrc文件，而在升级到最新
9.x后，如果没有.babelrc文件配置，会导致js文件不能编译为es5。

**Comment by kazupon** [comment]
close (inactivity)
