### ISSUE TITLE
Redundant scoped attributes

### ISSUE THREAD

**Issue by edmandiesamonte** [vuejs/vue-loader#386]
I noticed that the compiled output of a scoped component has redundant attributes
```
<template>
    <button class="root shared">
        <i>Something</i><h4>Hello World</h4>
        <ul>
            <li>Testing</li>
            <li>Testing</li>
            <li>Testing</li>
        </ul>
    </button>
</template>

<script>
    export default {
        mounted() {
            console.log( 'Component ready.' )
        }
    }
</script>
<style lang="sass" rel="stylesheet/scss" scoped>
    .root {
        font-size: 12px;
        font-weight: bold;
    }
</style>
```

... generates
```
<button data-v-1 class="root shared">
    <i data-v-1>Something</i>
    <h4 data-v-1>Hello World</h4> 
    <ul data-v-1>
        <li data-v-1>Testing</li> 
        <li data-v-1>Testing</li> 
        <li data-v-1>Testing</li>
    </ul>
</button>
```

Notice the multiple `data-v-1` attribute. Even in SCSS those attributes are used instead of just using the root attribute (i.e. output: `root h4[data-v-1] {...}` which should just be `root[data-v-1] h4 {...}`

Is there a way we can minimized this?

**Comment by yyx990803** [comment]
There is a fundamental difference between `root h4[data-v-1] {...}` and `root[data-v-1] h4`: the former only affects the `h4`s inside **this component only**, the latter will affect all `h4`s nested inside, even in child components. So no, this is necessary for correct scoped CSS.
