### ISSUE TITLE
coverage report include node_modules

### ISSUE THREAD

**Issue by xiaoyunchen** [vuejs/vue-loader#388]
First of all, I try to search and resolve this problem by myself,but failed,so i need you help.

I'm using [vuejs-templates](https://github.com/vuejs-templates/webpack) to running the Vue Component Unit & e2e Test

the Vue-Loader using the inject-loader 
so the Vue files in the folder node_modules are also be injected
and coverage report include then too

So,how exclude the files from node_modules,and so thanks!

**Comment by coolhatharry** [comment]
What you can do is exclude directories in your test runner (using Karma)
```      
postLoaders: [
      {
        test: /\.js$/,
        exclude: /(test|node_modules)\//,
        loader: 'istanbul-instrumenter',
      },
      {
        test: /\.vue$/,
        loader: 'istanbul-instrumenter',
        include: projectRoot,
        exclude: /(test|node_modules)\//,
      },
    ],
```

**Comment by xiaoyunchen** [comment]
so thanks for your helps,but i got some other errors below when push these postLoaders for web pack:
`webpackConfig.module.postLoaders = webpackConfig.module.postLoaders || []
webpackConfig.module.postLoaders.push({
  test: /\.js$/,
  exclude: /(test|node_modules)\//,
  loader: 'istanbul-instrumenter',
})
webpackConfig.module.postLoaders.push({
  test: /\.vue$/,
  loader: 'istanbul-instrumenter',
  include: projectRoot,
  exclude: /(test|node_modules)\//,
})
`

`ERROR [coverage]: TypeError: Cannot read property 'skip' of undefined
    at /Users/xiaoyun/gitlab/myproject/node_modules/.npminstall/istanbul/0.4.5/istanbul/lib/object-utils.js:110:42`

so any ideas about the issue and thanks again

**Comment by kazupon** [comment]
Resolve?

**Comment by kazupon** [comment]
Close (inactivity)
