### ISSUE TITLE
[Vue 2.0.1] Object.assign not working with webpack 2 and buble-loader

### ISSUE THREAD

**Issue by dschissler** [vuejs/vue-loader#389]
Using: 
* Webpack 2
* Vue 2.0
* buble-loader
* vue-loader

I'll mention that I'm new to Vue starting with 2.0.

Object.assign `...` works in normal javascript files because I added `objectAssign: 'Object.assign'` to the query section of the main buble loader settings but it doesn't allow spread operations in the JS of .vue files.

I've tried a lot of variations with the LoaderOptionsPlugin but that doesn't seem to help:

```javascript
    new LoaderOptionsPlugin({
      options: {
        postcss: postcssSetup,
        vue: {
          postcss: postcssSetup,
          buble: {
            objectAssign: 'Object.assign',

            query: {
              objectAssign: 'Object.assign',
            }
          }
        },
        buble: {
          query: {
            objectAssign: 'Object.assign',
          },
          objectAssign: 'Object.assign',
        }
      },
    })
```

This also only works for normal .js files (but the modules setting goes through to buble in both environements).

```javascript
      {
        test: /\.js?$/,
        loaders: 'buble',
        query: {
          objectAssign: 'Object.assign',
          transforms: {
            modules: false,
            forOf: false
          }
        }
      }, {
```

**Comment by yyx990803** [comment]
You can now configure buble via `vue.buble` in 9.7.0.

**Comment by dschissler** [comment]
Thanks.  Other than the great feature set this is why I switched to Vue.  Stuff gets fixed around here.

**Comment by dschissler** [comment]
For those confused, the configurations must be used once for the buble-loader setup and once for Vue.  With Webpack 2 these Buble options for vue-loader must go into a `LoaderOptionsPlugin`.

**Comment by oldskool73** [comment]
@dschissler : I'm still confused :( Any chance of an idiots example of how you go this working? Thanks.

**Comment by dschissler** [comment]
Here is the loader setup: https://github.com/perchlayer/webird/blob/master/dev/webpack.js#L155

Here is the loader options that is necessary due to `.vue` components: https://github.com/perchlayer/webird/blob/master/dev/webpack.js#L119

**Comment by oldskool73** [comment]
Thanks for the nudge in the right direction @dschissler. Your config didn't work for me though, as soon as I combined the loader options plugin with the `devtool: 'source-map` option all my styles started kicking up errors. 

However just adding the params to the loader strings did work...

```
module: {
		rules: [
			{ 
				test: /\.js$/, 
				loader: 'buble?objectAssign=Object.assign!eslint',
				exclude: /node_modules/
			},
			{
				enforce: 'pre',
				test: /\.vue$/,
				loader: 'eslint',
				exclude: /node_modules/
			},
			{
				test: /\.vue$/,
				loader: 'vue',
				options: {
					loaders: {
						js: 'buble?objectAssign=Object.assign'
					}
				},
				exclude: /node_modules/
			},
			{ 
				test: /\.less$/, 
				loader: ExtractTextPlugin.extract("css!postcss!less"),
				exclude: /node_modules/
			},
...
```

I also needed to add to my `.eslintrc` to stop it complaining...
```
"parserOptions": {
        "ecmaFeatures": {
        	"experimentalObjectRestSpread" : true
        }
},
```

Hope that info might help someone else that stumbles on this issue.

**Comment by dschissler** [comment]
It looks like you are using Webpack 1 or a very early version of Webpack 2.

**Comment by oldskool73** [comment]
@dschissler : don't think so, webpack version is `2.1.0-beta.25`. Just upgraded to `2.1.0-beta.27` and still working with the string params.... not gonna touch anything now in case it all falls apart again! :)

**Comment by dschissler** [comment]
Interesting because I read that the string parameters no longer worked and I seem to remember them breaking during an earlier beta upgrade.  Ok.  I can understand your desire to not want to endlessly fiddle with Webpack.
