### ISSUE TITLE
不能过滤空格!!

### ISSUE THREAD

**Issue by leyec** [vuejs/vue-loader#397]
尤大,你好!
display:inline-block 因为空格会产生间隙,怎么做才可以在打包的时候过滤掉标签之间的空格呢?

我的webpack配置:
vue: {
	html: {
		collapseInlineTagWhitespace: true,
		collapseWhitespace: true,
		conservativeCollapse: false
	}
}

**Comment by egoist** [comment]
Fix this in your CSS instead of webpack...

**Comment by leyec** [comment]
如果webpack可以,不是更好吗?压缩之后标签之间空格本来就没什么必要呀!

**Comment by yyx990803** [comment]
With 9.6.0, use `preserveWhitespace: false` in vue-loader options.

**Comment by yyx990803** [comment]
忘了说了，要等 Vue 本身升级到 2.0.3

**Comment by LikeDege** [comment]
@yyx990803 尤大，你好！

添加preserveWhitespace: false后，报错
```
{
  preserveWhitespace: false,
  postcss: [
    require('autoprefixer')({
      browsers: ['last 3 versions']
    })
  ]
}
```

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
```

**Comment by LikeDege** [comment]
@yyx990803 升级webpack就好了。

**Comment by herrdu** [comment]
在vue-loader 15版本以后，preserveWhitespace 被移动到了 compilerOptions 下面。 
文档：https://vue-loader.vuejs.org/options.html#compileroptions
