### ISSUE TITLE
9.5.2 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by greennyreborn** [vuejs/vue-loader#398]
### Vue.js version

2.0.2

### vue-loader version

\>= 9.5.2

### Reproduction Link

Please check this demo [repository](https://github.com/greennyreborn/vue-loader-bug).

### Steps to reproduce

The current component:
>File name: src/components/test.vue

```js
<template>
  <div>
    <test></test>
  </div>
</template>

<script>
import test from './test/test.vue'
console.dir(test.name)

export default {
  components: {
    test
  }
}
</script>
```

The child component:
>File name: src/components/test/test.vue

```js
<template>
  <div>
    <p> {{ test }}</p>
  </div>
</template>
<script>
export default {
  data () {
    return {
      test: 'hello test'
    }
  }
}
</script>
```

### What is Expected?

```html
hello test
```

### What is actually happening?

Console throws error:

```
Uncaught RangeError: Maximum call stack size exceeded
```

### My thoughts

I use 'test' -- the child component in the single file component whose file name happens to be 'test', too. And it leads to  ```Recursive Component``` behaviour which causes ```Maximum call stack size exceeded``` eventually.

So I did a little research and found there was a commit [Provide default for name option(#396)](https://github.com/vuejs/vue-loader/commit/cd358d62497b475188c999e66a6c7c1598fd23bb) in vue-loader 9.5.2. It simply added a feature that **Use the filename to set a component's name option, if one isn't provided. This allows more helpful debugging messages by default**. I believe this causes the problem.

See, I don't provide a name for the current component. According to this commit, vue-loader will name it as the file name (which is 'test' in my case). As a result, this component will invoke itself which is not my intention. I intended to invoke another component called 'test'.

However, I'm not sure if this is a bug. But it does causes some confusion for beginners.

**Comment by leyec** [comment]
I have the same question.
Maximum call stack size exceeded
and
some component created 2 loop

**Comment by leyec** [comment]
I hav resolve this question,
name the filename of component unique in vue-loader 9.5.3,
I think it's a bug!

**Comment by yyx990803** [comment]
Reverted in 9.6.0.

**Comment by lewiscutey** [comment]
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at compileToFunctions (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:9021:28)
    at VueComponent.Vue$3.$mount (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:9282:19)
    at init (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:2934:15)
    at createComponent (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:4653:11)
    at createElm (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:4596:11)
    at VueComponent.patch [as __patch__] (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:5052:9)
    at VueComponent.Vue._update (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:2042:21)

**Comment by LinusBorg** [comment]
Please open new issues for bugs you find, old, closed issues are not tracked anymore.
