### ISSUE TITLE
引入的js文件，该如何写

### ISSUE THREAD

**Issue by zhaowx** [vuejs/vue-loader#399]
官网介绍说‘If you prefer splitting up your *.vue components into multiple files, you can use the src attribute to import an external file for a language block:’。 
能否给一个demo 示例？ 找了很久也没有找到。  不知道js文件的内容应该如何写。
多谢～

**Comment by yyx990803** [comment]
`<script src="./script.js"></script>`

``` js
// script.js
export default {
  // ...
}
```

**Comment by zhaowx** [comment]
export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}

这样？ 
不起作用啊，😢
