### ISSUE TITLE
请问为啥.vue文件里必须是vueOptions对象，而不能是Vue.extend({})的class？

### ISSUE THREAD

**Issue by sy890622** [vuejs/vue-loader#4]
Hi 哥们，
我这里把vue和webpack组合，cmd的模块加载机制。
我看loader里定义的.vue里面是vueOptions对象，但我们的模块都写成了 module.exports = Vue.extend({}); 这样的类，我可能还会拦截里面的created事件什么的，请问哪种是推荐的做法？
因为vue loader现在的机制我没法定义viewmodel class的模块了

**Comment by yyx990803** [comment]
不一定得是对象，直接 export class 也可以的。export 对象的好处是不用每个文件都 `require('vue')`，写单元测试也比较简单。

**Comment by sy890622** [comment]
export class的话，我看了下output的js，template属性不工作了，必须得是exportedClass.extend({template: templ});才能正确工作，但实际导出的是 exportedClass.template = templ

**Comment by yyx990803** [comment]
啊，确实。刚发布了 vue-component-compiler 1.1.8，现在支持导出 class 了。

**Comment by sy890622** [comment]
我没看到最新的1.1.8啊。。还是1.1.7
