### ISSUE TITLE
timestamp when reloading

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs/vue-loader#400]
Not sure if this is related to `vue-loader` or webpack, but is there anyway to add the timestamp for the console output while using `npm run dev` when the content was last rebuilt/reloaded?

The content is reloading on the fly, but looking at the console output it is difficult to know when the last reload took place. Adding the date-time of the reload in the output could help. For example,

```
webpack: bundle is now VALID (@ 13-Oct-2016 18:30)
```

This helps, since sometimes the rebuild does not happen, such as for any changes in the `webpack.base.conf` or similar files, the reloader is not working (and we have to manually run the `npm run dev` again to make the configuration change take effect). 

Currently the console output only shown the build time duration and not the actual date-time when it happens.

**Comment by shershen08** [comment]
I'll take a look and try to implement that feature in a fork

**Comment by yyx990803** [comment]
Closing outdated issues - if your issue still persists in the latest version of `vue-loader`, please file new one using [the issue helper](http://new-issue.vuejs.org/?repo=vuejs/vue-loader), thank you!

---

(This request should be for webpack not vue-loader anyway)
