### ISSUE TITLE
how to add another html page?

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs/vue-loader#401]
I am using the vue sample project generated by the CLI.

It is working fine with the index.html. Now, I have added another `person.html` page next to the `index.html` page (in the same folder) and when run `npm run dev` the location `localhost:8080/person.html` is not being resolved (getting `Cannot GET /person.html` error).

Added a link to the `person.html` inside the `index.html` - did not help.

Please inform, how to have multiple top level pages (at the same level as the index.html)?

**Comment by ijse** [comment]
You need proxy pass GET html request from `/*` to `/index.html`.
If you use anywhere as static serice, you can do:

```
anywhere -p 8000 -f /index.html
```

**Comment by KrishnaPG** [comment]
The `index.html` is being served fine. It is any other extra page added that is not being output into the `dest` folder.

**Comment by LinusBorg** [comment]
This belongs into the repo of the template: github.com/vuejs-templates/webpack
