### ISSUE TITLE
"webpack": "^1.13.2","vue-loader": "^9.6.0" 不能过滤空格

### ISSUE THREAD

**Issue by leyec** [vuejs/vue-loader#404]
谢谢尤大的邮件答复,
测试了几次问题依旧,
"webpack": "^1.13.2","vue-loader": "^9.6.0", 不能过滤空格,是不是我哪里疏漏了?这个配置在 8.5.2 是可以过滤空格的

`vue: {
		html: {
			preserveWhitespace: false
		}
	}`
下面3项加上或者去掉也都不行
`collapseInlineTagWhitespace: true,
			collapseWhitespace: true,
			conservativeCollapse: false,`

**Comment by yyx990803** [comment]
我的回复你看懂了没有啊...

1.  Vue 本身要更新到 2.0.3
2. `preserveWhitespace` 不要嵌套在 `html` 里面
