### ISSUE TITLE
jade已经改名pug

### ISSUE THREAD

**Issue by evolutionjay** [vuejs/vue-loader#405]
请更正 
```html
<template lang='jade'>
```
改为
```html
<template lang='pug'>
```

**Comment by evolutionjay** [comment]
哦～ 我看到 closed 的 #213 说了这个问题， Sorry

**Comment by yyx990803** [comment]
这种问题不属于 bug，请别开 issue，学会直接发 PR。

**Comment by franz-josef-kaiser** [comment]
@yyx990803 @evolutionjay Could you please use English on PRs and issues? Thanks.
