### ISSUE TITLE
when extracting less into a single css file, hot-reload can't work

### ISSUE THREAD

**Issue by emptyx** [vuejs/vue-loader#406]
Actually, I have seed the same issues and you suggested not to use ExtractTextPlugin in dev. But since vue2.0 has supported server-render, so I think ExtractTextPlugin is also useful in dev. So,how can I resolve this problem or at least I can refresh page automatically by webpack. Thank you!

**Comment by yyx990803** [comment]
Hot reload doesn't work when using extraction.
