### ISSUE TITLE
Can't build without vue dependency.

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue-loader#408]
By default, if `env !== production`  for bundle i need vue, it needed for work hot reload.
But if i want bundle my files without production env i got error in console about `vue module not founded`
How i can bundle my packeges without production env and without hot reload?

P.S. I must use vue-loader for full compability with vue2, for precompile templates.

**Comment by kazupon** [comment]
You need to create a `vue-cli` template.
I recommend you customize from forked [webpack-simple](https://github.com/vuejs-templates/webpack-simple) based.
the other,  Also there is [vue-template-loader](https://github.com/ktsn/vue-template-loader) by using vue-template-compiler.
