### ISSUE TITLE
Extracting CSS publicPath issues

### ISSUE THREAD

**Issue by milkmidi** [vuejs/vue-loader#410]
webpack.config.js
  vue: {
        loaders: {
            stylus: ExtractTextPlugin.extract( `css!stylus`, {
                publicPath: '../../../'
            })
        }
    },

export.css 
background-image:url( ../ )  
path always '../'

Thanks

**Comment by githoniel** [comment]
me too, publicPath: '../'  just no effect, 
and  when i use 
```
return ExtractTextPlugin.extract('vue-style-loader', sourceLoader,{
	publicPath: "./../"
})
```

webpack error with 'can't resolve file'

**Comment by yyx990803** [comment]
Not really sure if this is `vue-loader` related. Looks more like an `extract-text-webpack-plugin` issue. Also, I'd suggest using an absolute path instead of a relative path...
