### ISSUE TITLE
Style attribute with background-image

### ISSUE THREAD

**Issue by Tibo-le-canard** [vuejs/vue-loader#411]
Hello,

I just did a fresh install of webpack-simple. 
I was playing with the App.vue under npm run dev.
And I added a background-image in the style attribute of #app.

`<div id="app" style="background-image: url('./assets/main.png')"> ...
 </div>`

Nothing happened and no error when the file doesn't exist.
But If I move the background-image attribute in the `<style></style>` everything is okay.

`#app {
    background-image: url('./assets/logo.pngd');
}`

Maybe it's not an issue but I'd rather report it, just in case.
Thank you for your work !

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to use `url-loader` and `transformToRequire` option.

Thanks.
