### ISSUE TITLE
Support theming through attributes on style tags

### ISSUE THREAD

**Issue by zephraph** [vuejs/vue-loader#413]
``` html
<style lang="stylus">
  p
    color black
</style>

<style lang="stylus" theme="light">
  p
    color white
</style>
```

I'd like to be able to create component themes given an attribute name. Idealistically no theme attribute would roll up into the default css file and style blocks with the theme attribute would roll up in a css file of that name. 

I'm willing to do the leg work on this and put in a PR if it sounds reasonable.

**Comment by nblackburn** [comment]
I don't feel like this is relevant to vue-loader or something universally useful.

**Comment by zephraph** [comment]
You might be right in that it deals with more than vue-loader. The `theme` attribute, in particular, is unimportant. What I'd like to be able to do is have attributes pass through from vue-loader to the style blocks that eventually get injected into the browser. 

Generating separate stylesheets entirely would likely be handled by a modified version of the extract text plugin or something.

**Comment by kazupon** [comment]
Close (implementing custom blocks with #499)
