### ISSUE TITLE
Empty template tag causes an error

### ISSUE THREAD

**Issue by nblackburn** [vuejs/vue-loader#414]
I have a view that is is rendered inside a popup window to deal with oauth callbacks but because this view doesn't have the need to display anything, i have not put anything within the template tag.

Because the `__location` property is not available when the tag is empty, the following error is caused:

``` bash
ERROR in ./app/views/oauth/callback.vue
Module build failed: TypeError: Cannot read property '__location' of undefined
    at node_modules\vue-loader\lib\parser.js:99:35
    at Array.forEach (native)
    at module.exports (node_modules\vue-loader\lib\parser.js:38:23)
    at Object.module.exports (node_modules\vue-loader\lib\loader.js:168:15)
 @ ./app/config/routes.js 12:0-48
 @ ./app/initialize.js
```
## Steps to reproduce
- Create a vue file with an empty template tag.
- Run webpack.

Removing the tag entirely works but feel an empty tag should be no different.

**Comment by kazupon** [comment]
Thank you for your filling.
However, I could not reproduce.
Could you provide minimum reproduce code please?

**Comment by kazupon** [comment]
Close (inactivity, passed 5 days, and due to be able not to reproduce)
