### ISSUE TITLE
Mixin lazy loading failing with components

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs/vue-loader#418]
A mixin loaded asynchronously inside a component, as below
````
const pagecontentAjaxMixin = resolve => require(['components/pagecontent-ajax-mixin'], resolve);
export default {
	mixins:[
		pagecontentAjaxMixin
	],
}
````
is leading to errors 
````
Property or method "xyz" is not defined on the instance but referenced during render
````
Doing a direct `import` of the mixin without the lazy-loading is working fine.

But direct import is injecting the mix-in code directly into component (and if we have multiple components it is found to be injected into all components, unnecessarily increasing the size).

Mixins, by definition are common code and would be great if they can be separate and asynchronously  loaded (without having to statically inject the code into each component)

**Comment by yyx990803** [comment]
Vue only supports async components, never supported async mixin...
