### ISSUE TITLE
Vue-Loader for generating styleguides

### ISSUE THREAD

**Issue by iamkether** [vuejs/vue-loader#423]
I've been thinking about styleguides over the last few days after a discussion in the Vue slack channel with Alexander Hofstede. I'm not entirely sure if this would actually be something that would fit inside of the scope of Vue-Loader, but I think this is where it makes _the most sense_ to at least start the discussion because the syntax I'm thinking of is quite related to Vue-Loader's existing component spec. I published a [gist](https://gist.github.com/iamkether/7f03c7f4397dee6a92e646e6aa718e05) outlining the deeper ideas and reasoning, but the general idea is to add one more tag to the Vue-Loader component spec:

```
<styleguide lang="markdown">
  This area would allow virtually any kind of markdown text, comments, etc. 
</styleguide>

<template>
  // ...
</template>

<script>
  // ...
</script>

<style>
  // ...
</style>
```

And then we could use the markup from that tag to generate a component tree/styleguide based on the structure of existing projects.

**Comment by aphofstede** [comment]
Interesting. I think keeping the documentation close to the component it describes is an excellent idea (for Vue); It seems to fit the general paradigm of small scopes and self-contained components. A similar argument could be made for including tests in components' Vue files as well. 

I guess the primary discussion would come down to "how much crap do we want people to put in their Vue components' source?". I don't know the history and vision of Vue well, so I'd be interested to hear their point of view.

CSS- / JS doc can definitely be parsed to enrich the generated style guide; same goes for the Vue component's props.

On a side note / FYI: In [semantic-react](https://github.com/hallister/semantic-react), which uses [react-styleguidist](https://github.com/sapegin/react-styleguidist), they put their components in [subfolders](https://github.com/hallister/semantic-react/tree/master/src/components/elements/divider) and have their tests and examples (style guide) next to, but not in, their components.

**Comment by iamkether** [comment]
@aphofstede quite valid points and after looking at the level of documentation for some of the components in that semantic-react library, I can tell I was underestimating the level of complexity for the documentation requirements.

**Comment by egoist** [comment]
This would play nice with https://github.com/vue-play/vue-play 😃 It accepts an `readme` property to display something like `styleguide`

**Comment by iamkether** [comment]
@egoist My only concern with the `vue-play` format is that it feels separate from the Vue-Loader Component spec. I feel like a Vue-Loader styleguide (or separate but related library as it's looking the more research and thinking I do about this) should feel part of one coherent whole the way the rest of the offical Vuejs libraries do. I'm also concerned with requiring designers to be writing javascript if they're just trying to output a page for color palettes, brand guidelines, or typography.

@aphofstede to go along with the semantic-react library, I think the [Pivotal styleguide](http://styleguide.pivotal.io/) is also a really good example of the depths of complexity to be considered. That styleguide is also on a [repo](https://github.com/pivotal-cf/pivotal-ui/blob/development/styleguide/docs/react/autocomplete.js) for reference. The robustness of their documentation is fantastic, but this:

```
/*doc
 ---
 title: onSearch
 name: autocomplete_onsearch
 parent: autocomplete_react
 ---
 // ... additional markdown stuff
*/
```

Could easily be done like this:

```
<styleguide title="Autocomplete" parent="App Components">
    <section title="onSearch">
          // ... additional markdown stuff
    </section>
</styleguide>
```

Or even easier if we use the src attribute like in the Vue-loader component spec:

```
<styleguide title="Autocomplete" parent="App Components">
    <section title="onSearch" src="./onSearch.md"></section>
</styleguide>
```

**Comment by iamkether** [comment]
Just a one-off thought as well, but the `src` attribute could be used to start helping teams do some degree of auto-generated documentation for 3rd party components/libraries as well. 

For example, if there was a Vuejs Grid package some app team was using, and the Grid package's repo already had some form of styleguide written in our format above, it would allow developers to just do `<styleguide src="vuejs-grid/vuejs-grid.styleguide.vue" parent="3rd Party Libraries">`. At the very least, they could also just do `<styleguide src="vuejs-grid/readme.md" parent="3rd Party Libraries">`. 

I'm not sure how useful this would be in actual practice, but what I am thinking is that it would be great, for example, for version locking documentation of 3rd party libraries to an app. I can't tell you the number of times I've had to go googling hard for old versions of Bootstrap or Foundation on projects that came back several years later and want updates. Or, even more commonly, going to read documentation on a library in a repo, only to find that the library has re-written their api and there's little or no documentation online of their old api that the project is currently using.

**Comment by kazupon** [comment]
custom blocks was released
close
