### ISSUE TITLE
Useless code added into the bundle

### ISSUE THREAD

**Issue by 403177368** [vuejs/vue-loader#425]
a same piece of code  as follows will be generated and added into the final bundle for every .vue file get bundled using webpack.
If(false)
  Module.hot.accept()
  Hotapi.update(id...
i tried to delete them and nothing went wrong anyway.
So how could I get them removed automatically?

**Comment by LinusBorg** [comment]
thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service, if nessessary a repository) that reproduces the problem.


Thank you.

**Comment by rmp135** [comment]
This is because webpack in running in development mode. Enable building in production mode by setting the NODE_ENV environment variable to 'production', or running `webpack -p`.

**Comment by LinusBorg** [comment]
And then, this code would be removed by uglify during compression.

**Comment by rmp135** [comment]
The code is actually [removed in the loader](https://github.com/vuejs/vue-loader/blob/39978d8df2ebd2b299d523f552c96ca6ffe82679/lib/loader.js#L292), but you're right it would have been removed by UglifyJS anyway.

**Comment by 403177368** [comment]
thanks fellas
