### ISSUE TITLE
Duplicated addStyles.js module

### ISSUE THREAD

**Issue by 403177368** [vuejs/vue-loader#426]
addStyles.js module used by style-loader and that used by vue-style-loader seem slightly different and both got bundled, and sometimes caused strange problem that every chunk generated using code-splitting has a addStyles module.
Wired.

**Comment by LinusBorg** [comment]
thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service, if nessessary a repsoitory) that reproduces the problem.

Thank you.

**Comment by kazupon** [comment]
close (inactivity)
