### ISSUE TITLE
Strict Mode Error w/ Webpack 2.0.1-beta

### ISSUE THREAD

**Issue by kyledecot** [vuejs/vue-loader#427]
In my vue application I upgraded webpack to 2.0.1-beta (to try out the new tree shaking feature) and not I am getting the following error:

```
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-2fbe5406!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/App.vue
Module parse failed: /Users/kyledecot/Development/Personal/repos/lorem/node_modules/vue-loader/lib/template-compiler.js?id=data-v-2fbe5406!/Users/kyledecot/Development/Personal/repos/lorem/node_modules/vue-loader/lib/selector.js?type=template&index=0!/Users/kyledecot/Development/Personal/repos/lorem/src/components/App.vue 'with' in strict mode (1:35)
You may need an appropriate loader to handle this file type.
| module.exports={render:function (){with(this) {
|   return _h('div', {
|     attrs: {
 @ ./src/components/App.vue 7:23-143
```

Has anyone else seen this error or successfully used vue-loader w/ the new beta of webpack?

Update: I should also note that my application was created using `vue-cli` so my webpack config was created from that.

**Comment by LinusBorg** [comment]
See here: #4115. Workaround is outlined there.

This has to be solved in Vue's template compiler, so I will close this for now.

**Comment by kyledecot** [comment]
https://github.com/vuejs/vue/issues/4115

**Comment by LinusBorg** [comment]
Oh, right. Thanks for the correcion :+1:
