### ISSUE TITLE
[Features] Support require.ensure() in webpack 2.0

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue-loader#431]
I find that `require.ensure()` doesn't works well in webpack@2.0, and the lazy loading demo also support use `System.import()` to replace `require.ensure()`. But `System.import()` doesn't support put multi-component in one file, Is there a plan to support it?

**Comment by LinusBorg** [comment]
Hello @leaves4j ,

thank you for your filing this issue.

"doesn't work well" is not a very helpful description of your problem. Can you elaborate?

Also, please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by leaves4j** [comment]
In `vue-router`, If I  lazy loading a component with `require.ensure()`, when I change the route, the inactive component can't become active, but change to use `System.import()`, it works well

**Comment by LinusBorg** [comment]
> Also, please follow the guidelines on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.

Please help use help you by saving us some time with this. Thank you.

**Comment by zweifisch** [comment]
@leaves4j you don't need `require.ensure()`, there is async component, which is well supported in webpack

```
Vue.component('ast-viewer', resolve => require(['./components/AstViewer'], resolve))
```

use with `vue-router`

```
{
      path: '/',
      component: resolve => require(['./containers/Home'], resolve)
}
```

**Comment by kazupon** [comment]
Close (inactivity)
