### ISSUE TITLE
render function is lost when used in Constructor style

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/vue-loader#432]
minimal reproduction

``` typescript
import Vue from 'vue'
var Users = Vue.extend({})
Users['options'].render = (h) => h('h1', 'hhhh')
Vue.mixin({}) // mixin here will break render

const app = new Vue({
  el: '#root',
  components: { Users: Users },
  render: h => h('users')
})
```

Related:
https://github.com/vuejs/vue/issues/4052

Problem:
 `resolveConstructorOptionis` only recomputes options with `superOptionis` and `extendOptions`. But vue-loader only change `Ctor.options` which is lost after `Vue.mixin`

**Comment by yyx990803** [comment]
Fixed in core (https://github.com/vuejs/vue/commit/09f9783943613ee732c5b45951907fd069322f7d)
