### ISSUE TITLE
Using scoped css in v-html generated elements

### ISSUE THREAD

**Issue by dcefram** [vuejs/vue-loader#436]
I filed this issue in vuejs issue tracker (vuejs/vue#4078), which was the wrong place to file this issue. Sorry xD. Here's the copy-paste:

First off, I'm aware that #3045 was filed before. But it is closed, and I would like to elaborate the special case that this would actually be needed, and how other tools actually accomplish this, along with suggestions on how to get this done.

## Scenario

First off, the case that I'm having is that I'm trying to style elements generated by a markdown parser. I wouldn't want the styles of a particular component mess up the styles of other components, so I would really prefer using `scoped` css.

**Sample code:**

```javascript
<template>
  <div class="some-component">
    <div class="contents" v-html="marked(value)"></div>
  </div>
</template>

<script>
import marked from 'marked';

export default {
  name: 'story',
  data() {
    return {
      value: '#Hello World',
    };
  },
  methods: {
    marked(value) {
      return marked(value);
    },
  },
};
</script>

<style lang="stylus" scoped>
.some-component
  
  h1
    color #F00
</style>
```

I could've used BEM or other approaches to do this, but I believe that Vue's `scoped` feature was intended to do what BEM was for, but just much cleaner and more elegant (in the source code at least).

Unfortunately, this wouldn't work since the generated html element won't have the unique identifier attribute that Vue would append to other elements, whilst the generated css would append that unique identifier to the `h1` style.

## How other tools compare

The only other tool that I ever used when using another view layer library was CSS Modules. Here's a sample code:

```javascript
render() {
  return (
    <div class={styles.someComponent}>
      {marked(this.props.value)}
    </div>
  );
}
```

```stylus
.someComponent

  h1
    color #F00
```

The code above would work properly, without the H1 styling mess up with the global H1 styles. Even if I have another component probably made by someone else, who has the same classname (`.someComponent`), it wouldn't still get the style of my H1, since css modules would replace/append unique strings to the class name, but at the same time, it wouldn't add anything to the h1.

On Vue's scoped approach, Vue seems to append a unique attribute even to element styles (those that are not classes or ids). So the style `h1` would be `h1[data-v-someuniquevalue]`.

## Suggestion (ie. my expected behavior)

Vue's scoped feature should just append a unique data-v-identifier to the root element of a component. Since Vue **requires** you to have only **one** root element for each component, I believe that is the best place to only append the unique identifier attribute.

The CSS should then be transpiled in such a way that it would not append attribute selectors, but rather, it would just prepend the parent element.

**Example:**
```
.some-component

  h1
    color #F00
```

should then be transpiled to:
```
[data-v-someuniqueid] h1 {
  color: #F00;
}
```

This way, it would still behave the same way as it is right now, but on the plus side, it would still be able to style any element added to a child element with a `v-html` attribute.

It would also mimic how css modules works, which is an extra plus for people coming from other libraries and were expecting a certain behavior to be the expected behavior... well, because that behavior makes more sense.

I would love to know what others would think, and obviously, since I believe there's only 2 of us who uses vue that is concerned with this behavior, it would be just fine if you someone can point out a workaround to this matter (without using BEM, or requiring me to name my classes in funny cryptic class names)

Thanks! And sorry in advance if ever I worded some sentences in a rude way.

**Comment by simplesmiler** [comment]
One issue is that styles would still bleed through.
``` css
[parent] div { padding: 10px; }
[child] div { color: blue; }
```
The child's div would have padding, because it in fact is matched by both `[child] div` and `[parent] div`.

**Comment by simplesmiler** [comment]
I think a better approach would be to expose the prefix during compilation, so that you coiuld use it in runtime for manually constructed HTML.

**Comment by dcefram** [comment]
I see what you mean, I didn't think of that scenario (components with other child components).

And on the other hand, I just found this: https://github.com/vuejs/vue-loader/pull/331. I'm not sure if this still works, since it's not documented anywhere anymore, but I'll give it a try later when I get back home from work.

If all else fails, I'll have to figure out how to expose/get the prefix somehow and use that on a non-scoped style block.

Thanks for the reply :)

**Comment by dcefram** [comment]
I just tried it out, and it does seem like #331 wasn't merged to v9.x (the rewriter file that he made isn't merged/added to vue-loader).

With that said, I'll have to figure out other ways to do this. Since I can't figure out how to get the prefix during compilation, I'll have to resort to BEM or just pull #331's changes to my machine.

But again, upon looking into what you said (`One issue is that styles would still bleed through.`), I believe this would be 'just fine' if the styles that would bleed through are from element selectors that do not have any class or id.

The following case should bleed to the child components
```css
[unique-id] div { color: red; } 
```

However, classes and IDs should not. One way to do this is to ensure that we append the unique id attribute to classes and IDs, but not to the generic element selectors (h1, div, etc.)

That's too much to ask for me, and I guess I was just expecting the `scoped` CSS to behave the same way as CSS Modules would, which I think isn't the objective of 'scoped' CSS.

So yeah, it would've been great if #331 was merged to v9.x of vue-loader :)

**Comment by PowerfulPony** [comment]
8* version has support css-modules, 9* not support, missed merge
scoped allows children to use ancestral classes, it should not be
Ideologically correct operation should be as css-modules

**Comment by dcefram** [comment]
So basically, why I would like css modules to get back to vue-loader, or at least if it is possible for `scoped` vue to mimic this behavior (though I'm not sure if `scoped` should mimic css-modules, since `scoped`'s objective is to mimic how [Shadow DOM behaves](http://vue-loader.vuejs.org/en/features/scoped-css.html)) is to resolve situations like authoring reusable components (like a markdown parser), but making sure that the styles wont bleed to other sibling components.

So basically, the behavior of css modules such as the following is ideal:

```javascript
<template>
  <div class="some-component">
    <div class="styles.content" v-html="marked(marked)" />
    <slot></slot>
  </div>
</template>

<style lang="scss" module="styles">
.content {
  padding: 5px;

  h3 {
    color: red;
  }
}
</style>
```

On the example above, `.content`'s styles will be unique to its own (padding 5px), even if other components have a class named `content`. 

However, the elements that were rendered on runtime through `v-html` will be colored red. Any child components added into `some-component` that has the `h3` tag will obviously inherit the color red. That's how CSS modules behave, and it is logical.

On the other hand, sibling components that have h3 will not inherit the color red, since according to the style, the parent of h3 should be `.content` (wherein css modules would replace/append that classname with some unique identifier string) for it to get colored red.

I hope what I am trying to explain is clear enough :)

**Comment by LinusBorg** [comment]
CSS modules arrived in vue-loader 9.8.0, so I think we can close this.
