### ISSUE TITLE
发现一个很奇葩的问题

### ISSUE THREAD

**Issue by luxueyan** [vuejs/vue-loader#440]
在webpack.base.conf.js 配置了autoprefixer，dev和production 都是用这个配置
![image](https://cloud.githubusercontent.com/assets/1555552/19959753/cd7f0126-a1e3-11e6-8c37-520fe942b691.png)

但是奇葩的问题来了，开发模式：display:flex; 编译后结果：
![image](https://cloud.githubusercontent.com/assets/1555552/19959805/10fe58de-a1e4-11e6-96c1-c64f4a626605.png)

npm run build 构建后的结果：
![image](https://cloud.githubusercontent.com/assets/1555552/19959816/248a74fa-a1e4-11e6-94c2-181e12a9f041.png)

结果不一样，少了一个display:-webkit-flex; 这导致我调试半天，找不到问题所在，我确认默认是用vue-cli生成的项目，然后添加了这个autoprefixer 的配置，求大侠们指点！

**Comment by luxueyan** [comment]
尼玛，找到问题了 貌似 uglifyjs 导致的webpack的bug，以至于css-loader出问题
https://github.com/postcss/autoprefixer/issues/660#issuecomment-220808316
https://github.com/webpack/webpack/issues/2543

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-loader/issues/234

这个不是 vue-loader 的问题了...
