### ISSUE TITLE
Vue CSS Composition

### ISSUE THREAD

**Issue by matheusazzi** [vuejs/vue-loader#441]
Hey guys, this isn't necessary an issue, but I've a question about how to do css compositions with Vue and the single-file-components.

Just to use as an example, in React and CSS modules I can do it:

```css
.btn { ... }

.btnDanger {
  composes: btn;
  color: red;
}
```
```jsx
<MyButton className="btnDanger">Delete</MyButton>
```
When it renders, it will include the composed class, rendering something like:

```html
<button class="btn btnDanger">Delete</button>
```

Basically if i've a class that composes others, when it renders, it'll include them all.

---

I know that Vue doesn't use CSS Modules, instead it has its own Component-Scoped CSS, and that's awesome, but I'm looking for a way to compose css.

My goals are: I don't want to use any kind of SASS @Include or @extend that will generate extra css. I want to use classes composition without having to add them to my template. Im looking for something like:

```html
<template>
  <button class="stop-button">Stop Now!!!</button>
</template>

<style>
  .stop-button {
    composes: btn, btnWide, btnDanger;
    height: 200px;
  }
</style>
```
That generates:
```html
<button class="btn btn-wide btn-danger stop-button">Stop Now!!!</button>
```

There's any way to get a similar behavior with single-file-components?

**Comment by matheusazzi** [comment]
To put more context:

I'm creating a huge styleguide, another example could be this:

```html
// Card.vue

<template>
  ...
  <h3 class="card-title card-text title title-3 title-bullet">{{title}}</h3>
  ...
</template>

<style>
  .card-text {
    ...
  }

  .card-title {
    padding: 10px;
    line-height: 1.6;
  }
</style>
```

Be written as:

```html
// Card.vue

<template>
  ...
  <h3 class="card-title">{{title}}</h3>
  ...
</template>

<style>
  .card-text {
    ...
  }

  .card-title {
    composes: cardText title title3 titleBullet;
    padding: 10px;
    line-height: 1.6;
  }
</style>
```

But the compiled result be the same as:
```html
<h3 class="card-title card-text title title-3 title-bullet">{{title}}</h3>
```

**Comment by LinusBorg** [comment]
AFAIK, the compose feature is a CSS Modules feature - but the good news is that vue-loader now supports that, too (new in `v9.8.0`):

* 
* https://vue-loader.vuejs.org/en/features/css-modules.html
