### ISSUE TITLE
HTML comments rendered as plain text.

### ISSUE THREAD

**Issue by sahibalejandro** [vuejs/vue-loader#443]
I have a fresh install of Laravel with `laravel-elixir-vue-2 0.2.0` and `vue-loader 9.7.0`, when .vue files are compiled, the HTML commends inside the component are rendered as plain text and I can see them in the navigator, the strange thing is that only "child" comments on their own line are rendered as plain text, but no the top-level comments, or comments an the end of the line.

Let me explain this with code:

```html
<template>
    <!-- Hidden, it's OK -->
    <div>
        <!-- Rendered as plain text, bad! -->
        <span>Hello world</span>
        <span>Foo Bar</span><!-- Hidden, it's OK -->
    </div>
</template>
```

I think is related with vue-loader because when I use browserify and vueify with the same proyect the comments works as expected.

Can anybody help?

**Comment by yyx990803** [comment]
This is a regression in 2.0.4 and will be fixed soon.
