### ISSUE TITLE
how to require postcss-import 

### ISSUE THREAD

**Issue by alidcastano** [vuejs/vue-loader#447]
Following the discussion in this [issue](https://github.com/vuejs/vue-loader/issues/74), I tried the two approaches discussed to configure `postcss-import`, and neither seem to work. When I try to import an npm package from a css file, it throws an error if the path is not prefixed with `node_modules`. 

```
vue: {
    postcss: [
      require('postcss-import')({addDependency: webpack}),
      require('autoprefixer')({ browsers: ['last 2 versions'] })
    ]
  }
```
```
  vue: {
    postcss: function (webpack) {
      return [
        require('postcss-import')({addDependency: webpack}),
        require('autoprefixer')({ browsers: ['last 2 versions'] })
      ]
    }
  }
```

Is it still possible to use `postcss-import` with the vue-loader, and if so, how?

**Comment by kazupon** [comment]
You need to require `postcss-cssnext`.

```
  vue: {
    postcss: [
      require('postcss-import')({ addDependency: webpack }),
      require('postcss-cssnext')(),
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ]
  }
```
