### ISSUE TITLE
Using a css-modules with hot.reload not updated computed props $style

### ISSUE THREAD

**Issue by PowerfulPony** [vuejs/vue-loader#450]
After initialization, styles, for example:
```
<style lang="stylus" module>
.classA
  background #000
</style>
```
It will be available for computed variable with the contents of the hash

```
// this.$style
{
  classA: 'style-hash-id'  
}
```

If we add another class
```
<style lang="stylus" module>
.classA
  background #000
.classB
  background #fff
</style>
```
variable `$style` is not update with HOT.RELOAD

Because of what has to reload the page for the new class

@YiSiWang because of what can this be?

**Comment by YiSiWang** [comment]
A repo to clone please?

**Comment by kazupon** [comment]
Close (inactivity, passed 5 days)
