### ISSUE TITLE
Changing element attribute/content which is inside slot don't trigger module reloading

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#455]
Hi  just go the repo https://github.com/sqal/vue-hot-reload-bug clone && npm run dev.  The issue is that when element is in default slot (in this case `<h1 class="red">Edit me</h1>`) and you try to change the class or the content of that element, you can see that hot reload of that module simply doesn't work.  But if you try to update some text which hasn't surrounding element (foo) then hot reload works correctly.

**Comment by LinusBorg** [comment]
Hello @sqal,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. (in this case, probably a small demo repo we can clone.)

Thank you.

**Comment by sqal** [comment]
Hii @LinusBorg how can I provide example of vue-loader bug on jsfiddle? I provided whole repo and simple description of the bug, I am not sure what else do you need :)

**Comment by LinusBorg** [comment]
Oh sorry, seems I somehow missed the repo link in todays "quick-review ALL the issues!"-run. :D

So thanks for the repro!

We will look into it, but be aware that we have some hot-reloading issues laying around already, as those are generally not high-priority (inconcenient, but nothing breaks), so it may take some time.

**Comment by yyx990803** [comment]
This has been addressed in Vue core and will be fixed in next release.

**Comment by sqal** [comment]
> This has been addressed in Vue core and will be fixed in next release.

Yup. It's working fine now. Thanks @yyx990803
