### ISSUE TITLE
[feature request][discussion welcome] Component Translation Section

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vue-loader#457]
Reusable components could be used in different language environments. That being said, we could benefit from having modular translations, by adding another section in single-file components we already use, probably JSON-based:

<translation>

```json
{
  "Select a color": {
    "ru": "Выберите цвет",
    "de": "wählen Sie eine Farbe"
  }
}
```
</translation>

**Comment by kazupon** [comment]
Close (implementing custom blocks with #499)
