### ISSUE TITLE
Not work with webpack.LoaderOptionsPlugin when using in SSR

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-loader#462]
It seems `vue-loader` is using `this.options.target === 'node'` to check if it's used on server-side, but after adding:

```js
{
  plugins: [
    new webpack.LoaderOptionsPlugin({options: {}})
  ]
}
```

`this.options` would be overridden

https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L42

**Comment by yyx990803** [comment]
See https://github.com/webpack/webpack/issues/2684

I think this is a webpack issue. For now just include `target` in your options...
