### ISSUE TITLE
Detect homepage in package.json to serve from github pages

### ISSUE THREAD

**Issue by marcosfede** [vuejs/vue-loader#463]
Hi! Not sure if this is the correct place to post this, but I'm currently using the webpack app generated using the vue-cli.

When I make an app and want to serve it from github pages,  the js and css resources can not be found because the route starts with /static/... 

with react-create-app , you could specify a "homepage: <link-to-your-ghpages-app>" in the package.json, and webpack modifies the assetsPublicPath appropriately so your app works when deployed. 

it would be nice if the vue-cli generated project looked for an option like that to ease deployment.

**Comment by yyx990803** [comment]
This should belong to the webpack template: https://github.com/vuejs-templates/webpack
