### ISSUE TITLE
Vue packages version mismatch error

### ISSUE THREAD

**Issue by jasonsanjose** [vuejs/vue-loader#470]
```
Vue packages version mismatch:

- vue@2.0.5
- vue-template-compiler@2.0.6

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.
```

In our project, we use exact dependencies:

```
    "vue": "2.0.5",
    "vue-loader": "9.7.0",
```

Since `vue-loader` uses caret ranges for `vue-template-compiler`...

```
"vue-template-compiler": "^2.0.5",
```

...when our Jenkins CI job runs `npm install`, the latest version of `vue-template-compiler` will get installed and will mismatch our `vue` version, causing random build failures whenever `vue-template-compiler` is upgraded.

A workaround suggested here https://github.com/vuejs/vue/issues/3941 is to re-install `vue-loader`. We would rather work with exact versions of our dependencies and choose on our own when to upgrade.

To make matters more difficult, we can't use shrinkwrap in our repository due to https://github.com/npm/npm/issues/2679.

Can `vue` or `vue-loader` address this case somehow?

**Comment by yyx990803** [comment]
Have you considered using yarn with a lockfile?

**Comment by jasonsanjose** [comment]
Not yet. Was hoping not to introduce a yet another tool to our build. :) 

We can give that a shot and report back.

It would be nice if this worked with `npm` or if dependencies were organized in a way where this problem doesn't happen in the first place.

**Comment by yyx990803** [comment]
Since your team seems to prefer a locked version approach, `yarn` would fit your workflow much better than npm, both for CI and for development as well - basically a better shrinkwrap. It's also in most cases a drop-in replacement for npm.

**Comment by ernestoalejo** [comment]
This should be fixed now in v10.0.0 according to the [changelog](https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#vue-loader1000).

Will that change reach vueify too or do I open a new issue there?

**Comment by mehranrasulian** [comment]
I have the same problem when I'm using Yarn. But when trying npm, gulp compiles the vue components without any problem:

using yarn:
```
Vue packages version mismatch:

- vue@2.1.3
- vue-template-compiler@2.0.3
``` 

my dev dependencies are:

    "devDependencies": {
      "gulp": "^3.9.1",
      "laravel-elixir": "^6.0.0-15",
      "laravel-elixir-vue-2": "^0.2.0",
      "laravel-elixir-webpack-official": "^1.0.9"

**Comment by mehranrasulian** [comment]
Just cleaned the yarn cache and tried again, now it works well !

**Comment by Kristjan-Reinsberg** [comment]
same mismatch problem with new spark 4.09 install.

**Comment by developerewt** [comment]
Fixed for me:

`npm install vue-template-compiler --save-dev`

    │ └─┬ vue-loader@9.9.5
    │   └── vue-template-compiler@2.2.6  deduped
    └─┬ vue-template-compiler@2.2.6 
      └──` he@1.1.1

**Comment by arvidkahl** [comment]
I'll just leave this here if the above does not work.

With yarn, the `yarn.lock` file can be manually changed to fix this issue. Some library requires a rather old version, so I found that changing the section in `yarn.lock` actually resolves this issue:

```
vue-template-compiler@^2.0.0-alpha.8, vue-template-compiler@^2.5.16:
  version "2.5.16"
  resolved "https://registry.yarnpkg.com/vue-template-compiler/-/vue-template-compiler-2.5.16.tgz#93b48570e56c720cdf3f051cc15287c26fbd04cb"
  dependencies:
    de-indent "^1.0.2"
    he "^1.1.0"
```

Relevant part here is `vue-template-compiler@^2.0.0-alpha.8, vue-template-compiler@^2.5.16:` which you might need to adjust for whatever older version you want or have to override.

**Comment by saikathalderr** [comment]
i Use Vue cli ui tool to update everything.
it's update everything automatically and then i start project successfully.

**Comment by MarkSonn** [comment]
For me it was because my Vue version was behind my vue-template-compiler by 4 patches (vue@2.6.6 vs vue-template-compiler@2.6.10). I just updated vue both globally and locally and everything worked.

So with Yarn as my package manager:
```
yarn global add vue
yarn add vue
```

**Comment by MarkSonn** [comment]
I'm so glad that I posted my above comment becuase I ran into the same issue and forgot how to solve it. This time, however, my vue-template-compiler was behind.

Get them both up-to-date globally with:
```
yarn global add vue
yarn global add vue-template-compiler
```

**Comment by soymizra** [comment]
> Fixed for me:
> 
> `npm install vue-template-compiler --save-dev`
> 
> ```
> │ └─┬ vue-loader@9.9.5
> │   └── vue-template-compiler@2.2.6  deduped
> └─┬ vue-template-compiler@2.2.6 
>   └──` he@1.1.1 
> ```

This was what I needed... Very thanks!

**Comment by SamuelSoaresSilva** [comment]
- vue@2.6.12 
- vue-template-compiler@2.7.16
```
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
``` 
Fixed for me:

```
npm i vue@2.7.16 --save-dev
``` 

I just needed to keep the version of Vue compatible with the compiler

**Comment by SamuelSoaresSilva** [comment]
.
