### ISSUE TITLE
support webpack v2.1.0-beta.26

### ISSUE THREAD

**Issue by chrisbraddock** [vuejs/vue-loader#471]
webpack beta 26 [removes '-loader' insertion](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26)

build starts reporting errors like:

```javascript
throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
```

Adding ['-loader' in the webpack configs seesm to do the trick](https://github.com/chrisbraddock/vue-devtools/commit/15c82f61d202b030b9d992753aca40a9539060a7) but one of the unit tests is failing so I didn't want to create a PR. I'm not sure if the test passed before the change or not since I couldn't run.

**Comment by riovir** [comment]
On a related note https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html advises to use ```const ExampleInjector = require('!!vue?inject!./example.vue')``` to create component injectors.

The proper syntax would be either of the following
```const ExampleInjector = require('!!vue-loader?inject!./example.vue')``` or
```const ExampleInjector = require('!!vue-loader?inject-loader!./example.vue')```

In either case however the loader bugs out at the moment, as it's attempting the use he inject loader without its fully specified name.

**Comment by yyx990803** [comment]
The latest version (10.0.2) should work with webpack 2 beta.27 and the tests have been updated to use that version too.

@riovir 10.0.2 should fix the problem with `inject-loader`. I've also found inject-loader@3.x to be unstable, but 2.x seems to work as expected.
