### ISSUE TITLE
template syntax error - invalid expression

### ISSUE THREAD

**Issue by vizo** [vuejs/vue-loader#473]
I get an error:

template syntax error - invalid expression:  {{ $intl.messageFormat({messageKey: 'NUM_PHOTOS', values: {numPhotos: 3}}) }}

So when i use in template
```
{{ $intl.messageFormat({messageKey: 'NUM_PHOTOS', values: {numPhotos: 3}}) }}
```
i get error but when i bind text to element, like
```
<span v-text="$intl.messageFormat({messageKey: 'NUM_PHOTOS', values: {numPhotos: 3}})"></span>
```
it works ....

I am using latest vue and latest vue-loader. 

Any thoughts?
Thanks

**Comment by vizo** [comment]
I guess it must be something with parsing of {{ }} brackets. So nested objects fails as expression ...

**Comment by kazupon** [comment]
Thanks for filing the issue! 
Can you provide  a minimal reproduction codes with GitHub repo please?

**Comment by kazupon** [comment]
Close (inactivity)
