### ISSUE TITLE
Chain loaders to vue html loader

### ISSUE THREAD

**Issue by thetutlage** [vuejs/vue-loader#475]
I have a situation where I want to chain my custom loader to the `template` part of the `.vue` file. I tried following the below approach but that results in an error called.`Failed to mount component: template or render function not defined. `

### webpack config
```javascript
{
  vue: {
    loaders: {
      html: 'vue-html!my-custom-load',
    }
  }
}
```

If I remove the `html` node from the loader object all works fine.

**Comment by ThomasRalee** [comment]
Any luck fixing "Failed to mount component: template or render function not defined." ? 
I am getting the same issue if i pipe it through html-loader

**Comment by kazupon** [comment]
support loader channing.
https://github.com/vuejs/vue-loader/releases/tag/v10.1.0

close.
