### ISSUE TITLE
why require does not work inside .vue file?

### ISSUE THREAD

**Issue by whatsthatjn** [vuejs/vue-loader#48]
My application has directories as following:

App
  /node_modules
  /components/mobile/a.vue
 /b.vue

with such dirs, I can use require in b.vue to use node module inside node_modules, but it fails when I try to use require in a.vue , webpack will report module not found. what is wrong? thanks!

**Comment by azamat-sharapov** [comment]
got some code to show?

**Comment by whatsthatjn** [comment]
I just tried the vue-loader-example project and it failed again.

It is very simple, that firstly I install vue-html-editor inside vue-loader-example directory with npm install vue-html-editor --save-dev. 

and then I just add one line into  src/app.vue as following:
var editor = require('vue-html-editor');

then I run npm run-script dev and failed with following errors:

ERROR in ./~/babel-loader?optional[]=runtime&loose=all!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
Module not found: Error: Cannot resolve module 'vue-html-editor' in /Users/whatsthat/Development/github/vue-loader-example/src
 @ ./~/babel-loader?optional[]=runtime&loose=all!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue 15:13-39

Seems it is something wrong with selector.js of vue-loader?

**Comment by azamat-sharapov** [comment]
> and then I just add one line into src/app.vue as following:

I don't see any code following..  

Are you using npm version 3? And why would you `--save-dev` it instead of `--save`?

**Comment by yyx990803** [comment]
You need to surround your code blocks with three backticks... otherwise GitHub will filter away any HTML tags. I can't tell anything wrong with your description, so you need to provide a repo of your code if you want any further help.

**Comment by whatsthatjn** [comment]
ok, I found the problem is inside the modules I want to require inside .vue files. These modules have same problems in their package.json file, the main field value is an array , not just string.

**Comment by goyote** [comment]
What was the solution to this?

**Comment by imachug** [comment]
@goyote The solution was to fix other module's code.
