### ISSUE TITLE
External Pug template not working if it's filename is the same as the component's one. 

### ISSUE THREAD

**Issue by phiphou** [vuejs/vue-loader#484]
I got this code in a `Hello.vue` component ;  

```
<template lang="pug" src="./Hello..pug"></template>
<script>
export default {
  name: 'hello',
  .....
  }
}
</script>
<style lang='sass' src='./style.sass'></style>
```
That doesn't work.

I noticed that it only appens when template name is the exact same as the component's one.

If for instance template name is sufixed like `Hello.tpl.pug`, that works.

**Comment by kazupon** [comment]
Close (inactivity, passed 5 days, and due to be able not to reproduce)
