### ISSUE TITLE
The inline style is stripped in vue-loader@9.9.5

### ISSUE THREAD

**Issue by cycold** [vuejs/vue-loader#486]
In vue@2.0.8 vue-loader@9.9.5 vue-template-compiler@2.1.0
`<h3 style="color: red">hello</h3>`
==>
`<h3 >hello</h3>`

When I downgrad to vue@2.0.3 vue-loader@9.7.0 vue-template-compiler@2.0.3
 It's ok.

**Comment by yyx990803** [comment]
Can you confirm this still happens with latest?

- vue@2.1.3
- vue-template-compiler@2.1.3
- vue-loader@10.0.2
