### ISSUE TITLE
Hang up without error if unclosed comment was in a template

### ISSUE THREAD

**Issue by ggaborx** [vuejs/vue-loader#496]
vue: 2.1.3
vue-loader: 10.0.1
vue-template-compiler: 2.1.3

I tried to build my project as I always do but webpack hanged up **without any error message**. 
After an hour I finally figured out that it was a vue-loader issue which caused by a missing close tag for a comment in one of my single file component. It was clearly my fault but without any error message it was very hard to find that bug. 

Simplified example:

```
<template>
   <div>
        <!-- UNCLOSED TEMPLATE COMMENT 
   </div>
</template>
<script>
 
   export default { }

</script>
```

**Comment by coupej** [comment]
+1 

I came across the same issue, with webpack hanging silently forever. 

vue: 2.1.4
vue-loader: 10.0.2
vue-template-compiler: 2.1.4

Example 

`<template>
  <div>
    <div id="tes"><

    </div>
  </div>
</template>
<script>
   export default { }
</script>`

**Comment by kazupon** [comment]
I seem this issue same #557

**Comment by kazupon** [comment]
Close (See #557)
