### ISSUE TITLE
override defaultLang

### ISSUE THREAD

**Issue by cj** [vuejs/vue-loader#497]
It would be nice to be able to override https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L30-L34 in the vue settings.

**Comment by JounQin** [comment]
@yyx990803 I've tried to implement it in pr#500

**Comment by yyx990803** [comment]
Closing outdated issues - if your issue still persists in the latest version of `vue-loader`, please file new one using [the issue helper](http://new-issue.vuejs.org/?repo=vuejs/vue-loader), thank you!
