### ISSUE TITLE
Use webpack loaders to load included files

### ISSUE THREAD

**Issue by sjoerdvisscher** [vuejs/vue-loader#5]
You say "note you'll have to save the vue file to trigger a rebuild since the imported file is not tracked by Browserify as a dependency". (I guess you mean webpack instead of Browserify)

I really would like a fix for this. Is it not possible to use the webpack loaders to load included files, so the included files are tracked as well?

**Comment by yyx990803** [comment]
It is indeed possible and is now available in `vue-loader` 1.1.5 :)

**Comment by sjoerdvisscher** [comment]
Thanks, but sadly it doesn't seem to work, or I can't get it to work.

I'm testing it with a vue file with a piece of less that does an `@import`. Should that work, or is the dependency event not fired for less imports?

**Comment by yyx990803** [comment]
Ah, sorry currently it only works for `src=""` imports... I guess I misunderstood your need

**Comment by sjoerdvisscher** [comment]
Ah! At least that's something, I can rewrite the top-level imports to use the src syntax, that will already fix most cases as we don't have deep import chains.
