### ISSUE TITLE
Using ES6 fat arrow functions in method definitions

### ISSUE THREAD

**Issue by dsl101** [vuejs/vue-loader#508]
Replacing this:

    methods: {
      login: function () {
        console.log(this)

with this:

    methods: {
      login: () => {
        console.log(this)

results in `this` being undefined, so it is no longer possible to refer to the Vue instance / data members, etc.  Is it intended that Vue will supprt ES6 in method definitions? Or did I just do it wrong? This is a trivial example obviously, but in trying to maintain consistent code style, I'd prefer to stick to one or the other, and much of the rest of the code is using ES6 features.

**Comment by ktsn** [comment]
The arrow function will automatically bind `this` value. This behavior is in ES2015 spec.
Just use object literal shorthand to use `this` in component methods.

```js
methods: {
  login () {
    console.log(this)
```

**Comment by dsl101** [comment]
Yes - I had assumed the new `this` behaviour was behind it. Many thanks for the better alternative :).

**Comment by dsl101** [comment]
Although, I guess that can't be used if there are parameters to the method...

**Comment by ktsn** [comment]
Do you mean arguments?

``` js
methods: {
  login (a, b, c) {
    console.log(a, b, c)
```

**Comment by dsl101** [comment]
I tried that - I get this Babel-related error:

	Module build failed: SyntaxError: Unexpected token, expected , (172:19)

	  170 |   },
	  171 |   methods: {
	> 172 |     changeTab: (e) {
	      |                    ^
	  173 |       console.log('Activate:', e.target.id)
	  174 |       this.currentView = e.target.id
	  175 |     },

Do I need to configure something else first?

**Comment by ktsn** [comment]
Colon is not allowed for object method shorthand.

```
changeTab (e) {
  console.log('Activate:', e.target.id)
  this.currentView = e.target.id
},
```

**Comment by dsl101** [comment]
Doh!. Sorry - still new to ES6. So, this works by 'accident'?

	methods: {
	  login: () {  // Note the colon here
	    console.log(this)

but not if there are arguments?

**Comment by ktsn** [comment]
Hmm, I'm not sure about that behavior. I think it should throw an error.
I tried it on the babel repl but it causes a syntax error.
https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=latest%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&code=export%20default%20%7B%0A%20%20methods%3A%20%7B%0A%20%20%20%20login%3A%20()%20%7B%20%20%2F%2F%20Note%20the%20colon%20here%0A%20%20%20%20%20%20console.log(this)%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
