### ISSUE TITLE
和happyPack一起使用的时候遇到一个问题

### ISSUE THREAD

**Issue by qianL93** [vuejs/vue-loader#511]
![default](https://cloud.githubusercontent.com/assets/11720452/20785597/fedf0dd4-b7db-11e6-9486-a92b0cb3bf5a.JPG)

这个时候 vue-loader options 好像就没有生效。vue-loader 编译的时候 vueOptions 为 undefined

**Comment by kazupon** [comment]
Thank you for your reporting!

Vue-loader is implemented based on  webpack loader API.
We cannot support about the depedency feature of happypack.
