### ISSUE TITLE
[Documentation] mention vue-mode for Emacs

### ISSUE THREAD

**Issue by lomereiter** [vuejs/vue-loader#512]
Hi, I'm going through the official docs, would be nice to have a link to https://github.com/CodeFalling/vue-mode

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

I hope send your PR. 😉 

Thanks.
