### ISSUE TITLE
Path of Vue component file is exposed by `__vue_options__.__file`.

### ISSUE THREAD

**Issue by songsiqi** [vuejs/vue-loader#516]
I use vue-loader@^9.

```
__vue_options__.__file = "/Users/username/Documents/path/to/component.vue"
__vue_options__.render = __vue_template__.render
__vue_options__.staticRenderFns = __vue_template__.staticRenderFns
```

How to avoid this?

**Comment by LinusBorg** [comment]
This is [disabled in production](https://github.com/vuejs/vue-loader/blob/912ec9c14cf7b44b03fdfaabf7995b4c5f149350/lib/loader.js#L257) and is used in development to provide better error messages.

**Comment by fritx** [comment]
Excuse me, how to turn that `minimize` on ???

**Comment by kevingermain** [comment]
I'm joining fritx :)

**Comment by LinusBorg** [comment]
Just minimize your code, e.g.  with uglify webpack plugin. We already do or in our template.

**Comment by justblender** [comment]
I'm sorry for bumping this old issue, but is there any reason why even production builds now expose component's filename? Maybe there should be a way to disable this behavior?

**Comment by LinusBorg** [comment]
See:

https://github.com/vuejs/vue-loader/blob/f0beed3296d676dfdfcad85f115c9e75aaaca08b/lib/index.js#L178-L186

**Comment by LinusBorg** [comment]
you can always 
* Fork vue-loader
* Remove the code you don't like.

If you actually want to make an effort to have this changed in vue-loader itself, please open a feature request with an explanation about why this is a problem for you and why offering a way to remove it is valuable to you, and if you want to help us even more, send a PR.

**Comment by gitlab-winnie** [comment]
I have created https://github.com/vuejs/vue-loader/pull/1446 to document the behavior.

**Comment by 2-5** [comment]
For those who inspected their minified bundles and were most surprised by this sensitive information leak, here is how to fix it if you use `webpack`. We are going to go over the `vue-loader` output and 
strip it with a regular expression, with the help of the `string-replace-loader` plugin:

```
npm install --save-dev string-replace-loader
```

And in your webpack config:

```javascript
module: {
  rules: [
    {
      test: /\.vue$/,
      use: [
        {
          loader: 'string-replace-loader',
          options: {
            search: '\\.options\\.__file = ".*"',
            replace: '.options.__file = "a.vue"',
            flags: '',
          },
        },
        { loader: 'vue-loader' },
      ],
    },
  ],
},
```

Of course, it's relatively fragile, so check periodically that it's still working.
