### ISSUE TITLE
Use props in css/inline?

### ISSUE THREAD

**Issue by simonwjackson** [vuejs/vue-loader#519]
Maybe im doing this wrong, but the image paths dont seem to be rewritten:

**This component..**
```javascript
<template>
  <div id="hello">
    <div :style="{ 'background-image': `url(${this.image})` }" />
  </div>
</template>

<script>
export default {
    props: ['image']
}
</script>
```

**Called like this..**

```
<hello image="./assets/logo.png" />
```

**compiles to this..**
```
<div data-v-fe02f932="" id="hello">
    <div data-v-fe02f932="" style="background-image: url(./assets/logo.png);"></div>
</div>
```

As you can see, the url is still the same.. which means it doesn't work.

Any thoughts?

**Comment by yyx990803** [comment]
Only static paths in templates are converted into `require` automatically - for dynamic values, the `image` prop itself needs to be passed in as `require('./assets/logo.png')` from the JavaScript side.
