### ISSUE TITLE
Remove loaders this plugin depends on.

### ISSUE THREAD

**Issue by dannyfritz** [vuejs/vue-loader#52]
What do you think about removing dependencies on babel-loader and autoprefixer?
I mean, I'll probably use babel-loader and autoprefixer in all my projects, but shouldn't it be something I add to the loader chain myself? :stuck_out_tongue:

**Comment by yyx990803** [comment]
With npm3 peerDependencies are not installed by default anyway. What problems do you have with these dependencies and why is it worth a breaking change?

**Comment by dannyfritz** [comment]
It's more of a tiny module argument than anything else really. If you don't think it is worth it, feel free to consider it bike shedding and close it.
