### ISSUE TITLE
IE11 Template tag compatibility

### ISSUE THREAD

**Issue by adrianolobo** [vuejs/vue-loader#520]
We have to make an app created using Vue compatible to IE11.

But as IE11 doesn't suppport <template> tag I tryied to switch to <script type="x/templates"> but the loader doesn't let me put 2 scripts tag. Is there a way to let me do that?

We had to switch all templates to separate files, but this goes against the .vue component pattern and makes the code way more ugly. We don't think it worth it because of Microsoft's incopotency.

**Comment by LinusBorg** [comment]
The template tags are only in the .vue files. During build into the final bundle.js file, they are removed.

So `<template>` in a `.vue` file this can't be a problem for IE11 - it will never see it.
