### ISSUE TITLE
Error: Cannot find module 'vue-template-compiler'

### ISSUE THREAD

**Issue by belawaeckerlig** [vuejs/vue-loader#522]
Hi,

I tried updating vue-loader to 10.0.2 (before it was 9.x) and now I get Errors in my components telling me the vue-template-compiler could not be found. I saw that you moved it in the devDependencies, but it will still be imported in the parser.js, which causes those errors.

**Comment by blake-newman** [comment]
You will need to add to your package.json and install it, it is now a peer dependency. So you will now need to have it installed at project level.

**Comment by aeosynth** [comment]
can this be documented? the 'setting up a project' page only mentions using `vue-cli`.
