### ISSUE TITLE
Template containing '<>' will cause webpack to block (stuck)

### ISSUE THREAD

**Issue by Hentioe** [vuejs/vue-loader#526]
Example:

````html
<template>
  <div class="example">
    <span>I'm Example</span><>
  </div>
</template>
````
Webpack build blocking....

But:
````html
<template>
  <div class="example">
    <><span>I'm Example</span>
  </div>
</template>
````
Or
````html
<template>
  <div class="example">
    <>
    <span>I'm Example</span>
  </div>
</template>
````
Will build through.

**Comment by LinusBorg** [comment]
Hello @Hentioe,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If nessessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .


Thank you.

**Comment by kazupon** [comment]
close (inactivity)
