### ISSUE TITLE
用css单位vh报错

### ISSUE THREAD

**Issue by cleartime** [vuejs/vue-loader#528]
我用了height:calc(100vh - 100px)，然后
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/index.vue
Module build failed: SyntaxError: Identifier directly after number (29:27)
放在style标签里面也会报错，放到template里面就正常了

**Comment by scott-leung** [comment]
经测试，使用该你上述描述的height:calc(100vh - 100px)，是正常的，没有你所描述的问题。
请校对样例，看有没有配置的遗漏或者其他语法的错误。

**Comment by kazupon** [comment]
close (inactivity)
