### ISSUE TITLE
import bug: Failed to mount component: template or render function not defined. 

### ISSUE THREAD

**Issue by junhwong** [vuejs/vue-loader#529]
After I test,I consider this a Bug.

The screenshot below is direct referenced file (not via NPM, not in current project directory ).
![snapshot](https://cloud.githubusercontent.com/assets/8044424/21079077/d1969986-bfc0-11e6-83d3-923e4ef3f52a.jpg)

webpack config:
```js
  resolve: {
    extensions: ['', '.js', '.vue'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'vue$': 'vue/dist/vue',
      'vue-ui': '/workspace/vue-ui/src',
```

------------------------------------------------------
目标项目A： 目标项目使用的是官方的webpack项目模板，版本2.X。
自定义库L：定义的一些公共组件库

在项目A中引用 L, webpack配置(webpack.base.conf.js)
```js
  resolve: {
    extensions: ['', '.js', '.vue'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'vue$': 'vue/dist/vue',
      'common-ui': 'common-ui/src/components/Input.vue',
```

项目L中的Input.vue 的定义：
```vue
<script>
export default {
  name: 'input',
  data () {
    return {
      value: ''
    }
  }
}
</script>
<template>
  <input v-model="value"/>
</template>
```

项目A中的，main.js:
```js
import Vue from 'vue'
import CUI from 'common-ui'
Vue.component('cui-input', CUI )
```

其它略，大体就是 使用 
```vue
<template>
...
<cui-input v-model="..." /> 
...
</template>
```
这样的，但是出现错误:
```
vue.js?1ea9:2643[Vue warn]: Failed to mount component: template or render function not defined. 
(found in component <cui-input>)
```

**重要**：在项目A中定义的vue组件 可以正常工作，只有引用L中的才出现上述错误。

-----------------------------

之前在 vue 项目下 issues 的：https://github.com/vuejs/vue/issues/4403
在 fnlctrl 的建议下 放在这边，并建立了 github 测试项目 下边是地址：

ui库： https://github.com/junhwong/vue-ui
测试：https://github.com/junhwong/vui-demo

**Comment by junhwong** [comment]
在这个demo 里边引用进来的对象是空的：
```
Object
__file:"D:\vui-demo\node_modules\.1.0.0@vue-ui\src\components\index.vue"
__proto__:Object
```

**Comment by junhwong** [comment]
i trace dist/vue.js , found this code:
```js
  /**
   * Class inheritance
   */
  Vue.extend = function (extendOptions) {
    extendOptions = extendOptions || {};
    var Super = this;
    var isFirstExtend = Super.cid === 0;
    console.error('>>>[vue:3253]',extendOptions.name, extendOptions.render)
    isFirstExtend = false // always create new Class
    if (isFirstExtend && extendOptions._Ctor) {
```

added new line:
```js
isFirstExtend = false // always create new Class
```

it be worked!!!   so i sure this question is a bug.
But i not sure that is **vue-loader** or **vue** Bug,  so i cant fix it my salf  PR , pls check it , thks !!!

**Comment by kazupon** [comment]
Close 
Please check with vue-loader 10.1.x latest version.
If this issue still occured,  register new isseus please.
