### ISSUE TITLE
[vue-loader] public/js/src/settings/index.vue: named exports in *.vue files are ignored.

### ISSUE THREAD

**Issue by happilymarrieddad** [vuejs/vue-loader#530]
Hi,

Is there any way to allow this? Or if not, what is the proper way to nest vue components with vue-router. Thanks!

![selection_265](https://cloud.githubusercontent.com/assets/6416323/20989203/1afda3b8-bc91-11e6-9697-8a94d48260c0.png)
![selection_266](https://cloud.githubusercontent.com/assets/6416323/20989202/1afae236-bc91-11e6-8355-e20ab493c33c.png)
![selection_267](https://cloud.githubusercontent.com/assets/6416323/20989204/1b004e10-bc91-11e6-9c39-e115359fdc37.png)

 - Nick

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

I think you should not be designed setting with single file component.

Thanks.
