### ISSUE TITLE
vue文件使用多个loader时不能正常工作

### ISSUE THREAD

**Issue by zhangfisher** [vuejs/vue-loader#531]
以下是我写的一个简单的loader，用来将vue文件里面的L("aaaas")替代成L("aaaas","talk")样式
在webpack里面是这样配置的:
`
        {
                    test: /\.vue$/,
                    loader: 'vue-loader!lang-loader'
        }
`
这个加载器的作用是用来进行处理多语言时使用的。
但我发现lang-loader可以正常运行，在console.log跟踪也可以正常进行字符串的替换的
但是结果输出时并没有，好象vue-loader只对原始文件进行处理，而不是在上一个输入的基础上
处理。

加载器的代码如下：
`
//本加载器用来专门处理多语言文件中的Region问题
// 将文件里的翻译函数注入Region变量
// 如 L("要翻译的内容")
// 如果上述语言定义在一个叫iptalk的翻译域中，
// 则将其转换成L("要翻译的内容","iptalk")
// 

var langConfig = require("../src/language/language.config.json")
var loaderUtils = require('loader-utils');
var path =  require("path")

//  L("dfsdfds")
var langRegExp = new RegExp(/\bL\(\"(.*?)\"\)/g)

//根据文件名称返回其所在的Region
function getfileRegion(srcFile){
	var resultRegion="main"
	for(region in langConfig.regions || {}){
		var regPath=path.resolve(__dirname,"../src",langConfig.regions[region])
		var ref=path.relative(regPath,srcFile)
		if(!(ref==srcFile || ref.slice(0,2)=="..")){
			resultRegion=region
			break;
		}
	}
	return resultRegion
}

module.exports = function(source) {
  var query = loaderUtils.parseQuery(this.query);
  var region=getfileRegion(this.resourcePath)
  if(region!="main"){
  	source=source.replace(langRegExp,'L("$1","' + region + '")')
  }
  return source
};
`

**Comment by xjchengo** [comment]
用options来自定义loader试试，参考：｀https://vue-loader.vuejs.org/en/configurations/advanced.html｀

**Comment by zhangfisher** [comment]
查了源码，发现vue-loader里面并没有处理加载的内容
而是生成：
```

/* styles */
require("!!vue-style-loader!css-loader!vue-loader/lib/style-rewriter?id=data-v-06111052!vue-loader/lib/selector?type=styles&index=0!./app.vue")

/* script */
__vue_exports__ = require("!!babel-loader!vue-loader/lib/selector?type=script&index=0!./app.vue")

/* template */
var __vue_template__ = require("!!vue-loader/lib/template-compiler?id=data-v-06111052!vue-loader/lib/selector?type=template&index=0!./app.vue")


```
由上述代码分析vue-loader只是生成如如何加载的语句，并没有对webpack加载链的数据进行任何处理，因此直接写'vue-loader!lang-loader'根本无效。
按照上述的代码：
`
__vue_exports__ = require("!!babel-loader!vue-loader/lib/selector?type=script&index=0!./app.vue")
`
需要将我写的lang-loader加到这个require里面，像这样：
`
__vue_exports__ = require("!!babel-loader!vue-loader/lib/selector?type=script&index=0!**lang-loader**!./app.vue")
`

**Comment by xjchengo** [comment]
不能热加载的问题可以通过增加一个`add-lang-loader`的方式来hack:
```
{ test: /\.vue$/, loader: 'add-lang-loader!vue-loader' }
```
在`add-lang-loader`中对vue-loader返回的template和script的require进行replace,加入你的lang-loader.

或者也可以提个PR，让loader option支持函数，然后把`moduleId`等重要变量通过上下文传入：
```
vue: {
  loaders: {
    html: function (context) {
      return 'vue-loader/lib/template-compiler?id=' + context.moduleId + '!lang-loader'
    }
  }
}
```

另外，多语言为何不放到运行时确定，要在编译过程中就定好？

**Comment by zhangfisher** [comment]
多语言的确是采用运行时确定，提供一个L函数，类似：
L("ok")的方式调用。

我只是要提供一个特性，用来在编译阶段，将L("ok")转换成L(“ok”,"region")
注入一个region值，多语言机制利用region来区分不同的语言上下文，我希望能够自动注入语言上下文，以便能更好的翻译。

**Comment by zhangfisher** [comment]
以下是我实现的多语言机制的使用文档

# 一、基本方法  #

本工程的多语言实现方法采用动态函数转换的机制，系统提供一个全局的翻译函数L，用来将需要翻译的文本翻译成正确的语言，基本的应用过程如下：

## 1.默认语言 ##

一般情况下，我们应指定一个默认语言，在config对应的配置文件webpack.config.js里面指定默认语言，方法是在Plugins里面加入一个常量：
	  
      plugins:{
           new webpack.DefinePlugin({
                __DEFAULT_LANGUAGE__:JSON.stringify('zh-CN'),//默认语言
            })
     }

在本项目中，默认语言是中文，也就是说中文不需要翻译，因为我们在整个工程中均采用中文。
只有其他语言才需要翻译。

## 2.指定需要翻译的内容 ##

然后在工程中，我们需要所有的VUE组件中，对所有需要翻译的地方进行改造，针对脚本和模板部分改造方法不同。


**- script段**

我们提供一个L全局函数，可以js脚本的任何地方直接调用，如：

`alert("确定否?")`

需要改成：

`alert(L("确定否?"))  
`

L全局函数会将输入的字符串正确翻译成所需要的语言，内部的实现机制我们后续再讲。


**- template段**

模板部分无法通过调用全局函数实现，我们通过一个叫VueLanguage的插件为全局Vue组件注入一个L函数，功能与上面的全局函数一样，使用方法如下：

例如，我们的模板是这样：

    <template>
    	<div class="iptalk" id="iptalk">
    		<div class="workspace" title="非常好">
    			{{ IP对讲管理中心 }}
    		</div>
    	</div>
    </template>

要实现多语言，需要改成这样：


    <template>
    	<div class="iptalk" id="iptalk">
    		<div class="workspace" :title='L("非常好")'>
    			{{ L("IP对讲管理中心") }}
    		</div>
    	</div>
    </template>

其原理实现上是调用了全局插件VueLanguage提供的绑定L函数来实现的。需要注意的是：
如果要翻译的内容在属性中，则需要将属性转换成vue的响应属性。
比如上例中：

    		<div class="workspace" title='非常好'>

改成：

    		<div class="workspace" ：title='L("非常好")'>


**- 注意事项**


 L函数的调用方式必须严格按照，如下格式：

    L("要翻译的内容")'

像以下调用方式是无效的：

    L( “aaaaa")
    L( “aaaaa" )
    L('aaaaa')
    L('aaaaa' )

之所以无效是因为，我们的多语言处理机制是通过正则表达式来查找需要翻译的内容的。
现有的正则表达式只匹配`L("要翻译的内容")'`。


## 3.提取要翻译的内容 ##


当我们整个工程编写完毕后，如果只是支持中文，则不需要做任何翻工作，因为我们的默认语言是中文。
如果说我们需要翻译成英文或其他语言，则需要提取整个工程需要翻译的内容进行翻译。

工程提供了一个gulp命令来完成翻译内容的提取工作。用法如下：

在工程根文件下进入命令行，执行：

    gulp language

命令执行后，应会在`src/language下`生成一个en-US的文件夹，里面的若干个json文件,一般情况下，至少有一个`main.json`文件。

打开`main.json`文件，我们可以看到类似下面的内容：
    
    {
         "__REGION__": "main",
         "确定":"确定",
         "取消": "取消",
         ......
         "__LANGUAGE__": "en-US"
    }
    
里面的`__REGION__`、`__LANGUAGE__`是保留字，不要更改。
接下来你就可以对main.json的内容进行翻译了，比如翻译成：
    
    {
         "__REGION__": "main",
         "确定":"OK",
         "取消": "Cancel",
         ......
         "__LANGUAGE__": "en-US"
    }
    
一般情况下，翻译完成`main.json`后，保存即可。


**- 指定目标翻译语言**

同样的，如果你需要翻译日语，则执行：

    gulp language --target jp

执行后，该命令就会提取出所有需要翻译的字典内容，在`src/language/jp`下生成`main.json`等语言字典文件。

**- 添加字典注解**

 `gulp language`命令支持两个可选参数：


    gulp language --annotate
 
增加`--annotate`参数后，在生成字典文件时，会在翻译内容后面生成注解，注解该字典内容是从哪个文件提取，如下：
    
    {
         "__REGION__": "main",
         "确定":"OK[c:\\src\\a.vue]",
         "取消": "Cancel[c:\\src\\b.vue]",
         ......
         "__LANGUAGE__": "en-US"
    }
    
`--annotate`的作用是方便在翻译时可以知道该字典内容是从哪个文件提取的，以便可以查询上下文。需要注意的是，翻译完成后要手工删除注解内容。

**- 自动更新选项**

默认情况，`gulp language`命令会在重新生成字典文件时进行文件合并，如通过`gulp language`命令生成了`main.json`文件,然后你在该文件进行翻译。如果你程序进行了更改（如修改输出内容，添了要翻译的内容等），再次运行`gulp language`命令时，会保留你翻译的内容，并自动添加新的内容。

如果你想禁用自动合并更新选择，则可以使用：


    gulp language --update false

这样执行后，就会覆盖掉原先的语言字典文件。

## 4.打包语言文件 ##


语言文件翻译完成后，执行webpack打包命令。

    gulp webpack

执行打包后，命令会读取位于src/language里面的所有语言，按照一种语言一个包的方式进行打包。
最后会在打包输出文件夹里面生成语言包文件：
    
    zh-CN.bundle.js
    en-US.bundle.js
    jp.bundle.js
    

## 5.加载语言文件 ##

在实现使用时，如果你需要哪种语言就加载对应的语言包文件即可。如要显示英文：
    
    <body>   
       	<div id="app"></div>
       	<script type="text/javascript" src="assets/en-US.bundle.js" charset="utf-8"></script>
        ...............
    </body>
    
    
# 二、高级应用  #

在基础应用中，本工程的机制是将所有语言转换为一个JSON对象，像这样：
    
    {
         "__REGION__": "main",
         "确定":"OK",
         "取消": "Cancel",
         ......
         "__LANGUAGE__": "en-US"
    }

这样的机制存在几个问题：

1. 当翻译内容数量较多时，不好分类管理。
1. 难以定位要翻译内容的上下文应用环境，无法联系上下文语境进行翻译，只能直译，准确性较差。
2. 因为同样的语句在不同的上下文环境中，不同语种翻译内容可能不一样，该机制无法有效区分。

为解决问题，我们引入翻译域(Region)的概念：

一个域(Region)对应一个文件夹，文件夹下（包含子文件夹）的所有VUE文件均属于同一个域。一般情况下，我们会将一个模块划为一个域。

比如告警模块，我们可以单独定义一个域，以便可以在该域环境下进行翻译。

域的定义在`src/language/language.config.json`里面定义：
    
    ｛
    	regions:{
    	  "iptalk":"apps/iptalk"
    	}
     }
    
以上定义了一个域名叫`iptalk`，对应的文件夹是`src/apps/iptalk`。
定义完毕后，当执行`gulp language`生成翻译字典文件后，除生成`main.json`字典文件外，还会生成一个叫`iptalk.json`的字典文件。

`iptalk.json`的字典文件的内容就是从`src/apps/iptalk`文件夹里面的所有vue文件中提取出来的。

原则上，我们应该按模块来划分域，不同的模块代码位于不同的文件夹，语义上下文环境根据文件夹或模块来区分，通过域的引入将翻译内容提取到不同的文件,从而简化管理，提供语义上下文支持。

**Comment by xjchengo** [comment]
可以在webpack里用`DefinePlugin`试试：
```
new webpack.DefinePlugin({
  _LANG: JSON.stringify("zh-ch")
})

function L(str, locale) {
  if (!locale) { locale = _LANG }
  ...
}

```

**Comment by kenberkeley** [comment]
https://github.com/vuejs/vue-loader/issues/565

**Comment by yyx990803** [comment]
Closed via e2b41ea
