### ISSUE TITLE
How can I minify template before it compile to render function?

### ISSUE THREAD

**Issue by lmk123** [vuejs/vue-loader#533]
I have a vue file like below:

```html
<template>
  <div id="hi">
    <div>
      <p>
        Hello Vue.js
      </p>
    </div>
  </div>
</template>
```

And it compile to:

```js
{
  staticRenderFns: [
    function () {
      var e = this, t = e.$createElement;
      return t("div", { attrs: { id: "hi" } }, [t("div", [t("p", ["\n      Hello Vue.js\n    "])])])
    }
  ]
}
```

I think the white space and `\n` is not need in production, but how can I minify the template before it compile to render function?

**Comment by medelasri** [comment]
![template](https://cloud.githubusercontent.com/assets/3819817/21107569/1477c4c2-c08a-11e6-9be0-298a2066b073.PNG)

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You can use the `webpack.DefinePlugin`.

Thanks.

**Comment by OperKH** [comment]
Same issue I got extra spaces in production when I don't see them in development.
