### ISSUE TITLE
vue-loader en EJS 

### ISSUE THREAD

**Issue by Neewd** [vuejs/vue-loader#534]
Hello, 

Just a question about the vue-loader module, is that possible to use ejs instead of jade in the template ? 
Because when I use <% myVariable %> the result told me that myVariable isn't defined in VueJS ;-( 

I just render it like this in my Express server res.render('index', { myVariable : 'test' }); 

Is that possible or ?

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You can use the `delimiters` option.
https://vuejs.org/v2/api/#delimiters

Thanks.
