### ISSUE TITLE
如何使用vue-loader编译string?

### ISSUE THREAD

**Issue by cxd7744556** [vuejs/vue-loader#535]
目前我们系统是在线编写.vue文件形式的代码，希望提交到后台自动编译成一个组件，这个过程是直接用node编译string,目前是我们自己做了一个简单的编译过程，但是想要和官方规范达到一致还需要很多工作，所以想知道vue-loader有没有直接提供node模块？

**Comment by airyland** [comment]
vue-loader用于webpack, webpack本身就支持通过代码来执行构建。建个通用webpack配置，每次运行配置不同entry不就搞定了，代码还是经过了vue-loader处理，不明白和官方规范达到一致是什么意思？

**Comment by cxd7744556** [comment]
webpack不是编译本地文件么，entry是路径，能够直接传一段代码string进行编译这种能实现么，跟babel-core一样，官方规范达到一致的意思是我写了个简单的编译，想要和vue-loader书写方式一样还是要做很多工作的。

**Comment by airyland** [comment]
你转换下思路呀，建个模板，把string写到文件再调用webpack指定entry为文件名不就完全一致了。

**Comment by JounQin** [comment]
[vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) + [vue-template-es2015-compiler](https://www.npmjs.com/package/vue-template-es2015-compiler) 即可，自行封装一下，这也是 `vue-loader` 内部使用的编译包。

**Comment by kazupon** [comment]
close (due to resolve with vue-template-compiler + vue-template-es2015-compiler )
