### ISSUE TITLE
Allow loaders option syntax to match webpack's loader syntax

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#536]
Currently there is only one way to define loaders under `loaders` option and it is a string:

`scss: style-loader!css-loader?importLoaders=1!postcss-loader!sass-loader?sourceMap`

can we do something about it and perhaps allow user to define loaders in the same way like in webpack's configuration? E.g.

```
scss: [
  { loader: 'style-loader' },
  { loader: 'css-loader' },
  { loader: 'postcss-loader' },
  {
    loader: 'sass-loader',
    options: {
      sourceMap: true,
    },
  },
]
```

This way it would be easier to share the same config for specific loader under vue-loader options and in other places in webpack's config.

**Comment by niksy** [comment]
You can try using [webpack-combine-loaders](https://github.com/jsdf/webpack-combine-loaders) helper for that.

**Comment by kazupon** [comment]
Close (due to resolve with solution by @niksy)

**Comment by niksy** [comment]
@kazupon although helper is nice solution, maybe there should be an option to allow standard "array" definition. Seems more consistent with other Webpack loaders and won’t create confusion for others who are looking for this.

**Comment by indirectlylit** [comment]
Agree. The list-of-arrays syntax was a big win in webpack 2. I'd predict that over time the `!` pipe syntax will become much less common in general.

Perhaps related: in webpack 2, [preloaders and postloaders are deprecated](https://webpack.js.org/guides/migrating/#module-preloaders-and-module-postloaders-was-removed), but vue loader still uses them.

**Comment by evenfrost** [comment]
I'd consider reopening the issue as this is still present and provided `webpack-combine-loaders` helper doesn't really solve that.
