### ISSUE TITLE
Nested vue-loader couldn't normalize dependencies' absolute path

### ISSUE THREAD

**Issue by geekdada** [vuejs/vue-loader#539]
I put vue-loader inside a dependency that my project depend on, in order to make all kinds of loder isolate from the project, I use `require.resolve` syntax to resolve absolute loader path, but in this file https://github.com/vuejs/vue-loader/blob/master/lib/normalize.js, it couldn't normalize such kind of loader.

**Comment by geekdada** [comment]
```
ERROR in ./app/components/page/App.vue
Module not found: Error: Can't resolve 'vue-loader/lib/style-rewriter' in '/Users/.../app/components/page'
 @ ./app/components/page/App.vue 5:0-316
 @ ./app/components/main.js
 @ multi app
```

**Comment by geekdada** [comment]
https://github.com/geekdada/vue-loader/commit/e4c06abeb56464f9ad7810b4598c2e1f886bc8cc

**Comment by geekdada** [comment]
这个问题没有人管吗…

**Comment by kazupon** [comment]
Thank you for your filling!
This issue is same the #525
Close.
