### ISSUE TITLE
Throw syntax error if any tags are open but do not close

### ISSUE THREAD

**Issue by lsavage92** [vuejs/vue-loader#544]
I ran into an issue where I had inadvertently forgotten a closing `/` on a tag within my component. It threw a lot of errors but none that seemed to tell me that I had an open but no closing tag. It would be very helpful if while parsing the template for build if there was a check for closing tags on non-self-closing elements Here's an example:

```
<template>
  <div class="wrapper">
    <someSelfClosingComponent :props="whatever" >
    <div class="rest-of-component">
      ...
    </div>
  </div>
</template>
```

**Comment by yyx990803** [comment]
Use https://github.com/vuejs/eslint-plugin-vue !
