### ISSUE TITLE
npm test throws error:  Uncaught TypeError: _vm._v is not a function

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-loader#547]

**Comment by btipling** [comment]
I'm seeing this same error in my hello world vue.js app that worked prior to upgrading. I upgraded from `"vue": "^2.1.3"` to `"vue": "^2.1.6"` this should not be a breaking upgrade.

**Comment by btipling** [comment]
FWI I have seen this be a problem when I have a mismatch between the version used for building vue and the one it's being run with. For example I upgraded my local vue.js to the most recent version and then deployed that built version with to an image with an old version of vue.js and saw this exact same error. Making sure the image had the right version of vue.js fixed this for me.

**Comment by asselin** [comment]
I'm getting a similar error,  Cannot read property '_c' of undefined.  As far as I can tell, test.js's mockRender function doesn't have the required properties.  For the case I reported, the code that blows up is `var _c=_vm._self._c||_h` (there is no _self passed in from test.js).  For the _v issue, later there is code `[_vm._v(_vm._s(_vm.msg))]`, and _v isn't passed in either.  This appears to be generated by vue-template-es2015-compiler's buble.js.

**Comment by asselin** [comment]
The maximum versions of compatible dependent packages supported are:

vue-template-es2015-compiler: 1.3.1
vue: 2.1.4
vue-template-compiler: 2.1.4

Anything after those versions makes npm test throw errors due to changes to the compiler that haven't been propagated to test.js's `mockRender()`

**Comment by airyland** [comment]
@asselin 👍

**Comment by kazupon** [comment]
Close (#550 merged)
