### ISSUE TITLE
Got err msg:  template syntax error text "{{ /*asdf*/ }}" between v-if and v-else(-if) will be ignored.

### ISSUE THREAD

**Issue by dserWei** [vuejs/vue-loader#552]
I got this error while I used to run it properly before I clone my repository newly. I just wonder why I didn't get the error with the same code before and how I fix it now assuming that I have to write annotation between v-if and v-else

**Comment by yyx990803** [comment]
Use proper HTML comments instead of interpolations.

**Comment by dserWei** [comment]
@yyx990803 the same as what I think, thx
