### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by lbh0619** [vuejs/vue-loader#556]
![6](https://cloud.githubusercontent.com/assets/20679508/21637002/f3b94256-d29f-11e6-9ddd-2179477e7f27.png)
help me！thanks！

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I seem you use standalone building.
You can check the below url of official site.
https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build
