### ISSUE TITLE
"<" character causes loader to hang infinitely

### ISSUE THREAD

**Issue by uptownhr** [vuejs/vue-loader#557]
```
<a @click="$router.go(-1)">< Back</a>
<a @click="$router.go(-1)"><+ Back</a>
```

Valid html template synthaxx but the "<" character causes vue-loader to hang. In results causes webpack to hang and requires a restart.

**Comment by yyx990803** [comment]
Fixed by https://github.com/vuejs/vue/pull/4753, will be out in next Vue release
