### ISSUE TITLE
not compiling correctly

### ISSUE THREAD

**Issue by app-sparkler** [vuejs/vue-loader#558]
Getting the error `Uncaught SyntaxError: Unexpected token export` in browser when trying to compile `App.vue` files with `babel-loader` and `vue-loader`.

**Note** : There is no error in `console`

```
//in webpack.config.js >> module >> loaders[ ] >> 
{
	loader 	: 'babel',
	test	: /\.js$/,
	exclude	: /node_modules/,
	query	: {
		presets	: [ 'latest', 'stage-2' ]
	}
} , {
	loader	: 'vue',
	test	: /\.vue$/,
	exclude	: /node_modules/
}
```
```
//App.vue
<template>
  <h1>Hello World!</h1>
</template>

<script>
  export default {
	name	: 'App'
  }
</script>

<style>
 h1 {
	background-color	: blue;
	color			: #fff;
	font-weight		: bold; 
 }
</style>
```

### This works fine when working with `module.exports`

```
<script>
  module.exports = {
    name  :  'App'
  }
</script>
```

### `package.json`
```
...
"dependencies": {
    "vue": "^2.1.8"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "css-loader": "^0.26.1",
    "html-webpack-plugin": "^2.26.0",
    "vue-loader": "^10.0.2",
    "vue-template-compiler": "^2.1.8",
    "webpack": "^1.14.0"
  }
...
```

Please advise what could be going wrong.

Thanks.

**Comment by airyland** [comment]
wrong name: App.Vue => app.vue
also typo: exlcude => exclude

**Comment by app-sparkler** [comment]
@airyland i've updated the file name and corrected the typo; however, i'm still facing this issue.

Thanks.

**Comment by app-sparkler** [comment]
## Solution

I've answered this here : 

https://github.com/vuejs/vue-loader/issues/561

**Comment by kazupon** [comment]
Thank you for your filling!

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues.
The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
