### ISSUE TITLE
Scoped CSS Doesn't work on dynamic content 

### ISSUE THREAD

**Issue by ramakrishnamundru** [vuejs/vue-loader#559]
When using scoped CSS the styles and the elements are given data- attributes. But when content is added Dynamically it won't have those data- attributes. So the styles are not applying to the dynamic content.

I think it's better to add a data- attribute to the root element of the template and add the styles as the children of that attribute instead of adding attributes to individual elements..

**Comment by kazupon** [comment]
Thank you for your filling!

Can you provide the minimum reproduction code please?

**Comment by ramakrishnamundru** [comment]
I don't know how to reproduce it in a fiddle but look at this image.
![scoped_css](https://cloud.githubusercontent.com/assets/23165864/21758007/e272a04e-d65c-11e6-9392-9be6de7f4172.png)

here I am using a jquery plugin lc_switch which adds content to replace default checkbox.

the dynamic content is not getting the data- attributes.

so the scoped css styles are not applied

**Comment by ramakrishnamundru** [comment]
I created a repo showing this issue.

https://github.com/ramakrishnamundru/Vue-loader-scoped

just remove scoped for the plugin css and see changes

**Comment by kazupon** [comment]
Thank you for your codes!

scoped CSS with vue-loader & vue core can not give  scopeId to the dynamic content with jQuery etc.
This is hacky event though, you can implemented with `_scopedId` options.

### src/components/Hello.vue
```js
    mounted: function() {
      $('#switch').lc_switch('ON', 'OFF', this.$options._scopeId);
    }
```

### src/assets/LC-switch/lc_switch.js
```js
$.fn.lc_switch = function(on_text, off_text, scopeId) {
  // ...

  // should be changed dynamic content with scopeId
  var on_label = (ckd_on_txt) ? '<div ' + scopeId + ' class="lcs_label lcs_label_on">'+ ckd_on_txt +'</div>' : '';
  var off_label = (ckd_off_txt) ? '<div ' + scopeId + ' class="lcs_label lcs_label_off">'+ ckd_off_txt +'</div>' : '';
 // ...
```

**Comment by ramakrishnamundru** [comment]
Maybe,  But in this way I have to edit most of the plugin files as many will create dynamic content because lc_switch is just an example.

Is in't there a way to add scopeId to the root of the component and modify the css as the children of the root scopeId. Like:

```
<template>
<div data-scopeId>
<content>
</content>
</div>
</template>
```

     And modify css like:

`[data-scopeId] content{
/*
somestyles
*/
}`

**Comment by LinusBorg** [comment]
Something like this might work (untested):

```javascript
Vue.directive('scope', {
  bind: updateScopeId,
  componentUpdated: updateScopeId
}

function updateScopeId(el, __, vNode) {
  const vm = vNode.context
  const scopeId = vm & vm.$options._scopeId
  if (scopeId) {
    vm.$nextTick(() => { // wait till DOM was updated
      setScopeRecursively(el, `v-${scopeId}`)
    })
  }
}

function setScopeRecursively(el, scopeString) {
  const nodes = el.children
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i]
    if (node.dataset[scopeString] !== '') {
      node.dataset[scopeString] = ''
    }
   if (node.children.length > 0) {
     setScopeRecursively(node, scopeString)
    }
  }
}
```
Usage
```html
<div v-scope>
  <!-- 
    if you add any elements in here with jQuery, 
    the directive will add the scope data attributes for you.
    it will also re-check whenever the component updated, in case Vue changed the DOM
  -->
</div>
```

### Limitations

* If your jQuery plugin adds any DOM Nodes after the component rendered and *without* any data change in the component triggering this update, the component will not update, and the directive will not update either. You might have to use `vm.$forceUpdate()` to make it update.

**Comment by ramakrishnamundru** [comment]
@LinusBorg your code didn't work for me. the setScopeRecursively function is never executed. 

But I think the way of adding scopeId to the root element and modifying CSS accordingly is better solution. Is there a way you can implement this in vue loader....

**Comment by LinusBorg** [comment]
If you want to use a base base class on the root element and nested styled under it, you don't need scope, just use a unique classname.

**Comment by ramakrishnamundru** [comment]
Yes ,I might do something like this:

[https://mattstauffer.co/blog/nesting-sass-imports-with-bem](url)

but that may break some plugins that apply styles to body and HTML tags.

Is there a way You can incorporate this directly into vue-loader??

**Comment by ramakrishnamundru** [comment]
@kazupon , @LinusBorg  I there a way you can make vue-loader add and remove the style tag for scoped css along with the component i.e style tag added to dom when component created and removed when component destroyed,
Then there will be no such issue even with dynamic content as styles are automatically applied.

**Comment by ramakrishnamundru** [comment]
@yyx990803 This is clearly a problem because any thing dynamic should have it's css applied globally. So, It will effect content of other components. So the solution I think of is to move the style tag with scoped attribute into the template, so that it will only appear when its needed. otherwise many jquery plugins css will have to be applied globally, which have a lot of problems.

**Comment by LinusBorg** [comment]
> So the solution I think of is to move the style tag with scoped attribute into the template, so that it will only appear when its needed.  

That CSS is still being applied globally - it would merely reduced the "risk's"  probability a little.

So I still don't see how we could have truly scoped CSS applie by Vue for elements that it doesn't know of, because third party libs create them.

**Comment by ramakrishnamundru** [comment]
> That CSS is still being applied globally - it would merely reduce the "risk's" probability a little

If the style tag is removed from the dom then its content is also removed. and no styles will be applied to other components.
There is a discussion here:
https://github.com/angular/angular.js/issues/2387

about style tags. I think it is possible to accommodate dynamic elements css by adding the style tag to template like this:

```
<template>
<root>
<content></content>
<link rel="stylesheet" type="text/css" href="link to scped css bundle">
</root>
</template>
```

just bundling all the files with scoped attribute and adding them to template will ensure that the css only comes when required and is removed with the component when switching route.

**Comment by LinusBorg** [comment]
> If the style tag is removed from the dom then its content is also removed. 

Of course, I don't deny that. But that CSS is still *not* scoped to the component, it's still applied to the whole document.

So if you have two component with conflicting CSS rules in the document *at the same time*, the CSS **will** be screwed up.

The ´discussion you linked to doesn't revolve around scoping issues either, AFAIK,

**Comment by ramakrishnamundru** [comment]
OK, Now I understand your concern, and the clear meaning of scope.

 Then is there any way you can add another mode like "bound" or something else which shows the css loaded is applied globally, but can also be moved with the template hence separating the confusion between the "security" the scoped css provides , and the "flexibility" the bound to the component css provides.

 Because it is not just about third party libraries, but many people create dynamic content and the loss of styling to the content is a clear drawback to the loader.

**Comment by LinusBorg** [comment]
Please open a new issue as a featue request with a detailed description of what you want, and why it's useful. This issue was about scoped CSS, we should start clean.

However, as a disclaimer: I don't think that his will have a high priority, because (aside from the fact that it's a **very** common practice to serve all CSS as one bundle initially) the focus of vue-loader files it to take care of CSS *for Vue components*, which can be scoped, so there's not issue.  

Its focus is *not* to support any kind of dynamic styling for any a third-party lib thatmight be used in the component by some third party lib.

> Because it is not just about third party libraries, but many people create dynamic content 

I don't understand what kind of content you refer to here.

**Comment by ramakrishnamundru** [comment]
> I don't understand what kind of content you refer to here

I mean content like dynamic chat or task manager, editable tables etc..

And thanks I will file a new issue.

**Comment by LinusBorg** [comment]
> I mean content like dynamic chat or task manager, editable tables etc..

Well, either those are created with Vue, so you can use scoped CSS (so you have no problem), or they are created with third-party libs - like jQuery plugins. I don't see a third possibility that woudl make sense.

**Comment by aboutqx** [comment]
I had the same problem,and just give up using `scoped`.

**Comment by ramakrishnamundru** [comment]
@aboutqx you can use the [deep selector](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) as @yyx990803 mentioned [here](https://github.com/vuejs/vue-loader/issues/580#issuecomment-370964129)

**Comment by andre-dw** [comment]
I have some component that are filled with content from the backend as HTML and will be rendered with `v-html`. All the tags that are rendered are not getting the `data-v-f3f3eg9` attributes and so the scoped styles wont apply on those tags.

**Comment by jrsmith17** [comment]
> I don't see a third possibility that woudl make sense.

Vue bills itself as something you can transition into. Not having the scoped css apply to dynamic elements breaks that promise. e.g. when I dynamically add elements with d3. Yes, I can eventually transition to d3 + vue templates, but this means a lot more up front work when Vue should just work out of the box.

**Comment by Luke-Wilson** [comment]
I also have an issue with the scopeId not being applied to dynamically generated children elements. I tried a similar approach to @LinusBorg's `setScopeRecursively`. This worked for me whenever the scopeId has a number as the first character (e.g. v-123ab456a), but it fails when the first character is  a letter (e.g. v-b2636b92). The reason it fails is that DOMStringMap converts the latter to a camelCased string (e.g. vB2636b92), but Vue is still looking for the original scopeId string (v-b2636b92).

It would be great to either (a) have Vue automatically apply the scopeId to dynamically created elements, or (b) allow us to configure the scopeId to always start with a letter so that we can do something like `setScopeRecursively`.

**Comment by Luke-Wilson** [comment]
I tried something similar to @LinusBorg's `setScopeRecursively` but this was throwing an error whenever the scopeId started with a letter (e.g v-b9231fa123 as opposed to v-123f1123a). This is because the DOMStringMap needs data attributes to be camelCasified in this instance. 
Instead of setting the element's data attribute using `node.dataset[scopeString] = ""` as Linus suggested, I used `node.setAttribute('data-${scopeString}', "")`. This camelCasifies the string correctly (when the scopeId starts with a letter) and this worked for me.

Below is my version:

```
export const setScopeRecursively = function(targetEl, scopeId) {
  // This function will recursively travel down from the targetEl and apply the scopeId as a data attribute for CSS scoping.
  // scopeId should be a string (e.g. v-123f1123a)
  try {
    targetEl.setAttribute(`data-${scopeId}`,"")
  } catch(e) {
    console.log(e)
  }

  // Recursively call setScopeRecursively for any children.
  if (targetEl.hasChildNodes()) {
    const list = targetEl.children
    for (var item of list) {
      setScopeRecursively(item, scopeId)
    }
  }
}
```

**Comment by SamuelEarl** [comment]
I am using D3.js inside of Vue.js single file components. I was trying to style some elements that were added to the DOM after the Vue component was created and found that [deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) work well for this. I wanted to share what I found in the hope that it helps someone.

To apply deep selectors, you start by selecting an element that exists in your `<template>` tag (e.g., an `<svg>` element), then you add three greater-than symbols (`>>>`), then you select the element that you want to style.

For example, if I want to change the colors of the axes (path) and tick marks (line) in a line chart to blue, then I would use this deep selector:

```
svg >>> path, line {
  stroke: blue;
}
```

Notice that I did not select any other child elements that were between the `<svg>` and the `<path>` or `<line>` elements. When using deep selectors, you only select the parent element that already exists in your `<template>` tag and then you select the child element that you want to style. You do not select any other child elements that are between those two elements. 

This also means that you need to be careful when nesting styles. Make sure that you use the deep selectors properly and that you do not mix up any nested styles with deep selector styles. If you do mix them up, then your deep selector styles probably won’t work.

It is important to note that the `<path>` element is two levels below the `<svg>` element and the `<line>` element is three levels below the `<svg>` element. So if you are styling multiple child elements with the same set of style rules, then those child elements do not need to be at the same level in the DOM tree.

**If you don’t see your deep selector changes in the browser, then refresh it**
After saving your style changes, if you don’t see your deep selector styles applied in the browser, then you might need to manually refresh your browser. It appears that the deep selector style changes don’t always trigger a hot reload.

**Comment by TheMangoTrain** [comment]
If it helps anyone, you _can_ have multiple <style>'s in a single template.

**MyTemplate.vue**
```
<template></template>
<script></script>

<style scoped>
/* Rules scoped specifically to just the template */
</style

<style>
/* Rules that get applied globally, and will work on dynamic components */
</style>
```
