### ISSUE TITLE
peerinvalid Peer vue-loader@6.0.4 wants babel-loader@^5.3.2

### ISSUE THREAD

**Issue by MichaelGong** [vuejs/vue-loader#56]
peerinvalid Peer vue-loader@6.0.4 wants babel-loader@^5.3.2  

I know ,I can use `npm install  babel-loader@5.3.2 --save-dev` to resolve this, But i like to use it without   version,can u deal with this?

**Comment by yyx990803** [comment]
babel-loader 6 uses babel 6, which brings a lot of breaking changes and is still unstable. It is recommended to stay with babel 5 for now.

`vue-loader` will upgrade to babel 6 when it gets more stable (hopefully in a few weeks)
