### ISSUE TITLE
Missing ">" at end of vue file will hang webpack

### ISSUE THREAD

**Issue by 99Percent** [vuejs/vue-loader#562]
In a .vue file I accidentally omitted closing </script> tag without ending >  leaving it like this: </script
as the last part of the file and webpack hangs with no message, cpu load shoots through the roof.

**Comment by kazupon** [comment]
I seem this issue same #557.

**Comment by tonypee** [comment]
I just ran into this too

**Comment by kazupon** [comment]
close (see #557)
