### ISSUE TITLE
how to work with i18n-webpack-plugin

### ISSUE THREAD

**Issue by kenberkeley** [vuejs/vue-loader#565]
[`i18n-webpack-plugin`](https://github.com/webpack/i18n-webpack-plugin) works as below:

source: `test.en.js`
```js
console.log(__('Hello'));
```

processing with `i18n.zh-cn.json`
```json
{
  "Hello": "你好"
}
```

result: `test.zh-cn.js`
```js
console.log('你好');
```

***

but it has a problem when working with `vue-loader`:
source:
```
<template>
  <div>
    __('Hello') {{ name }}
  </div>
</template>
<script>
export default {
  data () {
    return { name: __('John') }
  }
}
</script>
```
processing with `i18n.zh-cn.json`:
```
{
  "Hello": "你好",
  "John": "约翰"
}
```

result:
```
<template>
  <div>
    __('Hello') {{ name }}
  </div>
</template>
<script>
export default {
  data () {
    return { name: '约翰' }
  }
}
</script>
```

as you can see, `__('Hello')` is not transpiled  
I tried `${__('Hello')}` / `{{{__('Hello')}}}` / `{{{${__('Hello')}}}}` etc, but still not working

***
### workarounds

1. according to https://github.com/webpack/i18n-webpack-plugin/issues/7, [`string-replace-webpack-plugin`](https://github.com/jamesandersen/string-replace-webpack-plugin) can be used as the preLoader of `vue` which can replace `__('Hello')` with `你好`
2. according to [Advanced Loader Configuration](http://vue-loader.vuejs.org/en/configurations/advanced.html), load `<template>` directly as HTML string, then replace `__('Hello')` with `你好`

***
Can `vue-loader` work well with `i18-webpack-plugin`? Thanks in advance

**Comment by kazupon** [comment]
Thank you for your filling.

>according to webpack/i18n-webpack-plugin#7, string-replace-webpack-plugin can be used as the preLoader of vue which can replace __('Hello') with 你好

Maybe, probably you can avoid with `string-replace-webpack-plugin`.

>according to Advanced Loader Configuration, load <template> directly as HTML string, then replace __('Hello') with 你好

I think you will be very difficult as long as don't provide hook. Because it generates the query dynamically in vue-loader.
e.g. https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L48

**Comment by fishear** [comment]
Hi, Can you post the code how you work around with string-replace-webpack-plugin? thank you very much~~
> ### workarounds
> 1. according to [webpack-contrib/i18n-webpack-plugin#7](https://github.com/webpack-contrib/i18n-webpack-plugin/issues/7), [`string-replace-webpack-plugin`](https://github.com/jamesandersen/string-replace-webpack-plugin) can be used as the preLoader of `vue` which can replace `__('Hello')` with `你好`
