### ISSUE TITLE
Can I keep buble folder in node_modules but tell vue-loader to use babel?

### ISSUE THREAD

**Issue by leocflam** [vuejs/vue-loader#568]
My scenario is that:

My vue-cli share the same project directory and package.json with Laravel Elixir.
the problem is that vue-loader in vue-cli always prefer loading buble first
as buble folder exists, it tries to use it to compile .vue 
but my vue-cli webpack is not setup to use buble at purpose

so the ES6 import is "Unexpected token import" after vue-cli webpack compile it with buble

My temporary fix is to either:
Go to /node_modules/vue-loader/libs/loader.js, always disable buble by commenting out
```
var hasBuble = false
// try {
//   hasBuble = !!require('buble-loader')
// } catch (e) {}
```
or
```
Just delete all buble folders in node_modules :/
```
since some of my other Laravel Elixir modules requires buble, removing buble is not an option
There should be a better way I tell vue-loader prefer babel.

More details:

 Laravel-Elixir-Vue creates its own vue-loader so it does not load buble

**Comment by LinusBorg** [comment]
Explicitly set babel-loader in the vue-loader config:

https://vue-loader.vuejs.org/en/configurations/advanced.html
