### ISSUE TITLE
Feature Request: Testing area

### ISSUE THREAD

**Issue by uptownhr** [vuejs/vue-loader#570]
I'm not entirely sure if it's possible but if the vue-loader allowed for a `<test>` area, that would be a dream come true! Template, script, style and tests defined together!

```
<template></template>
<script></script>
<test runner="mocha">

</test>
```

**Comment by uptownhr** [comment]
https://github.com/webpack/mocha-loader does exist

**Comment by kazupon** [comment]
Thank you for your filling.

This feature can be realized by custom block.
It is currently awaiting review of #499
Please wait. 😉

**Comment by uptownhr** [comment]
@kazupon awesome! loving the vue community.
