### ISSUE TITLE
[question] use production build in cordova

### ISSUE THREAD

**Issue by beebase** [vuejs/vue-loader#571]
After npm run build, I'd like to embed this build in a cordova project.
Sim linking the dist folder to the cordova/www folder (or copying over) is not enough, cause I get a blank screen when running a cordova build on android/ios emulators and devices.
Are there some links anywhere, explaining how to make a vue-loader build work with cordova?

**Comment by beebase** [comment]
I fixed it doing:
1. add <script src="cordova.js"></script> to my index.html file
2. after running a build, I had to remove the first slash in all the paths in the generated dist/index.html

![image](https://cloud.githubusercontent.com/assets/446089/21857158/c923c9d2-d824-11e6-91bf-111067c594c2.png)
should be
`src= static/js/manifest.99dbb16beb01930f54eb.js`
![image](https://cloud.githubusercontent.com/assets/446089/21857170/d4f4241e-d824-11e6-86a8-745d50884412.png)


I'm not sure why I have slashes in front of all file references.
![image](https://cloud.githubusercontent.com/assets/446089/21857251/192ce846-d825-11e6-83d2-c2d1cb798a97.png)

**Comment by beebase** [comment]
Maybe related, during npm run build I'm getting
`⠋ building for production...cp: no such file or directory: static/*`

This post says it's harmless though...
https://github.com/vuejs-templates/webpack/issues/401

**Comment by beebase** [comment]
I changed build.assetsPublicPath from '/' to '' in config/index.js to permanently get rid of the first slash. (Not that I have any idea what I'm doing here. Is this going to break things elsewhere?)
Would like to know if this is a bug or me doing something wrong.

![image](https://cloud.githubusercontent.com/assets/446089/21863920/a98fba5c-d83f-11e6-94c3-773a0df4ee9e.png)

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

As far as I have examined, There is webpack template for cordova.
https://github.com/lesion/vue-webpack-cordova

You can check it. 😉 

Thanks.
