### ISSUE TITLE
[Proposal] Support for functional components

### ISSUE THREAD

**Issue by scottbedard** [vuejs/vue-loader#573]
What are the barriers around supporting functional components, would it be possible to have a component with no `<template>` block but does have a `render` function? Allowing this would make it easier to drop down to a functional component when possible, without having to give up the joy of scoped css.

If this is something we could do, I would be happy to put in the work to make it happen.

**Comment by ktsn** [comment]
> to have a component with no <template> block but does have a render function

It looks like already allowed? #390

**Comment by scottbedard** [comment]
Last I checked, it was not allowed. I'll double check to see if this was added since August.

See #325

**Comment by Alphmega** [comment]
Any progress for this issus ?

**Comment by scottbedard** [comment]
@yyx990803 could you provide some information about the challenges in supporting functional components? It might help to know what I'm up against if I get the go-ahead to work on this.

**Comment by yyx990803** [comment]
The primary reason is that the render function context is different for normal/functional components. This means the template compiler needs to output different render function code for a functional component. This work would need to happen in Vue core and it may need to cover quite a few subtle edge cases, which is why I haven't spent the time to actually work on it.

**Comment by scottbedard** [comment]
Ah, sounds like more than I'm able to take on. Thanks for the fast response.

**Comment by scottbedard** [comment]
@yyx990803 one additional thought on this matter. Would this still be difficult to support if we took the template compiler out of the equation? Could a functional component in a `.vue` file not just define a `render` function, and still be able to utilize the `<style>` block benefits of a single file component?

**Comment by yyx990803** [comment]
@scottbedard yes, you can do that

**Comment by blake-newman** [comment]
@scotbedard.

All is working fine for me in latest release. Using render function with script file no longer throws error. 

Only condition to throw error is if using a template with `functional: true`

**Comment by scottbedard** [comment]
Perfect, I guess I've been on an older version of the loader that still threw an error. Thanks guys!

**Comment by scottbedard** [comment]
Sorry to revive this, but it appears that the scope id is not being applied to functional components. Scoped css does works with non-functional components defining a render function. I'm using vue-loader 10.1.2 and Vue 2.1.20

**Comment by blake-newman** [comment]
Strange, it seemed to be working for me. 

Scope: 
<img width="583" alt="screen shot 2017-02-01 at 17 09 49" src="https://cloud.githubusercontent.com/assets/7272211/22517530/552179e8-e8a1-11e6-84bd-8fc9a8b6c39d.png">

No scoped:
<img width="674" alt="screen shot 2017-02-01 at 17 09 04" src="https://cloud.githubusercontent.com/assets/7272211/22517531/553a6ed0-e8a1-11e6-9d1a-f376bc89032b.png">

**Comment by vladferix** [comment]
In my case, scoped ids were also not applied for functional component. Removing functional: true made this to work.
