### ISSUE TITLE
Problem configuring `scss` lang for stylesheets

### ISSUE THREAD

**Issue by ShayDavidson** [vuejs/vue-loader#58]
I'm trying to define a "custom" lang for `scss`, so it'll use the `sass-loader` for `<style lang='scss'>`, but can't manage to make it work.

This is the `vue` section in my webpack.config:
```javascript
module.exports = {
    ...
    vue: {
        loaders: {
            scss: 'sass'
    }
}
```

And this is the error:
```
ERROR in ./~/sass-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/app.vue
Module build failed: TypeError: undefined is not a function
    at Object.module.exports (/Users/sdavidson/Development/bring/node_modules/sass-loader/index.js:211:17)
```

Am I missing adding pipes to the `scss` loader?

**Comment by aidistan** [comment]
Consider use following instead
```
vue: {
    loaders: {
      scss: 'style!css!sass'
    }
  }
```

**Comment by octref** [comment]
Just in case people come to this thread, this works for me in the current version:

```
  vue: {
    loaders: {
      'scss': 'vue-style!css!sass'
    }
  }

```

Versions:

```
├── css-loader@0.23.1
├── node-sass@3.7.0
├── sass-loader@3.2.0
├── vue@1.0.24
├── vue-hot-reload-api@1.3.2
├── vue-loader@8.5.2
├── vue-style-loader@1.0.0
├── webpack@1.13.1
└── webpack-dev-server@1.14.1
```

**Comment by Beatusvir** [comment]
@fsaenger I'm trying your suggestion but I get this error:
```
Module not found: Error: Can't resolve 'style'
```

**Comment by chanonroy** [comment]
```javascript
loaders: {
    scss: 'style-loader!css-loader!sass-loader'
}
```

The code above ended up working for me. Seems like it needs the exact spelling of the loaders to resolve.

**Comment by Beatusvir** [comment]
@chanonroy 
Trying this right away, updating answer asap

**Comment by chanonroy** [comment]
Also - make sure you have `style-loader`, `css-loader`, `sass-loader`, and `node-sass` saved in your package.json's devDependencies.

**Comment by Beatusvir** [comment]
Yes it worked! had to install `style-loader` as you mentioned, weird since it was previously there and didnt see an error before.

Thanks @chanonroy

**Comment by chanonroy** [comment]
<3 @Beatusvir

**Comment by cj** [comment]
I'm still getting this error `TypeError: undefined is not a function` when using `lang='scss'`.

```javascript
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: [
            require('autoprefixer')({
              browsers: ['last 3 versions']
            })
          ],
          loaders: {
            scss: 'style-loader!css-loader!sass-loader'
          }
        }
      },
```

**Comment by Beatusvir** [comment]
That doesn't look like the error we were getting. Sounds like JavaScript error to me.
