### ISSUE TITLE
Doesn't compile when saving imported CSS files

### ISSUE THREAD

**Issue by demrks** [vuejs/vue-loader#584]
I have the following folder structure

```
src/
  assets/
    css/
      subfolder/
        imported.css
      components/
        component1.css
      main.css
  components/
    Component1.vue
  App.vue
  main.js
```

The main.css file includes every css file (via `postcss-import`), e.g. in "subfolder", except for the files in "components" ("css/"), which are included in each component, e.g. "Component1.vue".

In the "App.vue" file, I include my `main.css` file

```vue
<template>...</template>
<script>...</script>
<style src="assets/css/main.css"></style>
```

All my assets are compiled with webpack and the webpack dev server. While that works just fine whenever I save any ".vue.js" file, the "main.css" or the component css files (all included by a ".vue" file), it just doesn't do anything when I try to save my "imported.css". 

```javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: [
            require('postcss-import')()
          ]
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },

  /* ... */
}
```

I think that this issue is related to vue-loader because I use it to include and compile my CSS files. Please let me know if that's not correct.

**Comment by kazupon** [comment]
I seem this issue is same as #447 
Please try to `postcss-cssnext` setting too.

**Comment by demrks** [comment]
In fact, that's what I already do in my project. I just tried to create a reduced test case. I read that using `postcss-loader` with `postcss-import` could solve this problem, but I'm not sure if you can combine those two with vue-loader, can you?

**Comment by sgraewe** [comment]
Did you find a solution?

**Comment by demrks** [comment]
@sgraewe No, I've tried a few things, but haven't found a way to fix this issue yet. I would greatly appreciate any advice, though.
