### ISSUE TITLE
[Proposal] allow to use postcss.config.js

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#585]
I am asking for adding https://github.com/michael-ciniawsky/postcss-load-config to vue-loader. It would be helpful for people (like me ^^) who use gulp-postcss/postcss-loader and keep postcss config in one place. Now in order to use postcss in vue-loader I do:

```.js
{
  postcss: require('../postcss.config')
}
```

it's not the end of the world, but I think would be nice if we could skip the require and idk pass `true` as a value?

```js
{
  postcss: true // will try to get config from postcss.config.js
}
```

**Comment by yyx990803** [comment]
I actually think it's better to explicitly require the config. This makes the config much easier to follow. Otherwise if someone is unaware of this implicit behavior they'd be confused.

**Comment by barraponto** [comment]
That's how it works now for `.babelrc` and `eslintrc`. It is actually weird that it _doesn't_ support `postcss.config.js`.

**Comment by yyx990803** [comment]
Didn't know that this is the convention used by postcss-loader, yeah that makes sense to keep it consistent.

**Comment by barraponto** [comment]
@yyx990803 it doesn't need `postcss: true` now, it just loads by default, right?

**Comment by yyx990803** [comment]
yeah, not released yet. Will likely be 11.0 since auto-loading is potentially a breaking change if the user already uses a postcss config file.
