### ISSUE TITLE
10.1.0: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by johman10** [vuejs/vue-loader#599]
Hi!
I just updated Vue loader to the newest version 10.1.0 but I seem to get an error when loading the page. It's complaining that process is not defined.

I traced it down to this line:
https://github.com/vuejs/vue-loader/commit/07b94527d1de4e9fd63917a3c7ddfe68576ba6be#diff-4faad1ca329bebe3369cba6e6d9fec39R14

Seems like you're assuming that a certain variable will be available but might not be the case? Not sure though.

I think we are using Vue loader in a pretty straightforward matter:
```js
module: {
    loaders: [
        {
            test: /\.vue$/,
            loader: 'vue'
        }
    ]
}
```

Hope this can be fixed somehow?

**Comment by LinusBorg** [comment]
Hm that's weird. webpack is a node application, and `process` [is a global](https://nodejs.org/api/globals.html#globals_process) in node.

**Comment by johman10** [comment]
Thanks for the super quick fix! I will test this out when there is new release! :)
