### ISSUE TITLE
An error occurred while trying to start webpack server

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vue-loader#604]
In all my projects with even new webpack, pops up the following error:

```
ERROR in ./src/App.vue
Module not found: Error: Can't resolve 'D:ProjetosPHPpublic     ccplease
ode_modules♂ue-loaderlibcomponent-normalizer' in 'D:\Projetos\PHP\public\tcc\please\src'
 @ ./src/App.vue 5:16-109
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

The correct path would be:

'D:\Projetos\PHP\public\tcc\please\node_modules/vue-loader/lib/component-normalizer.js

What can be?

**Comment by yyx990803** [comment]
Same with #601 - Please upgrade to latest (10.1.2)

**Comment by leonardovilarinho** [comment]
Thanks, it worked! Another option was to change the npm for yarn, where with the yarn install worked.
