### ISSUE TITLE
transpile code in .vue file to ES5

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vue-loader#605]
```javascript
{
  entry: './src/index.js',
  output: {
    path: __dirname+"/dist/",
    filename: "build.js",
    
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: "vue-loader",
        options: {
          buble: {
            objectAssign: 'Object.assign',
            transforms: {
              stripWith: false
            }
          }
        }
      },
      {
        test: /\.css$/,
        loader: "style-loader!css-loader"
      },
      {
        test: /\.jpg$/,
        loader: "file-loader"
      },
      {
        test: /\.png$/,
        loader: "file-loader"
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)(\?\S*)?$/,
        loader: 'file-loader'
      },
      {
        test: /\.js?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: [
            'es2015'
          ]
        }
      }
    ]
  },
  plugins: [
    
  ],
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.common.js'
    }
  },
}
```

only code in the `.js` file could be transpiled to ES5
code in `.vue` file will not be transpiled
why?

**Comment by zzzgit** [comment]
and,i don't have a .babelrc file in my project
is it the reason?

**Comment by zzzgit** [comment]
yes it works after adding a `.babelrc` file to the project
but why?

![image](https://cloud.githubusercontent.com/assets/1060733/22405949/d7b11eb4-e684-11e6-824d-c81425177294.png)

![image](https://cloud.githubusercontent.com/assets/1060733/22405951/e4d897f2-e684-11e6-9f09-90ce76cea1da.png)

adding a `.babelrc`,is it the only way to config ES6 transpilation support for `.vue`?
is there a way to config it in the `webpack.config.js` file?

**Comment by barraponto** [comment]
@zzzgit never tried, but... did you try:

```javascript
module.exports = {
  // other options...
  module: {
    // module.rules is the same as module.loaders in 1.x
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        // vue-loader options goes here
        options: {
          loaders: {
            'js': 'babel-loader'
          }
        }
      }
    ]
  }
}
```

It is documented in http://vue-loader.vuejs.org/en/configurations/advanced.html

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

As @barraponto mentioned, You can configure at vue options. see the [vue-loader docs](http://vue-loader.vuejs.org/en/configurations/advanced.html) and [babel-loader docs](https://github.com/babel/babel-loader)

Thanks.
