### ISSUE TITLE
Cannot add a loader after compiling the template (regression in 10.2)

### ISSUE THREAD

**Issue by ernestoalejo** [vuejs/vue-loader#615]
I have a custom babel plugin to extract translations from calls to a `__('My text')` function inside `<template>` and `<script>`. I need to pass the JS output of template-compiler through babel-loader to extract that messages. Before 10.2 I could simply use this config:

```js
    vue: {
      loaders: {
        html: 'babel-loader!vue-loader/lib/template-compiler',
      },
    },
```

After [this commit](f1df374d5fd5d921daf7d5b0619ce7fac4be0c1d) the html loader is *always* prefixed by the template-compiler, and there is no option to reorder it. I'm not using hot replacement so not having the moduleId wasn't a problem before.

I can't use a normal HTML preprocessor because the calls are inside Vue interpolations:

```html
<a :title="__('Foo')">
  {{__('Bar')}}
</a>
```

I would like to have a way to disable that prefixing, a way to override it or a new option to prefix loaders.

**Comment by kazupon** [comment]
Thank you for your filling!

>After **this commit** the html loader is always prefixed by the template-compiler,

Can you tell us the commit link please?
I could not check the commit url due to dead link. 😿

BTW, 10.1 later, we did support chaining with other loaders for pre-processing. 😉 
https://github.com/vuejs/vue-loader/commit/e2b41eac5528152396a703a594aa2ef4af5216c4

**Comment by ernestoalejo** [comment]
Sorry Github changed the URL, here it is: f1df374d5fd5d921daf7d5b0619ce7fac4be0c1d

**Comment by yyx990803** [comment]
Why not just use a pre-loader with simple regex? Is there anything specific that requires the use of babel?

Btw, your original usage would break scoped styles as the template-compiler will not get the component's moduleId.

**Comment by ernestoalejo** [comment]
Three reasons here:
1) It extracts in one pass and replaces the translated texts in another one. That could allegedly be done with regexps but the code will be more difficult to maintain.
2) It's difficult to match inside attributes, I'll have to import and use an HTML parser to replace and then emit something vue-template-compiler can still process without any space changes (let's ignore sourcemaps for a moment).
```
<div :title="__('First example')">
  {{__('{OPTIONS, plural, one {There is 1 option} other {There are # options} }', {
    OPTIONS: state.options,
  })}}
</div>
```
3) It requires two different plugins, one for HTML, one for JS.


A single babel plugin can solve all those problems at once in a very simple way:

```js
var ReplaceMessagesPlugin = function() {
  return {
    visitor: {
      CallExpression: function(path) {
        var node = path.node;

        var vmCall = (...check babel parse tree here...);
        var directCall = (...);
        var scriptCall = (...);
        if (vmCall || directCall || scriptCall) {
          node.arguments[0].value = shorthash.unique(node.arguments[0].value);
        }
      },
    },
  };
};
```

I wasn't using scoped styles either, I didn't noticed the bug. That commit was really needed and shouldn't be reverted because it solves issues.

I'm asking for some way to intercept *.vue files after the compilation in other loader. In its current form vue-loader cannot be chained to anything else later, only the generated file in `output` (with requires and hotAPI calls, nothing more) is sent through the pipe.

You can post-process the CSS output with your own loaders, you can post-process the JS output with your own loaders, but you can't post-process the templates output.

**Comment by yyx990803** [comment]
This should now be solvable with the new `postLoaders` option in 10.3.0: http://vue-loader.vuejs.org/en/options.html#postloaders
