### ISSUE TITLE
disable custom block warning for specified blocks

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-loader#617]
Before vux-loader's `custom block` feature came out, I have `<i18n>` blocks in my .vue files and I parsed it in my own way. After upgrading there are many many warnings for this and I cannot disable them. 

According to the document, the only way to make them disappeared is setting a loader for the block. But I don't think it's a good way.

What do you think?

**Comment by yyx990803** [comment]
Removed the warning in 10.2.4.

**Comment by airyland** [comment]
thx 👍
