### ISSUE TITLE
eslint linting inside temp loader folders

### ISSUE THREAD

**Issue by juancabrera** [vuejs/vue-loader#618]
I have this configuration on Webpack 2. Added the `eslint` configuration as per [docs](https://github.com/vuejs/vue-loader/blob/master/docs/en/workflow/linting.md).

```javascript
  module: {
    rules: [
      {
        enforce: 'pre', 
        test: /.vue$/,
        loader: 'eslint-loader'
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: {
            plugins: [
              require('stylelint')(),
              require('postcss-import')(),
              require('postcss-cssnext')({
                browsers: 'last 2 versions'
              }),
              require("postcss-reporter")({ clearMessages: true }),
            ],
            options: {
              autoprefixer: false
            }
          }
        }
      },
      {
        test: /\.js$/,
        loaders: ["babel-loader", "eslint-loader"],
        include: projectRoot,
        exclude: /node_modules/,
      }
    ]
  }
```

But when I run webpack, got the linting warning and erros on the `.vue` files, which is cool, but also it run the lint in the temporary loader folders, here an example of the output I got:

```shell
WARNING in ./src/Application.vue

/Users/cabrera/htdocs/ssense-frontend/src/Application.vue
  10:43  warning  Extra semicolon  semi

✖ 1 problem (0 errors, 1 warning)

 @ ./src/client.js 2:0-36

WARNING in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader!./src/Application.vue

/Users/cabrera/htdocs/ssense-frontend/src/Application.vue
  10:43  warning  Extra semicolon  semi

✖ 1 problem (0 errors, 1 warning)

 @ ./src/Application.vue 7:2-148
 @ ./src/client.js

WARNING in ./~/vue-loader/lib/template-compiler.js?id=data-v-65b562da!./~/vue-loader/lib/selector.js?type=template&index=0!./~/eslint-loader!./src/Application.vue

/Users/cabrera/htdocs/ssense-frontend/src/Application.vue
  10:43  warning  Extra semicolon  semi

✖ 1 problem (0 errors, 1 warning)

 @ ./src/Application.vue 9:2-207
 @ ./src/client.js

WARNING in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-65b562da!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/eslint-loader!./src/Application.vue

/Users/cabrera/htdocs/ssense-frontend/src/Application.vue
  10:43  warning  Extra semicolon  semi

✖ 1 problem (0 errors, 1 warning)
```

I have tried to exclude the `/~/` temporary folder but is still linting inside that folder.

**Comment by LinusBorg** [comment]
you haven't defined any `exclude` or `exclude:` for the vue-loader rule (like you did for the babel-loader rule).

It should look like this:
```
{
  test: /\.vue$/,
   loader: 'vue-loader',
   include: projectRoot,
  exclude: /node_modules/,
  options: {
  //...
  }
}
```

**Comment by juancabrera** [comment]
@LinusBorg I did try that, and actually as your example you will be excluding the `/node_modules/` bit it's still linting inside the temporary folders `/~/`

**Comment by LinusBorg** [comment]
I have never come across this, can you please setup a reproduction repository?

**Comment by juancabrera** [comment]
@LinusBorg sure, here is the repo and instructions: https://github.com/juancabrera/vue-loader-repro-repo.

**Comment by LinusBorg** [comment]
Thanks.

When I run this, I get one eslint error about the semicolon at line 10 in `Application.vue`

When I fix that, no more errors appear.

This line:

```
ARNING in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-6e7e7c0d!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/eslint-loader!./src/Application.vue
```

Is just the webpack-internal path (in-memory, it doesn't use a temp folder). And it disappears as soon as the error in Application.vue is fixed.

localhost:3000 goves me the app:

![bildschirmfoto 2017-02-03 um 21 39 29](https://cloud.githubusercontent.com/assets/1444526/22607715/5580e040-ea59-11e6-821c-a8b26c59b109.png)

So - I don't see the problem, sorry.

**Comment by juancabrera** [comment]
@LinusBorg thanks for the quick check.

maybe is not a problem, is more of a ideal scenario, because it's showing each warning 4 times, instead of just one from the `./src/**/.vue` path

**Comment by LinusBorg** [comment]
Oh, right. Didn't really catch that.

But good news: vue-loader 10.3.0 just got released, and it only displays once now:

![image](https://cloud.githubusercontent.com/assets/1444526/22608738/6bcf7f8c-ea5e-11e6-88df-d1494912f193.png)

**Comment by juancabrera** [comment]
lucky me, thank you for following this up @LinusBorg, much appreciated!
