### ISSUE TITLE
Vue-Router + Hot Reload

### ISSUE THREAD

**Issue by exah** [vuejs/vue-loader#62]
Strange behaviour when I trying hot reload component inside routes: http://cl.ly/dlnM

Component in video: https://github.com/exah/goremykina/blob/master/components/art/index.vue
RouterView: https://github.com/exah/goremykina/blob/master/pages/index.vue
Root: https://github.com/exah/goremykina/blob/master/index.js

Am I doing something wrong?

**Comment by sergeymorkovkin** [comment]
How did you resolve this? In my case it's only reproducing when hot-reloading layout.vue

**Comment by vagusX** [comment]
@exah  hot to resolve it ?

**Comment by skyrpex** [comment]
This is related to #252.

The problem is that the components are defined using vue files that load index.js and index.css. Seems that the reload code thinks that those index.js and index.css files are the same, even being in different directories.

This should be solved...

**Comment by exah** [comment]
@vagusX, @sergeymorkovkin problem disappears after updating to latest version, thats why I closed issue. Sorry not to mention this.
