### ISSUE TITLE
stylelint not working properly when used with vue-loader

### ISSUE THREAD

**Issue by juancabrera** [vuejs/vue-loader#627]
### What's the issue

`stylelint` not linting properly when used with `vue-loader`.

####  Example:

For this CSS code:
```css
<style>
:root {
  --color-main: green;
}

.my-app {
  background: #eee;
  padding: 10px;

  & .child {
    color: var(--color-main);
  }
}
</style>
```

I'm getting these warnings from `stylelint`:

```shell
src/Application.vue
29:1	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
33:3	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
33:3	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
35:1	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
```

###  What's the expected outcome

Get same results as when running the `stylelint` cli.

#### Example:

When I run this:

```shell
node_modules/stylelint/bin/stylelint.js '**/*.vue'
```

Got the expected outcome:

```shell
src/components/MyCmp.vue
 1:1  ✖  Unexpected empty source   no-empty-source
```

### Notes

`vue-loader` version: `10.3.0`
`stylelint` version: `7.8.0`

configuration (`webpack`):
```javascript
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: {
            plugins: [
              require('stylelint')(),
              require('postcss-import')(),
              require('postcss-cssnext')({
                browsers: 'last 2 versions'
              }),
              require("postcss-reporter")({ clearMessages: true }),
            ],
            options: {
              autoprefixer: false
            }
          }
        },
        include: projectRoot,
        exclude: /node_modules/
      },
```

#### Repro repo:
https://github.com/juancabrera/vue-loader-repro-repo

Run `node_modules/stylelint/bin/stylelint.js '**/*.vue'` for expected outcome
Run `npm run build-c` to see unexpected ourcome.

**Comment by juancabrera** [comment]
Just as FYI, I implemented `stylelint` using the webpack plugin and that works as expected. Not sure if you still want to dig into this issue, you can follow up the other discussion in here: https://github.com/stylelint/stylelint/issues/2316

**Comment by yyx990803** [comment]
vue-loader pads empty lines when extracting CSS to ensure correct source mapping lines, this may be the cause of the issue. Anyway, it's recommended to use a dedicated pre-processor setup as suggested in #303.
