### ISSUE TITLE
Compiler halts if a Vue component ends with `</tag`

### ISSUE THREAD

**Issue by edjroot** [vuejs/vue-loader#628]
Hello,

I'm using Webpack with hot reloading. If one of my Vue components ends with anything that looks like an unclosed closing tag (`</`, `</script`, `</whatever`), the compiler halts and doesn't work anymore unless I kill it and start it again. Other content (including invalid tags) seem to cause no problems. There are no error messages, just "webpack: bundle is now INVALID". I believe this is unwanted behavior since no other error (eg. in JS syntax) causes halting.

**Comment by yyx990803** [comment]
Fixed in https://github.com/vuejs/vue/commit/a0a619f6119c4cc6c71934c29fe3e62d3d608da9

**Comment by edjroot** [comment]
Thanks a lot, Evan!
