### ISSUE TITLE
Array destructuring in v-for

### ISSUE THREAD

**Issue by posva** [vuejs/vue-loader#630]
> Moved from https://github.com/vuejs/vue/issues/4884

According to https://github.com/vuejs/vue-loader/blob/v10.0.0/docs/en/features/es2015.md#es2015-in-templates, object destructuring is possible. What about arrays?

```js
export default {
  data() {
    return {
      map: new Map([['a', 1], ['b', 2]])
    }
  }
}
```
```html
<div v-for="[ key, value ] in Array.from(map)"></div>
```
Compilation fails for me with:
```
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-b057b41e!./resources/assets/js/modulos/ventas/facturas/show/template.html
Module parse failed: C:\Users\Carlos\Dev\compuservice\web\salesmaster\node_modules\vue-loader\lib\template-compiler.js?id=data-v-b057b41e!C:\Use
rs\Carlos\Dev\compuservice\web\salesmaster\resources\assets\js\modulos\ventas\facturas\show\template.html Unexpected token (35:11)
You may need an appropriate loader to handle this file type.
|     staticClass: "panel-heading"
|   }, [_vm._v("Devoluciones")]), _vm._v(" "), _vm._l((Array.from(_vm.devoluciones)), function(ref) {
|     var _vm.key = ref[0];
|     var _vm.value = ref[1];
|
 @ ./resources/assets/js/modulos/ventas/facturas/show/index.vue 5:2-118
 @ ./resources/assets/js/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./resources/assets/js/app.js ./resources/assets/sass/app.scss`
```

Relevant: [Map.prototype\[@@iterator\]()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/@@iterator)

**Comment by posva** [comment]
Ha, it may actually be because of the compiler. The generated code is:

```js
    var _vm.val = ref[0];
    var _vm.key = ref[1];
```

**Comment by rhyek** [comment]
If you need me to test anything, just let me know.

**Comment by kazupon** [comment]
Yeah, [vue-template-es2015-compiler](https://github.com/vuejs/vue-template-es2015-compiler/blob/master/buble.js) have a bug.
We need to fix [this](https://github.com/yyx990803/buble).

**Comment by yyx990803** [comment]
Fixed in https://github.com/vuejs/vue-template-es2015-compiler/commit/96d2570a6e0cb11f40bb006ba70f6b7e2f3fc17b
