### ISSUE TITLE
Hot reload does not work with ES6 class declaration

### ISSUE THREAD

**Issue by phenrigomes** [vuejs/vue-loader#636]
I am using "vue-loader": "^10.3.0" of webpack template, but hot reload has issues to function.

**Comment by yyx990803** [comment]
Please be more specific - are you using https://github.com/vuejs/vue-class-component ? If yes, with babel or TypeScript? If no, please note there is not native ES6 class support in Vue's API.

**Comment by phenrigomes** [comment]
I am using Babel:

```
{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
},
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')],
        exclude: /node_modules/
}
```

import Vue from 'vue';
import Component from 'vue-class-component';

@Component({})
export default class AdvantagesZone extends Vue {}

---

But changes on template or js dont trigger hot reload.

**Comment by yyx990803** [comment]
This is a vue class component issue then, please open issue at corresponding repo.

**Comment by John0x** [comment]
@yyx990803 are you sure, that it is a problem with the class component?
Changes to the code trigger "something", at least it outputs to the console the following:
````
[HMR] Checking for updates on the server...
process-update.js:100 [HMR] Updated modules:
process-update.js:102 [HMR]  - ./~/vue-loader/lib/template-compiler.js?id=data-v-027f3a80!./~/vue-loader/lib/selector.js?type=template&index=0!./src/pages/front/index.vue
process-update.js:107 [HMR] App is up to date.
````

It just doesn't reload the changes. Once you reload it in the browser (f5) the changes are there.

**Comment by John0x** [comment]
Repro repo:
https://github.com/John0x/babel-vue-repro
