### ISSUE TITLE
Cannot export a vue file on declare.

### ISSUE THREAD

**Issue by Dafrok** [vuejs/vue-loader#638]
### Description

Exporting a `.vue` file in a `.js` file on declare causes a Vue warn of component definition.

### Enviroment

- webpack 2.2.1
- vue-loader 10.3.0
- vue 2.1.10

### Reproduction

[https://github.com/Dafrok/issue-of-vue-loader](https://github.com/Dafrok/issue-of-vue-loader)

### Expected Output

When I has compiled the `component.js`, I except same result of both case 1 and case 2.

#### Case 1

```javascript
export default './Component.vue' // This line causes a waring.
```

#### Case 2

```javascript
import Component from './Component.vue'
export default Component
```

### Actual Output

The case 1 causes a waring and `Component` can't be mounted. But the case 2 works well.

```
[Vue warn]: Invalid Component definition: ./Component.vue 
```

**Comment by znck** [comment]
Provide minimal reproduction code. You can create a repository on github.

**Comment by Dafrok** [comment]
@znck OK, I've done it.

https://github.com/Dafrok/issue-of-vue-loader/blob/master/README.md

**Comment by Dafrok** [comment]
Sorry, it's a mistake.

**Comment by ty7466** [comment]
What was the issue? @Dafrok
