### ISSUE TITLE
The problem of include Jade  file with vue-loader

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/vue-loader#64]
Here is my Vue component structure：
```vue
<template lang="jade">
include index.jade
</template>

<style lang="less">
@import "index.less";
</style>

<script>
</script>
```

When the index.jade file changes，webpack-dev-server will not automatically compile code, there is no good solution to it?

**Comment by findborg** [comment]
maybe try the require command instead of @import.  Just guessing.
did you see this?
@import "~bootstrap/less/bootstrap";

**Comment by chaoren1641** [comment]
@findborg Using `@import` in less, vue-loader can work, but jade is not

**Comment by skyrpex** [comment]
Yeah, the real problem is that the

```jade
include index.jade
```

doesn't keep track of ```index.jade``` changes...

**Comment by yyx990803** [comment]
Hmm I can probably add support for `<template src="...">` to deal with this.

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue-loader/releases/tag/7.1.0

**Comment by skyrpex** [comment]
You're so fast! Will test ASAP. Thanks =)
