### ISSUE TITLE
官方能否提供一个加速构建速度的例子

### ISSUE THREAD

**Issue by chaiyanlin** [vuejs/vue-loader#640]
如题，不管是用类似happypack的多线程工具，还是用dll的方式，官方能否提供一个最符合的范例给我们。

**Comment by yinheli** [comment]
感觉用了 webpack2 以后快了很多呢

**Comment by chaiyanlin** [comment]
webpack2快我没太感受到。

最新的vue-cli构建出来的项目已经是用了webpack2了，就脚手架生成的默认hello.vue项目直接npm install都要7s...

我现在能做的就是webpack cache开启，babel-loader的cacheDirectory开启，能快3s左右而已。

________________________________
发件人: yinheli <notifications@github.com>
发送时间: 2017年2月22日 9:58:27
收件人: vuejs/vue-loader
抄送: Yanlin Chai; Author
主题: Re: [vuejs/vue-loader] 官方能否提供一个加速构建速度的例子 (#640)


感觉用了 webpack2 以后快了很多呢

―

**Comment by chaiyanlin** [comment]
@yinheli 
webpack2快我没太感受到。

最新的vue-cli构建出来的项目已经是用了webpack2了，就脚手架生成的默认hello.vue项目直接npm run build都要7s...

我现在能做的就是webpack cache开启，babel-loader的cacheDirectory开启，能快3s左右而已。

**Comment by blade254353074** [comment]
换个更好的 CPU 吧。。。
要是没法换的话，用 DllPlugin 再试试

**Comment by flyyang** [comment]
最近用happypack做了一点测试。[地址](https://flyyang.github.io/2017/03/09/%E4%BD%BF%E7%94%A8happypack%E5%B0%86vuejs%E9%A1%B9%E7%9B%AEwebpack%E5%88%9D%E5%A7%8B%E5%8C%96%E6%9E%84%E5%BB%BA%E9%80%9F%E5%BA%A6%E6%8F%90%E5%8D%8750/)。

**Comment by chaiyanlin** [comment]
现在haptpack 已经支持vue_loader了，由大大在那边拉了一个pr，但我还是没配成功

发自我的 iPhone

在 2017年3月10日，上午2:11，Pengfei Yang <notifications@github.com<mailto:notifications@github.com>> 写道：


最近用happypack做了一点测试。地址<https://flyyang.github.io/2017/03/09/%E4%BD%BF%E7%94%A8happypack%E5%B0%86vuejs%E9%A1%B9%E7%9B%AEwebpack%E5%88%9D%E5%A7%8B%E5%8C%96%E6%9E%84%E5%BB%BA%E9%80%9F%E5%BA%A6%E6%8F%90%E5%8D%8750/>。
