### ISSUE TITLE
background-image in style property, what is the best practice?

### ISSUE THREAD

**Issue by NemoAlex** [vuejs/vue-loader#646]
In .vue template, we usually use img tag to show a image, like
```
<img src="./link/to/image.png">
```
which is OK.
However sometime we need to use background-image within inline style property:
```
<div style="background-image: url(./link/to/image.png)"
```
But it's not working, somehow I need to write it like this:
```
<div :style="{'background-image': 'url(' + require('./link/to/image.png') + ')'}">
```
or the ES2015 way:
```
<div :style="{'background-image': `url(${require('./link/to/image.png')})`}">
```
which is still not neat.
So I'm just wondering is there any better way to do this?

**Comment by Krispomoho** [comment]
I have met the same question, especially the image can't be converted as base64

**Comment by NemoAlex** [comment]
Maybe it's a bad idea to use base64 image in style property, it makes HTML kinda ugly.

**Comment by yyx990803** [comment]
Why not just use CSS instead of inline styles?

**Comment by blade254353074** [comment]
Required images is transformed to base64 DataURI is due to the limit option of [url-loader](https://github.com/webpack-contrib/url-loader).
You can reduce the limit, may be 10000 (bytes). It's useful to reduce the number of requests.

Then, vue-loader is piping `<style></style>` to the corresponding loader (depends on your config).
Such as scss-loader, postcss-loader, css-loader, style-loader, and css-loader will piping the results to url-loader and file-loader.
So you can just write css to instead of inline styles:

`url(image.png)` => `require('./image.png')`
`url(~module/image.png)` => `require('module/image.png')`

**Comment by NemoAlex** [comment]
@yyx990803 @blade254353074 I know what we CAN. But it's a little bit annoying to do these workarounds.

**Comment by blade254353074** [comment]
For reducing requests, url-loader limit option must be configured......Although it's annoying.

**Comment by NemoAlex** [comment]
@blade254353074 I believe the size limitation is not relevant in this conversation.

**Comment by blade254353074** [comment]
@NemoAlex But you said "base64 image in style property makes HTML kinda ugly"...

**Comment by willChowFront** [comment]
@yyx990803 I have the same issue .I need change this background-image frequently by data in component, in css , i can't find a way to solve it

**Comment by shshaw** [comment]
This isn't really vue-loader's fault, but I kept running into a similar issue where an image URL contained a space, so the style was invalid and would not appear on the element. 

Ensure your `backgroundImage` declarations are wrapped in `url(` and quotes so the style works correctly, no matter the file name.

ES2015 Style:

```
<div :style="{ backgroundImage: `url('${image}')` }"></div>
```

Or without ES2015:

```
<div :style="{ backgroundImage: 'url(\'' + image + '\')' }"></div>
```

**Comment by dimitrieh** [comment]
for Googlers, I had success with (using Nuxt):

`:style="{ backgroundImage: 'url(' + require(`@/assets/img/${page.image}`) + ')' }"`

**Comment by johnyluyte** [comment]
for Googlers, I has success with (same using Nuxt):

`:style="{ backgroundImage: 'url(' + require('@/assets/imgs/bg'+backgroundId+'.png') + ')' }"`

@dimitrieh 's answer is indeed correct, but his [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) was "absorbed" by github's Markdown parser. If you copy his code from his comment directly, the code is not going to work.

However if you are using ES2015 you should be using Template literals. My code here is just for understanding the concept.

**Comment by PierBover** [comment]
Again, for Googlers...

In my case (an old Vue project) the problem seemed to be that the image wasn't being bundled by Webpack, even if the URL was right. Using `require(...)` returns the correct URL in the final bundle, but will also "tell Webpack" to bundle the image.

**Comment by chandregowda** [comment]
I placed the image inside public/img/<image.jpg> and then referred the image path mentioned in data property

`<div class="text-center mb-4" :style="{ backgroundImage: `url('${bgImage}')` }">
`
```
data() {
    return {
      bgImage: "/img/virtual-mac.jpg"
    };
  },
```

**Comment by steelegg** [comment]
我没有找到更好的方法
I didn't find a better way.
但这样也可以解决我的问题
But it can also solve my problem.
如下:
as follows
```
<div class="col-md-12 white box-shadow" :style="{'background-image':'url('+backgroundUrl+');'}">
```

```
 data() {
         return { backgroundUrl:require('~/static/img/ads.png') }
        },
```
or

```
data(){
         return { backgroundUrl:'http://timgsa.baidu.com/timg?image&quality=80&size=b10000_10000&sec=1532246957&di=5c7453291ff3ca5963cca9c40a0be2ca&imgtype=jpg&src=http%3A%2F%2Fimg6.bdstatic.com%2Fimg%2Fimage%2Fpcindex%2Ftongmengpctufanbingbing.jpg' }
}
```

**Comment by Ubunfu** [comment]
I was able to accomplish what I believe is a similar end goal by using a computed property to  build a collection of individual CSS attributes (dynamic or not), and then assign the whole group to the DOM element as an inline style. 
#### Template:
```
<div class="movie-wrapper" :style="styles">
</div>
```
#### Computed Props:
```
<script>
const BACKDROP_BASE = 'https://image.tmdb.org/t/p/w1280';
export default {
    computed: {
        styles() {
            return {
                'background-image': `url(${BACKDROP_BASE}/${this.movie.backdrop_path})`,
                'background-repeat': 'no-repeat',
                'background-size': 'cover'
            }
        }
    }
}
```
And I could still attach additional properties with normal CSS, but it looks like any properties assigned via the computed property may take precedence as I think they are applied on top of the regular CSS.
#### Regular CSS:
```
<style scoped>
.movie-wrapper {
    position: relative;
    padding-top: 50vh;
}
</style>
```

**Comment by vitortraut95** [comment]
Vue.filter('ifEmptyFoto',  function(value) {
      if (!value || value == "") { return 'images/foto_padrao.jpg'; }
      else return value;
})

Vue.filter('bgImage',  function(value) {
      return 'background-image: url('+ value +');';
})

<div class="foto" :style="caminhoDaImagem | ifEmptyFoto | bgImage"></div>

**Comment by OkaSroka** [comment]
> for Googlers, I had success with (using Nuxt):
> 
> `:style="{ backgroundImage: 'url(' + require(`@/assets/img/${page.image}`) + ')' }"`

:style="{ backgroundImage: 'url(' + require(`../assets/images/${slide.src}`) + ')' }"

**Comment by OkaSroka** [comment]
:style="{ backgroundImage: 'url(' + require(`../assets/images/${slide.src}`) + ')' }"

**Comment by OkaSroka** [comment]
`:style="{ backgroundImage: 'url(' + require(`../assets/images/${slide.src}`) + ')' }"`

**Comment by OkaSroka** [comment]
`
:style="{ backgroundImage: 'url(' + require(`../assets/images/${slide.src}`) + ')' }"
`

**Comment by terryjohnpaul** [comment]
body
{background-image: url(image link);
background-size:cover;
} 

//place it in style tag..it worked for me

**Comment by adoniskrasniqi** [comment]
> Why not just use CSS instead of inline styles?

Dynamic data.

**Comment by onuriltan** [comment]
Hello everyone, if you want to use css background property from your assests, you can use it as follows 
`background-image: url('~@/assets/img.jpeg');`
If you want to know how this works, you can read it from [https://vuejs-templates.github.io/webpack/static.html](url). Hope this helps :)

**Comment by Seankps** [comment]
I had to format mine like this with url('')
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700');

**Comment by jaeyholic** [comment]
I had difficulties with how to set dynamic background images in nuxt but i did it and it worked perfectly.

_**In SCRIPT**_
computed: {
    service() {
      return this.services.find(service => service.id === this.id)
    },
    backgroundURL() {
      return require(`~/assets/img/bgheads/${this.service.head}`)
    }
  }

**_In HTML_**
<div
          class="bgcolor"
          :style="{backgroundImage: `url(${backgroundURL})`, backgroundSize: 'cover', height: 400 + 'px', paddingTop: 30 + 'rem'}"
        >
          <div class="container">
            <h1>{{service.name}}</h1>
          </div>
        </div>



just in case if someone is also finding the same problems i faced. it took me some hours to figure it out

**Comment by keryanS** [comment]
Hi,

and how about to do that in a v-for ? 

`<div v-for="bg in paths" :style="{'background-image': `url(${require(${bg.path)})`}">`

does'nt work obviously.. someone has a way to do that ?

**Comment by Farb** [comment]
![image](https://user-images.githubusercontent.com/7587900/70964530-2932d780-20c7-11ea-90c1-8d21c57897c7.png)
![image](https://user-images.githubusercontent.com/7587900/70964604-70b96380-20c7-11ea-888d-de75afcc80c0.png)

I did it,but I fell it is annoying!

**Comment by pratyushtewari** [comment]
> Hello everyone, if you want to use css background property from your assests, you can use it as follows;
> `background-image: url('~@/assets/img.jpeg');`
> If you want to know how this works, you can read it from [here](https://vuejs-templates.github.io/webpack/static.html). Hope this helps :)

We need to put this into the nuxt documentation. Please!

**Comment by onuriltan** [comment]
> [#646 (comment)](https://github.com/vuejs/vue-loader/issues/646#issuecomment-454959580)
> 
> > Hello everyone, if you want to use css background property from your assests, you can use it as follows;
> > `background-image: url('~@/assets/img.jpeg');`
> > If you want to know how this works, you can read it from [here](https://vuejs-templates.github.io/webpack/static.html). Hope this helps :)
> 
> We need to put this into the nuxt documentation. Please!

Let me try it with Nuxt! Then I can send a pr to nuxt docs :)

**Comment by onuriltan** [comment]
> > [#646 (comment)](https://github.com/vuejs/vue-loader/issues/646#issuecomment-454959580)
> > > Hello everyone, if you want to use css background property from your assests, you can use it as follows;
> > > `background-image: url('~@/assets/img.jpeg');`
> > > If you want to know how this works, you can read it from [here](https://vuejs-templates.github.io/webpack/static.html). Hope this helps :)
> > 
> > 
> > We need to put this into the nuxt documentation. Please!
> 
> Let me try it with Nuxt! Then I can send a pr to nuxt docs :)

Actually Next Team stated about this issue in the docs, I read it carefully in order to catch the info :) 
![image](https://user-images.githubusercontent.com/7993238/71512628-65202680-2897-11ea-8708-f3546ffc9b98.png)

**Comment by pratyushtewari** [comment]
@onuriltan I saw this on nuxt, but your solution had both ~ and @ together and which is not mentioned in the nuxt documentation. 

In the sass and css files I need to use the "@" path.
In the scoped css inside the vue files I need to use your solution the "~@" together.

**Comment by onuriltan** [comment]
@pratyushtewari actually I tried both ways

1. `~assets/img.jpeg` = worked
2. `@assets/img.jpeg` = didn't work
3. `~@/assets/img.jpeg` = worked

Yes the guide is a little bit misleading, I can open a pr but just in english language :)

**Comment by dirablue** [comment]
> @pratyushtewari actually I tried those
> 
> 1. `~assets/img.jpeg` = worked
> 2. `@assets/img.jpeg` = didn't work
> 3. `~@/assets/img.jpeg` = worked
> 
> Yes the guide is a little bit misleading, I can open a pr but just in english language :)
@onuriltan great!

@/assets/img.jpeg  = this is also didn't' work.

but it works inside template tag.
do you know the reason?

**Comment by coolternet** [comment]
> @pratyushtewari actually I tried those
> 
> 1. `~assets/img.jpeg` = worked
> 2. `@assets/img.jpeg` = didn't work
> 3. `~@/assets/img.jpeg` = worked
> 
> Yes the guide is a little bit misleading, I can open a pr but just in english language :)

it doesn't work for me

**Comment by kayoderock** [comment]
Don't waste time, @onuriltan is right.

**Comment by arijitnaskar** [comment]
This is Working for me:
```
:style="
    { backgroundImage: 'url(' + require('../assets/images/bg1.jpg') + ')'}"
```

But This is throwing compile error:

 ```
:style="
    { backgroundImage: 'url(' + require('../assets/images/bg1.jpg') + ')' ,
    backgroundSize:'cover'}"
```

Can someone help please.

Error:

Errors compiling template:

```
  invalid expression: Unexpected token ':' in

    
    { backgroundImage: 'url(' + require('../assets/images/bg1.jpg') + ')' ,
    backgroundSize:'cover'}
```

**Comment by pratyushtewari** [comment]
@arijitnaskar - Can you try this and see if this works?

`:style="{ backgroundImage: url('" + require('../assets/images/bg1.jpg') + "') , backgroundSize: cover}"`

**Comment by arijitnaskar** [comment]
Mine is working with this:

```
:style="
    [{ backgroundImage: 'url(' + require('../assets/images/bg1.jpg') + ')' 
   },{backgroundSize:'100%'},{backgroundPosition:'center bottom'}]"
```

**Comment by nejat-njonjo** [comment]
Close this.

**Comment by EmmyMay** [comment]
I am having this same issue. The path is resolving correctly but not as a string. 

![image](https://user-images.githubusercontent.com/31524469/117848598-5b744480-b27b-11eb-90fe-f99417d67333.png)

**Comment by nejat-njonjo** [comment]
Solutions were provided above.

**Comment by VivianS-GitHub** [comment]
> I was able to accomplish what I believe is a similar end goal by using a computed property to build a collection of individual CSS attributes (dynamic or not), and then assign the whole group to the DOM element as an inline style.
> 
> #### Template:
> ```
> <div class="movie-wrapper" :style="styles">
> </div>
> ```
> 
> #### Computed Props:
> ```
> <script>
> const BACKDROP_BASE = 'https://image.tmdb.org/t/p/w1280';
> export default {
>     computed: {
>         styles() {
>             return {
>                 'background-image': `url(${BACKDROP_BASE}/${this.movie.backdrop_path})`,
>                 'background-repeat': 'no-repeat',
>                 'background-size': 'cover'
>             }
>         }
>     }
> }
> ```
> 
> And I could still attach additional properties with normal CSS, but it looks like any properties assigned via the computed property may take precedence as I think they are applied on top of the regular CSS.
> 
> #### Regular CSS:
> ```
> <style scoped>
> .movie-wrapper {
>     position: relative;
>     padding-top: 50vh;
> }
> </style>
> ```

how if hving multiple image?

**Comment by Penguin-learning-to-walk** [comment]
мне помогло следующее:
`<footer class="footer-area bg-img background-overlay" style="background-image: url('html/img/bg-img/4.jpg');">`

**Comment by kipropbrian** [comment]
If you have an issue where background-image works in development but leads to 404 in when you build, just move the image to public.
