### ISSUE TITLE
vue-cli webpack template: dependencies were not found in node_modules

### ISSUE THREAD

**Issue by lanlin** [vuejs/vue-loader#648]
ENV:
```
      osx: 10.12.2
      webpack: ^2.2.1
      vue: ^2.1.10
      vue-loader: ^11.0.0
      vue-style-loader: ^2.0.0
      node: ^7.5.0
      npm: ^4.1.0
```

After upgrade my project configs & other dependencies to same as  the latest vue-cli webpack template.

Not build the project with `"vue-cli init webpack xxx" `,  but just modify the configs to the same as this template was.

When run dev, i got these errors

![image](https://cloud.githubusercontent.com/assets/3468024/23007304/cfc1a428-f442-11e6-9f5a-c50cb4b3cc52.png)

the resolve config is same as vue-cli webpack template.

![image](https://cloud.githubusercontent.com/assets/3468024/23007347/20ce3df4-f443-11e6-867b-91435e12fb2c.png)

so, what happened?

**Comment by yyx990803** [comment]
Fresh install from `vue-cli` and everything works as intended. Sorry but we can't magically help you debug config that's not written by us.

**Comment by lanlin** [comment]
@yyx990803 seems find the resion, it's caused by "less"

After built from vue-cli webpack template,  i add a file named "colors.less" to src/assets.

Then import it from App.vue and run dev， got a same error.

![image](https://cloud.githubusercontent.com/assets/3468024/23120595/edc3b242-f797-11e6-97b8-d5086d327d86.png)

![image](https://cloud.githubusercontent.com/assets/3468024/23120615/07ca720c-f798-11e6-8330-906699e06ea1.png)

![image](https://cloud.githubusercontent.com/assets/3468024/23120663/393378ac-f798-11e6-96c9-be28d5ef691e.png)

I do not change anything else.

**Comment by yyx990803** [comment]
cli 模板不会帮你装预处理器。http://vuejs-templates.github.io/webpack/pre-processors.html

**Comment by lanlin** [comment]
Sorry, 没有注意这个东西。从 webpack 1.x 转过来的。1.x 构建好工程之后 package.json 已经引入 less-loader 了。升级后没去注意这些，我以为新版的是直接通过 vue-loader 处理完组件里面的其他 import 呢。

不好意思，耽误你时间了啊，亲。
