### ISSUE TITLE
Embedded css not minified

### ISSUE THREAD

**Issue by ramakrishnamundru** [vuejs/vue-loader#649]
When used code splitting, the css of vue file is embedded in the js. But its not minified. 

eg:
`#bar[data-v-2a424420] {\n    height : 0;\n}\n#line[data-v-2a424420] {\n    height : 0;\n}`

the `\n` and the spaces are added from the original css.

can this be removed by the vue loader

**Comment by yyx990803** [comment]
This is a configuration problem in the webpack template. Fixed here: https://github.com/vuejs-templates/webpack/commit/17876a4778f8ca4d2463cda177604a748dd3e047
