### ISSUE TITLE
Disable auto-loading PostCSS config file

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-loader#654]
Since `postcss-loader` does not load it when option is set. https://github.com/postcss/postcss-loader/blob/master/index.js#L67

**Comment by michael-ciniawsky** [comment]
@egoist I work on a PR already including a few other smaller improvements and yes I would also change it to that logic. `inline ? use(inline) : use('postcss.config.js')  // inline = webpack.config.js`. So it's either explicit via `webpack.config.js` or implicit via `postcss.config.js, but clearly separated.
