### ISSUE TITLE
imported .css file in sass isn't under scope

### ISSUE THREAD

**Issue by slimfancy** [vuejs/vue-loader#657]
When I @import a .css file in .vue scoped sass as below:

```
<template>
<div id="test"></div>
</template>

<style lang="scss" scoped>
  @import "foo.css";
</style>
```

`foo.css` content

```
#test {
    color: red;
}
```

the `#test` style is not just applied under the component scope.

![image](https://cloud.githubusercontent.com/assets/4530475/23100047/d6175de8-f6b0-11e6-8e17-e32d678c147b.png)

But, if I change `foo.css` to sass file `foo.scss`, the scoped css will work. 

![image](https://cloud.githubusercontent.com/assets/4530475/23100052/03c99fc6-f6b1-11e6-82c9-a9e5e05e3614.png)

**Comment by yyx990803** [comment]
Importing a plain `.css` in SCSS results in a raw URL import instead of inlining the target file into the current file. There's no way for vue-loader to process an URL import.
