### ISSUE TITLE
Support /deep/ selector

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-loader#661]
moved from https://github.com/vuejs/vue/issues/4298

**Comment by indooorsman** [comment]
looking forward to this feature !

**Comment by jsikorski** [comment]
👍

**Comment by xamgore** [comment]
It's not really clear about the /deep/ selector, does it solve the following problem?

There is a child component:
```vue
<template>
  <div class="red">child</div>
</template>

<style scoped>
  .red { color: red }
</style>
```

In the parent component we just want to change the color of the child.
```
<template>
  <child class="forceBlue"/>
<template>

<style scoped>
  .forceBlue { color: blue }

  /* or just the child tag */
  child { color: blue }
</style>

**Comment by xamgore** [comment]
It's not really clear about the /deep/ selector, does it solve the following problem?

There is a child component:
```vue
<template>
  <div class="red">child</div>
</template>

<style scoped>
  .red { color: red }
</style>
```

In the parent component we just want to change the color of the child.
```vue
<template>
  <child class="forceBlue"/>
<template>

<style scoped>
  .forceBlue { color: blue }

  /* or just the child tag */
  child { color: blue }
</style>
```

As a result we expect the blue label:
```html
<div class="red blue">child</div>
```

Why? It maybe convenient to set default styles in the child component, but refine something (i.e. positioning) in the parent. If you know another ways to solve the issue, let me know, please :)

(Guys from the telegram channel @vuejs_ru have advised me to use vue-custom-element plugin, but it's a bit strange solution.)

**Comment by tonypee** [comment]
I've been encountering this issue. It would be great to have a solution, currently i just have to namespace everything, and not use scoped

**Comment by jsnick** [comment]
@yyx990803 
I really want to solve this..
the style of a component can be changed by each parent components.
But I have no way to modify scoped child component style from scoped parent component because the scope of parent component is not applied to child component deeply!
(but of course, we have `!important` keyword..)

for example.. 
```
<!-- Child component and style-->
<div class="my-child-component">
  <h1 class="my-child-component__title">I'm Child Component</h1>
</div>

<style scoped>
.my-child-component__title {
  color: red;
}
</style>



<!-- Parent component and style -->
<div class="my-parent-component">
  <my-child-component></my-child-component>
</div>

<style scoped>
.my-parent-component {
  & > .my-child-component__title {
    color: blue;
  }
}
</style>
```

output of parent component

```
<div class="my-parent-component" data-v-parenthash>
  <div class="my-child-component" data-v-parenthash data-v-childhash>
    <h1 class="my-child-component__title" data-v-childhash>I'm Child Component</h1>
    <!-- only child-hash applied, not parent-hash -->
  </div>
</div>


<!-- parent style output -->
.my-parent-component .my-child-component__title[data-v-parenthash] {
    color: blue; /* this is not applied cause title component has no parenthash attribute */
}
```


So my team don't use scoped attributes in all components.
Just name all class with a component prefix like `my-child-component , my-parent-component` in above example.

**Comment by jordyvandomselaar** [comment]
For single styles I've been using variables in css: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables, it works like a charm. For multiple styles you could use: https://tabatkins.github.io/specs/css-apply-rule/, the Polymer framework uses both and has polyfills for them (browsers are starting to support both features, but not all do so as of now.). Maybe Vue-loader could include said polyfills?

**Comment by yyx990803** [comment]
This is now implemented in 12.2.0: https://github.com/vuejs/vue-loader/releases/tag/v12.2.0

**Comment by indooorsman** [comment]
awesome!

2017年5月27日 18:48，"Evan You" <notifications@github.com>写道：

**Comment by lucasm-iRonin** [comment]
It looks great. Does it work for `lang="scss"` to?

**Comment by yyx990803** [comment]
@lucasm-iRonin yeah, but you need to use `/deep/` instead of `>>>` because SASS cannot parse the latter

**Comment by librae8226** [comment]
Great, just encountered this issue then find this fix immediately. 
```
.nav-badge >>> .nav-badge-style {
  width: 16px;
  height: 16px;
  font-size: 10px;
}
```
**Compiled to =>**
```
.nav-badge[data-v-2c25094c] .nav-badge-style {
    width: 16px;
    height: 16px;
    font-size: 10px;
}
```
Works like a charm to override muse-ui badge style. 😊

**Comment by jordyvandomselaar** [comment]
Scss parses`>>>` just fine =)

**Comment by MikaelEdebro** [comment]
@jordyvandomselaar At least for me >>> does not work with SCSS. /deep/ is working fine though.

**Comment by yangdm2015** [comment]
I'm using scss and neither >>> or /deep/ works for me

`<style rel="stylesheet/scss" lang="scss" scoped>
.main-paragraph /deep/ .test {color: red;}
</style>`
Compiled to =>
`.main-paragraph /deep/ .test[data-v-3a3fa84f] {
  color: red;
}
`

**Comment by michaelpumo** [comment]
Can confirm that in SCSS, >>> does not work. Using /deep/ fixes this issue.

e.g. We can style a component with class name '.Another-Component' inside of our parent component with a class name of '.Filters'.

```
<style lang="scss" scoped>
.Filters {

  /deep/ .Another-Component {

    background-color: blue;

  }

}
</style>
```

Happy coding!

**Comment by mikeevstropov** [comment]
If you are using nested components (often) a "scoped" attribute is nothing. Look at following example:

*parent-component.vue*
```html
<template>
    <div class="parent-component">
        <span class="label">My label</span>
        <child-component/>
    </div>
</template>

<style scoped>
    .parent-component >>> .label {
        color: red;
    }
</style>
```

*child-component.vue*
```html
<template>
    <div class="child-component">
        <span class="label"></span>
    </div>
</template>
```
What you think about `color` property in `.child-component .label`, yes it will be `red` but do we want this?

What we can say about "scoped" attribute? Do u really use it? NO. You just adding fu***g prefix for all classes! This is dirty way but we do it. So why vue-loader cant do it for us? Just add prefix for all classes if scoped attribute requested.

Thank you

**Comment by jordyvandomselaar** [comment]
Still wondering why we're not using the spec for this. (Css variables, mixins) would be much easier.

**Comment by lucduong** [comment]
@yyx990803 Sorry for bothering you but In my case, it doesn't work as expected.

```
<style lang='scss' scoped>
.box-card {
  margin: 0;
  &.report-settings {
    .el-form {
      .el-form-item {
        /deep/ .el-form-item__label {
          line-height: 20px;
          padding: 0;
        }
      }
    }
  }
}
</style>
```

It rendered to 
```
.box-card.report-settings .el-form .el-form-item /deep/ .el-form-item__label[data-v-edf5593e] {
    line-height: 20px;
    padding: 0;
}
```

What I expected is:
```
.box-card.report-settings .el-form .el-form-item[data-v-edf5593e] .el-form-item__label {
    line-height: 20px;
    padding: 0;
}
```

My HTML after rendering is:
![scss_scoped_vue](https://user-images.githubusercontent.com/2667418/32581508-bc4d9d24-c51c-11e7-876f-99f7c44482a5.png)

**Comment by yyx990803** [comment]
@lucduong please open a separate issue with a reproduction.
