### ISSUE TITLE
scss compiles only in a single line {}

### ISSUE THREAD

**Issue by leandroruel** [vuejs/vue-loader#662]
when i try save my style, shows this error when my css have multilines, but when i change to a single line, everything works fine.
i'm not sure what is happening.
```
 ERROR  Failed to compile with 1 errors

 error  in ./src/assets/sass/app.scss

Module build failed:
undefined
             ^
      Invalid CSS after ".app-sidenav {": expected "}", was "{"
      in C:\wamp\www\api_view\src\assets\sass\app.scss (line 10, column 15)

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-63ff7eff!./~/sass-loader?indentedSyntax!./src/assets/sass/app.scss 4:14-217 13:2-17:4 14:20-223
```

**Comment by LinusBorg** [comment]
Hello @leandroruel,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.

**Comment by LinusBorg** [comment]
Hi there!

I close this issue because of inactivity. If you want to follow up on this issue, please open a new one, and provide the necessary information (a working reproduction etc.) in that issue.

**Comment by meirotstein** [comment]
You're probably using lang="sass".
If you want the CSS-superset syntax you should use lang="scss" instead.
