### ISSUE TITLE
Hot reloading fails if path has special characters in it ie Dropbox Business

### ISSUE THREAD

**Issue by monowales** [vuejs/vue-loader#665]
Not sure if this is an issue, or an issue for hotreload middleware, but if you are serving app from Dropbox business folder, (which forces you to use **Dropbox (Business Name)** as a name format), the hot reloading feature doesn't work anymore.

**Comment by kazupon** [comment]
Thank you for your filling!

I can understand about Dropbox business folder.
Can you tell us the more explanation it?

**Comment by LinusBorg** [comment]
@kapuzon that's a problem of webpack-hot-middleware. it watches the files on the file system, and that mechanism collides with Dropbox' file watch functionality.

Happens with other sync services as well.

 I think we can do little about it in vue-loader.

**Comment by LinusBorg** [comment]
@monowales after some research: does the path to your Dropbox folder contain spüecial chars like parenthesis? Dropbox for business adds something like `Dropboxy (Personal)` which seems to choke the `--watch` capabilities of webpack.

https://github.com/webpack/watchpack/issues/42

**Comment by monowales** [comment]
Yep @LinusBorg, see title. Is the done thing to just wait for the dependency library maintainers to get around to fixing this?

**Comment by LinusBorg** [comment]
Well, *we* can'T fix webpack or its dependencies ...

**Comment by monowales** [comment]
Thanks @LinusBorg, I already have a symlink **to** Dropbox for development, and that doesn't solve it. I've hacked the `chokidar` dependency to require at least `3.0.0` of `is-glob` now and it seems to be working. I *think* this is unstable for Windows users though, which is why it hasn't been included yet. Still, for Mac and `vue-loader` users, this might be a handy short term fix...

Thanks for the great work by the way.

**Comment by yyx990803** [comment]
Closing since this seems to be out of our hands?
