### ISSUE TITLE
Loader option syntax doesn't work with advanced options

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue-loader#673]
https://github.com/vuejs/vue-loader/issues/536 suggests that we must use `webpack-combine-loaders` to convert an options object to a query string, but it doesn't work for all options objects.

Given this setup:

```js
var combine = require('webpack-combine-loaders');

{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      js: babelLoader,
    },
  },
}
```

This works:

```js
const babelLoader = combine([{
  loader: 'babel-loader',
  query: {
    presets: ['es2015', 'stage-0'],
  },
}])
// babel-loader?presets[]=es2015&presets[]=stage-0
```

This doesn't:

```js
const babelLoader = combine([{
  loader: 'babel-loader',
  query: {
    presets: [['es2015', { modules: false }], 'stage-0'],  // Nested array
  },
}])
// babel-loader?presets[][]=es2015&presets[][][modules]=false&presets[]=stage-0
```

It appears that https://github.com/webpack/loader-utils `parseQuery` can't handle the second case above.

How can I pass options to `babel-loader`? I can't rely on a `.babelrc` file since the options are dynamically determined in the `webpack.config.js` file.

**Comment by nemtsov** [comment]
@decademoon you can use the [.babelrc env options](https://babeljs.io/docs/usage/babelrc/#env-option) to define your environments in `.babelrc` and then in the `vue-loader`'s `options.loaders.js` use: `babel-loader?forceEnv=<env_defined_in_babelrc>`. I use this to have a different babel configuration for client and server -side js in server-side rendered vue apps.

**Comment by qiyuan-wang** [comment]
@decademoon I write a webpack plugin, vue-loader-options-plugin](https://github.com/qiyuan-wang/vue-loader-options-plugin),  to deal with babel-loader's options in vue-loader config, you can have a try.

**Comment by maoberlehner** [comment]
Any updates on this issue, this is very frustrating for me :(

**Comment by Akimyou** [comment]
I used the root git submodule for my project, have to use:
```js
{
  babelrc: false,
  extends: resolve('.babelrc')
}
```
to specified local .babelrc file.

But vue-loader ignore it.

Thanks to @qiyuan-wang , It can work like this:

```js
  plugins: [
    new VueLoaderOptionsPlugin({
      babel: {
        babelrc: false,
        extends: resolve('.babelrc')
      }
    })
  ]
```

**Comment by yyx990803** [comment]
Closing as this is resolved in v15
