### ISSUE TITLE
为什么父组件添加scoped后不能影响子组件

### ISSUE THREAD

**Issue by zWingz** [vuejs/vue-loader#674]
![image](https://cloud.githubusercontent.com/assets/13031838/23346990/d758b092-fcd9-11e6-9124-c7594cb51149.png)

这里不是写了子组件会受父组件的有作用于的样式影响吗 ?

**Comment by Jinjiang** [comment]
原文的意思是子组件的跟元素，不是整个子组件都受影响

Translation:
This question is asking why it doesn't affect child component.

That's a miss-understanding for the docs and I have gave the explanation. So this issue could be closed I guess.
Thanks.
