### ISSUE TITLE
yarn update issue

### ISSUE THREAD

**Issue by steambap** [vuejs/vue-loader#675]
When I update vue-loader to the latest (11.1.3), yarn package manager will use vue-hot-reload-api version 2.0.6, not the latest(2.0.11). And it refuse to use the latest vue-hot-reload-api even if I explicitly add it as dependency. This will result in runtime error with latest vue esm runtime. 

I know this is probably yarn's issue, but I assume that this can be resolved simply by bump dependencies in package.json?

**Comment by rferro** [comment]
+1

**Comment by jialanmo** [comment]
+1

**Comment by blade254353074** [comment]
+1

**Comment by sqal** [comment]
Yeah, this causing error in my App since I updated to vue@2.2.1 vue-router@2.3.0

![img1](http://image.prntscr.com/image/09b944b89e924a3f93c997c17d548065.png)
![img2](http://image.prntscr.com/image/d6b568a40afe45909628f55196953c4a.png)

Had to disable HMR for now...

**Comment by blade254353074** [comment]
I made a pr to update the dependencies.
Waiting for

**Comment by LinusBorg** [comment]
I assume this is because yarn caches dependencies on your machine for some time.

you could clean the cache with `yarn cache clean`

**Comment by sqal** [comment]
@LinusBorg ok I managed to resolve my previus issue by cleaning yarn cache, removing node_modules/yarn.lock and installing dependencies once again. But if i may, I have one more question though. I have disabled production tip in my app via config `Vue.config.productionTip = false` but this only works when HMR is disabled. Why is that?

**Comment by LinusBorg** [comment]
Sorry to say, but I have no idea :D It may have something to do that the HMR API loads vue itself during the replacement process, in somehwere in that proceess the setting gets lost? 

Maybe open an issue?

**Comment by yyx990803** [comment]
published 11.1.4 with bumped `vue-hot-reload-api` version.
