### ISSUE TITLE
Have a page to list all officially supported preprocessors

### ISSUE THREAD

**Issue by octref** [vuejs/vue-loader#680]
Currently the supported preprocessors is very vague in the doc.

I suggest dedicating a page to supported preprocessors, where for each supported lang, list:

- Needed webpack config
- Needed loader / dependency

This will help eliminating people inventing syntaxes like:

- `<template lang="html">`
- `<script lang="babel">`
- `<script type="text/babel">`

This will also help linting tools and textmate grammar authors.

I can work on a PR to the doc, if someone can tell me what I'm missing in this list of supported lang values:

- pug/jade
- sass/scss
- less
- stylus
- postcss
- js
- ts
- coffee

**Comment by octref** [comment]
@kazupon Should I just go ahead to submit a PR to the doc?

**Comment by kazupon** [comment]
@octref 
yes, you can submit your PR!
We are wating your improvement PR. 😺

**Comment by linde12** [comment]
This would be a nice addition to the docs :+1:

**Comment by Jinjiang** [comment]
My concern is that we don't _officially_ support any loaders. Any loader can be created or disabled any time from the whole community. So there is too many uncertain factors if we write them down.

IMO another way to make it clear is just creating an independent repo which includes all kinds of examples and welcome contributions for all people. And then we can put the link into the docs.

Thanks. 🙂

**Comment by octref** [comment]
With Webpack it's indeed more flexible, anyway for Vetur (for the sake of having correct syntax highlighting), I put a table here: https://vuejs.github.io/vetur/highlighting.html

![image](https://user-images.githubusercontent.com/4033249/40127562-80a0c600-58e4-11e8-9434-4dede49a2655.png)

Also this page (https://vue-loader.vuejs.org/spec.html#language-blocks) seems to already cover everything so I'm marking this issue closed.
