### ISSUE TITLE
Separate output file for each .vue component...

### ISSUE THREAD

**Issue by pstephenwille** [vuejs/vue-loader#681]
Is this even possible? 
The webpack docs say you can only have one output file.  Can the Vue-loader output each compiled .vue component into a separate file, like so...

myxxx.vue => myxxx.js

**Comment by LinusBorg** [comment]
it's webpack's job to determine how files are bundled, and so the exact files that are generated depend on your webpack config. vue-loader will never write files to your disk itself.

Nonetheless, I don't see the use case if this was possible?

**Comment by StephRagazzi** [comment]
That's exactly what I'm looking for...
[http://stackoverflow.com/questions/42354974/create-a-javascript-file-for-each-vue-js-component](http://stackoverflow.com/questions/42354974/create-a-javascript-file-for-each-vue-js-component)
The idea is to be able to distribute stand alone web components, like I explain in my question... thanks

**Comment by airyland** [comment]
you can just reused webpack.prod.conf.js. Import it and set entry to your .vue file path like this:

![image](https://cloud.githubusercontent.com/assets/559179/23611907/20e3ac0a-02b4-11e7-8d5e-acd6edde8f49.png)

then build it:

```
webpack(config, function (err, stats) {})
```
so you can build .vue files one by one.

reference: https://github.com/airyland/vux/blob/v2/build/build-components.js

**Comment by kazupon** [comment]
I think this solution is mentioned by @airyland 
Close
