### ISSUE TITLE
es2015 not working

### ISSUE THREAD

**Issue by ggaborx** [vuejs/vue-loader#683]
I have a .vue file which contains:

```
methods: {
    open(item) {
        ...
    }
}
```

And it seems like won't be transpiled properly because I had a syntax error in webpack's uglifyjs plugin:

> Unexpected token punc «(», expected punc «:»

When change my Vue component's open(item) method declaration into this:

```
methods: {
  open: function(item) {
     ...
  }
}
```
The uglifier won't complains about unexpected token anymore. 

Here is the babel-loader config for **.js** files:

```
use: [{
   loader: 'babel-loader',
        options: {
            presets: [
                ['es2015', { "modules": false }]
            ]
        }
}]
```
It works fine but only for **.js** files. I created a simple code in my site.js to test:

```
const test = {
    some(val) {
        console.log(val);
    }
}
```
It was transpiled (+uglified) correctly. So I think the issue must be in the vue-loader.

**Comment by ggaborx** [comment]
It seems like works only if .babelrc file present. 
Is there a configuration option to setup babel related values within the webpack.config file?

**Comment by Alex-Sokolov** [comment]
https://babeljs.io/docs/usage/babelrc/
> Lookup behavior
> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

I'm using `babel` inside package.json, I think it's better

**Comment by yyx990803** [comment]
When you use `options` for `babel-loader`, those option only apply to files matched by that specific rule - it doesn't cover `vue` files. As suggested, use `.babelrc` or `babel` field in `package.json` instead.
