### ISSUE TITLE
Hot reload not working with TypeScript (lang="ts")

### ISSUE THREAD

**Issue by chanon** [vuejs/vue-loader#687]
Reproduction here:
https://github.com/chanon/ts-vue-hmr
(Updated to Vue 2.2.1 with all npm dependencies updated.)

The current (unwanted) behavior is that any changes to the template or TypeScript code in the .vue file triggers a whole page reload.

See:
https://github.com/chanon/ts-vue-hmr/blob/c8638b8/src/components/Hello.vue#L36-L44

**Comment by chanon** [comment]
Using the latest vue-cli webpack template as a starting point, this looks like it has been fixed / the behavior is correct.

**Comment by chanon** [comment]
Yes, configuring webpack and getting hot reloading to work is the most frustrating thing! I spent a day too when starting my most recent project a few weeks ago. But I do have it working with .vue single file components and using script lang="ts" right now.

I could probably create a minimal example project. Should have a bit of time later today.

**Comment by ApricumMedia** [comment]
Thanks for looking into it so promptly after over a year, @chanon! It's only an issue when using external `.ts` files, from the experiments I tried to do, it must be failing (or, not-noticing, rather) between Webpack watching and the TypeScript compiler.

Do you have an example config file, for `webpack` and a `tsconfig`?

**Comment by chanon** [comment]
Alright, here you go:
https://github.com/chanon/vue-ts-hot-reload-example

**Comment by ApricumMedia** [comment]
Thanks, it does have the same issue for me, however:

1. Open `127.0.0.1:8080` as-is, we can see "Hello there".
2. Open `saySomething.ts` in an editor, change text.
3. Text is *not changed* via hot reload, only after reloading the page manually.

Can you reproduce this or does it refresh without a manual kickstart?

**Comment by chanon** [comment]
You need to open it with `http://localhost:8080` otherwise, as the javascript console displays in my case, you will get:

![image](https://user-images.githubusercontent.com/357737/44205090-63146680-a17f-11e8-8024-283a09241725.png)

So, yes, if I open it with `127.0.0.1:8080` it does not work. 
But if I open it with `http://localhost:8080`, then everything works fine.

**Comment by ApricumMedia** [comment]
Sorry, that misunderstanding was entirely my fault — I did open it via `localhost`, just typed out the url as an example.

The issue, though, remains the same. Changing anything in the external `.ts` doesn't trigger a hot reload, other changes do (like changing the contents of components directly). I did find one example project where this worked for me, however: https://github.com/ryutamaki/vue-template-webpack-typescript

Here I can put the script-content of the `HelloWorld.vue` into a `HelloWorld.ts` and reference that with a `<script lang="ts" src="./HelloWorld.ts"></script>`, it does work with hot reloading. Now I need to find out what the differences are.

**Comment by chanon** [comment]
The project you linked uses webpack 3.6, webpack-dev-server 2.9.1, so it is probably very different (and using old stuff)

**Comment by ApricumMedia** [comment]
Interesting, do you have the suspicion that there was some sort of issue introduced in a later version of the `webpack-dev-server` related to the watch functionality of the TypeScript compile step?

My own project's dependencies brought onboard by `nuxt` are as follows:

```yml
webpack "^3.11.0"
webpack-bundle-analyzer "^2.10.0"
webpack-dev-middleware "^2.0.5"
webpack-hot-middleware "^2.21.0"
webpack-node-externals "^1.6.0"
```

**Comment by yyx990803** [comment]
Just use Vue CLI 3...

**Comment by chanon** [comment]
Yes, vue-cli 3 worked out of the box for me too, so you should try that.

For me, I just found with vue-cli template it was hard to customize the webpack config. Maybe it isn't that hard, but I didn't want to have to learn about configuring with webpack chain thing after already investing so much time to understand webpack config itself. That is why I wrote my own webpack configs. But I did use vue-cli as a guideline.

**Comment by ApricumMedia** [comment]
Alright, you fabulous people, I must thank you both. I try to find my way with `vue` and `nuxt` and I didn't know about `vue-cli`. Started off on version 3, selected all my extras and hot reloading external TypeScript files worked straight away. Trying to combine that with `nuxt` now.

**Comment by bifacil** [comment]
We have a similar problem and @milewski  solution worked for us.

We just set the `transpileOnly` option and it worked!

![image](https://user-images.githubusercontent.com/4572969/84840548-2433ee00-b040-11ea-8c84-5ae9a07dd394.png)

We spend many hours trying to figure it out...
