### ISSUE TITLE
不是必现的，gulp-webpack 有 {watch: true} 配置时 <style> 会被误认为是 scoped

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vue-loader#69]
很奇怪，同一个文件，开了 gulp watch，在不同的时候保存，生成的 CSS 一会儿有 scoped 一会儿没有

版本号：7.0.3

webpack 配置信息

```json
vue: {
    "postcss": [ ],
    "autoprefixer": { "browsers": ["ios_saf >= 7", "android >= 4"] }
},
```

**Comment by yyx990803** [comment]
没遇到过，不过我从来不用 gulp，可能跟 gulp-webpack 的 watch 机制有关...

**Comment by Jinjiang** [comment]
可以能走到 scoped 逻辑这还是感觉怪怪的…… webpack 应该没有这个本事，另外时好时坏，我连个毕现的 demo 都提取不出来

如果没有什么明显的线索，我明天再抽空试试看吧，有新的进展我同步到这里

**Comment by Jinjiang** [comment]
https://gist.github.com/Jinjiang/933ebd132694bde5f218

这里有一个可重现的 demo

如果在 `lib/style-rewritter.js` 中加入日志，会发现每次执行到这里时 `plugins.length` 一直在涨，对应的 `add-in` 会被重复执行多次

另外这个问题如果没有那个 `yo` 的空 postcss 插件是不会出现的

这是我目前排查的进展

**Comment by yyx990803** [comment]
啊！明白了。因为忘记把 postcss plugins 做一个拷贝。

**Comment by yyx990803** [comment]
看下 7.1.7 应该解决了：https://github.com/vuejs/vue-loader/blob/master/lib/style-rewriter.js#L40

**Comment by Jinjiang** [comment]
赞！p.s. 我顺便学会了 postcss 和 webpack 的插件开发
