### ISSUE TITLE
The pug failed to parse attribute 

### ISSUE THREAD

**Issue by elvis-macak** [vuejs/vue-loader#693]
When I create a directive named `log-click`, and my templates code are written in pug/html.

html:
 - `<a v-log-click>`  ---> OK

pug:
 - `a(v-log-click='')` --->  OK
 - `a(v-log-click)`   ---> Failed

In the console it reports errors:
```
[Vue warn]: Property or method "v" is not defined on the instance but referenced during render
[Vue warn]: Property or method "log" is not defined on the instance but referenced during render
[Vue warn]: Property or method "click" is not defined on the instance but referenced during render
```

after inspecting the code, I found the compiled code is like below.

the value field is incorrect here.

```
directives: [{
      name: "log-click",
      rawName: "v-log-click",
      value: (_vm.v - _vm.log - _vm.click),
      expression: "v-log-click"
    }],
```

**Comment by LinusBorg** [comment]
it seems pug doesn't like attributes without a value and with dashes in their name.

**Comment by elvis-macak** [comment]
Get another issue
https://github.com/vuejs/vue-loader/issues/55

So just add `doctype html` in the vue-loader option works

**Comment by LinusBorg** [comment]
Strange. The pug-loader readme says that's the default?
