### ISSUE TITLE
Disable css modules for unit tests

### ISSUE THREAD

**Issue by znck** [vuejs/vue-loader#703]
Event after setting 

```
cssModules: {
            modules: false,
            localIdentName: '[local]'
          }
```

class names like `foo` are transformed to `foo_0`. There should be a way to disable as unit tests heavily depend on selectors.

**Comment by LinusBorg** [comment]
Seems useful to me!

**Comment by Jinjiang** [comment]
I find a simple way to keep the same class name by removing the index suffix for the first `<style>` tag. But if there are more than one `<style>` tag, the index suffix would be appended from the 2nd one.
