### ISSUE TITLE
Static class names replacement in template

### ISSUE THREAD

**Issue by znck** [vuejs/vue-loader#704]
When using CSS modules, class names are replaced in template at compile time.

For example:

```
<div class="red">Foo</div>
```

should become

```
<div class="_lkcjalei8942jksa_0">Foo</div>
```

before compiling to render function. This would save from unnecessary class attribute bindings.

------
See http://vuejs.github.io/rollup-plugin-vue/#/en/2.3/?id=static-class-replacement for reference.

**Comment by LinusBorg** [comment]
Wouldn't that make it hard/impossible to use a non-module class by the same name?

Imagine we have some global styles, one of which is called "red". Then we also have a local style called "red", which uses CSS modules.

In this case, both cases in the template would end up with the css module class, and the global one would be lost.

**Comment by znck** [comment]
That's a case but for reusable components it is expected that they don't leak any styles and should not be effected by external styles.

**Comment by Jinjiang** [comment]
@znck I am not sure whether I misunderstand it, but `<div class="foo" :class="[$style.red, 'bar']">Foo</div>` will be compiled to `<div class="foo DWJpyXqhbluGVSso6aZ-t_0 bar">Foo</div>` right now by default vue-loader config. So external styles like `.foo {}` and `.bar {}` could be effected.
Thanks.

**Comment by znck** [comment]
For `<div class="red"></div>`, with assumption that all styles used in component are local, `red` can be replaced with `DWJpyXqhbluGVSso6aZ-t_0`. This simplifies template from `<div :class="$style.red"></div>` and it would generate a static render function.

Though this might be confusing for many users. I feel this request should be ignored.

**Comment by Jinjiang** [comment]
Get your question. Yes I think the current way have less coupling between the template and style. And the connection is just `this.$style` which is programmable enough. So it's more flexible imo.
And I believe the effects from external styles could be well controlled by code convention and style guides.
Thanks.
