### ISSUE TITLE
Warning console named exports in *.vue files are ignored

### ISSUE THREAD

**Issue by gmferreir1** [vuejs/vue-loader#708]
My project display an warning in debug console once you started using version 8.7.0
In all files *.vue

## named exports in *.vue files are ignored.

I'm using the laravel-elixir-vue@0.1.8, i,m back to version vue-loader@8.3.1 all the warnings are gone.
Warnings appear only in gulp watch.

Gulp production warinings do not appear.

**Comment by simplesmiler** [comment]
Do your `.vue` files in fact have named exports?

**Comment by gmferreir1** [comment]
yes. i'm use
export default{ }
The application works, but the warnings keeps appearing.

**Comment by socieboy** [comment]
Any resolve on this?

**Comment by erikwestlund** [comment]
I am also having this issue.

**Comment by gabrielkoerich** [comment]
Same problem here.

**Comment by gmferreir1** [comment]
remove vue-loader and install version vue-loader@8.3.1.

**Comment by LucasLeandro1204** [comment]
vue-loader@8.5.3 seems okay too

**Comment by LinusBorg** [comment]
This was an intentional design decision.

**Comment by gmferreir1** [comment]
Because ?

Em 29 de mar de 2017 7:31 PM, "Thorsten Lünborg" <notifications@github.com>
escreveu:

**Comment by LinusBorg** [comment]
Already removed my comment, I misunderstood the issue.

**Comment by Dorisfhy** [comment]
@gmferreir1  it works !  Thx~

**Comment by Jinjiang** [comment]
@gmferreir1 Does this problem have been solved? Or does #1087 could solve this, which has been supported in v13.6.0?
Thanks.

**Comment by yyx990803** [comment]
Closing outdated issues - if the problem still persists in the latest version, please open a new issue using the [issue helper](new-issue.vuejs.org/?repo=vuejs/vue-loader) with a reproduction. Thanks.
