### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by skyrpex** [vuejs/vue-loader#71]
Is there a way to use the Hot Module Replacement having my component split into three files (JS, HTML and CSS)?

I ask this because I'd really love to keep the Atom's linters working on my code... Thanks.

**Comment by yyx990803** [comment]
HMR really depends on Webpack knowing that a file is a Vue component, so you must use the Vue format as the base. But there's one hacky way to do it: use `src` import for CSS, and just import and re-export another JS file in `<script>`.

**Comment by skyrpex** [comment]
Thanks for the info. Will do that.
