### ISSUE TITLE
Multiple v-for in a parent causes an error after compiling

### ISSUE THREAD

**Issue by kilobyte2007** [vuejs/vue-loader#714]
Hello,
There is a problem when using multiple v-fors in an parent node. For example I have this template:

```
<ul class="dates">
   <li v-for="blank in 3"></li>
    <li v-for="date in 28">
        <span>{{ date }}</span>
    </li>
 </ul>
```

After compiling from a **.vue** file, the second **li** is not being appended to the **ul**, but to the text node. For this to work I had to change my template like following (removing the newline):

```
<ul class="dates">
   <li v-for="blank in 3"></li><li v-for="date in 28">
        <span>{{ date }}</span>
    </li>
 </ul>
```

Is this a known issue, or a bug?

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
