### ISSUE TITLE
console warning is wrong: `<el-option v-for="item in options">: component lists rendered with v-for should have explicit keys.`

### ISSUE THREAD

**Issue by awuliu** [vuejs/vue-loader#715]
hi , maybe it`s not a problem , it seems fine , but the console log warning is wrong

Versions 
vue@^2.2.4
element-ui@^1.2.4
vue-loader@^11.1.4
vue-template-compiler@^2.2.4

Steps to reproduce
vue init webpack 
modify Hello.vue to 

```
<template>
  <div class="hello">

    <p v-for="(item, key) of options">{{item.label}} : {{item.value}}</p>

    <el-select v-model="type">
      <el-option v-for="(item, key) in options" :label="item.label + key" :value="item.value"></el-option>
    </el-select>

  </div>
</template>

<script>
export default {
  name: 'hello',
  data () {
    return {
      type: 'Welcome to Your Vue.js App',
      options: [
        {label: 'type1', value: '1'},
        {label: 'type2', value: '2'}
      ]
    }
  }
}
</script>
```
What is Expected?

no warning

What is actually happening?
```
 WARNING  Compiled with 1 warnings                                                                                                                                                11:06:01

 warning  in ./src/components/Hello.vue

<el-option v-for="item in options">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

```

**Comment by simplesmiler** [comment]
See https://github.com/vuejs/vue/releases/tag/v2.2.0
> When using `v-for` with a component, a `key` is now required. You will likely see a bunch of "soft warnings" when you upgrade, but this does not affect the current behavior of your app.

**Comment by awuliu** [comment]
I knew , just found <p v-for> did`t show the warning but ElementUI`s el-option does

**Comment by awuliu** [comment]
I knew , just found `<p v-for="(item, key) in options">` did not show the warning but ElementUI `<el-option v-for="(item, key) in options">` does

**Comment by yyx990803** [comment]
The warning only applies for components.

**Comment by dpdahal** [comment]
vue.js:603 [Vue tip]: <task v-for="task in tasks">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

//============here my code============

Vue.component('task-list', {
    template: `<div>
                <task v-for='(task,key) in tasks'>{{task.description}}</task>
                </div>`,

    data() {

        return {
            tasks: [
                {description: "got to the store", completed: true},
                {description: "got to the home", completed: false},
                {description: "got to the back", completed: true},
                {description: "got to the hospital", completed: false},
                {description: "got to the airport", completed: true},

            ]
        }
    }


});


Vue.component('task', {
    template: "<li><slot></slot></li>"

});
let app = new Vue({
    el: '#app'

});
