### ISSUE TITLE
[Feature Request] vue-loader doesn't support video(poster="xxx.png")

### ISSUE THREAD

**Issue by zhuowenli** [vuejs/vue-loader#718]
The vue-loader doesn't support the video `poster` attributes.

example:
```pug
<template lang="pug">
    .tutorials
        video(controls poster="../assets/poster.png") ❌
            source(src="../assets/video.mp4" type="video/mp4")
        img(src="../assets/poster.png") ✔️
</template>
```

**Comment by ktsn** [comment]
You can specify `transformToRequire` option to deal with that attribute.
http://vue-loader.vuejs.org/en/options.html#transformtorequire

**Comment by zhuowenli** [comment]
@ktsn THX,  It is so much helpful to me!
