### ISSUE TITLE
CSS SourceMap

### ISSUE THREAD

**Issue by ferhtgoldaraz** [vuejs/vue-loader#72]
I'm tryng to get CSS source maps. Should this be working, or what did I do wrong?

```js
// webpack.config.js
module.exports = {
    entry: './main.js',
    output: {
        path: './static/',
        publicPath: '/static/',
        filename: 'build.js'
    },
    module: {
        loaders: [
            { test: /\.vue$/, loader: 'vue' }
        ]
    },
    vue: {
        loaders: {
            stylus: 'css?sourceMap!stylus'
        }
    },
    devtool: 'source-map'
};
```

The app and project is exactly like the one described in the readme. Copy-pasted.
If you need more info tell me. Neither running webpack, nor the webpack-dev-server seem to work.

**Comment by yyx990803** [comment]
You also need to add `style!` loader which actually loads the style:

```
style!css?sourceMap!stylus
```
