### ISSUE TITLE
为什么用webpack2打包会生成多余代码

### ISSUE THREAD

**Issue by muyi0327** [vuejs/vue-loader#720]
用webpack2打包编译vue会生成很多多余代码，例如：
`"webpack:///(webpack)/~/node-libs-browser/~/buffer/index.js","webpack:///(webpack)/~/node-libs-browser/~/buffer/~/base64-js/index.js","webpack:///(webpack)/~/node-libs-browser/~/buffer/~/ieee754/index.js","webpack:///(webpack)/~/node-libs-browser/~/buffer/~/isarray/index.js","w`

这是截取的相应的sourcemap文件中对应的文件。对应源码里多了1500行左右代码。

**Comment by lookas2001** [comment]
Use English, please.

**Comment by agileago** [comment]
@muyi0327  这个是css-loader的问题 ，他们好像正在解决 https://github.com/webpack-contrib/css-loader/issues/454

暂时可以在 webpack的配置里面加上

```
node: {
  Buffer: false
}
```

**Comment by muyi0327** [comment]
@agileago fixed! thanks a lot!
