### ISSUE TITLE
using vue-loader?inject with scss and webpack 2 fails to find loader

### ISSUE THREAD

**Issue by squirmy** [vuejs/vue-loader#724]
When using the inject option of the vue-loader in webpack 2 it doesn't get the options that have been passed into it in the webpack configuration.

This part in the vuejs webpack template:

```javascript
  // http://vuejs.github.io/vue-loader/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', { indentedSyntax: true }),
    scss: generateLoaders('sass'),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }
```

This is fine for most loaders as they are named the same as the lang option in the single file vue component. However, as you can see above, scss uses the sass loader which causes vue-loader to not find the loader when passing in the inject parameter.

There is a solution [here](https://forum.vuejs.org/t/getting-vue-loader-testing-with-mocks-approach-to-work-with-webpack-2/5312). Where it creates two configurations; one with inject, and one without. This works, but you then hit another problem in that coverage cannot find the source file as it has the query parameter appended to the filename.

Considering I don't even need the styles in my unit tests - this all just seems a bit hard and I'm wondering if it's the correct approach.

**Comment by rsoule3** [comment]
Also seeing this issue, everything works great unless `<style lang="scss"></style>` is in the .vue file.  It looks like the vue-loader is looking at the defined lang and using that to load the appropriate loader when inject-loader is being used.

The issue with this is that `lang="scss"` actually needs to use `sass-loader`, so when it goes to load it can't find `scss-loader` as that is not a loader available.

**Comment by rsoule3** [comment]
@squirmy Leaving a workaround I got working tonight.

To get around this issue what I did was alias scss-loader to sass-loader, in my webpack.test.confg file I added this property:
```
    module: {
        ...
    },
    devtool: ...,
    // added field here, others given for reference
    resolveLoader: {
        alias: {
            'scss-loader': 'sass-loader',
        },
    },
```

Hope this helps!

**Comment by squirmy** [comment]
Thanks @rsoule3, I'll give it a shot.

**Comment by StudentWan** [comment]
@rsoule3 
Still, there seems some problem.

I built my project with the `vue-loader` guidence.

It says to loading a global settings file, I can do follow:

```
npm install sass-resources-loader --save-dev
```

Then add the following webpack rule:

```
{
  loader: 'sass-resources-loader',
  options: {
    resources: path.resolve(__dirname, '../src/style/_variables.scss')
  }
}
```

It all works well, but when goes to `inject-loader`, the global settings file can not be loaded....

![scss-global-error](http://p20zi8dae.bkt.clouddn.com/vue-err.png)
