### ISSUE TITLE
<template lang="pug"> Syntax highlighting in Atom

### ISSUE THREAD

**Issue by dzift** [vuejs/vue-loader#726]
I have pug installed as dependency. Both compile normally from what I've tested. Syntax highlighting is not working for pug. What might the problem be?

Using `<template lang="jade">` is working fine:
![jade](https://cloud.githubusercontent.com/assets/21025134/24139640/27d93b82-0e1d-11e7-9236-d1b0fe746ed3.png)

Using `<template lang="pug">` :
![pug](https://cloud.githubusercontent.com/assets/21025134/24139671/53812d94-0e1d-11e7-8ab7-069f116470f3.png)

**Comment by dzift** [comment]
Sorry for posting this. Seems like language-pug is buggy. Btw removing the extra line before the closing `</template>` fixes this.

**Comment by dperrymorrow** [comment]
thanks for posting this. Has been bugging me. Even had me going back to sublime for a bit.
