### ISSUE TITLE
vue-loader logging and persistence howto

### ISSUE THREAD

**Issue by borislitvak** [vuejs/vue-loader#727]
Hi, 

I cannot import .vue components from another .vue component. 
I'd like to request a configuration feature to log the action vue-loader is performing and to optionally to persist the files it generates, ala App.vue.ts.

You can view the full details at:
https://forum.vuejs.org/t/how-can-i-view-vue-loader-logs-and-generated-files/8350
Code:
https://github.com/borislitvak/vue-from-vue-question

Thanks, Boris

**Comment by borislitvak** [comment]
Dear Friends, I cannot proceed with Vuejs without this, your help is much appreciated!

**Comment by yyx990803** [comment]
Closing outdated issues - if the problem still persists in the latest version, please open a new issue using the [issue helper](new-issue.vuejs.org/?repo=vuejs/vue-loader) with a reproduction. Thanks.
