### ISSUE TITLE
'src' in html, 'url' in css, 'import from' in js ，path is not uniform

### ISSUE THREAD

**Issue by Cheese-Yu** [vuejs/vue-loader#736]
When I quote images in html & css & js ,use webpack packed my projected. Their path is not uniform.How should I do ? Thk U !

**Comment by kazupon** [comment]
Thank you for your filling!

Sorry, I don't your explanation.
Could you provide the more explanation (e.g) please ?

**Comment by Cheese-Yu** [comment]
just like:
in html: ```<img src="./../assets/logo.png">```
in css: ```background: url("./../assets/astronaut.png");```
in js: 
```
import luan from '../assets/luan.jpg'
import mouse from '../assets/mouse.jpg'
import yellow from '../assets/yellow.jpg'

    export default{
        data(){
            return{
                banners: [
                    { imgUrl: luan ,name: 'Alex Nowak' },
                    { imgUrl: mouse ,name: 'Metiew & Smith' },
                    { imgUrl: yellow ,name: 'Victory' },
                ],
                Wmouse: true,
                Wluan: false,
                Wyellow: false
            }
        },
  }
```
When I use the 'build', these path are not uniform.
in webpack.base.conf.js , this is my configure :
```
{
        test: /\.(png|jpe?g|gif)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: ('static/img/[name].[hash:7].[ext]')
        }
      },
```
After build ,this is the file path in 'index.html',path about url in the css is wrong
```file:///G:/myVuePage/Global/Global/dist/static/css/static/img/astronaut.ddab0dd.png```
The true file path is:
```file:///G:/myVuePage/Global/Global/dist/static/img/astronaut.ddab0dd.png```

If I change the webpack.base.conf.js,when the file path in 'index.html' is right,the true file path is 
 wrong.
I don't know how to configure these.
Thank U !

**Comment by LinusBorg** [comment]
Sorry, but your problem is still not clear, at learnt to me. 

Can you provide an actual reproduction repository that I can run?

**Comment by Cheese-Yu** [comment]
It's here https://github.com/Cheese-Yu/Global-Vue2.0 .In this repository,I have changed location of images by hand when I built it after.

**Comment by LinusBorg** [comment]
So you changed the [defaults of the template](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L58). Why? The defaults would be fine and do exactly what you seemt to want it to.

**Comment by Cheese-Yu** [comment]
Thank U very much! I am clear about it.Thanks for your explanation.
