### ISSUE TITLE
CSS separation

### ISSUE THREAD

**Issue by grofzero** [vuejs/vue-loader#741]
Hi, 

We have vue-loader in our webpack config with ExtractTextWebpackPlugin. It extracts all our component's  CSS into one file, but we would like to separate our CSS into multiple files. Is there a way to do this?

Thanks in advance

**Comment by kazupon** [comment]
Thank you for your filling!

You can it with `ExtractTextWebpackPlugin`.

See:
https://github.com/webpack-contrib/extract-text-webpack-plugin#options

**Comment by grofzero** [comment]
In my understanding:

loaders: {
            css: ExtractTextPlugin.extract({
              use: 'css-loader',
              fallback: 'vue-style-loader'
            })
          }

with this config I can get all the styles in all of my components to build into the same css. I would like to achieve the opposite. I would like to know if it's possible to separate them into multiple css files?
