### ISSUE TITLE
Vue-loader with Bootstrap-css framwork.

### ISSUE THREAD

**Issue by Talbourdet** [vuejs/vue-loader#743]
Hello.

Could some one help me to understand how I can use bootstrap-css when I work with Vuejs and Vue-loader?

Thanks.

**Comment by kazupon** [comment]
Thanks for filing the issue!

Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by FlorianWerndl** [comment]
@Talbourdet did you find any answer?
