### ISSUE TITLE
Cloudflare hiding the package name

### ISSUE THREAD

**Issue by gauravmak** [vuejs/vue-loader#747]
On [this page](https://vue-loader.vuejs.org/en/configurations/extract-css.html), Cloudflare takes the package name as an email address and tries to protect it.
![extracting css file gitbook](https://cloud.githubusercontent.com/assets/11887260/24353685/4edaa498-130c-11e7-81c5-de2e0fde97ca.png)

**Comment by znck** [comment]
Directly visiting the url - package name is not hidden

Visit https://vue-loader.vuejs.org then click on extract css - package name is hidden
