### ISSUE TITLE
Scoped styles don't apply to v-html injections

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vuejs/vue-loader#749]
### Version
11.0.0

### Reproduction link
[https://github.com/foundryspatial-duncan/vue-loader-issue-demo/blob/master/src/App.vue](https://github.com/foundryspatial-duncan/vue-loader-issue-demo/blob/master/src/App.vue)

### Steps to reproduce
1. In a single-file Vue component (.vue file), add some scoped styles (with the `scoped` property on the `style` tag).
2. Inject some HTML that matches your scoped style's selector with v-html

### What is expected?
The styles would affect the injected HTML

### What is actually happening?
The styles do not affect the injected HTML

---
Looks like HTML injected with v-html aren't given the "data-v-[hash]" property (like data-v-08ce5946).
I think there's a proposal somewhere to only add the data-v-[hash] to the component's root element and then _prefix_ all the styles to scope them. That would solve this issue as well.

**Comment by yyx990803** [comment]
Prefixing is simply different from what scoped CSS does. The HTML injected is raw and we are likely not going to change this. You can just give the container element a class and use nested selectors to style the raw HTML.

**Comment by Xheldon** [comment]
There still has a problem.

template:

`<span class="focus-btn" @click="focus" :class="{'focued': isFocus}" v-html="isFocusText"></span>`

script:

`
        computed: {
            isFocusText () {
                return this.isFocus ? '已关注' : '<i class="plus">+</i>关注';
            }
        }`

scss:

`<style scoped lang="scss">
.focus-btn  i.plus{ color:red;}
</style>`

Omit some unrelated code.

it's style not work till remove 'scope' in style tag.

Should I remove 'scope' in style tag or remove '\<i>' in isFocusText?

**Comment by foundryspatial-duncan** [comment]
You could use something like `v-if` to show your focus text instead. @yyx990803 said above that they probably won't address this, but if you're using scss you can "scope" your styles by nesting everything in a selector for your component's root element. So, not the end of the world 👍

**Comment by MikaelEdebro** [comment]
You can use the `/deep/` selector to get your styles to be applied:

```
<div class="description" v-if="description" v-html="description"></div>

.description {
  /deep/ p {
    margin-bottom: 10px;
  }
}
```

**Comment by lucas-medina** [comment]
`/deep/` selection helped me a lot. Thanks :)

**Comment by alancwoo** [comment]
I stumbled upon this today and oddly, nothing was working (unscoped css, global css).

I noticed that while this solution worked, the `/deep/` selector was deprecated by some time ago and throws errors in IE: https://stackoverflow.com/questions/25609678/what-do-deep-and-shadow-mean-in-a-css-selector

I then found this: https://medium.com/@brockreece/scoped-styles-with-v-html-c0f6d2dc5d8e

Which recommends something along the lines of:

```
.description >>> p {
  margin-bottom: 10px;
}
```

Which works as well.

**Comment by foundryspatial-duncan** [comment]
Since the discussion is still going on, I just wanted to draw attention to my [comment above](https://github.com/vuejs/vue-loader/issues/749#issuecomment-296249177) about using the root element's selector to scope your styles. It can produce simpler, more predictable style behaviors and doesn't muddy up the DOM with the extra scope attributes. You just have to be aware of how one component's styles might affect its child components. I use the `scoped` attribute pretty sparingly these days, in favor of a slightly more thoughtful design. I think it's worth considering if it suits your project!

**Comment by alancwoo** [comment]
Yes I totally agree - something very weird was happening where even unscoped Styling in the component and even the global Stylesheet was not working - and only the deep selector worked - in the end it turned out webpack was hung up on something and restarting it fixed everything.

I agree I would aim for a root selector instead as well and switched things over when it worked again.

**Comment by renesansz** [comment]
> You can use the `/deep/` selector to get your styles to be applied:
> 
> ```
> <div class="description" v-if="description" v-html="description"></div>
> 
> .description {
>   /deep/ p {
>     margin-bottom: 10px;
>   }
> }
> ```

wow.. `/deep/` works. learned something today :)

**Comment by RahulDey12** [comment]
> /deep/ p

not working with with scss

**Comment by carlosabcs** [comment]
> > /deep/ p
> 
> not working with with scss

In my case, with `scss`, it is working pretty fine:
```scss
    /deep/ &-icon {
      // See: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors
      font-size: 30px;
    }
```

**Comment by ZermattChris** [comment]
Not sure if I missed it, but would be great to put a mention in the Docs about this not working (might save some churn for other noobs like myself :-) )

**Comment by luquera** [comment]
> You can use the `/deep/` selector to get your styles to be applied:
> 
> ```
> <div class="description" v-if="description" v-html="description"></div>
> 
> .description {
>   /deep/ p {
>     margin-bottom: 10px;
>   }
> }
> ```

`/deep/` works bro, tks so much

**Comment by gblue1223** [comment]
**/deep/** is not working in Vue@2.6.12 use **::v-deep** instead.
`
      .right {
        ::v-deep * { ... }
      }
`

**Comment by ayoubkhan558** [comment]
```css
.content ::v-deep {
  h2 {
    color: blue;
  }
  a {
    color: blue;
  }
}
```

**Comment by chaderenyore** [comment]
> I stumbled upon this today and oddly, nothing was working (unscoped css, global css).
> 
> I noticed that while this solution worked, the `/deep/` selector was deprecated by some time ago and throws errors in IE: https://stackoverflow.com/questions/25609678/what-do-deep-and-shadow-mean-in-a-css-selector
> 
> I then found this: https://medium.com/@brockreece/scoped-styles-with-v-html-c0f6d2dc5d8e
> 
> Which recommends something along the lines of:
> 
> ```
> .description >>> p {
>   margin-bottom: 10px;
> }
> ```
> 
> Which works as well, without a deprecated selector.
> 
> _edit:_ Then again, the vue docs say `>>>` is just an alias for `/deep/`, so I'm not sure anymore https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

Any one still having this issue sould use this comment and not deep because as the user said it is deprecated. thanks a lot

**Comment by chaderenyore** [comment]
Update!!!!!!!!
As of March 2022 the /deep/ and >>> deep selectors have been deprecated.
Now you should use :deep()

`.a :deep(p) {}`
to go deeper and target the p tag

**Comment by leegee** [comment]
Would it be a good idea to add this to the documentation?
