### ISSUE TITLE
work with standalone postcss style files

### ISSUE THREAD

**Issue by c-cho** [vuejs/vue-loader#753]
I'm using postcss with [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) in my project. Everything works fine if I write my style in the .vue file. But if I move the style code into a standalone .css file and then import it into the original .vue file, postcss-nesting plugin will not work.  
What file should I configure to make it work?

**Comment by LinusBorg** [comment]
you should configure postcss-loader for `.css` files. This has nothing to do with Vue or vue-loader, so you should ask the webpack or postcss communities for details if you need help with that.
