### ISSUE TITLE
How to use 'autoprefixer' and scss with webpack 1.x & 2.x

### ISSUE THREAD

**Issue by keydone** [vuejs/vue-loader#755]
I read http://vue-loader.vuejs.org/en/features/postcss.html, but it not working, so can u help me? By the way, I used file.scss & <style lang='scss'> with vue2.1.x, when I run build, the 'autofrefixer' is no working.

**Comment by keydone** [comment]
By the way, I used scss with vue2.1.x, when I run build, the 'autofrefixer' is no working.

**Comment by yyx990803** [comment]
Make sure you specified the correct target browsers. The default gets updated quite often.
