### ISSUE TITLE
使用vue-loader后为什么还是不能解析.vue文件？

### ISSUE THREAD

**Issue by JinChunCheng** [vuejs/vue-loader#756]
`D:\code\demo>npm` run dev

> demo@1.0.0 dev D:\code\demo
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 2 errors                                 13:54:26

 error  in ./src/App.vue

Module parse failed: D:\code\demo\src\App.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div id="app">
|         <mt-header class='header' fixed :title="title">

 @ ./src/main.js 8:0-23
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/index.vue

Module parse failed: D:\code\demo\src\components\index.vue Unexpected token (1:0
)
You may need an appropriate loader to handle this file type.
| <template>
|     <div class="index">
|     <sub_nav></sub_nav>

 @ ./src/router/index.js `3:0-39`
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

webpack.base.config.js配置：
`var path = require('path')
var webpack = require("webpack");

var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var ExtractTextPlugin = require("extract-text-webpack-plugin"); //将组件中的样式提取出来

function resolve(dir) {
    return path.join(__dirname, '..', dir)
}

module.exports = {
    entry: {
        app: './src/main.js'
    },
    output: {
        path: config.build.assetsRoot,
        filename: 'build.[hash:8].js',
        publicPath: process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath
    },
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            'vue$': 'vue/dist/vue.esm.js',
            '@': resolve('src')
        }
    },
    module: {
        loaders: [{
                test: /\.vue$/,
                loader: 'vue-loader',
                exclude: /node_modules/
            }, {
                test: /\.js$/,
                loader: 'babel-loader',
                include: [resolve('src'), resolve('test')]
            }, {
                //.scss 文件想要编译，scss就需要这些东西！来编译处理
                //install css-loader style-loader sass-loader node-sass --save-dev
                test: /\.scss$/,
                loader: 'style!css!sass?sourceMap'
            }, {
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('img/[name].[hash:7].[ext]')
                }
            }, {
                //html模板编译？
                test: /\.(html|tpl)$/,
                loader: 'html-loader'
            }, {
                // 编译css并自动添加css前缀
                test: /\.css$/,
                loader: ExtractTextPlugin.extract(
                    "style-loader", "css-loader?sourceMap!cssnext-loader")
            }, {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
                }
            }]
            // .vue的配置。需要单独出来配置
    },
    plugins: [
        new webpack.LoaderOptionsPlugin({
            options: {
                vue: {
                    loaders: {
                        css: ExtractTextPlugin.extract('vue-style-loader', 'css-loader', 'sass-loader'),
                        sass: ExtractTextPlugin.extract('vue-style-loader', 'css-loader!sass-loader')
                    }
                },
                //使用es5语法
                babel: {
                    presets: ['es2015'],
                    plugins: ['transform-runtime'] //这个必须install babel-plugin-transform-runtime
                }
            }
        })
    ]
}
`
求纠正，谢谢

**Comment by qinghua5453** [comment]
请问楼主解决了吗
