### ISSUE TITLE
Hot Module Replacement does not work for changes in <script>

### ISSUE THREAD

**Issue by DmacMcgreg** [vuejs/vue-loader#758]
To reproduce: 
1. Use the default vue-cli webpack template.
2. Add a counter to the page and increment it.
3. Change styles or html (you will see that the state of the javascript does not change, which is good)
4. Add a new variable or function to the component

After adding the new javascript to the component, the hot module replacement will fail, as the application has lost its state.

**Comment by DmacMcgreg** [comment]
It should behave like in the following example with React

[!image](http://matthewlehner.net/images/react-hmr-f51607a1.gif)

**Comment by yyx990803** [comment]
HMR works differently with Vue files. State is preserved when you edit the `<template>`, but the whole component is reloaded when you edit `<script>`, because you may have edited lifecycle hooks.

**Comment by DmacMcgreg** [comment]
Why should it work any different than the above React component I posted above?
Why is the state in a different component not preserved when I edit a sibling component?

I personally don't consider this closed...
Why should Vue have to suffer from a poorer developer experience than React?

**Comment by yyx990803** [comment]
@DmacMcgreg because Vue is not React and internal implementations differ. It also isn't necessarily a poorer experience - most of the time when I edit `<script>` with hooks that have side effects, I actually **want** the component to be reloaded with fresh state, because simply re-rendering can cause the app to be stuck in a weird state and eventually requires manually refreshing the entire page.

**Comment by DmacMcgreg** [comment]
@yyx990803 Hi Evan,
Thanks for the response. 
I appreciate all the work you put into Vue and for responding to my questions. Apologies for how my tone came out in the messages. 

Two final questions for you:

1. Is there a possibility for enabling this type of React-like behaviour as some sort of toggle for those who may want to deal with the side-effects?
2. Is there a reason why we couldn't save the state of a sister sibling? At the moment, from using the standard webpack vue-cli template, if I edit a vue template, its sibling loses state as well.

**Comment by yyx990803** [comment]
Sibling losing state sounds like a potential bug, but that will need a proper reproduction.

**Comment by DmacMcgreg** [comment]
@yyx990803 I'll create a new ticket with a GIF of the issue.

Thanks!
