### ISSUE TITLE
scoped css会连续追加attribute的bug

### ISSUE THREAD

**Issue by songsiqi** [vuejs/vue-loader#76]
`style-rewriter`有bug。给style设置了scoped属性之后，当运行watch时，每修改样式并保存一次时，属性`currentId`就会增加一个，例如会出现如下这种情况：

```
p[_v-c0c51eca][_v-c0c51eca][_v-c0c51eca][_v-c0c51eca] {
  display: block;
  text-align: center;
}
```

**Comment by yyx990803** [comment]
给个重现吧，应该和你的配置有关。

**Comment by songsiqi** [comment]
和[勾股发现的bug](https://github.com/vuejs/vue-loader/issues/69)是同一个bug~
