### ISSUE TITLE
Support for JSX in Vue SFC

### ISSUE THREAD

**Issue by octref** [vuejs/vue-loader#769]
### What problem does this feature solve?
I gathered from these blog-posts/doc/starters that JSX support is only for JS file for now.

- https://vuejs.org/v2/guide/render-function#JSX
- https://medium.com/js-dojo/whats-new-in-vue-js-2-0-beyond-templates-with-jsx-4b8cda05f95f
- https://github.com/egoist/vuepack

People are opening issues for having editor support for JSX in Vue SFC: https://github.com/octref/vetur/issues/112

but I'd like to make sure this is something Vue would officially support before adding any support.
I currently can't find any official examples of JSX in Vue SFC.

### What does the proposed API look like?
N/A

**Comment by LinusBorg** [comment]
Any scripts in SFCs are run through babel-loader by default, so if you have set up babel to ttanspile JSX, it will be transpiled in SFCs as well.

**Comment by octref** [comment]
Thanks, forgot to close the issue.
I do hope there is at least an official example using JSX in Vue component though.
Also hope `eslint-plugin-vue` could be updated to handle JSX correctly: https://github.com/vuejs/eslint-plugin-vue/issues/9

**Comment by LinusBorg** [comment]
I don't know what you expect from an official example, it will look *exactly* like a normal `.js` file, except that the code is wrapped in the SFC elements (`<script>`) There is literally *zero* difference.

**Comment by octref** [comment]
> There is literally zero difference.

Oh OK. Think I had a misunderstanding of the JSX usage. Sorry.
