### ISSUE TITLE
vue单文件里写函数式组件，添加了functional: true选项后 style标签的scoped就无效了

### ISSUE THREAD

**Issue by hjc22** [vuejs/vue-loader#775]
vue单文件里写函数式组件，添加了functional: true选项后 style标签的scoped就无效了

**Comment by Jinjiang** [comment]
参考：https://vue-loader.vuejs.org/zh-cn/features/scoped-css.html

**Comment by Jinjiang** [comment]
你需要确认为函数式组件渲染出来的节点加上 `data-v-${scopeId}` 这样的 attribute 就可以了

**Comment by Jinjiang** [comment]
Translation: This issue is asking about using render function with scoped style.

I think we should add `data-v-${scopeId}` in render function manually.
Thanks.

**Comment by yyx990803** [comment]
Supported in >13.3.0
