### ISSUE TITLE
lang="pug"

### ISSUE THREAD

**Issue by peteringram0** [vuejs/vue-loader#777]
### Version
11.0.0

---
Is there a way to pass in an option to stop pug from removing all spaces within the template though vue-loader? Thanks

**Comment by LinusBorg** [comment]
I assume you mean the [`pretty` option](https://pugjs.org/api/reference.html#options) from pug?

This functionality is deprecated, so it will be removed in the next major release of pug, and usage is not recommended, the documentation states.

However, pug-loader supports it :https://github.com/pugjs/pug-loader

So you can simply add those options explicitly in the loader config fpr pug in vue-loaderas per the documentation:

http://vue-loader.vuejs.org/en/configurations/advanced.html

If you have problems making that work, please ask on forum.vuejs.org, StackOverflow, Gitter etc.

Github is reserved for bugs & Feature requests, thanks.
