### ISSUE TITLE
Improvement - Allow tests within single component

### ISSUE THREAD

**Issue by peteringram0** [vuejs/vue-loader#781]
Suggestion to add something like the following.

````javascript
<script>
// Scripts Here
</script>
<test>
// Unit tests here
</test>
````

**Comment by LinusBorg** [comment]
We already allow [custom blocks](http://vue-loader.vuejs.org/en/configurations/custom-blocks.html), with them that should totally doable, but may be depending on the extend and nature of webpack support of the test runner/lib you use.

**Comment by uptownhr** [comment]
This would be an awesome feature! Would be awesome to see an example of this!

**Comment by egoist** [comment]
It's possible with custom blocks, but why would you put tests within your component? I would try to make component file look as slim as possible.
