### ISSUE TITLE
ES6 props parsing error in *.vue file

### ISSUE THREAD

**Issue by caikan** [vuejs/vue-loader#784]
### Version
11.0.0

### Reproduction link
[https://github.com/caikan/vue-bug/tree/9d39d3d5c552863898a22e79e9cf9de340211e44](https://github.com/caikan/vue-bug/tree/9d39d3d5c552863898a22e79e9cf9de340211e44)

### Steps to reproduce
In *.vue files:
template:
```
<foo :bar="[...base || [], 3, 4]"></foo>
```
data:
```
base: [1, 2]
```

### What is expected?
bar: [1, 2, 3, 4]

### What is actually happening?
bar: [1, 2]

**Comment by LinusBorg** [comment]
Thanks, We'll look into it.

**Comment by yyx990803** [comment]
This is a bug in buble (which is used by `vue-template-es2015-compiler`) - tracking here: https://gitlab.com/Rich-Harris/buble/issues/194
