### ISSUE TITLE
Async single-file component error: missing template

### ISSUE THREAD

**Issue by blakcap** [vuejs/vue-loader#785]
### Version
11.0.0

### Reproduction link
[https://gitlab.com/blakcap/vue-testbed/tree/async-sfc-bug](https://gitlab.com/blakcap/vue-testbed/tree/async-sfc-bug)

### Steps to reproduce
Run `yarn start` or `npm run start` (after installing the deps) to run the webpack-dev-server in HMR mode with code splitting enabled. When you open the console, you'll see an error: 
```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <Test>)
```
See the `Test` component here: https://gitlab.com/blakcap/vue-testbed/blob/async-sfc-bug/src/Test.vue

See the dynamic load here: https://gitlab.com/blakcap/vue-testbed/blob/async-sfc-bug/src/App.vue#L30

### What is expected?
The component is fetched and rendered successfully.

### What is actually happening?
Only the JS is fetched, while the template is not.

### Notes
- I've updated the [webpack config](https://gitlab.com/blakcap/vue-testbed/blob/async-sfc-bug/webpack.config.js) alot...maybe that has something to do with it?
- This webpack config & async component scheme works for me with React, just not for the single-file components.

**Comment by blakcap** [comment]
For reference, a possible solution to this problem is [`vue-dynamic`](https://github.com/JounQin/vue-dynamic). However I feel that there should be an official and much cleaner solution.

**Comment by blakcap** [comment]
Oh, another note - even without the `Promise.resolve` wrapper, it doesn't work (gives same error).

**Comment by LinusBorg** [comment]
When I remove the Promise.resolve (as you should, that's not intended to be working, and not let alone necessary), it works fine for me:

<img width="614" alt="bildschirmfoto 2017-04-22 um 19 21 53" src="https://cloud.githubusercontent.com/assets/1444526/25306617/f694db34-2790-11e7-928d-4bd52f319053.png">

**Comment by blakcap** [comment]
@LinusBorg Ahah! The `node_modules` had some extra things in it from experimenting on the master branch, and it was being automatically pulled in somehow. A clean `yarn install` fixed it all. Apologies & thank you so much!
