### ISSUE TITLE
Support hot reload for manually mounted components

### ISSUE THREAD

**Issue by sherzinger** [vuejs/vue-loader#786]
### What problem does this feature solve?
I believe when using Vue as part of a library the code below is a quite common occurrence.
Essentially putting a component somewhere in an existing web page, e.g. a chart.

```
import MyComponent from '../somewhere/MyComponent.vue'

const Component = Vue.extend(MyComponent)
const vm = new Component()
vm.$mount(selector)
```

This breaks hot reload for MyComponent because it is manually mounted, which is also mentioned in the browser console.
I believe it would greatly improve the developer experience to add this feature.

Independent of whether or not this request will be accepted I would very much appreciate if someone could suggest a workaround.

### What does the proposed API look like?
No change in API.

**Comment by yyx990803** [comment]
Closing outdated issues - if the problem still persists in the latest version, please open a new issue using the [issue helper](new-issue.vuejs.org/?repo=vuejs/vue-loader) with a reproduction. Thanks.
---
In practice we don't really encourage manually mounted instances except for the root. And there are technical reasons why root instances cannot be hot-reloaded.
