### ISSUE TITLE
vue-loader 使用了postcss,但是在并没有 在result的时候抛出 postcss返回的warning导致调试麻烦

### ISSUE THREAD

**Issue by xiachaoxulu** [vuejs/vue-loader#788]
路径： lib/style-compiler/index.js
return postcss(plugins)
      .process(css, options)
      .then(function (result) {
        var map = result.map && result.map.toJSON()
        **```
result.warnings().forEach(function (warn) {
          console.warn(warn.toString());
        });
```**
        cb(null, result.css, map)
        return null // silence bluebird warning
      })

是不是加上这几行代码

**Comment by yyx990803** [comment]
Use https://github.com/postcss/postcss-reporter

**Comment by xiachaoxulu** [comment]
谢谢，you da da
