### ISSUE TITLE
Support for Relay Modern

### ISSUE THREAD

**Issue by dimroc** [vuejs/vue-loader#789]
### What problem does this feature solve?
Making data requests as composable as the UI, and migrating from traditional REST endpoints to GraphQL.
https://facebook.github.io/relay/docs/fragment-container.html

Relay is often touted as the tie breaker between React and Vue, and it's a valid one. As it stands now, a component.vue file can hold the template, script, and style. Let's add the required data with Relay:

![Vue-Loader Vue Example](https://camo.githubusercontent.com/14e5f4477f49cf0fc0d8f228facb17772a0b1025/687474703a2f2f626c6f672e6576616e796f752e6d652f696d616765732f7675652d636f6d706f6e656e742e706e67)

Having a fourth section with graphql would be amazing.

## Vue Component

```
<!-- my-component.vue -->
<template>
  <div>This will be pre-compiled</div>
</template>
<script src="./my-component.js"></script>
<style src="./my-component.css"></style>
graphql`
  # This fragment only applies to objects of type 'Todo'.
  fragment TodoItem_item on Todo {
    text
    isComplete
  }
`
```

React example:

```
module.exports = createFragmentContainer(
  TodoItem,
  graphql`
    fragment TodoItem_item on Todo {
      text
      isComplete
    }
  `,
);
```

**Comment by yyx990803** [comment]
This should already be possible via [Custom Blocks](http://vue-loader.vuejs.org/en/configurations/custom-blocks.html) - it's unlikely for us to have this built-in because that makes `vue-loader` tightly-coupled with a specific backend solution.

**Comment by dimroc** [comment]
Got it. So a `vue-relay` that grabs the graphql for the components and their children to build out the data needs of every component, plugged in through custom blocks is the way to go.

**Comment by dimroc** [comment]
I see this conversation has happened before:
https://github.com/vuejs/vuex/issues/18

Noted.
