### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by MDSLKTR** [vuejs/vue-loader#795]
### Version
12.0.2

### Reproduction link
[https://gist.github.com/MDSLKTR/617da6ba3ef40f88b655a2df5a160c36](https://gist.github.com/MDSLKTR/617da6ba3ef40f88b655a2df5a160c36)

### Steps to reproduce
1. Use vue-loader 12.0.2 with webpack 2.4.1
2. Bundle files
3. See warnings and errors in console

### What is expected?
No Warning and Error

### What is actually happening?
WARNING in ./~/vue-loader/lib/utils/try-require.js
12:11-27 Critical dependency: the request of a dependency is an expression

WARNING in ./~/vue-loader/lib/utils/try-require.js
15:13-25 Critical dependency: the request of a dependency is an expression

ERROR in ./~/vue-loader/lib/utils/normalize.js
Module not found: Error: Can't resolve 'fs' in 'C:\Projects\grill-microsite-client\node_modules\vue-loader\lib\utils'

---
i know the 'fs' warning can be fixed by specifiying node: {fs: 'empty'} but is that the correct fix. No idea for the other warning though.

**Comment by MDSLKTR** [comment]
Sorry the issue wasn't vue-loader related. Therefore close.

**Comment by kerstvo** [comment]
How did you fixed it?

**Comment by MDSLKTR** [comment]
For some reason a node.js dev dependency was included in the dependencies array in my package.json. Therefore the bundle wasn't valid in the browser.

**Comment by kerstvo** [comment]
Thanks!
-- 
Kirill Maramygin
website: maramygin.ru
e-mail: kirill.maramygin@gmail.ru

**Comment by Berkmann18** [comment]
In my case, I also seemed to have a Node dependency in `dependencies` which I removed but I still get the same warnings.
```
 WARNING  Compiled with 4 warnings                                                                                                                                                    16:15:27

 warning  in ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/natural/lib/natural/classifiers/classifier.js

Module not found: Error: Can't resolve 'webworker-threads' in '/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/neocms/node_modules/natural/lib/natural/classifiers'

 warning  in ./node_modules/natural/lib/natural/wordnet/wordnet.js

Module not found: Error: Can't resolve 'wordnet-db' in '/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/neocms/node_modules/natural/lib/natural/wordnet'
```
