### ISSUE TITLE
Source map doesn't seem to work properly

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-loader#8]

**Comment by sjoerdvisscher** [comment]
As far as I can tell this is an issue with the other loaders. Loaders should take into account source maps for their input document, but afaict no loader except the css-loader does this.

**Comment by yyx990803** [comment]
Interestingly, it seems to work if the `<script>` is using a pre-processor, e.g. `coffee`, but breaks when using a plain `<script>`. I'm still trying to figure out why.

**Comment by yyx990803** [comment]
Looks like all the parts are properly source-mapped, but the `*.vue` file itself is not. For example if we throw an error in the `<script>` tag, we get the correct line number, but the source is simply `null` in Chrome's debugger.

**Comment by yyx990803** [comment]
Turns out we don't need to generate the source map ourselves. Simply not returning a map in `selector.js` fixes the issue.

**Comment by sjoerdvisscher** [comment]
That doesn't make any sense, how can webpack know where the lines are coming from?
