### ISSUE TITLE
`Loader`使用简写可能会有潜在的问题

### ISSUE THREAD

**Issue by jzlxiaohei** [vuejs/vue-loader#80]
[loader.js的代码](https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L15-L17)中，`css-loader`,`babel-loader`都使用的简写

我遇到了这样的报错信息`/babel/index.js?optional[]=runtime&loose=all&nonStandard=false didn't return a function`。
把`babel`改成`babel-loader`就ok了。
我是使用的`vue-loader` 6.0.5的版本。下面两个链接可能会有帮助

[http://stackoverflow.com/questions/29883534/webpack-node-modules-css-index-js-didnt-return-a-function](http://stackoverflow.com/questions/29883534/webpack-node-modules-css-index-js-didnt-return-a-function)

[https://github.com/goatslacker/alt/issues/382](https://github.com/goatslacker/alt/issues/382)

另外能否把6.x的版本也更新掉，7.x 对应的`babel 6`目前个人认为没法用在生产上

**Comment by yyx990803** [comment]
发布了 6.1.0，顺道把几个 7.x 的修正也包括进去了。

**Comment by jzlxiaohei** [comment]
赞
