### ISSUE TITLE
Disable postcss config file when using inline config

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-loader#800]
### What problem does this feature solve?
I manually load postcss config from its config file and set `postcss` in vue loader options, but `vue-loader` will also load it and merge inline config with config file so it leads to duplicated plugins.

btw, `postcss-loader` does not use config file when inline config is set.

### What does the proposed API look like?
Maybe this should be the default behavior, or we can introduce an option for this.

**Comment by barraponto** [comment]
Agreed. It would be very useful for `neutrino-middleware-vue`.

**Comment by barraponto** [comment]
btw, can we close in favor of #654 ?
