### ISSUE TITLE
Hot Module Reloading Broken when using CSS modules

### ISSUE THREAD

**Issue by trainiac** [vuejs/vue-loader#801]
### Version
12.0.2

### Reproduction link
[https://github.com/trainiac/hmr-vue-loader-12-bug](https://github.com/trainiac/hmr-vue-loader-12-bug)

### Steps to reproduce
1. Run the server
$ git clone git@github.com:trainiac/hmr-vue-loader-12-bug.git
$ cd hmr-vue-loader-12-bug
$ npm install
$ node ./server.js

2. Edit anything in the script section of App.vue and save

3. Notice the error in the console. 

### What is expected?
Hot update

### What is actually happening?
An error is being thrown

Uncaught TypeError: Cannot read property 'hot' of undefined

---
I've tested vue-loader 11.0.0 and this bug does not exist.  I also don't get this bug without using CSS modules.

**Comment by yyx990803** [comment]
I can no longer reproduce this so I assume it's been fixed with latest deps - please reopen if otherwise.
