### ISSUE TITLE
Again "pug include" question

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue-loader#802]
i want continue issue #472, please watch my situation)
i use pug mixins for inline sugar elements, example:
```
mixin Up
  mark &#9650;
mixin Down
  mark &#9660;
mixin Left
  mark &#9664;
mixin Right
  mark &#9654;
mixin Alt
  mark.w &#8997; Alt

div.helper #[+Up], #[+Down] + #[+Alt] - something hotkey
```

Do I understand correctly #472 if i want reuse this mixin into others components - i should create for it new component with components with render () functions and import this how mixin.
I really should complicate and scripting my system for the sake of 3-5 mini inline-templates? Not expensive?
At least my variant more readable...

**Comment by LinusBorg** [comment]
Closing because this issue does not conform to the required issue format for bugs or feature requests.

**Comment by patriciussanctus** [comment]
#1122 solved!
