### ISSUE TITLE
Inject <style> properties when rendering.

### ISSUE THREAD

**Issue by hernandev** [vuejs/vue-loader#810]
### What problem does this feature solve?
When using styles inside vuejs components, other porperties, like `media="print|screen"` are not automatically injected.

When you define inside a vue component, something like:

```html
<style media="screen">
 // some style here
</style>
```
The resulting injected style, will not contain any defined properties.

```html
<style>
<!-- injected style does not contains the properties defined on the component. -->
</style>
```

### What does the proposed API look like?
No API change. just different injected `<style>` tags.

### P.S
Migrated from vuejs/vue#5662

**Comment by yyx990803** [comment]
The problem here is that the styles may get extracted into a common CSS file in some build configurations - I'd suggest using explicit `@media` queries instead, which works consistently in both cases.
