### ISSUE TITLE
无法在.vue文件中使用import

### ISSUE THREAD

**Issue by Yee1023** [vuejs/vue-loader#813]
我没有使用vue-cli脚手架，我在webpack中这样配置的'moudle':
module: {
            noParse: ['jquery'],
            loaders: [
                {
                    test: /\.(jpe?g|png|gif|svg)$/i,
                    loader: 'url-loader?limit=1&minetype=image/jpg&name=images/[name]_[hash].[ext]'
                },
                {
                    test: /\.(woff|eot|ttf)$/i,
                    loader: 'url?limit=1&name=fonts/[name].[ext]'
                },
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader',
                    query: {
                        presets: ['es2015']
                    }
                },
                {
                    test: /\.vue$/,
                    loader: 'vue-loader'
                }
            ]
        }
不知道是什么原因，我在.vue文件中无法使用import和export，我在vue文件中的js如下：
<script>
import Header from './layout/header.vue'

export default {
  components: {
    Header
  }
}
</script>

**Comment by xyzhanjiang** [comment]
配置一下 .babelrc 文件

**Comment by yyx990803** [comment]
^ 用 `babelrc` 不要用 query
