### ISSUE TITLE
give an option making 'dist' folder has the same folder structure of 'src'

### ISSUE THREAD

**Issue by marszoolong** [vuejs/vue-loader#815]
Hi,

as you see in title, is it possible to give us an option that making 'dist' folder has the same structure with 'src', example:

from: 'src/views/moduleA/pageA/main.vue',
to: 'dist/views/moduleA/pageA/main.js'

thank you！

**Comment by LinusBorg** [comment]
This can't be done with vue-loader, this would have to be done in your webpack config / build scripts.
