### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by rcscott** [vuejs/vue-loader#817]
### What problem does this feature solve?
Please add release notes for the recent version upgrades to this package. Release notes haven't been included since 12.0.2. Without them, it's difficult to figure out what changed.

Also because of the missing release notes, the Version dropdown on https://new-issue.vuejs.org/?repo=vuejs/vue-loader only goes up to 12.0.2.

### What does the proposed API look like?
N/A

**Comment by yyx990803** [comment]
Updated!

**Comment by rcscott** [comment]
Thanks @yyx990803!
