### ISSUE TITLE
can support import rule for .vue like js?

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-loader#82]
```javascript
require('./hello')
```

1. if there is `hello.js` require it
2. if hello is a path require `./hello/index.js`

could u support for `.vue`?
1. if there is `hello.js` require it
2. if hello is a path require `./hello/index.js`
3. if there is `hello.vue` require it
4. if hello is a path require `./hello/index.vue`

**Comment by yyx990803** [comment]
This is possible, but not within `vue-loader`. You need to write a custom webpack ResolverPlugin: https://github.com/webpack/docs/wiki/list-of-plugins#resolverplugin

**Comment by yyx990803** [comment]
Actually just realized there's an easy way to do this:

``` js
// webpack.config.js
module.exports = {
  // ...
  resolve: {
    extensions: ['', '.js', '.vue']
  }
}
```

**Comment by amanpatel** [comment]
:+1:  Thanks for posting the solution. I was just able to use this.

**Comment by yozman** [comment]
@yyx990803 excellent :+1:
