### ISSUE TITLE
webpack打包vue模版文件中的JS代码没经过babel编译

### ISSUE THREAD

**Issue by wenston** [vuejs/vue-loader#825]
#### 如题所述问题

* vue版本2.3.3
* vue-loader版本12.1.0
* babel-loader版本7.0.0

编译时，发现vue文件中`<script>`标签包裹的部分没有被babel编译。  
其他使用者也发现了这个问题，请参考：

[https://segmentfault.com/q/1010000008121807](https://segmentfault.com/q/1010000008121807)

**Comment by yyx990803** [comment]
信息太少了，官方的 webpack 模板不能重现，如果是你自己的配置问题，请补上 repo 重现。
