### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by xlcs0110** [vuejs/vue-loader#827]
引用vue-awesome会报`Uncaught SyntaxError: Unexpected token import`错误，在非node_modules目录下的文件都不会报这个错误，我想因为vue-awesome资源是使用es6写的，我把babel的exclude改成包含vue-awesome但不包含其他npm包也还是不行，以下是我的配置

webpack配置：
```
{
            test: /\.vue$/,
            loader: 'vue',
            options: vueLoaderConfig
},
{
            test: /\.js$/,
            loader: 'babel',
            exclude: utils.getWebpackBabelLoaderExclude()
 }
```
.babelrc文件
```
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

另附vue-awesome的使用方式和报错的地方
使用方式：
`import 'vue-awesome/icons/flag.js'`

报错出处 flag.js
`import Icon from '../components/Icon.vue'`

我不觉得是vue-awesome的问题，觉得是babel没有成功处理，谢谢。

**Comment by yyx990803** [comment]
你的 `utils.getWebpackBabelLoaderExclude()` 很显然把 node_modules 里的模块 exclude 了。这跟 vue-loader 没有关系...
