### ISSUE TITLE
.vue文件中被script标签包裹的部分不能被babel-loader编译成es2015

### ISSUE THREAD

**Issue by wenston** [vuejs/vue-loader#828]
#### .vue文件中被`script`标签包裹的部分不能被`babel-loader`编译成es2015

* 不知道是不是webpack.config.js中的配置有问题?
* 了解不深,还请多多指教 :) 

repo:[https://github.com/wenston/vue-loader-issue](https://github.com/wenston/vue-loader-issue)

感谢~

**Comment by yyx990803** [comment]
用 `.babelrc`，`babel-loader` 的 options 只作用于 babel-loader，对 vue-loader 无效。

**Comment by wenston** [comment]
:+1:

**Comment by dai-siki** [comment]
找了一天原因，终于
