### ISSUE TITLE
Component constructor cache _Ctor prevents component extending with decorator pattern

### ISSUE THREAD

**Issue by fobdy** [vuejs/vue-loader#83]
```javascript
// comp.vue
export default {
   mixins: []
}

// app.vue
import Comp from 'comp.vue'
let ExtendedComp = Object.assign({}, Comp, { mixins: [/* some mixins */]})

// Now ExtendedComp is out of sync with the ExtendedComp._Ctor
export default {
  components: { comp: ExtendedComp }
}

// app.js
import App from 'app.vue';
new Vue({
  el: 'body',
  components: {
    app: App,
  }
});
```

So Vue sees only original mixins and not later being added

**Comment by yyx990803** [comment]
This should be fixed with the latest version of `vue-hot-reload-api` - try update that and see if the problem persists.

**Comment by fobdy** [comment]
Ok. Thank you. It helps me. i've switched to the latest `vue-loader` and other stuff.

I switched to `7.0.3` early with hope that css extract should work. But it didn't.

**Comment by karol-f** [comment]
I have the same problem - vue-loader@11.1.2. Is it regression?

**Comment by LinusBorg** [comment]
It might be a good idea to actually open a new issue than commenting on two year old closed tickets. Notifications for these get drowned quickly in the GH timeline.

As always: provide a reproduction, please.

**Comment by karol-f** [comment]
@LinusBorg Thanks for explanation. My use case is quite niche so I woun't bother you guys with this issue. I can probably hack it. Regards.

**Comment by rohmanhm** [comment]
Hi, I got same problem. It's come back

**Comment by LinusBorg** [comment]
Please read my previous comment.
