### ISSUE TITLE
Merge $style Object when Mixin with .vue file

### ISSUE THREAD

**Issue by Elric-pp** [vuejs/vue-loader#835]
### Version
12.2.1

### Reproduction link
[https://gist.github.com/Elric-pp/6326393b43a7c5a8c4b82e4f9b05b134](https://gist.github.com/Elric-pp/6326393b43a7c5a8c4b82e4f9b05b134)

### Steps to reproduce
mixin with the .vue component which already have $style object

### What is expected?
merge the $style object

### What is actually happening?
throw an error with `Cannot redefine property: $style`

---
I don't know if it is a bug or a feature, but i think is quite handy if the $style can be merge.

Code Locate：function injectStyle

**Comment by webnoob** [comment]
@Elric-pp See my solution to the linked problem (https://github.com/jpex-js/vue-inject/issues/14). You can define your own rules for how the merging takes place for mixins and components (by default it overwrites them)

**Comment by yyx990803** [comment]
Closing outdated issues - if the problem still persists in the latest version, please open a new issue using the [issue helper](new-issue.vuejs.org/?repo=vuejs/vue-loader) with a reproduction. Thanks.
