### ISSUE TITLE
Don't load SCSS component

### ISSUE THREAD

**Issue by Signorini** [vuejs/vue-loader#836]
### Version
12.2.1

### Reproduction link
[https://jsfiddle.net/signorini/50wL7mdz/37447/](https://jsfiddle.net/signorini/50wL7mdz/37447/)

### Steps to reproduce
* I create one component with only SCSS
* Call this component in father component
* My SCSS don't import without your instance

### What is expected?
Import SCSS without need to instance the component.

### What is actually happening?
This actually happens when upgrade 12.xx vue-loader, its because by Upgrading "vue-style-loader to 3.0 introduces a small breaking change, lazy loading inject".

---
It possible to exist a option to cancel lazy-loading? I like to use components with SCSS, like buttons, grids and etc, and normally this scss use by other component, i like this organization.

**Comment by LinusBorg** [comment]
If you want to re-use the CSS in other places than your component, then it does not belong into your component. That's an anti-pattern.
