### ISSUE TITLE
Introduce `stylelint` in the document?

### ISSUE THREAD

**Issue by gucong3000** [vuejs/vue-loader#839]
`stylelint`目前已经支持Vue 组件了，我是否可以推送一个PR，来介绍一下配置？
`stylelint` already support vue component. Can I push a PR to introduce the configuration?

我会写这里：
I'll write it here:
https://github.com/vuejs/vue-loader/blob/master/docs/zh-cn/workflow/linting.md

**Comment by gucong3000** [comment]
stylelint/stylelint#2596

**Comment by gucong3000** [comment]
```bash
npm i --save-dev stylelint postcss-html
stylelint --custom-syntax postcss-html src/**/*.vue
```

**Comment by yyx990803** [comment]
PR is welcome if you are still interested.

**Comment by rdhelms** [comment]
Sorry - what happened to this? Is there documentation somewhere now regarding how to configure stylelint for a Vue app?

I saw this as well, but the most recent comments suggest that there are still issues:
https://github.com/vuejs/vue-loader/issues/303
