### ISSUE TITLE
how to import 3rd vue module that after vue-loader building

### ISSUE THREAD

**Issue by GodFaker** [vuejs/vue-loader#843]
hello everyone:
i have created a system admin vue module that work fine in webjar。now I want to use the system admin module in a different project。so is npm public can achieve the purpose？i mean how to import a module that after npm build？how to import other module vue page(the js is app.0b44313948cb6c9ebc3f.js) in my module?

**Comment by LinusBorg** [comment]
Please ask for support on forum.vuejs.org
