### ISSUE TITLE
Upgrade vue-loader to webpack 3

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vue-loader#850]
### What problem does this feature solve?
With the recent [launch of webpack 3](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b), some exciting features was added, including Scope Hoisting. As stated by the team:

> "Migrating from webpack 2 to 3, should involve no effort beyond running the upgrade commands in your terminal. We marked this as a Major change because of internal breaking changes that could affect some plugins."

So, I believe the migration will be easy and will give only benefits:

`npm install webpack@3.0.0 --save-dev`

**Comment by LinusBorg** [comment]
@erickpetru I'm not sure what you are asking - here should *we* update webpack? In this repository? 

Or are you simply asking if vue-loader works with webpack 3?

The latter is: yes, but we are currently working on implementing true esmodule exports to reap the benefits of the ModuleConcatenationPlugin - which currently bails on `.vue` files as @serkanyersen correctly observed.

**Comment by ErickPetru** [comment]
@LinusBorg I'm sorry for the confusion, I'll try to be clearer:

1. Update the webpack version in this project `package.json`.
2. Offer support out of the box to the `ModuleConcatenationPlugin`.

By the way, I'm happy to know you're already working on it.

**Comment by fnlctrl** [comment]
Working on a PR here: 
https://github.com/vuejs/vue-loader/pull/860

**Comment by bentolor** [comment]
Issue #860 is already merged & released with v13. 

So is something still missing to achive out-of-the box support of `ModuleConcatenationPlugin` ?

**Comment by LinusBorg** [comment]
No. This issue is still open as it's about an update of this repo to webpack3, which hasn't happened yet.
