### ISSUE TITLE
Minifying CSS with `extractCSS: true`

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue-loader#855]
### What problem does this feature solve?
When `extractCSS: true` is used, `use: 'css-loader',` is no longer exposed to add the `minimize` parameter. Open an option to enable minimizing CSS.

### What does the proposed API look like?
`minimizeCSS` option in vue-loader

**Comment by LinusBorg** [comment]
`extractCSS` *does* minify CSS when builing for production (`NODE_ENV=production`)

If that feature doesn't work for you as expected, a bug report with a minimal runnable reproduction of the problem (in form of a repository) would be the way to go.

**Comment by hirokiosame** [comment]
Thanks @LinusBorg  it worked. I'm having trouble finding where this is documented, but I found the logic in the code. Where did you learn about this?

**Comment by LinusBorg** [comment]
from the documentation:

https://vue-loader.vuejs.org/en/options.html
