### ISSUE TITLE
Dependency mocking with inject-loader as described in the docs does not work with Webpack 2

### ISSUE THREAD

**Issue by jp887** [vuejs/vue-loader#858]
### Version
12.2.1

### Reproduction link
[https://github.com/jp887/vue-loader-mocking-issue](https://github.com/jp887/vue-loader-mocking-issue)

### Steps to reproduce
1) Use vue-cli to initialise a new vue   webpack project using vue-loader: vue init webpack

2) npm install

3) Implement the test described here in the vue-loader docs: https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html

4) npm test

### What is expected?
The component dependencies are injected with the test.

### What is actually happening?
Object is not a constructor (evaluating 'ExampleInjector({
              // mock it
              '../service': {
                msg: 'Hello from a mocked service!'
              }
            })')

**Comment by LinusBorg** [comment]
Inject loader does not work when we don't convert es6 modules to commonjs. 

Which is why we do this for unit tests in the template (see the `.babelrc` file in your project and the `npm run unit` command). The tests also run fine in CI and I can't reproduce this

**Comment by jp887** [comment]
Thanks for taking a look @LinusBorg. Did you clone my repo to reproduce? I have confirmed with others that they can reproduce from that repo. It seems other people have hit the same problem and found workarounds but not without issue. https://github.com/vuejs/vue-loader/issues/644

**Comment by LinusBorg** [comment]
So I took a look and found a couple of problems, none of which were related to a bug in vue-loader:
```javascript
// 1. Vue was not imported
// 2. also, this would import the runtime-only build, 
//  which would result in a test failur as the template can't be compiled
// So we need to fix the webpack.test.conf.js as well (see further below)
import Vue from 'vue'

// you had `vue-loader?inject-loader` which is incorrect, the option is named `inject`
const ExampleInjector = require('!!vue-loader?inject!../../../src/components/example.vue')

describe('example component', () => {

  it('should render', () => {

    const ExampleWithMocks = new ExampleInjector({
      // mock it
      '../service': {
        msg: 'Hello from a mocked service!'
      }
    })

    const vm = new Vue({
      template: '<div><test></test></div>',
      components: {
        'test': ExampleWithMocks
      }
    }).$mount()

    // 2. here you had a matcher that is not chai: toBe(...)
    expect(vm.$el.querySelector('.msg').textContent).to.equal('Hello from a mocked service!')
  })
});

// webpack.test.conf.js
var webpackConfig = merge(baseConfig, {
 // ... the existing config is here
}
// we need to switch the build to the one that has the runtime.
webpackConfig.resolve.alias['vue$'] = 'vue/dist/vue.common.js',
```

**Comment by jp887** [comment]
@LinusBorg thanks for this. These changes did indeed fix the issue. I think the docs may need a couple of tweaks though. The example [here](https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html) uses:

`const ExampleInjector = require('!!vue?inject!./example.vue')`

Which doesn't work for me. I have to use !!vue-loader otherwise I get an error.

Once I fixed this the other issues became obvious and easy to fix. The chai assertion was a copy and paste error from the docs which use Jasmine. As the default in the templates is Mocha and Chai maybe it would be clearer if the docs use chai too.

Thanks again for looking into this.

**Comment by LinusBorg** [comment]
> Which doesn't work for me. I have to use !!vue-loader otherwise I get an error.

 This is indeed a problem because of Webpack 2, good catch.

> As the default in the templates is Mocha and Chai maybe it would be clearer if the docs use chai too.

Even though this is the vue-loader docs, that may make sense as most people willprobably use that template.

Will add those changes to the docs.

**Comment by williamdias** [comment]
@LinusBorg 
Do you have an example of .babelrc file to convert es6 to commonjs?
I'm using webpack and karma to run my tests but can't make inject loader work.
Thanks!
