### ISSUE TITLE
文档翻译贡献问题

### ISSUE THREAD

**Issue by willin** [vuejs/vue-loader#862]
正常情况下,项目文档会是英文先更新(应该).

假如说我fork了 vuejs.org 英文文档项目进行翻译, 其中更新了之后, 我怎么能够比较变化,并且知道某篇已经翻译的文档中又新增了需要翻译的段落呢?

我今天在github上看到了一个项目,一点开对比,就有类似merge request一样的列表,一项项打钩表示没有问题,保持最新. 但是忘记收藏了,现在又找不到了.  

类似的服务或者工具叫什么名字?

后来找到一个类似的项目:  https://github.com/translation-gang/ru.vue-router

This branch is 26 commits ahead, 50 commits behind vuejs:dev.

点击 `compare` https://github.com/vuejs/vue-router/compare/dev...translation-gang:ru-translation

**Comment by Jinjiang** [comment]
compare 早期中文翻译也是这样类似的方式做的，由于操作略显反锁，所以对于翻译贡献者来说形成了客观的成本，所以现在的流程简化了很多。
对这方面有进一步探讨兴趣的话可以来中文站点的 repo
刚好前几天还聊到翻译流程问题 https://github.com/vuejs/cn.vuejs.org/issues/327 可以做个参考

**Comment by Jinjiang** [comment]
Well guys, above is a discussion about how to sync the doc translations strictly version-by-version.

More discussion is welcome in repo: cn.vuejs.org
Thanks.

**Comment by willin** [comment]
thx
