### ISSUE TITLE
Doesn't support require.ensure with the dynamic component anymore?

### ISSUE THREAD

**Issue by fanyuzzz** [vuejs/vue-loader#865]
### Version
13.0.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
I am so sorry, i don't know how to use jsfiddle, but the code it works in the vue-loader@12.2.1, and it can be loaded as a chuck file. But it report me a error in chrome console in the vue-loader@13.0.0.
```javascript
const MySale = resolve => require.ensure([], () => resolve(require('../controllers/mySale.vue')), 'my.sale')
const MyCard = resolve => require.ensure([], () => resolve(require('../controllers/myCard.vue')), 'my.card')

export default {
    data() {
        return {
            currentView: (() => {
                if(true) {
                    return MyCard
                } else {
                    return MySale
                }
            })()
        }
    }
}
```

### What is expected?
if it's a bug, please fix it, thx

### What is actually happening?
it doesn't support with the dynamic component anymore

**Comment by LinusBorg** [comment]
As explained in the [release notes](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0), you now have to get the `.default` prop on the result when using  `require()`.
```javascript
require('../controllers/mySale.vue').default
```
