### ISSUE TITLE
Make possible to utilize common webpack loaders config for src imports

### ISSUE THREAD

**Issue by evenfrost** [vuejs/vue-loader#869]
### What problem does this feature solve?
Right now we have to specify explicitly which loaders vue-loader must use for imports either via providing `options` config or via `lang` attribute.

It would be handy though if vue-loader could guess this from common webpack config, e.g. if I have `<style src="./style.styl"></style>` in my Vue component and corresponding `/\.styl$/` rule in `module.rules` webpack config section, vue-loader will use loaders from this section without any additional tweaking.

### What does the proposed API look like?
When utilizing src imports, use loaders from corresponding webpack rule based on import extension.

**Comment by yyx990803** [comment]
We also want this but currently webpack doesn't provide a good API for achieving this.
