### ISSUE TITLE
cssModules options handle issue

### ISSUE THREAD

**Issue by septs** [vuejs/vue-loader#871]
### Version
13.0.0

### Reproduction link
[https://gist.github.com/septs/d8f35d8ea772b08baaaf0610b634cf9d](https://gist.github.com/septs/d8f35d8ea772b08baaaf0610b634cf9d)

### Steps to reproduce
```
$ git clone https://gist.github.com/septs/d8f35d8ea772b08baaaf0610b634cf9d
$ npm build
$ cat styles.css
```

### What is expected?
https://github.com/vuejs/vue-loader/blob/ead854df098ae1f8e59157cd77c3ebc6b8fc8d94/lib/loader.js#L169

`DEFAULT_OPTIONS` not is force values

This is what I hope `Object.assign(query, OPTIONS, DEFAULT_OPTIONS, option)`

### What is actually happening?
https://github.com/vuejs/vue-loader/blob/ead854df098ae1f8e59157cd77c3ebc6b8fc8d94/lib/loader.js#L169

`DEFAULT_OPTIONS` override the user's options

-----------------------

see #142

**Comment by Jinjiang** [comment]
Because your write `cssModules` field in `webpack.config.js` so it's `true` through `DEFAULT_OPTIONS` by force:

``` js
const DEFAULT_OPTIONS = {
  modules: true
}
```

I don't think this is a problem or a bug, just by design.
If you want to ensure `module: false`, you can just remove `cssModules` field in config.

Thanks.

**Comment by septs** [comment]
@Jinjiang see https://github.com/vuejs/vue-loader/issues/142#issuecomment-312219585

**Comment by Jinjiang** [comment]
Still not quite understand your purpose behind. I suggest you provide more detail about your use case (and explain why) to discuss if you don't mind.

**Comment by septs** [comment]
```vue
<template>
  <section :class="$style.example">
     <nav>
         <a class="active">Active</a>
     </nav>
     <button class="btn-text">Text Button</button>
  </section>
</template>

<style module>
  :local(.example) a.active {
     border-bottom: 1px solid blue;
  }
  :local(.example) .btn-text {
     border: none;
     background-color: transparent;
     padding: 0;
  }
</style>
```

**Comment by JounQin** [comment]
Please use `:global`...

**Comment by septs** [comment]
@Jinjiang

**Comment by Jinjiang** [comment]
As @JounQin 's advice: using `:global`:

``` vue
<style module>
  :local(.foo) {
    color: red;
  }
  :global(.bar) {
    color: blue;
  }
</style>
```

will result in:

``` css
._3HXsU3tjHIBnqn8w12XHbS_0 {
  color: red;
}
.bar {
  color: blue;
}
```

Or you can set another `<style>` tag without `module` attribute:

``` vue
<style module>
  :local(.foo) {
    color: red;
  }
</style>

<style>
  .baz {
    color: yellow;
  }
</style>
```

also result in:

``` css
._3HXsU3tjHIBnqn8w12XHbS_0 {
  color: red;
}

.baz {
  color: yellow;
}
```

Thanks.

**Comment by septs** [comment]
@Jinjiang You do not consider the nesting problem.

```
<style module lang="less">
.example {
  :global(a.active) {
    border-bottom: 1px solid blue;
  }
  :global(.btn-text) {
    border: none;
    background-color: transparent;
    padding: 0;
  }
}
</style>
```

->

**Comment by Jinjiang** [comment]
Just no more special. So what's your expected code which is generated from the less code above?

**Comment by yyx990803** [comment]
You can use a separate `<style>` block for global styles.
