### ISSUE TITLE
lang="jsx" for <template />

### ISSUE THREAD

**Issue by nickmessing** [vuejs/vue-loader#872]
### What problem does this feature solve?
Sometimes JSX is useful, we can simply use it without `<template />` just by adding `render(){}` method to default export from `<script />`. It could be usefult have an option to use JSX in `<template />` for hot-reloading (separate reloading for template, without re-initialization of the component).

### What does the proposed API look like?
```html
<template lang="jsx">
export default function () { return <h1>{this.hello}</h1> }
</template>
<script>
export default {
  data: () => ({
    hello: 'world'
  })
}
</script>
```
or just
```html
<template lang="jsx">
  <h1>{this.hello}</h1>
</template>
<script>
export default {
  data: () => ({
    hello: 'world'
  })
}
</script>
```

**Comment by egoist** [comment]
why not just use JSX in `render` function?

**Comment by nickmessing** [comment]
@egoist, I do that sometimes atm (when JSX is shorter than vue template) but hot-reload re-initialises whole component as opposite to re-render when using `<template />`, it's just a matter of dev experience.

**Comment by skyrpex** [comment]
@nickmessing have you tried [vue-jsx-hot-loader](https://github.com/skyrpex/vue-jsx-hot-loader)?

I wanted to ask @yyx990803 to bring a bit of love to it and maybe become an official loader.

**Comment by nickmessing** [comment]
@skyrpex, I didn't even know it exists, thank you, will check that out, I don't know about making it officail but we can try and make a `vuejs-templates/jsx` later

**Comment by nickmessing** [comment]
I'll take a more detailed look at `vue-jsx-hot-loader`, looks like the solution.
