### ISSUE TITLE
named exports are not supported in *.vue files.

### ISSUE THREAD

**Issue by chang20159** [vuejs/vue-loader#877]
什么情况下汇报这个错呢？named exports are not supported in *.vue files.

还有这个：[vue-loader] Badge.vue: functional components are not supported with templates, they should use render functions.

**Comment by fritx** [comment]
```js
import {
  closest, getOffset, getPrecedingRange,
  getRange, applyRange,
  scrollIntoView, getAtAndIndex, insertText
} from './util'
import AtTemplate from './AtTemplate.vue'

export { insertText }

export default {
  name: 'At',
```

Cannot export other names than `default`.

**Comment by johnathankent** [comment]
@fritx Can you provide the contents of `./util`? Looking to see what kind of module we are talking about here...

**Comment by fritx** [comment]
@johnathankent oops sorry for the delay:

https://github.com/fritx/vue-at/blob/dev/src/util.js

**Comment by saintplay** [comment]
I'm trying to import some variables for testing, and I dont really wan't to separate them in other file 

```js
export const DEFAULT_BACKGROUND_COLOR = '#ffffff'
export const DEFAULT_BORDER_RADIUS = '10px'
export const DEFAULT_MAX_HEIGHT = 300
export const DEFAULT_ROW_LENGTH = 5
export const DEFAULT_SWATCH_SIZE = 42
export const DEFAULT_SHOW_BORDER = false

export default {
  name: 'swatches',
  components: {
    Swatch
  },
```

So, it seems that the only module I can import from `.vue` file is the default one.
> named exports are not supported in *.vue files.

**Comment by yyx990803** [comment]
This has been supported since 13.6

**Comment by davidpelayo** [comment]
@yyx990803 there is no example in the documentation. Could you provide any that we can look at, please?

**Comment by blackboxx** [comment]
yes

**Comment by yoavniran** [comment]
hi @yyx990803 

i have a Button.vue file with - 

```
<script>
export const COLORS = {BLUE: "blue", ORANGE: "orange"};

export default {
		name: "Button",
...
</script>
```

In another component (AdvancedParams.vue) I do:

```

<script>
 import Button, {COLORS} from "../Button";

 ...
</script>

```

When i run yarn serve though i see this warning: 

 warning  in ./src/components/Customization/AdvancedParams.vue?vue&type=script&lang=js

"export 'COLORS' was not found in '../Button'

Isnt this supposed to be supported? what am I missing?

vue-cli service: 3.0.0-rc.3 
vue-loader: 15.2.0 

thanks.

**Comment by ilyakamens** [comment]
Not fixed for me either. On vue-loader 15.X.

**Comment by victorz** [comment]
Not fixed for me either, vue-loader 15 and 16.

Maybe reopen this?
