### ISSUE TITLE
npm got error when I use precss in vue-loader.

### ISSUE THREAD

**Issue by mov1er** [vuejs/vue-loader#878]
### Version
13.0.1

### Reproduction link
[https://github.com/jonathantneal/precss](https://github.com/jonathantneal/precss)

### Steps to reproduce
Here is code:
>postcss: [
>require('postcss-cssnext')(), //**postcss is working fine if I only write this row.**
>require('precss')().process({ parser: require('postcss-scss') }) //**npm got error when I add this row**
]

Here is error log:
**Module build failed: Error: PostCSS syntaxes cannot be used as plugins. Instead, please use one of the syntax/parser/stringifier options as outlined in your PostCSS runner documentation.**

It seems every .vue file got same error?... I'm dont understand,pls, someone help me.

### What is expected?
use precss in vue-cli

### What is actually happening?
got error

**Comment by sqal** [comment]
I am looking at examples in the precss readme - https://github.com/jonathantneal/precss and looks to me like you're using Node example instead of postcss - there's a difference where you should use process function

**Comment by mov1er** [comment]
@sqal no,I am using postcss in vue-loader.conf.js which has already been added in latest vue-cli.

**Comment by mov1er** [comment]
Is there anybody can help out?

@egoist 可以帮我看看吗，谢谢了

**Comment by gucong3000** [comment]
@mov1er 别紧张，配置写错了而已
```js
// webpack.config.js
module.exports = {
	// other options...
	module: {
		// module.rules is the same as module.loaders in 1.x
		rules: [
			{
				test: /\.vue$/,
				loader: 'vue-loader',
				// vue-loader options goes here
				options: {
					// ...
					postcss:  {
						plugins: [
							require('postcss-cssnext'),
							require('precss')
						],
						options: {
							parser: require('postcss-scss')
						}
					}
				}
			}
		]
	}
}
```

**Comment by gucong3000** [comment]
你的写法是precss独立使用时的写法，当precss再postcss内运行时，parser参数应该时postcss这一层中的参数

**Comment by mov1er** [comment]
@gucong3000 是这样的，谢谢
