### ISSUE TITLE
disable lazy-injected CSS

### ISSUE THREAD

**Issue by throrin19** [vuejs/vue-loader#881]
Hi, I have a problem since the release 0.12.0 with the CSS lazy-inject :

> Upgrading vue-style-loader to 3.0 introduces a small breaking change: the CSS contained in a *.vue component will now be lazy-injected, when the component is rendered for the first time. (Previously the style is injected as soon as the component is imported.)

With external libraries like muse-ui, ... we can use all the library directly or load components individually. In this case, it's not possible, with this breaking change, to override the design easilly. 

For example, with muse-ui, we can import specific css file to override the default theme. With the lazy-inject, the css theme is load before the component and, in this case, the theme is not applied.

It's possible to choose if we want the lazy-inject or not ?

Thanks

**Comment by yyx990803** [comment]
If you want deterministic style order, extract the CSS with `extract-text-webpack-plugin`.
