### ISSUE TITLE
Using file-loader to resolve relative image paths in <script> of SFCs

### ISSUE THREAD

**Issue by btoo** [vuejs/vue-loader#882]
### Version
13.0.2

### Steps to reproduce
How can I resolve image paths that exist in an SFC's data but are then used in the template?

In the vue-loader webpack configuration, I have:
```
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      js : {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'file-loader',
        options: {
          name: '[path][name].[ext]'
        }
      }
    }
  }
},
```

In my SFC (hello.vue), I have:
```
<template>
  <img :src="imagePath">
</template>

<script>
  export  default {
    data(){
      return {
        imagePath: './img/imagePath.png' // can this image path be resolved with file-loader?
      }
    }
  }
</script>
```

### What is expected?
The template will compile the <img> with a src of [path][name].[ext]. File-loader should also emit the image at [path][name].[ext]

**Comment by woshi82** [comment]
This is work, don't need any extra config. `import fox from '../../../assets/images/fox.jpg';`

**Comment by yyx990803** [comment]
Wrap the path with a `require` call, or import it so that it gets processed by `file-loader`.

**Comment by hiveer** [comment]
my case is a little different, I'm using Vue3 in Rails with esbuild, I can't import image from a relative path
<img width="1394" alt="image" src="https://github.com/vuejs/vue-loader/assets/3827780/32337f7b-e6ff-433b-8d96-9b0c4f17c884">

not sure how to handle this
