### ISSUE TITLE
HMR: Uncaught TypeError: Cannot read property 'hot' of undefined

### ISSUE THREAD

**Issue by guoerwei** [vuejs/vue-loader#890]
```
manifest.js:590 Uncaught TypeError: Cannot read property 'hot' of undefined
    at hotApply (manifest.js:590)
    at hotUpdateDownloaded (manifest.js:314)
    at hotAddUpdateChunk (manifest.js:294)
    at webpackHotUpdateCallback (manifest.js:37)
    at 0.a0cbf6c….hot-update.js:1
```

I‘m using webpack3 + vue-loader through webpack nodejs api.

when I modify the `template` tag in the `.vue` file, hmr worked fine.
moduleId `./App.vue` was in the installedModules array

but if I modify the code in the `script` tag, the error above was thrown,
and moduleId `./App.vue` was gone.

In my `dev.config.js` file, I added `hmr: ['webpack/hot/dev-server', 'webpack-dev-server/client?http://localhost:8080']` into the entry field, and `new webpack.HotModuleReplacementPlugin()` into the plugins array, also, `hot: true` was in the `webpackDevServer`'s second arguments as well

I tried CLI to run webpack-dev-server with `--hot --inline`, both `template` tag and `script` tag work fine.

**Comment by gabrielfin** [comment]
I have the same issue. Related issue webpack/webpack#2387

**Comment by trainiac** [comment]
I've reported the issue here with a basic reproduction 
https://github.com/vuejs/vue-loader/issues/838

**Comment by yyx990803** [comment]
Sorry that this issue wasn't promptly looked at, but since it lacks a reproduction we can't really see what's going on here. If this is still a problem, please open a new issue with a proper reproduction. Thanks!
