### ISSUE TITLE
Inject-Loader 3.0.0 warning is out of date

### ISSUE THREAD

**Issue by joflashstudios** [vuejs/vue-loader#892]
### Version
12.2.2

### Reproduction link
[https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html](https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html)

### Steps to reproduce
The documentation states that Inject-Loader 3.0.0 is unstable (circa September 2016), but 3.0.0 has been out of beta since March 2017, so it seems like this warning is out of date.

### What is expected?
No warning about inject-loader 3.0.0

### What is actually happening?
Warning about inject-loader 3.0.0

**Comment by Jinjiang** [comment]
I think the warning could be removed. Also I found another important warning: disabling `esModule` option in inject mode because `import/export` must be top-level.

I will create a PR for this soon.

Thanks.
