### ISSUE TITLE
v-model on input with type=radio breaks in PhantomJS

### ISSUE THREAD

**Issue by mattixittam** [vuejs/vue-loader#902]
### Version
13.0.2

### Reproduction link
[http://cannot/reproduce/without/phantomJS](http://cannot/reproduce/without/phantomJS)

### Steps to reproduce
Use an <input type="radio"> element with v-model set and load it using webpack and vue-loader 13.0.2 into PhantomJS

### What is expected?
The radiogroup works

### What is actually happening?
PhantomJS gives this error:

```
SyntaxError: Unexpected token '}'
```

---
This occurs for me when trying to run unit tests on our component library, which is based on a modified version the vue-cli webpack template.

The issue appears after an upgrade of vue-loader from 12.2.2 to 13.0.2

**Comment by ellis2323** [comment]
Same problem. Upgrade from 12.x to 13.x doesn't work when i do 
npm run test
I have a SyntaxError: Unexpected token '}'

**Comment by RonyVidaur** [comment]
I have the same issue, but not with radio buttons, I have both of my inputs as type="text"
`<div v-if="type == 'edit'">
            <div class="field" v-for="(field, index) in object" :key="field">
              <label class="label">{{index}}</label>
              <div class="control">
                <input v-if="index === Object.keys(object)[0]" type="text"  class="input" :value="field" v-model="updatedPostBody[index]" disabled />
                <input v-else type="text" :value="field" class="input" v-model="updatedPostBody[index]"/>
              </div>
            </div>   
          </div>`

**Comment by RonyVidaur** [comment]
anyone with any updates on this issue? I have two inputs, they're both type="text"

**Comment by Jinjiang** [comment]
Strange, I have tried the `v-model` demo code in official docs:

``` vue
<template>
  <div id="app">
    <input type="radio" id="one" value="One" v-model="picked">
    <label for="one">One</label>
    <br>
    <input type="radio" id="two" value="Two" v-model="picked">
    <label for="two">Two</label>
    <br>
    <span>Picked: {{ picked }}</span>
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      picked: 'One'
    }
  }
}
</script>
```

and build it by `vue-loader@13.0.2` but haven't seen the error 🤔.

Would you guys like to supply more informations like source code, generated code, phantom version or vue version as much as possible?

Thanks.

**Comment by RonyVidaur** [comment]
Hi! the thing is that it works when you run the app, however, as @mattixittam  mentioned above, it breaks when you try to run unit test on it. I will be uploading some code to reproduce in a little while.

**Comment by yyx990803** [comment]
I tried the compiled output of `v-model` with `type="radio"` in PhantomJS 2.1.1 and it works as intended. With the given information here, there's nothing we can do unless a real repro is provided.
