### ISSUE TITLE
Improve documents of Custom Blocks

### ISSUE THREAD

**Issue by viruscamp** [vuejs/vue-loader#903]
https://github.com/vuejs/vue-loader/blob/master/docs/en/configurations/custom-blocks.md

* webpack.config.js of Webpack 2.x
  loader: 'vue' should be loader: 'vue-loader'

* Runtime available docs
  The component contains <docs/>, can use it like: this.$options.__docs

**Comment by yyx990803** [comment]
Please submit a PR instead.
