### ISSUE TITLE
13.0.2 breaks vue loading with pug

### ISSUE THREAD

**Issue by imrefazekas** [vuejs/vue-loader#904]
Guys,

I was using v12.2.2 with pug as template language. Just moved to 13.0.2 and I receive this when mounting the vue:
"Failed to mount component: template or render function not defined"

Reinstalling 12.2.2, it works again. 13.0.2 breaks it. Any ideas? Thanks...

**Comment by LinusBorg** [comment]
Please provide an example, Judging from the error, I rather think that toy as require() and don't respect the new syntax necessary by a breaking change in vue-loader 13.* (see releases page.)

**Comment by Kauto** [comment]
Where do I find the releases page or news about the breaking changes?

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

**Comment by Kauto** [comment]
thanks, this solved my issue
