### ISSUE TITLE
Automatically require dependencies

### ISSUE THREAD

**Issue by stephan-v** [vuejs/vue-loader#907]
### What problem does this feature solve?
It seems vue-loader cannot run without vue-template compiler. If this is the case why not directly require vue-template-compiler within the vue-loader module?

Or it this not possible?

### What does the proposed API look like?
Make the vue-template-compiler a hard dependency.

**Comment by ktsn** [comment]
This is intentional. The reason that we leave it as peerDependencies is users can specify both vue and vue-template-compiler version. It is required since Vue and vue-template-compiler need to be exactly same version.

**Comment by stephan-v** [comment]
Ok thanks for the answer. :)
