### ISSUE TITLE
/deep/ selector will be deprecated soon

### ISSUE THREAD

**Issue by Jack-Works** [vuejs/vue-loader#913]
### Version
12.2.2

### Reproduction link
[http://no-link/](http://no-link/)

### Steps to reproduce
1. Use /deep/.

### What is expected?
Nothing happened.

### What is actually happening?
A deprecation warning.

---
[Deprecation] /deep/ combinator is deprecated and will be a no-op in M60, around August 2017. See https://www.chromestatus.com/features/4964279606312960 for more details.

**Comment by yyx990803** [comment]
Use `>>>` instead.

**Comment by Jack-Works** [comment]
And less can not recognize >>>

**Comment by yyx990803** [comment]
Then you can just ignore the warning... `/deep/` is compiled away and does not appear in your final CSS.

**Comment by Jack-Works** [comment]
Oh, that's cool, thanks

**Comment by Varkal** [comment]
That's not works for me : /deep/ selector aren't compiled at all. 
Maybe sass-loader need a specific  configuration to transpile them ?

**Comment by Yuliang-Lee** [comment]
@Varkal Did you solved this problem?

**Comment by Varkal** [comment]
I think i have made a mistake because now it's works... and don't change anything to my setup...

**Comment by paglias** [comment]
Confirmed that /deep/ isn't compiled away

**Comment by maurop123** [comment]
So my styles with /deep/ seem to work on Chrome, but not Safari. Is anyone else getting this?

**Comment by mercs600** [comment]
the same for me

**Comment by sesopenko** [comment]
Does this mean that vue-loader won't parse & replace /deep/ selectors, as described in the [Scoped CSS](https://vue-loader.vuejs.org/en/features/scoped-css.html#deep-selectors) documentation of vue-loader?

> Some pre-processors, such as SASS, may not be able to parse >>> properly. In those cases you can use the /deep/ combinator instead - it's an alias for >>> and works exactly the same.

Is this the feature being deprecated?

**Comment by mattaningram** [comment]
I'm confused, `>>>` doesn't work in `scss` for me, but `/deep/` does, is this going to be removed?

**Comment by bovas85** [comment]
@mattaningram as Evan said, /deep/ is compiled from sass to css so it's not used in the build version in production

**Comment by julian-ca** [comment]
It's almost a year since this was reported and I'm still confused. :/

`>>>` won't work

**Comment by bovas85** [comment]
Use /deep/

**Comment by pbastowski** [comment]
`/deep/` is no longer supported by Chrome. 

I get the following message:

![image](https://user-images.githubusercontent.com/5649024/48227246-0f8e6f00-e3a2-11e8-835a-12621f93adc3.png)

So, how do we do deep selectors now?

**Comment by ThomHurks** [comment]
This [Angular commit](https://github.com/angular/angular/commit/b754e600e30476a22e29019d89df71dd9b7fcbd5) says:

> - /deep/ is deprecated and being removed from Chrome
> - ">>>" is semantically invalid in a stylesheet
> - sass will no longer support either in any version of sass
> 
> -> use ::ng-deep in emulated shadow DOM mode
> 
> Because the deep combinator is deprecated in the CSS spec,
> `/deep/`, `>>>` and `::ng-deep` are also deprecated in emulated shadow DOM mode
> and will be removed in the future.

So it seems that vue-loader will hit the same problem? If ```>>>``` and ```/deep/``` are not valid SASS/SCSS then we can't use it because you would get a parse error before you even get to```vue-loader```.

**Comment by bovas85** [comment]
I get that warning in production

**Comment by Justineo** [comment]
@bovas85 https://github.com/vuejs/vue-loader/issues/913#issuecomment-437237791

**Comment by mohamedelhosseiny** [comment]
https://stackoverflow.com/questions/35741722/whats-the-substitute-for-shadow-and-deep

I tried replicating the instructions given in the above thread in a Vue component but it doesn't seem to work. However, it is working fine with AngularJs.

How can I use `:host()` & `:host-context()` in  a Vue component?

**Comment by pbastowski** [comment]
@mohamedelhosseiny 
`/deep/` still works for me inside Vue component files. These are file that have the `.vue` suffix.
It does not work for me in `.scss` or `.css` files.

**Comment by twickstrom** [comment]
I noticed this warning for the first time today in chrome. I am using /deep/ throughout my code. I noticed if I do not scope my styles I will get the warning. If they are scoped I do not get the warning.

<style lang="scss"> // Chrome will show the warning

<style lang="scss" scoped>  // Chrome will not show the warning

Must be in the way the loader is compiling the CSS/SCSS.

**Comment by sherily123** [comment]
Agree with @twickstrom .
My app use only original CSS style.
When I use /deep/ in a non-scoped style field, I get warning in Chrome; get no warning and style doesn't work in Firefox and Safari;
When I use /deep/ in a scoped field, the combinator will be changed into a descendant style in the runtime code, and works well in Chrome, Firefox and Safari.
So only /deep/ in style rules processed by vue css loader will work, otherwise not.

**Comment by plong0** [comment]
Using project created by vue-cli 3.5.0 with scss option enabled when running `vue create`.  For the most part `<style scoped lang="scss">` is working normally, but deep selector does not seem to be working with scss.

I cannot use `>>>` or `/deep/` when I have `<style scoped lang="scss">`.
When I remove `lang="scss"` and have `<style scoped>`, either `>>>` or `/deep/` work perfect.

Is it possible with current version to have a deep selector working with `lang="scss"`?

**Comment by Justineo** [comment]
@plong0 You can try `::v-deep`. https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by plong0** [comment]
@Justineo `::v-deep` worked! Thanks for the tip!

**Comment by ashmenon** [comment]
@plong0 @Justineo how does one use `::v-deep`? I don't see any examples of it on the page linked. I'm using /deep/ now and it appears to work, but I'm worried about long-term support.

**Comment by Justineo** [comment]
@ashmenon Just replace `/deep/` with `::v-deep`.

**Comment by GitHdu** [comment]
> @ashmenon Just replace `/deep/` with `::v-deep`.

chrome works well, like this `.checkbox-container /deep/ .checkbox-group`
howerve,firefox did not work and cannot find `/deep/`

**Comment by Justineo** [comment]
@GitHdu https://github.com/vuejs/vue-loader/issues/913#issuecomment-437237791

**Comment by GitHdu** [comment]
@Justineo the project was generated by vue-cli3 and just add the option as below
```config
pluginOptions: {
    'style-resources-loader': {
      preProcessor: 'less',
      patterns: [path.resolve(__dirname, './src/assets/style/base.less')]
    }
  }
```

**Comment by GitHdu** [comment]
#1407 @Justineo

**Comment by Justineo** [comment]
@GitHdu https://github.com/vuejs/vue-loader/issues/1407#issuecomment-449708501

**Comment by satyamqainfotech** [comment]
> @plong0 You can try `::v-deep`. https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

This is not working inside nested css - 

```
.foo {
   ::v-deep .bar {
         background: red; 
     }
}
```

**Comment by teawithsatyam** [comment]
> @plong0 You can try `::v-deep`. https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

`::v-deep` is not working inside nested css but `/deep/` works

```
.foo {
   ::v-deep .bar {
       background: red;
    }
}
```

**Comment by lizy0329** [comment]
summary: 
1. `>>>` deep selector is suitable only in css file
2. `/deep/` deep selector is suitable only in sass/less file, but chome Deprecation warnning here.
3. `::v-deep` deep selector is suitable only in vue file, but it's not working inside nested css

```javascript
// not work
.foo {
   ::v-deep .bar {
       background: red;
    }
}
```

**Comment by mstrlaw** [comment]
I'm able to use `::v-deep` (including nested) but _only_ when `scoped` is set.

```scss
// Works
<style scoped lang="scss">
.c-Object{
  &__element{
    &--is-disabled{
      ::v-deep mark {
        background-color: gray;
      }
    }
    ::v-deep mark {
      background-color: red;
    }
  }
}
</style>
```

```
vue@^2.6.10
node-sass@^4.12.0
sass-loader@^7.1.0
```

**Comment by curryz** [comment]
IE can't work, did you ever meet

**Comment by curryz** [comment]
can it work on the IE browser, @yyx990803

**Comment by yyx990803** [comment]
**They are all compiled away and has nothing to do with browser support.**
