### ISSUE TITLE
Is it possible to define two components in one .vue file?

### ISSUE THREAD

**Issue by f15gdsy** [vuejs/vue-loader#92]
Hi,

I want to do this:
```
<script>
  export const CompoA = { //... }
  export const CompoB = { //... }
</script>
```

But when I got an error saying: "Uncaught TypeError: Cannot set property 'template' of undefined".
And it works fine if I have
```
export default { //... }
```

**Comment by yyx990803** [comment]
No, that doesn't make sense...

**Comment by goforu** [comment]
> No, that doesn't make sense...

But on some circumstances, I only want a tiny sub component and I wish it could be accessible in the same file. Raising an another file could be a little be heavy for that I suppose.
