### ISSUE TITLE
Currently can not configure support ~ / assets?

### ISSUE THREAD

**Issue by yuchonghua** [vuejs/vue-loader#920]
@yyx990803
[Currently can not configure support ~ / assets](https://github.com/nuxt/nuxt.js/issues/1241)
[bug1](https://github.com/nuxt/nuxt.js/commit/1f85b2dd13622575dbf0d2569d7486152d261d13)

**Comment by LinusBorg** [comment]
1. Don't mention people in your initial issue for no reason. You are not the only one with an issue.
2. follow proper issue format: http:new-issue.vuejs.org
