### ISSUE TITLE
when set   extractCSS: true," chunk.sortModules " error

### ISSUE THREAD

**Issue by herrdu** [vuejs/vue-loader#923]
requires :'webpack 2.4.1'

parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
/Users/herrdu/work/vbProject/nongjia/ued/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at /Users/herrdu/work/vbProject/nongjia/ued/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/herrdu/work/vbProject/nongjia/ued/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/herrdu/work/vbProject/nongjia/ued/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/herrdu/work/vbProject/nongjia/ued/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/herrdu/work/vbProject/nongjia/ued/node_modules/async/dist/async.js:3145:5)
    at Compilation.<anonymous> (/Users/herrdu/work/vbProject/nongjia/ued/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/usr/local/lib/node_modules/webpack/lib/Compilation.js:575:8)
    at /usr/local/lib/node_modules/webpack/lib/Compiler.js:488:16
    at /usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/usr/local/lib/node_modules/webpack/lib/Compilation.js:477:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:448:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

webpack.conf.js
```
var path = require('path')
var webpack = require('webpack')
var ExtractTextPlugin = require("extract-text-webpack-plugin")
var InlineManifestWebpackPlugin = require("inline-manifest-webpack-plugin");


module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  module: {
    rules: [{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            css: ExtractTextPlugin.extract({
              use: 'css-loader',
              fallback: 'vue-style-loader' // <- this is a dep of vue-loader, so no need to explicitly install if using npm3
            })
            // Since sass-loader (weirdly) has SCSS as its default parse mode, we map
            // the "scss" and "sass" values for the lang attribute to the right configs here.
            // other preprocessors should work out of the box, no loader config like this necessary.
            // 'scss': 'vue-style-loader!css-loader!sass-loader',
            // 'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  plugins: [
    new InlineManifestWebpackPlugin({
      name: 'webpackManifest'
    }),
    new ExtractTextPlugin("style.css")
  ],
}
```

**Comment by LinusBorg** [comment]
thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.

**Comment by maximkoretskiy** [comment]
@herrdu Had the same problem. It looks like your `extract-text-webpack-plugin` version does not match webpack version.

**Comment by definedw** [comment]
@maximkoretskiy Thanks for you tip,it's work!
