### ISSUE TITLE
Parent Selectors Within Child Selectors not working

### ISSUE THREAD

**Issue by cpietsch** [vuejs/vue-loader#929]
### Version
13.0.2

### Reproduction link
[http://null](http://null)

### Steps to reproduce
```
.feature-class {
    color: #0090B2;
    .parent-class & {
      color: #00CEFF;
    }
}
```

### What is expected?
```
.feature-class {
  color: #0090B2;
}
.parent-class .feature-class {
  color: #00CEFF;
}
```

### What is actually happening?
the `.parent-class &` is not being executed, so no `.parent-class .feature-class` is generated. 

---
using `<style scoped lang="scss">` (sass)

**Comment by LinusBorg** [comment]
Please see the very end of this page in the docs: 

https://vue-loader.vuejs.org/en/features/scoped-css.html

**Comment by nlitwin** [comment]
I wasn't able to find this in the docs, but I got the parent selector to work by placing `/deep/` afterthe &:

```sass
.child-class {
  color: red

  /* compiles to .parent-class .child-class[data-v-534332] */
  .parent-class & /deep/ {
    color: blue;
  }
}
```

**Comment by LinusBorg** [comment]
> I wasn't able to find this in the docs

As mentioned, nea the end of this page:

https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by nlitwin** [comment]
I'm familiar with that section of the docs. It only explains how to use `/deep/` in regular circumstances:

```sass
.parent-class {
  color: red

  /* compiles to .parent-class[data-v-534332] .child-class */
  /deep/ .child-class {
    color: blue;
  }
}
```

But the documentation doesn't explain how to handle the [SASS-specific parent selector](https://sass-lang.com/documentation/style-rules/parent-selector), i.e. putting the `&` _after_ the nested class. Note the parent class is nested inside of the child class, and the `[data-v-*]` part has moved:

```sass
.child-class {
  color: red

  /* compiles to .parent-class .child-class[data-v-534332] */
  .parent-class & /deep/ {
    color: blue;
  }
}
```

Just wanted to comment here because it took some trial and error, and I hope someone in the same situation finds it useful

**Comment by nitsuj102284** [comment]
@nlitwin, this helped me immensely. I have a #sidepanel component and a #navigation component, in which I have 'a' tags. I needed different CSS on my 'a' tags when the the #sidepanel was .expanded.

My structure:
```
#side-panel        <~ parent component
    #navigation    <~ child component
       a
```

In my #navigation component:
```
<style lang="scss" scoped>
    #navigation {
        a {
            /* regular 'a' properties */
            color: blue;

            #side-panel.expanded & ::v-deep {
                  /* 'a' properties when side panel expanded */
                  color: red;
            }
        }
    }
</style>
```
I don't know the difference between '/deep/' and '::v-deep', other than that I read somewhere that '/deep/' is deprecated. Tried both and they work.
