### ISSUE TITLE
Cannot read property 'comments' of undefined

### ISSUE THREAD

**Issue by ccforward** [vuejs/vue-loader#931]
### Version
13.0.3

### Reproduction link
[http://null](http://null)

### Steps to reproduce
When I update the vue-loader to 13.0.3  The webpack can not compile the .vue file and report an error.

The webpack version is 2.7.0

### What is expected?
To compile the .vue file successfully.

### What is actually happening?
The webpack can not compile the .vue file .
The error occured at 92 line.
![image](https://user-images.githubusercontent.com/2782664/28968294-ed146652-7951-11e7-80cc-96f3fff1a426.png)
![image](https://user-images.githubusercontent.com/2782664/28968358-31289070-7952-11e7-92e7-148f67004fe4.png)

**Comment by suuzee** [comment]
test
