### ISSUE TITLE
Asynchronous .vue components & rendering

### ISSUE THREAD

**Issue by justinhelmer** [vuejs/vue-loader#935]
### Version
13.0.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/51954/](https://jsfiddle.net/50wL7mdz/51954/)

### Steps to reproduce
> Please note that the NPM-published version of `vue-loader` is actually `13.0.4`, but I will assume this corresponds with `13.0.2`, as this is the max release listed.

Consider the following asynchronous component code:

`index.html`:
```html
<div id="app">
  <test></test>
</div>
```

`app.js`:
```js
new Vue({
  el: '#app',
  components: {
    test: () => import('./Test.vue');
  }
})
```

`Test.vue`:
```html
<template>
    <div id="test">{{msg}}</div>
</template>

<script>
export default new Promise(function(resolve) {
  setTimeout(function() {
    resolve({
      data() {
        return {
          msg: 'Hello world!'
        }
      }
    });
  }, 500);
});
</script>
```

### What is expected?
"Hello world!" will be rendered

### What is actually happening?
The following error will be thrown:

```
[Vue warn]: Property or method "msg" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

---
This will work with a standard `.js` component using the `template` option (assuming I alias `vue` to use the full library instead of `vue.runtime.js`):

`Test.js`:
```js
export default Promise.resolve({
  name: 'test',
  template: '<div id="test">{{msg}}</div>',
  data: () => ({ msg: 'Hello world!'})
});
```

`webpack.config.js`:
```js
module.exports = {
  // ...
  resolve: {
    alias: {
      vue: 'vue/dist/vue.js'
    }
  },
  // ...
}
```

However, I would like to use the power of `vue-loader` to create single-file (scoped) components and also enable the use of just the vue runtime.

**Comment by LinusBorg** [comment]
You don't have to export a Promise, `import()` returns one by itself. That's the whole point: you don't have to change anything in your components to make them async.

So just export the component a usual, without any Promise.

Sidenote: the reason you see this error is that vue-loader expects the default export of a .vue file to be a components options object or a constructor - not a promise.

**Comment by justinhelmer** [comment]
@LinusBorg - sorry but can you please walk me through it a little more? Based on how I read the docs ([Async Components](https://vuejs.org/v2/guide/components.html#Async-Components)), the code in `./my-async-component` will export a Promise.

I'm trying to use this pattern to code-split while also having components execute asynchronous code before resolving. How would I go about doing so? With what you are suggesting:

```js
// async.vue

export default {
  data() {
    return {
      msg: 'Hello world!'
    }
  }
};
```

... since an object is exported, there is nothing "async" happening here. I want the component to execute async code before it resolves to its parent consumer.

Would I have to do something similar to nuxt and wire up a beforeResolve hook to vue-router to run any async code in the component? Perhaps the docs are just what's confusing me, and I'm expecting more to happen than actually does.

**Comment by LinusBorg** [comment]
> Based on how I read the docs (Async Components), the code in ./my-async-component will export a Promise.

No. The .vue file doesn't return a Promise. `import(....)` returns a Promise resolving to the component. 
```javascript
import myComponent from './component.vue' // exports a normal component options object
export default {
  components: {
    'my-component': myComponent, // synchonous definition
    'my-component': require('./component.vue'), // synchonous definition

    // this is the factory function the documentation is talking about:
    // it returns a Promise that will *resolve* to the component options object.
    'my-component': () => import('./component.vue'), // asynchronous definition
  }
}
```

**Comment by LinusBorg** [comment]
For further questions, please use forum.vuejs.org or chat.vuejs.org. This is a bug tracker and should be reserved for that.
