### ISSUE TITLE
vue文件css提取失败

### ISSUE THREAD

**Issue by submerge** [vuejs/vue-loader#936]
构建工具版本:webpack 2.X  vue-loader: 2.X
模块化方案ES module
按照官方文档上的配置
{
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        css: ExtractTextPlugin.extract({
                            use: 'css-loader',
                            fallback: 'vue-style-loader' 
                        })
                    }
                }
            }

编译之后，vue文件中的css并没有提取到css文件中，求指导

**Comment by winterJIE** [comment]
![image](https://user-images.githubusercontent.com/4085332/29109022-02b63f88-7d14-11e7-90ec-24a98caaaef0.png)

you must use plugin:  ExtractTextPlugin

**Comment by Jinjiang** [comment]
Translation: This issue is about how to use `ExtractTextPlugin` in the right way.
@LinusBorg I think this question has been fully answered by @winterJIE and it can be closed.
Thanks.
