### ISSUE TITLE
Style priority

### ISSUE THREAD

**Issue by dimti** [vuejs/vue-loader#938]
### Version
12.2.2

### Reproduction link
[https://jsfiddle.net/86t9xekq/](https://jsfiddle.net/86t9xekq/)

### Steps to reproduce
I have override child component styles in my own component.
On vue-loader ^10.0.0 all its ok. Style insertions in <head> tag with normal priority
First inserting child components styles
Continuously inserting styles described in my parent component.
Between 10.0.0 and inclusive to 12.2.2 version vue-loader politic priority of inserting of styles is changed. Why?

### What is expected?
http://imgur.com/a/w5BeR

### What is actually happening?
http://imgur.com/a/dXipo

---
Some similar (or not very similar) issues
https://github.com/vuejs/vue/issues/4298
https://stackoverflow.com/questions/41133833/how-to-override-scoped-styles-in-vue-components

**Comment by ashleahhill** [comment]
I ran into this on a project from a few months ago I was updating to use the latest build deps (eslint, webpack etc.) 

For me, the last version that restored order was 11.3.4. A much smaller site I built after that didn't have issues with 13.0.5 fine. I'm guessing it can't be seen without nested components used in more than one place.

**Comment by ashleahhill** [comment]
@dimti This breaking change in v12.0.0 is likely to be the cause of our woes. https://github.com/vuejs/vue-loader/releases/tag/v12.0.0

**Comment by yyx990803** [comment]
Rule of thumb: don't rely on insertion order to write your component styles. They should not be dependent on one another, and there is no guarantee of the order.

**Comment by dimti** [comment]
I like your answer. Really that architecture is slowly quality and better solution for me not connected style dependencies with components hierarchy
