### ISSUE TITLE
webpack报这个错，说叫作者修复

### ISSUE THREAD

**Issue by 2211868381** [vuejs/vue-loader#940]
(node:27928) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

详情看这个： https://github.com/webpack/loader-utils/issues/56

**Comment by Jinjiang** [comment]
问题已经定位到我们依赖的 `file-loader` 上。现在 master 分支里的代码应该已经可以修复了。

Problem found in `file-loader@0.10.x` (it's already `^0.11.2` in our current `master` branch). We will bump the version in the next release.

**Comment by 2211868381** [comment]
哦，Thank you !
