### ISSUE TITLE
/lib/selector.js code review

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue-loader#943]
https://github.com/vuejs/vue-loader/blob/21fb818709a78e01c429f133760951f1d8936f42/lib/selector.js#L13

I just wondering if:
`"..\..\webapp-test\src\views\Login.vue".replace(/\..+$/, '.vue') === ".vue"`
is expected ?

**Comment by Elevista** [comment]
Result of path.relative will not start with relative path like './' or '../ '
but thanks. I missed the case like "webapp-test/srcviews/Login.some.vue"
Should use the negative lookahead

**Comment by FranckFreiburger** [comment]
thanks!
