### ISSUE TITLE
Ability to set postcss config path

### ISSUE THREAD

**Issue by justinhelmer** [vuejs/vue-loader#944]
### What problem does this feature solve?
lots of configs in a project (app config, webpack.base, webpack.client, webpack.server, vue-loader.config, css-loader.config, etc...) means it makes sense to have a `config/` folder in the project. It's unfortunate that `postcss.config.js` has to remain in the root, because there is no ability to specify the path.

The [postcss-loader options](https://github.com/postcss/postcss-loader#options) show a `config` option, that when used, allows the loader to look in a different location for `postcss.config.js`. 

A similar functionality would be very useful for `vue-loader`.

### What does the proposed API look like?
Another option to `vue-loader`:

```js
module.exports = {
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    // ...
    postcss: {
      config: path.resolve(__dirname, './postcss.config.js')
    }
  }
};
```

**Comment by LinusBorg** [comment]
instead of providing a path, simply require the config file and pass it to vue-loader's `postcss` option. That works already.

**Comment by justinhelmer** [comment]
Thanks a ton for finagling this; I'll use the above approach until it's baked into the loader.

**Comment by yyx990803** [comment]
Close via 94d374b318be33c91306631d0f1482f61a00e63d
