### ISSUE TITLE
Add 'name' attribute to <template> tag

### ISSUE THREAD

**Issue by vblagomir** [vuejs/vue-loader#947]
### What problem does this feature solve?
When using single file .vue components, it is often that `<template>` tag appears on top of the file, yet the name of the template is still set in `<script>` tag, which leads to unnecessary delay in figuring out what component you are looking at.

I would suggest to add a 'name' attribute to `<template>` tag to be able to set the name of the component (in addition to currently set it within the `<script>` tag). This would allow to have the name clearly visible and quickly comprehend what is the component you are looking at. 

P.S. Due to a structure I use, the name of components does not strictly match filenames, for example template 'Layout' can be located within 'layout/index.vue' file. And I tend to use PascalCase to name the  components to separate them from typical html tags, whereas the file names are always spinal-cased (due to file system restrictions).

### What does the proposed API look like?
```
<template name='Layout'>
  ..some template body..
</template>

```

**Comment by Jinjiang** [comment]
I am not sure why you need the name because as the [spec](https://vue-loader.vuejs.org/en/start/spec.html#template) says each Vue component only has at most  one template. If you want to use a third-named template maybe [src imports](https://vue-loader.vuejs.org/en/start/spec.html#src-imports) like  `<template src="layout.html">` is good to you.
Thanks.

**Comment by vblagomir** [comment]
Just to specify, my suggestion was to be able to name the component right within <template> tag. It is not about adding any additional templates to existing component. So when saying <template name='some name'></template> it would mean the name of the whole *.vue component, and not the template. 

Now I understand why it might look confusing (as if you name the template not the component) but since there can be only one template per component, it might be ok to refer the 'name' to the component, not template.

**Comment by Jinjiang** [comment]
So do you hope

``` vue
<template name="foo">...</template>
```

equals to

``` vue
<template>...</template>
<script>export default { name: 'foo' }</script>
```

Am I right? I think this syntax would confuse people what the `name` belongs to. The `name` is belongs to the whole component as I think, not a `<template>` only. So I am afraid it is not very necessary and may make people confused.

Thanks.

**Comment by vblagomir** [comment]
Yes exactly. Well it is pity then..
