### ISSUE TITLE
autoprefix does not add scoped id when @keyframes in scoped style

### ISSUE THREAD

**Issue by githoniel** [vuejs/vue-loader#948]
### Version
vue-loader: 13.0.4
"autoprefixer": "^7.1.2",
"postcss-loader": "^2.0.6"

### Steps to reproduce
```
<style scoped>
    .swipe-card {
        animation: swipe 1s infinite;
    }
    @keyframes swipe
    {
        from {
            top: 0px;
            left: 15px;
        }
        to {
            top: 60px;
            left: 60px;
        }
    }
</style>
```

result in 
```
.swipe-card {
    -webkit-animation: swipe-data-v-6aaf155b 1s infinite;
    animation: swipe-data-v-6aaf155b 1s infinite
}
@-webkit-keyframes swipe {
    0% {
        top: 0;
        left: 15px
    }

    to {
        top: 60px;
        left: 60px
    }
}

@keyframes swipe-data-v-6aaf155b {
    0% {
        top: 0;
        left: 15px
    }

    to {
        top: 60px;
        left: 60px
    }
}
```

@-webkit-keyframes swipe   don't have id data-v-6aaf155b

### What is expected?
@-webkit-keyframes swipe  have id data-v-6aaf155b

### What is actually happening?
@-webkit-keyframes swipe   don't have id data-v-6aaf155b

**Comment by PeachScript** [comment]
Any updates for this issue?

**Comment by PeachScript** [comment]
I saw this [commit](https://github.com/vuejs/vue-loader/commit/9d2ecc3fa4952fbd5c16c1f81c33e03504a02a5a#diff-b9f03f03619fccd138ec99fbfd500b98) is has sovled this issue, so when will the next version be released?

**Comment by yyx990803** [comment]
Please upgrade to 13.0.5+
