### ISSUE TITLE
how to extract css using reqiure.ensure

### ISSUE THREAD

**Issue by zhangsalle** [vuejs/vue-loader#949]
can vue-loader solve this problem?

**Comment by LinusBorg** [comment]
When you lazy-load a component, it's CSS will also be lazy.loaded, but in JS, with style-loader. 
It can't be extracted, that's currently a limitation of webpack.

For more information,I refer you to this post of the webpack author:

https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7
