### ISSUE TITLE
Update vue-loader v12.* to postcss@6.0.9 so that postcss-cssnext@3.0.2 can be used

### ISSUE THREAD

**Issue by mkelley33** [vuejs/vue-loader#951]
### Version
12.2.2

### Reproduction link
[https://github.com/MoOx/postcss-cssnext/issues/412](https://github.com/MoOx/postcss-cssnext/issues/412)

### Steps to reproduce
Start a new project using vue-cli. Install postcss-next@3.0.2. Add CSS as in https://github.com/MoOx/postcss-cssnext/issues/412. Build.

### What is expected?
That nested CSS is processed into CSS that works across browsers.

### What is actually happening?
Webpack is erroring as mentioned in https://github.com/MoOx/postcss-cssnext/issues/412

---
Thank you for your time and consideration. I'll be happy to answer any further questions or respond to comments you may have.

**Comment by LinusBorg** [comment]
FYI vue-loader 13.0.0 already has bumped post-css to `6.0.*`. 

I assume you did not update vue-loader because of the necessary changes that come with its breaking change about default exports?

**Comment by yyx990803** [comment]
@LinusBorg hmm, I only bumped it in 13.0 because technically it was a breaking change (postcss 6.0 may not be compatible with old plugins)

My suggestion would be to upgrade to 13.0 since the breaking change is trivial to work around with and with latest `vue` and `vue-loader` it should be a smooth upgrade.

**Comment by LinusBorg** [comment]
Hm ok, I understand that makes sense. 

@mkelley33 Your should also upgrad vue-router so that lazy components are resolved correctly with vue-loader 13.

**Comment by mkelley33** [comment]
@LinusBorg @yyx990803 thanks guys, I used vue-cli to create my project and just got the vue-loader that came with that. I'll make the upgrade. The tips are much appreciated!
