### ISSUE TITLE
Double-slashed comments throw "Unknown word" error when @importing Bootstrap4 in style tag

### ISSUE THREAD

**Issue by monarchwadia** [vuejs/vue-loader#954]
### Version
13.0.2

### Reproduction link
[https://codepen.io/anon/pen/GvGLar](https://codepen.io/anon/pen/GvGLar)

### Steps to reproduce
1. Ensure bootstrap4 is installed in npm
2. Paste the following snippet in a .vue file:

<style type="scss">
   @import "~bootstrap/scss/bootstrap.scss";
</style>

### What is expected?
Bootstrap should function as expected.

### What is actually happening?
"Unknown Word" Error occurs. See minimal reproduction, "CSS" section.

**Comment by LinusBorg** [comment]
`<style type="scss">` is wrong

`<style lang="scss">` is right.

**Comment by monarchwadia** [comment]
Thanks, that worked.

Regards,
Monarch
