### ISSUE TITLE
component-parse will report some error if we put a correct js string which containing '</script>' in script section

### ISSUE THREAD

**Issue by hccde** [vuejs/vue-loader#955]
### Version
12.2.2

### Reproduction link
[https://github.com/hccde/vue-loader.git](https://github.com/hccde/vue-loader.git)

### Steps to reproduce
# npm install
# npm run test

### What is expected?
tests ok

### What is actually happening?
1 failed

---
this issue is the same to https://github.com/vuejs/vue/issues/6433
i add a **parse test case**

**Comment by nickmessing** [comment]
@hccde, that is expected as described in vuejs/vue#6433.

**Comment by hccde** [comment]
@nickmessing  😆  a friend suggest me that i should open an issue here.close the issue ,thxs
