### ISSUE TITLE
extractCSS doesn't work

### ISSUE THREAD

**Issue by cjd6568358** [vuejs/vue-loader#958]
![tim 20170829172617](https://user-images.githubusercontent.com/3970494/29814326-8a0c8b56-8cdf-11e7-885e-339ecfbdfc71.png)
![2](https://user-images.githubusercontent.com/3970494/29814327-8a0fb9ca-8cdf-11e7-9caa-ef17a51458dc.png)
![3](https://user-images.githubusercontent.com/3970494/29814329-8a174f00-8cdf-11e7-9c84-638c70317902.png)
![4](https://user-images.githubusercontent.com/3970494/29814328-8a14a4c6-8cdf-11e7-896c-30b558fcef7e.png)

**Comment by sharifzadesina** [comment]
This still doesn't work for me, and it never worked before :|

**Comment by LinusBorg** [comment]
@cjd6568358 I can't understand that code, what it should do or what your question is.

@sharifzadesina That option only works when you don't manually overwrite the loaders for `scss` etc.

If you do that, you have to add the extract loader yourself:

https://vue-loader.vuejs.org/en/configurations/extract-css.html

**Comment by robwierzbowski** [comment]
Would be useful to note that the simple way only works if you don't specify loaders. I don't see it mentioned in the extract-css page of the docs.
