### ISSUE TITLE
PostCSS not applied to CSS from CSS Modules `composes`

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue-loader#959]
### Version
12.2.2

### Reproduction link
[https://github.com/hirokiosame/vue-loader-css-modules-postcss](https://github.com/hirokiosame/vue-loader-css-modules-postcss)

### Steps to reproduce
PostCSS doesn't seem to be getting applied to the files that CSS Modules pulls in via `composes`. This seems to be happening because vue-loader applies the postcss plugins as a module instead of a webpack plugin.

### What is expected?
For PostCSS plugins to be applied to the files CSS Modules imports via `composes`.

### What is actually happening?
PostCSS is not being applied to the files CSS Modules imports via `composes`

In my reproduction link, I have a repo that contains a `vue init webpack` build with very minor changes. It comes with autoprefixer installed to postcss and it should be getting applied to every file, however, this shows that it's not getting applied to the files imported via CSS Modules.
<img width="431" alt="screen shot 2017-08-29 at 8 28 39 pm" src="https://user-images.githubusercontent.com/1075694/29850084-fd465f02-8cf8-11e7-963b-97093e9487a8.png">

---
This loader entry in my webpack config has been a temporary fix:
```
{
	test: /\.css$/,
	enforce: 'pre',
	loader: 'postcss-loader',
	include: [
		importedFilePath,
	],
},
```

**Comment by Jinjiang** [comment]
Yes, currently the pre postcss-loader you provided is the only way I have found to finish this job. I haven't found another way yet.

**Comment by hirokiosame** [comment]
This has been resolved to the new syntax changes in vue-loader 15

**Comment by fuguxu** [comment]
> This has been resolved to the new syntax changes in vue-loader 15

how to config it，in vue-loader 15 ?
