### ISSUE TITLE
hotAPI.install is not a function

### ISSUE THREAD

**Issue by sunorry** [vuejs/vue-loader#960]
### Version
13.0.4

### Reproduction link
[https://github.com/sunorry/mnz](https://github.com/sunorry/mnz)

### Steps to reproduce
1. `npm install && node server.js` (node version: 7.5.0)
2. change `src/css/base.scss`, it will console `hotAPI.install is not a function`

change the `components/Hello.vue` the hot reload is okey.
but change the `base.scss` is always crash, change `Hello.vue` again, the hot reloading not work. 

### What is expected?
expect to change the scss file and the hot reloading is okey.

### What is actually happening?
devtool console `hotAPI.install is not a function`.

**Comment by rousos87** [comment]
@sunorry 

 Vue loader doesn’t work with webpack 3 yet.

**Comment by sunorry** [comment]
@rousos87 got it.

**Comment by LinusBorg** [comment]
@rousos87 That's not true.

I assume you think that because the webpack template hasn't been upgraded towebpack 3 yet, but the issue wasn't vue-loader, it was html-webpack-plugin.

**Comment by rousos87** [comment]
@LinusBorg 
I didn't know it.i thought was related to this issue.

https://github.com/vuejs/vue-loader/issues/850

Thanks for letting us know.

**Comment by LinusBorg** [comment]
That issue is only open because package.json of the vue-loader repo is not updated yet, but PR #860 provided webpack compatibility for webpack3's ModuleConcatenationPlugin. Otherwise, there were no incompatibilities to start with.

**Comment by LinusBorg** [comment]
I will now close this ticket as I don't see anything related to vue-loader.

**Comment by rousos87** [comment]
Good to know

Thanks

**Comment by sunorry** [comment]
Thanks.
