### ISSUE TITLE
Completely ignoring .postcssrc.js

### ISSUE THREAD

**Issue by warent** [vuejs/vue-loader#965]
### Version
13.0.4

### Reproduction link
[https://github.com/warent/vue-loader-bug1](https://github.com/warent/vue-loader-bug1)

### Steps to reproduce
1. npm install
2. npm run build
3. npm start

### What is expected?
Should throw an error because .postcssrc.js has bogus data

### What is actually happening?
Everything runs fine

**Comment by warent** [comment]
By the way this is a fresh vue init from the webpack template. No changes except to .postcssrc.js

**Comment by Justineo** [comment]
So why should `.postcssrc.js` be ignored here?

**Comment by LinusBorg** [comment]
It seems it was a conscious decision to catch and swallow that error:

https://github.com/vuejs/vue-loader/blob/master/lib/style-compiler/load-postcss-config.js#L14

But I'M not sure what was a wise decision.

**Comment by Justineo** [comment]
Oh I misunderstood this earlier.

I don't think it's good to completely ignoring errors, but now we only have an error message to tell if the error is a bearable one. Depending on `'No PostCSS Config found'` may seem ugly but it works for the current issue IMO.

**Comment by warent** [comment]
Yes, please reconsider swallowing errors. I wasted several hours on this very simple issue bedeviling me because I wasn't getting any error indicating something was wrong, which means others might have a similar experience

**Comment by LinusBorg** [comment]
yeah, I think we should do something about this.

**Comment by Jinjiang** [comment]
Just simply wrapped a error message #1095
Hope to be helpful.
Thanks.
