### ISSUE TITLE
解析（originalPositionFor） vue-loader 输出的sourceMap信息, 结果为null

### ISSUE THREAD

**Issue by xiachaoxulu** [vuejs/vue-loader#968]
### Version
13.0.2

### Reproduction link
[https://github.com/xiachaoxulu/issues/blob/master/vueloader](https://github.com/xiachaoxulu/issues/blob/master/vueloader)

### Steps to reproduce
1.webpack 中使用vue-loader
2.入口是一个js文件，其中引入了vue组件
3.打包，devtool 为nosources-source-map
4.生成了 map,和 js 文件
5.使用官网的sourceMap 包,来解析这个 map文件。
6.输入:  打包之后的js  的行列信息， 来获取 其源代码的行列信息
7.得到的结果是null

### What is expected?
得到正确源代码 行列

### What is actually happening?
得到的结果是null

---
估计是vue-loader生成的map文件有问题

**Comment by xiachaoxulu** [comment]
应该是 vue-loader  内部的用的 babel-loader 的问题，我发现 它生成的sourceMap 不对，  vue-loader 生成的sourceMap 是正确的

**Comment by xiachaoxulu** [comment]
https://github.com/xiachaoxulu/sourceMapDemo

**Comment by xiachaoxulu** [comment]
这是一个demo

**Comment by clarkdo** [comment]
可以看下 https://github.com/mozilla/source-map/issues/261

**Comment by chenwenxian** [comment]
有人遇到下面的问题么：
weex配置webConfig的vue-loader css提取导致样式大小是native的两倍了，这个是什么问题来着？

**Comment by yyx990803** [comment]
tracked in https://github.com/vuejs/vue-loader/issues/1163
