### ISSUE TITLE
Whitespace adjusting in .vue files

### ISSUE THREAD

**Issue by davidpelaez** [vuejs/vue-loader#97]
This works:

```
<style scoped lang='sass'>
​@import 'style'
.main
  background: $red​
</style>
```

This doesn't:

```
<!-- NOTE the leading whitespace before @import-->
<style scoped lang='sass'>
  @import 'style'
  .main
    background: $red
</style>
```

Given the HTML like structure of the `.vue` file it's expected that the contents of a tag are nested one level in comparison to their parent. From my limited understanding of the loader code is that it only passes the contents of the style tag to the corresponding loader and hence it will not manipulate the whitespace. If the compilar doesn't accept the initial whitespace in the first line then it'll fail. For some reason the sass loader can understand indented regular selectors as first line in the sass code ej: `  .main` (note the two leading spaces) but this doesn't work with `@import`.

If we are strict it makes sense that it fails because the indentation is given by the convention of embedding the code in the an HTML-like dotvue file and I'd suggest this should be handled here. This is similar to indentation handling in heredocs in bash scripts.

What about a flag like `scoped` so that I can indicate that leading whitespace should be trimmed? We could for instance remove a common indentation level if all lines share it so that the first character inside the parsed contents of the `style` or `template` tags cannot be whitespace.

What do you think @angelbotto?

**Comment by davidpelaez** [comment]
This is exactly what https://www.npmjs.com/package/deindent does. Maybe we could have something like `<style deindent scoped lang='sass'>`?

**Comment by yyx990803** [comment]
or you can make a deindent-loader and pipe it like so:

``` html
<style lang='sass!deindent'>
```

**Comment by davidpelaez** [comment]
That a very clean solution indeed. Thanks for pointing it out.
