### ISSUE TITLE
-webkit-keyframes have no scope id

### ISSUE THREAD

**Issue by sampsonli** [vuejs/vue-loader#975]
I use scoped styles, I found the  generated style '@-webkit-keyframes test'  had not scoped id, the nomallized should be '@-webkit-keyframes test-data-v-42cae6da'

**Comment by fzred** [comment]
I have come across too.
![image](https://user-images.githubusercontent.com/7991717/30904014-46a7b300-a336-11e7-8d23-b4a9ce2b4fce.png)
![image](https://user-images.githubusercontent.com/7991717/30904265-17125036-a337-11e7-86f7-8efa232ac1be.png)

**Comment by yyx990803** [comment]
Please upgrade to 13.x
