### ISSUE TITLE
tag agnostic transformToRequire

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue-loader#978]
### What problem does this feature solve?
I have several components that accepts an image url as property.
To handle this, I have two options:
- use explicit require `<mycomponent :imgsrc="require('./Freepik-awesomecontent.jpg')">`.
- add imgsrc attribute to `transformToRequire` for each component I use

It could be convenient to make the tagname optional and specify only an attribute in `transformToRequire`

### What does the proposed API look like?
I propose a empty string for optional tag
`transformToRequire: { '':'imgsrc' }`

or

a function that tells `vue-loader` that the attribute has to be transformed into require
`transformToRequire: function(tagName, attributeName) { ...`

**Comment by blieque** [comment]
I'd love this feature too. [`html-loader` has a nice option `attrs`](https://github.com/webpack-contrib/html-loader#usage), which works like so: `attrs: ['img:src', 'link:href', ':data-src']`. This would transform all `<img>` `src` attributes, `<link>` `href` attributes, and all `data-src` attributes regardless of element.

Thank-you for the `v-bind` workaround though.
