### ISSUE TITLE
"this" in pug-templates points to global object

### ISSUE THREAD

**Issue by volth** [vuejs/vue-loader#979]
### Version
12.2.2

### Reproduction link
need .vue-file, jsfiddle/codepen does not support it

### Steps to reproduce
```
<template lang="pug">
div
  h1= this
</template>
```

same with
```
<template lang="pug" src="xxx.pug"/>
```

xxx.pug
```
div
  h1= this
```

### What is expected?
"this" points to component object as in html-templates

### What is actually happening?
"this" points to "[object global]"
thus, there is no way to use component data in pug-templates

**Comment by yyx990803** [comment]
You are not supposed to use `this` in templates at all. Pug in this case can only do syntax-level pre-processing, for data binding you need to use Vue's syntax.
