### ISSUE TITLE
华为部分手机中部分css3动画失效

### ISSUE THREAD

**Issue by chemandy** [vuejs/vue-loader#980]
v13.0.4

华为手机中css3动画均失效，经测试替换为低版本loader后则问题解决，华为手机中可以看到 Uncaught TypeError: Illegal invocation 报错，并未定位到问题所在

 <div class="active-anim"></div>

  .active-anim
      animation: animWheel 20s infinite linear

  @keyframes animWheel {
    0% {
      transform rotate(0deg)
    }
    100% {
      transform rotate(360deg)
    }
  }

**Comment by chemandy** [comment]
使用v11.3.4 可以，12.0.0及以上版本均无法触发css3动画，stylus编译。
测试手机：华为Mate7，Android 6.0，EMUI 4.0.1，原生浏览器
其他还有几台华为均有此问题，也有几台华为手机没有问题，比较诡异。

**Comment by chemandy** [comment]
浏览器、iOS手机、及大部分安卓手机均正常

**Comment by Jinjiang** [comment]
先把 Keyframes 改成纯小写 keyframes 再试试

如果还有问题，有劳比对一下生成码里有关这段 keyframes 的部分在 0.12 和 0.13 版本下是否有差异，方便大家继续确认问题

谢谢

**Comment by fzred** [comment]
不只你碰到这问题。
https://github.com/vuejs/vue-loader/issues/975
其实就是 keyframes name没有改成css局部作用域用的别名

**Comment by chemandy** [comment]
@fzred 但是，部分手机又没有问题

**Comment by yyx990803** [comment]
Please upgrade to 13.x
