### ISSUE TITLE
Blank files fail to resolve

### ISSUE THREAD

**Issue by corysimmons** [vuejs/vue-loader#985]
`<style lang="scss" src="./App.scss"></style>`

### App.scss
```scss
```

```
ERROR in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-bd67fc74","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js!./src/components/App/App.scss
Module build failed: No input specified: provide a file name or a source string to process
```

Should just fail silently.

**Comment by Jinjiang** [comment]
In webpack if you require/import a file with a broken path it always fails. It help you quickly find the error instead of let the wrong code existing silently. So I don't think this is a problem.
Thanks.
