### ISSUE TITLE
Is it possible to compiler the `@import` from `style` tag?

### ISSUE THREAD

**Issue by iGarym** [vuejs/vue-loader#988]
`vue-loader/lib/selector.js` will not handle `@import` from `style` ，so the import style file will not be handled by `postcss` 

### Example
- vue-loader:  v13.0.4
- webpack: use the config from `vue init webpack` , add `postcss` plugin：

```
postcss: [
    require('autoprefixer')({
      browsers: ['last 20 versions']  // just for test
    })
  ],
```
- Code：
```
// import.less
@import './import-css.css';
@import './import-less.less';

// component
<script>
  import './import.less';   // postcss: no
  export default {}
</script>

<style>
  @import './lang-css.css';  // postcss: no
</style>

<style lang="less">
  @import './lang-less.css';  // postcss: no
  @import './lang-less.less'; // postcss: yes
</style>
```

### Process：
1. `vue-loader/lib/selector.js` 
2.  `less-loader`  （lang="less"）
3. `vue-loader/lib/style-compiler/index.js` 
4. `css-loader` 
5. `vue-style-loader`

`@import './lang-less.less';` in the second `style` has been replace by `less-loader` . so the code has been handle by `postcss` . 
**But** until `css-loader` step, other `@import`   were handled.

**Comment by ronaldoooo** [comment]
正巧发现了同样的问题，不过我在vue文件用的stylus，需要引用一个第三方库的less文件......会包module build failed 错误。

**Comment by Justineo** [comment]
@ronaldoooo 你可以尝试在一个 `.vue` 文件中使用多个 `<style>` 块，分别启用 `lang="less"` 和 `lang="stylus"`。

**Comment by iGarym** [comment]
@Justineo 顾大大，我的这个问题，我现在是另写了一份覆盖了他的样式，除了这样还有其他办法吗？

场景：我是自己写的一个 `postcss` 的插件将 `px` 转成 `rem`，在引用 vux 的组件的时候碰到这个问题。

`vux` 的组件代码：
```
<style>
@import './scroller.css';
</style>
```

`scroller.css` 实际是在 `postcss` 之后才被 `import` 替换的，所以就没有被处理

**Comment by Justineo** [comment]
你给 vux 提 issue 吧，只要作为 Less 文件来 import 就可以了。

**Comment by Jinjiang** [comment]
我觉得有这么几个方面的问题：

1. vux 的代码是否可以支持定制甚至转换长度单位，建议在 vux 社区讨论——不管我们现在打算用什么技术去定制或转换它。如果没有官方的支持，显然是很难的，即便几天你能 hack 它，也不能保证它将来不会被重构，重构之后还能不能这样用你也不知道。
2. `<style>` 内的 import 语法是被 css-loader 内部解析和转换的，如果你想更改这部分的逻辑和行为，只能 hack css-loader，对此我不是特别支持。但是如果换成 `<style src="...">` 或是一些预处理器语法中的 import 可能就更有机会做处理和转换了。

所以结论：1 支持 @Justineo 的 `lang` 建议；2 具体用例 issue 提到 vux。

**Comment by iGarym** [comment]
@Jinjiang @Justineo 感谢两位的回复！之前和同事沟通也是觉得，为这个需求来修改整个 loader 的逻辑不太划算了。所以最终还是选择覆盖完事。对于vux，考虑到第三方的组件始终是不可控的，并且业务也并没有完全依赖它，现在也在逐步替换。
