### ISSUE TITLE
vue-loader 13.0.0以上版本报"Failed to mount component: template or render function not defined"

### ISSUE THREAD

**Issue by wen911119** [vuejs/vue-loader#996]

**Comment by wen911119** [comment]
### Version
13.0.0

### Reproduction link
[https://github.com/wen911119/vue-loader-bug-report](https://github.com/wen911119/vue-loader-bug-report)

### Steps to reproduce
> ### 13.0.0版本 默认启用esModule的情况下
```
git clone git@github.com:wen911119/vue-loader-bug-report.git
npm install 
npm run  dev
```
报错 "Failed to mount component: template or render function not defined"

> ### 换用12.2.2 版本试下
先删掉node_modules目录，然后
```
git fetch origin 12.2.2:12.2.2
git checkout 12.2.2
npm install 
npm run  dev
```
一切正常

或者关掉13.0.0 的esModule，也是正常的



### What is expected?
在12.2.2和13.0.0中都能正常运行

### What is actually happening?
在13.0.0试报错"Failed to mount component: template or render function not defined"

---
错误发生在 使用从npm上下载的组件的时候
使用的npm上组件地址为https://github.com/wen911119/Vue-Components/blob/master/ControlledInput/app.vue

**Comment by Jinjiang** [comment]
确定一下是否是 13.0 提到的 breaking change：

> The `esModule` option is now `true` by default

https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

**Comment by wen911119** [comment]
@Jinjiang 
我自己验证了，确实是breaking change导致的，不好意思！

**Comment by YTU94** [comment]
冒昧问一下，breaking change是什么，这个问题怎么解决，我现在是15.2.4版本 也报了这个错
